### ISSUE TITLE
Git Configuration hangs

### ISSUE THREAD

**Issue by s7ygian** [spring-projects/sts4#311] opened 2019-06-26 16:38 UTC
The preference page "Team -> Git -> Configuration" (see screenshot below) cannot be opened in a freshly downloaded STS v4.3.0. The program hangs and no longer responds.

In a freshly downloaded STS v4.2.2 this preference page works fine.

OS: Windows-10-1809 64-Bit
Java: OracleJDK 1.8.0_181-x86_64 or AdoptOpenJDK 11.0.3_7_openj9-0.14.3-x86_64

![image](https://user-images.githubusercontent.com/2044932/60197272-62d50500-983f-11e9-93c0-7bdce6749700.png)

**Comment by kdvolder** [comment] 2019-06-26 17:51
When the program hangs, one of the best sources of information to debug the issue is to take a stackdump of the process that is stuck (in this case the STS process). You can do this using CLI tools 'jps' and 'jstack' that come bundled with the JVM.

So can you please collect a stack dump and attach it here? That would be great, thanks!

**Comment by s7ygian** [comment] 2019-06-27 13:16
Thank you for the hint. I have generated the following stack dump with ".\jstack.exe 12980". STS v4.3.0 was started with java version "AdoptOpenJDK 11.0.3_7_openj9-0.14.3-x86_64" and an empty workspace.

2019-06-27T15:07:11.883113100
Virtual machine: 12980 JVM information JRE 11 Windows 10 amd64-64-Bit Compressed References 20190531_235 (JIT enabled, AOT enabled)
OpenJ9   - b8ab01656
OMR      - b56045d2
JCL      - dcdc97f9dc based on jdk-11.0.3+7
"main" prio=6 Id=1 TIMED_WAITING
        at 11.0.3/java.lang.Thread.sleep(Native Method)
        at 11.0.3/java.util.concurrent.TimeUnit.sleep(TimeUnit.java:446)
        at app//org.eclipse.jgit.util.FS$FileStoreAttributeCache.<init>(FS.java:240)
        at app//org.eclipse.jgit.util.FS$FileStoreAttributeCache.getFsTimestampResolution(FS.java:211)
        at app//org.eclipse.jgit.util.FS.getFsTimerResolution(FS.java:321)
        at app//org.eclipse.jgit.internal.storage.file.FileSnapshot.<init>(FileSnapshot.java:186)
        at app//org.eclipse.jgit.internal.storage.file.FileSnapshot.save(FileSnapshot.java:122)
        at app//org.eclipse.jgit.storage.file.FileBasedConfig.load(FileBasedConfig.java:156)
        at app//org.eclipse.egit.ui.internal.preferences.ConfigurationEditorComponent.initControlsFromConfig(ConfigurationEditorComponent.java:464)
        at app//org.eclipse.egit.ui.internal.preferences.ConfigurationEditorComponent.createContents(ConfigurationEditorComponent.java:428)
        at app//org.eclipse.egit.ui.internal.preferences.GlobalConfigurationPreferencePage.createContents(GlobalConfigurationPreferencePage.java:160)
        at app//org.eclipse.jface.preference.PreferencePage.createControl(PreferencePage.java:244)
        at app//org.eclipse.jface.preference.PreferenceDialog.createPageControl(PreferenceDialog.java:1429)
        at app//org.eclipse.jface.preference.PreferenceDialog$8.run(PreferenceDialog.java:1196)
        at app//org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
        at app//org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:47)
        at app//org.eclipse.ui.internal.JFaceUtil$$Lambda$85.000000001A10D900.run(Unknown Source)
        at app//org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:176)
        at app//org.eclipse.jface.preference.PreferenceDialog.showPage(PreferenceDialog.java:1188)
        at app//org.eclipse.ui.internal.dialogs.FilteredPreferenceDialog.showPage(FilteredPreferenceDialog.java:635)
        at app//org.eclipse.jface.preference.PreferenceDialog$5.lambda$0(PreferenceDialog.java:660)
        at app//org.eclipse.jface.preference.PreferenceDialog$5$$Lambda$571.0000000020518CD0.run(Unknown Source)
        at app//org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)
        at app//org.eclipse.jface.preference.PreferenceDialog$5.selectionChanged(PreferenceDialog.java:657)
        at app//org.eclipse.jface.viewers.StructuredViewer$3.run(StructuredViewer.java:817)
        at app//org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
        at app//org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:47)
        at app//org.eclipse.ui.internal.JFaceUtil$$Lambda$85.000000001A10D900.run(Unknown Source)
        at app//org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:176)
        at app//org.eclipse.jface.viewers.StructuredViewer.firePostSelectionChanged(StructuredViewer.java:814)
        at app//org.eclipse.jface.viewers.StructuredViewer.handlePostSelect(StructuredViewer.java:1183)
        at app//org.eclipse.jface.viewers.StructuredViewer.lambda$0(StructuredViewer.java:1206)
        at app//org.eclipse.jface.viewers.StructuredViewer$$Lambda$421.000000001D3DCBB0.accept(Unknown Source)
        at app//org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
        at app//org.eclipse.jface.util.OpenStrategy.firePostSelectionEvent(OpenStrategy.java:263)
        at app//org.eclipse.jface.util.OpenStrategy.access$5(OpenStrategy.java:258)
        at app//org.eclipse.jface.util.OpenStrategy$1.lambda$1(OpenStrategy.java:428)
        at app//org.eclipse.jface.util.OpenStrategy$1$$Lambda$582.000000001BD16A60.run(Unknown Source)
        at app//org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
        at app//org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
        - locked org.eclipse.swt.widgets.RunnableLock@a7951cf9
        at app//org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3919)
        at app//org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3550)
        at app//org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
        at app//org.eclipse.jface.window.Window.open(Window.java:799)
        at app//org.eclipse.ui.internal.OpenPreferencesAction.run(OpenPreferencesAction.java:66)
        at app//org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
        at app//org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:580)
        at app//org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:412)
        at app//org.eclipse.jface.action.ActionContributionItem$$Lambda$368.000000001BE4FE80.handleEvent(Unknown Source)
        at app//org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
        at app//org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
        at app//org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1056)
        at app//org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
        at app//org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
        at app//org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
        at app//org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
        at app//org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
        at app//org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
        at app//org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:635)
        at app//org.eclipse.ui.internal.Workbench$$Lambda$175.000000001A221890.run(Unknown Source)
        at app//org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
        at app//org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
        at app//org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
        at app//org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
        at app//org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at app//org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
        at app//org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
        at app//org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
        at app//org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at 11.0.3/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at 11.0.3/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at 11.0.3/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at 11.0.3/java.lang.reflect.Method.invoke(Method.java:566)
        at app//org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
        at app//org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
        at app//org.eclipse.equinox.launcher.Main.run(Main.java:1468)
        at app//org.eclipse.equinox.launcher.Main.main(Main.java:1441)
        CPU time: 13734375000 ns
        User time: 8281250000 ns

"JIT Compilation Thread-0" prio=10 Id=3 RUNNABLE
        CPU time: 4453125000 ns
        User time: 4359375000 ns

"JIT Compilation Thread-1 Suspended" prio=10 Id=4 RUNNABLE
        CPU time: 7375000000 ns
        User time: 7218750000 ns

"JIT Compilation Thread-2 Suspended" prio=10 Id=5 RUNNABLE
        CPU time: 62500000 ns
        User time: 62500000 ns

"JIT Diagnostic Compilation Thread-3 Suspended" prio=10 Id=6 RUNNABLE
        CPU time: 0 ns
        User time: 0 ns

"JIT-SamplerThread" prio=10 Id=7 TIMED_WAITING
        CPU time: 0 ns
        User time: 0 ns

"IProfiler" prio=5 Id=8 RUNNABLE
        CPU time: 4609375000 ns
        User time: 4234375000 ns

"Common-Cleaner" prio=8 Id=2 TIMED_WAITING
        at 11.0.3/java.lang.Object.wait(Native Method)
        at 11.0.3/java.lang.Object.wait(Object.java:221)
        at 11.0.3/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:138)
        - locked java.lang.ref.ReferenceQueue@eb4b06c8
        at 11.0.3/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:148)
        at 11.0.3/java.lang.Thread.run(Thread.java:831)
        at 11.0.3/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:134)
        CPU time: 15625000 ns
        User time: 0 ns

"Concurrent Mark Helper" prio=1 Id=9 RUNNABLE
        CPU time: 0 ns
        User time: 0 ns

"GC Slave" prio=5 Id=10 RUNNABLE
        CPU time: 390625000 ns
        User time: 390625000 ns

"GC Slave" prio=5 Id=11 RUNNABLE
        CPU time: 390625000 ns
        User time: 375000000 ns

"GC Slave" prio=5 Id=12 RUNNABLE
        CPU time: 390625000 ns
        User time: 375000000 ns

"Attach API wait loop" prio=10 Id=15 TIMED_WAITING
        at 11.0.3/java.lang.Thread.sleep(Native Method)
        at 11.0.3/java.lang.Thread.sleep(Thread.java:961)
        at 11.0.3/com.ibm.tools.attach.target.WaitLoop.checkReplyAndCreateAttachment(WaitLoop.java:140)
        at 11.0.3/com.ibm.tools.attach.target.WaitLoop.waitForNotification(WaitLoop.java:117)
        at 11.0.3/com.ibm.tools.attach.target.WaitLoop.run(WaitLoop.java:154)
        CPU time: 0 ns
        User time: 0 ns

"Finalizer thread" prio=5 Id=21 RUNNABLE
        CPU time: 0 ns
        User time: 0 ns

"Bundle File Closer" prio=5 Id=22 WAITING
        at 11.0.3/java.lang.Object.wait(Native Method)
        at 11.0.3/java.lang.Object.wait(Object.java:192)
        at app//org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.getNextEvent(EventManager.java:400)
        - locked org.eclipse.osgi.framework.eventmgr.EventManager$EventThread@a668c62
        at app//org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:341)
        CPU time: 109375000 ns
        User time: 78125000 ns

"Active Thread: Equinox Container: 703a114b-8ce6-470d-b9d5-7fe42418b2f7" prio=5 Id=23 TIMED_WAITING
        at 11.0.3/jdk.internal.misc.Unsafe.park(Native Method)
        at 11.0.3/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
        at 11.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2123)
        at 11.0.3/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
        at 11.0.3/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
        at 11.0.3/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054)
        at 11.0.3/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
        at 11.0.3/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at 11.0.3/java.lang.Thread.run(Thread.java:831)
        CPU time: 312500000 ns
        User time: 281250000 ns

"Framework Event Dispatcher: Equinox Container: 703a114b-8ce6-470d-b9d5-7fe42418b2f7" prio=5 Id=25 WAITING
        at 11.0.3/java.lang.Object.wait(Native Method)
        at 11.0.3/java.lang.Object.wait(Object.java:192)
        at app//org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.getNextEvent(EventManager.java:400)
        - locked org.eclipse.osgi.framework.eventmgr.EventManager$EventThread@9a62ec9
        at app//org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:341)
        CPU time: 31250000 ns
        User time: 31250000 ns

"Start Level: Equinox Container: 703a114b-8ce6-470d-b9d5-7fe42418b2f7" prio=5 Id=26 WAITING
        at 11.0.3/java.lang.Object.wait(Native Method)
        at 11.0.3/java.lang.Object.wait(Object.java:192)
        at app//org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.getNextEvent(EventManager.java:400)
        - locked org.eclipse.osgi.framework.eventmgr.EventManager$EventThread@baf0c4b1
        at app//org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:341)
        CPU time: 1546875000 ns
        User time: 1312500000 ns

"SCR Component Actor" prio=5 Id=27 WAITING
        at 11.0.3/java.lang.Object.wait(Native Method)
        at 11.0.3/java.lang.Object.wait(Object.java:192)
        at app//org.apache.felix.scr.impl.ComponentActorThread.run(ComponentActorThread.java:83)
        - locked java.util.LinkedList@51a28af2
        at 11.0.3/java.lang.Thread.run(Thread.java:831)
        CPU time: 0 ns
        User time: 0 ns

"Worker-JM" prio=5 Id=29 WAITING
        at 11.0.3/java.lang.Object.wait(Native Method)
        at 11.0.3/java.lang.Object.wait(Object.java:221)
        at app//org.eclipse.core.internal.jobs.InternalWorker.run(InternalWorker.java:62)
        - locked java.util.ArrayList@7ce53d8e
        CPU time: 0 ns
        User time: 0 ns

"Gogo shell" prio=5 Id=32 WAITING
        at 11.0.3/jdk.internal.misc.Unsafe.park(Native Method)
        at 11.0.3/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
        at 11.0.3/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
        at 11.0.3/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433)
        at 11.0.3/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1054)
        at 11.0.3/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1114)
        at 11.0.3/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at 11.0.3/java.lang.Thread.run(Thread.java:831)
        CPU time: 0 ns
        User time: 0 ns

"ForkJoinPool.commonPool-worker-3" prio=6 Id=35 WAITING
        at 11.0.3/jdk.internal.misc.Unsafe.park(Native Method)
        at 11.0.3/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
        at 11.0.3/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
        at 11.0.3/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
        CPU time: 15625000 ns
        User time: 15625000 ns

"EMF Reference Cleaner" prio=6 Id=38 WAITING
        at 11.0.3/java.lang.Object.wait(Native Method)
        at 11.0.3/java.lang.Object.wait(Object.java:221)
        at 11.0.3/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:138)
        - locked java.lang.ref.ReferenceQueue@a28d4e4a
        at 11.0.3/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:110)
        at app//org.eclipse.emf.common.util.CommonUtil$1ReferenceClearingQueuePollingThread.run(CommonUtil.java:70)
        CPU time: 0 ns
        User time: 0 ns

"Java indexing" prio=4 Id=40 WAITING
        at 11.0.3/java.lang.Object.wait(Native Method)
        at 11.0.3/java.lang.Object.wait(Object.java:192)
        at app//org.eclipse.jdt.internal.core.search.processing.JobManager.run(JobManager.java:378)
        - locked org.eclipse.jdt.internal.core.search.indexing.IndexManager@5cd21ef7
        at 11.0.3/java.lang.Thread.run(Thread.java:831)
        CPU time: 0 ns
        User time: 0 ns

"EventAdmin Async Event Dispatcher Thread" prio=6 Id=42 WAITING
        at 11.0.3/java.lang.Object.wait(Native Method)
        at 11.0.3/java.lang.Object.wait(Object.java:192)
        at app//org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.getNextEvent(EventManager.java:400)
        - locked org.eclipse.osgi.framework.eventmgr.EventManager$EventThread@3015cd3c
        at app//org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:341)
        CPU time: 46875000 ns
        User time: 46875000 ns

"Worker-7" prio=5 Id=49 TIMED_WAITING
        at 11.0.3/java.lang.Object.wait(Native Method)
        at 11.0.3/java.lang.Object.wait(Object.java:221)
        at app//org.eclipse.core.internal.jobs.WorkerPool.sleep(WorkerPool.java:200)
        - locked org.eclipse.core.internal.jobs.WorkerPool@f2cbc2f2
        at app//org.eclipse.core.internal.jobs.WorkerPool.startJob(WorkerPool.java:242)
        at app//org.eclipse.core.internal.jobs.Worker.run(Worker.java:58)
        CPU time: 0 ns
        User time: 0 ns

"Worker-10" prio=5 Id=52 TIMED_WAITING
        at 11.0.3/java.lang.Object.wait(Native Method)
        at 11.0.3/java.lang.Object.wait(Object.java:221)
        at app//org.eclipse.core.internal.jobs.WorkerPool.sleep(WorkerPool.java:200)
        - locked org.eclipse.core.internal.jobs.WorkerPool@f2cbc2f2
        at app//org.eclipse.core.internal.jobs.WorkerPool.startJob(WorkerPool.java:242)
        at app//org.eclipse.core.internal.jobs.Worker.run(Worker.java:58)
        CPU time: 46875000 ns
        User time: 31250000 ns

"Thread-10" prio=5 Id=53 TIMED_WAITING
        at 11.0.3/java.lang.Thread.sleep(Native Method)
        at 11.0.3/java.lang.Thread.sleep(Thread.java:961)
        at app//org.eclipse.equinox.internal.p2.updatechecker.UpdateChecker$UpdateCheckThread.run(UpdateChecker.java:73)
        CPU time: 0 ns
        User time: 0 ns

"file lock watchdog" prio=10 Id=57 TIMED_WAITING
        at 11.0.3/java.lang.Object.wait(Native Method)
        at 11.0.3/java.lang.Object.wait(Object.java:221)
        at 11.0.3/java.util.TimerThread.mainLoop(Timer.java:553)
        - locked java.util.TaskQueue@684c9e3b
        at 11.0.3/java.util.TimerThread.run(Timer.java:506)
        CPU time: 0 ns
        User time: 0 ns

"Attachment 50894" prio=10 Id=58 RUNNABLE
        at 11.0.3/com.ibm.java.lang.management.internal.ThreadMXBeanImpl.dumpAllThreadsImpl(Native Method)
        at 11.0.3/com.ibm.java.lang.management.internal.ThreadMXBeanImpl.dumpAllThreadsCommon(ThreadMXBeanImpl.java:653)
        at 11.0.3/com.ibm.java.lang.management.internal.ThreadMXBeanImpl.dumpAllThreads(ThreadMXBeanImpl.java:636)
        at 11.0.3@app/openj9.tools.attach.diagnostics.info.ThreadGroupInfo.getThreadInfoProperties(ThreadGroupInfo.java:107)
        at 11.0.3@app/openj9.tools.attach.diagnostics.target.TargetDiagnosticsProviderImpl.getThreadGroupInfo(TargetDiagnosticsProviderImpl.java:41)
        at 11.0.3/com.ibm.tools.attach.target.Attachment.doCommand(Attachment.java:211)
        at 11.0.3/com.ibm.tools.attach.target.Attachment.run(Attachment.java:163)
        CPU time: 62500000 ns
        User time: 62500000 ns

"MemoryMXBean notification dispatcher" prio=6 Id=59 RUNNABLE
        at 11.0.3/com.ibm.lang.management.internal.MemoryNotificationThread.processNotificationLoop(Native Method)
        at 11.0.3/com.ibm.lang.management.internal.MemoryNotificationThread.run(MemoryNotificationThread.java:183)
        CPU time: 0 ns
        User time: 0 ns

**Comment by kdvolder** [comment] 2019-06-27 15:48
The UI thread seems to be busy/blocked withing jgit loading some kind of configuration. This seems to be in turn part of showing an Eclipse preference page. 

I don't see anything specifically there that suggests this problem is caused by STS. I think its probably a bug / problem that comes from Eclipse git support which is a generic part of Eclipse, not something specific to STS.

Do you see a similar issue if you try the same thing with a 'vanilla' Eclipse? That woud be intersting to try in order to confirm this. If yes, then I'd say this is a problem that should be logged against Eclipse bugzilla tracker instead of STS.

**Comment by haqziaul21** [comment] 2019-07-18 15:05
I am facing the same issue with sts 4.3.1 seems its a bug.

**Comment by haqziaul21** [comment] 2019-07-18 17:05
Yes I can say its a problem with win10 even with eclipse 2019 , since I am not able to produce the problem with win7 and win8.

**Comment by kdvolder** [comment] 2019-07-18 17:27
Thanks for the extra information. So this seems to confirm the problem is not from STS itself, but from Eclipse EGit/JGit. Somebody should raise a bug against Eclipse instead. I would do it for you, but the problem seems to be rather specific to specific Windows environment, and I do not have a good way to reproduce the problem myself and provide a good documentation of the problem to the Eclipse folks to help them fix it.

Therefore I think it would be best of someone who is actually experiencing the issue should raise it and be availabe to answer questions on the ticket if need be.

I'm closing this ticket now as it seems clear this is not an STS bug. If someone decides they want to follow up and raise an Eclipse bug, (that would be great!), Then please also post a link to the bugzilla ticket here.

**Closed by kdvolder** 2019-07-18 17:27 UTC

**Comment by cebaa** [comment] 2019-07-23 20:28
These seem to be related:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=548188#c25
https://bugs.eclipse.org/bugs/show_bug.cgi?id=548598

**Comment by martinlippert** [comment] 2019-07-29 09:07
Awesome, thanks for the pointers to the bugs at Eclipse. Much appreciated for cross-posting here.
