### ISSUE TITLE
Vscode Spring Boot Tools extention cant get code completions

### ISSUE THREAD

**Issue by Booooooger** [spring-projects/sts4#376] opened 2019-10-12 03:12 UTC
The Spring Boot Tools extention does not work as expect,

# Context

- vscode remote-wsl: 
![image](https://user-images.githubusercontent.com/40785594/66693925-f3492f80-ece0-11e9-8544-7f30f763654f.png)
- ubuntu 18.04
- jdk: 8

as usage description:

> 
> Functionality for .properties and .yml

>This extension analyzes your project's classpath and parses and indexes any Spring Boot Properties Metadata it finds. Both Maven and Gradle projects are supported.

>The data in the index is used to provide validation, code completions and information hovers while editing Spring Boot Properties in either .properties or .yml format.

but when i edit my application.properties or application.yml files, i can not get any code completions. 

Surprisingly, it could work well sometime. I mean ,this problem does not happen every time.

that's all ,thanks

**Comment by sandeepamilineni** [comment] 2019-10-13 18:51
![image](https://user-images.githubusercontent.com/2767069/66720290-8933a600-ee18-11e9-8a96-a976865d6e04.png)

Facing same issue

**Comment by kdvolder** [comment] 2019-10-15 16:23
When there are no completions then it could be because of STS4 not getting the project's classpath information. If you check the language server log output it may have some messages in there that help determinining whether or not STS4 is getting classpath information for your project. 

You have to enable the log output via a workspace or user setting in vscode. Just open the workspace preferences and search for a key called 'spring-boot.ls.logfile'. For example I have added something like this to my workspace settings:

```
	"spring-boot.ls.logfile": "/tmp/bootls.log",
```

After you restart vscode you should then be able to open that file and see the log output there. 

If you could attach the log output it may help narrow down what direction we need to look for the cause of the problem. The cause could be many things. One possibility is that there is an error in your project's pom or gradle configuration. 

> Surprisingly, it could work well sometime. I mean ,this problem does not happen every time

Interesting. Is that with the same project? (I.e. it sometimes works and sometimes doesn't work with the same project? Or does it work with some projects but not others?)

One possible cause of the problem is a issue with the JDT language server which is not sending classpath data. The JDT language server isn't allways computing classpaths correctly or sometimes it just takes a long time (downloading dependencies for example). It might help just to wait a little and give the JDT language server a chance to do its thing. If you waited a reasonable time, then you can try restarting vscode. The JDT language server classpath updates may work better after a restart.

If you try some of these things it would be useful if you let us know how it goes. All of that is useful information to try and determine the cause of the problem as well as useful information for others looking for a workaround.

**Comment by sandeepamilineni** [comment] 2019-10-26 09:28
[bootls.log](https://github.com/spring-projects/sts4/files/3774662/bootls.log)

Attached logs. The issue is with this project only and happens always.

**Comment by martinlippert** [comment] 2019-10-28 17:50
The log file reads like you are trying auto-completion in a Java file. Can you maybe attach the sample project and provide exact steps how to reproduce and where you are trying content-assist? That would be awesome.

As for Java files, the Spring Boot language server doesn't provide a lot of additional content-assist features, so we would need to know exactly what you are trying to do here.

**Comment by martinlippert** [comment] 2021-02-16 13:43
I am closing this one here, since no additional feedback arrived since then and the issue is already quite old. If you come across this again, please comment and we can re-open this issue. In that case, please attach a sample project that helps us to reproduce the issue. Thanks!!!

**Closed by martinlippert** 2021-02-16 13:43 UTC
