### ISSUE TITLE
Generic Editor - Spring YAML Properties Not Support Map Recognition

### ISSUE THREAD

**Issue by yl-yue** [spring-projects/sts4#515] opened 2020-08-03 04:21 UTC
## @ConfigurationProperties  code definition
```java
@ConfigurationProperties(prefix = "justauth")
public class JustAuthProperties {
    private Map<AuthDefaultSource, AuthConfig> type = new HashMap<>();
}

public enum AuthDefaultSource implements AuthSource {
    ALIPAY {
        @Override
        public String authorize() {
            return "https://openauth.alipay.com/oauth2/publicAppAuthorize.htm";
        }

        @Override
        public String accessToken() {
            return "https://openapi.alipay.com/gateway.do";
        }

        @Override
        public String userInfo() {
            return "https://openapi.alipay.com/gateway.do";
        }
    }
}

public class AuthConfig {
    private String clientId;
    private String clientSecret;
}
```

## yml file config
```yml
justauth:
  enabled: true
  type:
    ALIPAY:
      client-id: 20210011
      client-secret: MIIEvwIBADANBgkqh
```

## error show
![image](https://user-images.githubusercontent.com/39790401/89145482-86f72f80-d583-11ea-9587-f412a0b07aa4.png)

## expectation
Support Map Recognition Prompt Correctly.

**Comment by kdvolder** [comment] 2020-08-24 19:44
Some things I needed to do to make the example code complete. In the future please try to package your example as a self-container project. As I am guessing to fill in the gaps, I am not certain that what I'm doing is the same as what you are doing. 

I am recording here the steps I did, this is for later reference by myself, and possible for you to see if there's a difference between what O'm doing versus your setup.

- put all the code inside a new spring-boot prpject created by initializer. Java version 1.8, Boot version 2.3.3.RELEASE I placed all code in the 'com.example.demo' package added package declaration and necessary import. 
- Added missing type 'AuthSource'

```
package com.example.demo;

public interface AuthSource {
	String authorize();
	String accessToken();
	String userInfo();
}
```

- Add getter and setter to `JustAuthProperties` (I think at least a getter is required, maybe the setter could be omitted.

```
package com.example.demo;

import java.util.HashMap;
import java.util.Map;

import org.springframework.boot.context.properties.ConfigurationProperties;

@ConfigurationProperties(prefix = "justauth")
public class JustAuthProperties {
    private Map<AuthDefaultSource, AuthConfig> type = new HashMap<>();

	public Map<AuthDefaultSource, AuthConfig> getType() {
		return type;
	}

	public void setType(Map<AuthDefaultSource, AuthConfig> type) {
		this.type = type;
	}
}
```

- Add `spring-boot-configuration-processor` dependency to pom.xml

```
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-configuration-processor</artifactId>
			<optional>true</optional>
		</dependency>
```

**Comment by kdvolder** [comment] 2020-08-24 19:58
Made sure project with new config is built by doing a 'clean' of the project.

I then verified that configuration metadata is generated correctly by Spring Boot configuration processor by checking for a file: ` /target/classes/META-INF/spring-configuration-metadata.json`.

Contains this data for me:

```
{
  "groups": [
    {
      "name": "justauth",
      "type": "com.example.demo.JustAuthProperties",
      "sourceType": "com.example.demo.JustAuthProperties"
    }
  ],
  "properties": [
    {
      "name": "justauth.type",
      "type": "java.util.Map<com.example.demo.AuthDefaultSource,com.example.demo.AuthConfig>",
      "sourceType": "com.example.demo.JustAuthProperties"
    }
  ],
  "hints": []
}
```

That seems correct and as expected.

Now we come to the real question... does the editor work properly with this metadata?

I closed all editors (there are sometimes issues with new metadata not being picked up by the editor. So I avoid those... closing all editors stops language servers and forces a 'clean slate'. Then create a `src/main/resources/application.yml` file and open it.

Editing the application.yml file works nicely. I get content assist for justauth.type and also for the 'ALIPAY` enum and the nested attributes. I created this content and it has no validation errors:

```
justauth:
  type:
    ALIPAY:
      client-id: 1363636
      client-secret: ASADASDASD
```

All working nicely for me.

**Comment by kdvolder** [comment] 2020-08-24 20:03
@yl-yue Do you see any differences in your setup from mine. Do you really have classes like

```
public class AuthConfig {
    private String clientId;
    private String clientSecret;
```

... without getters or setters? That will definitely explain the problem. Also please verify if the configuration processor is setup correctlly add that a file like `spring-configuration-metadata.json` is created on the project's classpath. If all of that checks out, then most likely we are having an issue with metadata that the editor/language server has parsed maybe being stale.

If you are still experiencing issues, please attach a complete sample project and exact step-by-step instructions on how to reproduce the problem. That will allow us to debug it more easily.

**Comment by kdvolder** [comment] 2020-08-24 20:06
I am attaching my own 'complete' sample project created as described above.

[justauth-example.zip](https://github.com/spring-projects/sts4/files/5119995/justauth-example.zip)

**Comment by kdvolder** [comment] 2020-08-24 20:09
I'm closing this ticket because as far as I know right now. Interpretation of the kind of metadata as would be created by the example is interpreted correctly. We can of course re-open this ticket again if you add more details and there is a problem that I can reproduce.

**Comment by yl-yue** [comment] 2020-09-10 07:37
> I am attaching my own 'complete' sample project created as described above.
> 
> [justauth-example.zip](https://github.com/spring-projects/sts4/files/5119995/justauth-example.zip)

通过你提供的 justauth-example.zip 示例项目，已确认类似的Map数据结构是支持的。
有问题的应该是这个依赖：

**Comment by kdvolder** [comment] 2020-09-10 16:40
Okay, thanks for providing extra information. I will try to create a project with dependency:

```
        <dependency>
            <groupId>com.xkcoding.justauth</groupId>
            <artifactId>justauth-spring-boot-starter</artifactId>
            <version>1.3.3</version>
        </dependency>
```

And see if I can reproduce the issue that way. So I am re-opening this ticket for further investigation.

**Comment by kdvolder** [comment] 2020-09-23 14:49
I am able to reproduce the issue. Don't understand exactly why this happens yet. The info that I see when hovering over `type` in:

```
justauth:
  enabled: true
  type:
```

Seems incorrect, it displays as 'Authconfig' instead of 'Map<...,...>' and the error is consistent with that. Trying to figure out now why the type is being inferred incorrectly.

**Comment by kdvolder** [comment] 2020-09-23 14:53
Looking at the metadata for justauth.type. Pasting it here for easy reference.

```
    {
      "name": "justauth.type",
      "type": "java.util.Map<me.zhyd.oauth.config.AuthDefaultSource,me.zhyd.oauth.config.AuthConfig>",
      "description": "JustAuth 配置.",
      "sourceType": "com.xkcoding.justauth.autoconfigure.JustAuthProperties"
    }
...
  "hints": [
    {
      "name": "justauth.type.keys",
      "providers": [
        {
          "name": "handle-as",
          "parameters": {
            "target": "me.zhyd.oauth.config.AuthSource"
          }
        }
      ]
    },
    {
      "name": "justauth.type.values",
      "providers": [
        {
          "name": "handle-as",
          "parameters": {
            "target": "me.zhyd.oauth.config.AuthConfig"
          }
        }
      ]
    }
  ]
```

**Comment by kdvolder** [comment] 2020-09-23 15:03
I think the reason for how this behaves is the declaration of 'handle-as' AuthSource for `justauth.type.keys`. I think if this metadata is removed then things will work as expected. In other words STS does not treat the key as an instance of an Enum because it has been explicitly instructed via the justauth libraries metadata to treat it as something else.

I would suggest raising this issue with the maintainers of the justauth boot starter and ask that they change/fix the metadata.

We can discuss more about this if you want. But for the time being I will close the ticket again as I do not beleave this is really a bug in STS.

**Closed by kdvolder** 2020-09-23 15:03 UTC

**Comment by kdvolder** [comment] 2020-09-23 15:10
BTW: Just to be clear about what I'm suggesting. I think the solution is for justauth to remove this metadata:

```
 "hints": [
    {
      "name": "justauth.type.keys",
      "providers": [
        {
          "name": "handle-as",
          "parameters": {
            "target": "me.zhyd.oauth.config.AuthSource"
          }
        }
      ]
    },
    {
      "name": "justauth.type.values",
      "providers": [
        {
          "name": "handle-as",
          "parameters": {
            "target": "me.zhyd.oauth.config.AuthConfig"
          }
        }
      ]
    }
  ]
```

Then the editor will just rely on the simpler:

```
 {
      "name": "justauth.type",
      "type": "java.util.Map<me.zhyd.oauth.config.AuthDefaultSource,me.zhyd.oauth.config.AuthConfig>",
      "description": "JustAuth 配置.",
      "sourceType": "com.xkcoding.justauth.autoconfigure.JustAuthProperties"
    }
```

And I think it should then work correctly.

For the record, I did not actually verify this as it is a little difficult for me to strip out the metadata from the jar. But in theory I think it should work (as was verified by my own similar example earlier).

**Comment by yl-yue** [comment] 2020-09-24 03:48
Sorry for the amount of work you had to do to deal with this issue. Although we have identified the cause as **justAuth** irregularities, the main reason For my confusion is that the `IntelliJ IDEA` used by my colleagues was properly displayed, which is why the problem was initially pointed to the `Spring Generic Editor`.

**Comment by kdvolder** [comment] 2020-09-25 14:36
No problem. There is no need to apologise. You did the right thing filing the report. Please do not hesitate to file more reports in the future.
