### ISSUE TITLE
Errors in eclipse log when running with Java 11

### ISSUE THREAD

**Issue by gayanper** [spring-projects/sts4#99] opened 2018-10-03 13:22 UTC
There a lot of bundle resolution errors when running eclipse 2018-09 with STS4 on java 11

**Comment by martinlippert** [comment] 2018-10-03 15:41
How did you install STS4 into Eclipse 2018-09 ?!? I double checked this multiple times to make sure the necessary bundles are being installed automatically to make Eclipse and STS4 run on a JDK 11. Can you provide more details how you installed this?

**Comment by gayanper** [comment] 2018-10-04 13:42
I used this http://download.springsource.com/release/TOOLS/sts4/update/4.0.0.RELEASE/e4.9. there was some other bundle failures as well from code recommenders rss feed plugin. I will uninstall and let you know spring failures was caused by it.

**Comment by martinlippert** [comment] 2018-10-04 14:19
Can you provide a few steps how to reproduce this? I know that this might be difficult, but installing the Spring Tools 4 into a plain Eclipse 2018-09 running on JDK11 should work just fine. Eclipse 2018-09 itself doesn't run well on JDK11 due to some missing packages, but installing the Spring Tools 4 should install those missing packages automatically. Looks like this wasn't the case for you.

It would also be interesting to see which bundles are installed and in what state they are. Would you open an OSGi Host Console (from the Console view), type in `ss` for `short status` and attach the result as a text file maybe? That would be quite interesting.

Sorry to bother you with more details and steps, but it would be good to get to the bottom of this issue here, I think.

There are three other things I would recommend:

- start your Eclipse with `-clean`, it will re-run the bundle resolution and might result in a different (maybe better) result
- you can go to https://spring.io/tools and download a ready-to-use STS4 distribution, which is based on Eclipse 2018-09 and should work out-of-the-box with JDK11.
- you could also modify the eclipse.ini file to run the IDE on a different JDK like JDK 8/9/10.

Just a few more thoughts on this.

**Comment by martinlippert** [comment] 2018-10-19 14:16
The out-of-the-box distribution of STS4 runs on JDK 11 without those resolution problems and the usual install into Eclipse, too. But plain Eclipse 2018-09 does not run fine on JDK 11, so there might be additional fixes coming up for this scenario in the upcoming Eclipse 2018-12 release. Since there is not a lot that we can do about this at the moment, I hope that my comment above helped to mitigate this issue. Closing this for now. If this is still an issue, please comment and we can re-open.

**Closed by martinlippert** 2018-10-19 14:16 UTC
