### ISSUE TITLE
support range markers show `Computing...` when looking for quick fixes

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#989] opened 2023-03-07 12:13 UTC
The support range markers look like they have a quick fix available (the quick fix context-menu item is enabled for them), but trying to show the quick fixes shows them as `Computing...`.

Since there are no quick fixes available for those support range markers, they should be marked as not having quick fixes, so that there is nothing trying to show quick fixes on the UI.

**Comment by BoykoAlex** [comment] 2023-03-07 19:40
Good catch... I feel like I might have spotted this before but didn't pay enough attention. This looks like a regression on the LSP4E side (refactoring of server executors api). Here is the PR for lsp4e: https://github.com/eclipse/lsp4e/pull/531

**Comment by BoykoAlex** [comment] 2023-03-08 21:39
Should be fixed in LSP4E via https://github.com/eclipse/lsp4e/pull/535

**Closed by BoykoAlex** 2023-03-08 21:39 UTC
Labels: type: bug, for: eclipse, for: vscode, theme: validation
