### ISSUE TITLE
Installing Roo Support fails on Eclipse IDE for Enterprise Java Developers 2020-09 (4.17.0) Build id: 20200910-1200 with STS 4.8.0

### ISSUE THREAD

**Issue by nvulin** [spring-projects/sts4#557] opened 2020-10-25 07:40 UTC
Environment:

Eclipse IDE for Enterprise Java Developers (includes Incubating components)
Version: 2020-09 (4.17.0)
Build id: 20200910-1200
OS: Windows 10, v.10.0, x86_64 / win32
Java version: 14.0.2

+Installed Spring Tools 4 (aka Spring Tools Suite 4) 4.8.0 release from Eclipse Marketplace.

Installing from:

Spring IDE - http://dist.springframework.org/release/IDE/

Reports error:

Cannot complete the install because one or more required items could not be found.
  Software being installed: Spring IDE Roo Support 3.9.14.202009150957-RELEASE (org.springframework.ide.eclipse.roo.feature.feature.group 3.9.14.202009150957-RELEASE)
  Missing requirement: Spring IDE Roo Support 3.9.14.202009150957-RELEASE (org.springframework.ide.eclipse.roo.feature.feature.group 3.9.14.202009150957-RELEASE) requires 'org.eclipse.equinox.p2.iu; org.eclipse.ajdt.feature.group 2.0.1' but it could not be found

**Comment by martinlippert** [comment] 2020-10-26 12:15
Closing this as a duplicate of this question on SO:
https://stackoverflow.com/questions/64521532/why-installing-roo-support-fails-on-eclipse-ide-for-enterprise-java-developers-2

Answer provided on SO as well.

**Closed by martinlippert** 2020-10-26 12:15 UTC
