### ISSUE TITLE
No code-block indentation with WildWebDeveloper editor.

### ISSUE THREAD

**Issue by 4javier** [spring-projects/sts4#411] opened 2020-02-17 18:58 UTC
> Spring Tool Suite 4
> Version: 4.5.1.RELEASE
> Build Id: 202001211336
> 
> Eclipse Web Developer Tools 3.16
> Wild Web Developers 0.8.1

Using WWD Generic Editor when I select multiple lines of code in an .html file and try to block-indent with TAB, nothing occurs.
Other people realized that this behaviour could be due to a conflict with WDT.

This is the link where tests were taken:
https://github.com/eclipse/wildwebdeveloper/issues/357

**Comment by martinlippert** [comment] 2020-02-19 08:57
As mentioned in the comments in https://github.com/eclipse/wildwebdeveloper/issues/357, the underlying problem is caused by WTP and appears when WWD is installed in combination with WTP. There is a fix in WTP for this that will be part of Eclipse 2020-03 and therefore will ship with the next Spring Tools 4 for Eclipse 4.6.0 release by the end of March.

The additional action from our side is to switch to WWD instead of WTP, which is captured and discussed here: https://github.com/spring-projects/sts4/issues/354

**Closed by martinlippert** 2020-02-19 08:57 UTC
