### ISSUE TITLE
popup warning message to show missing tools.jar even I config java.home property to point to JDK8 correctly

### ISSUE THREAD

**Issue by danielludan** [spring-projects/sts4#32] opened 2018-01-03 06:12 UTC
I have configured java.home property to point to JDK8 which tools.jar resided in lib folder but still get this warning.

**Comment by martinlippert** [comment] 2018-01-03 10:14
I assume you are running in VSCode here, right? The tooling uses the environment variable `JAVA_HOME`, not a property called `java.home`.

**Comment by danielludan** [comment] 2018-01-03 10:30
@martinlippert: thanks for response, actually I have set my JAVA_HOME system property in my .profile and below is the output on vscode's terminal:

localhost:racl daniel$ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home
localhost:racl daniel$

**Comment by martinlippert** [comment] 2018-01-03 14:22
Hmmm... That looks absolutely fine. Really wonder why the message appears. Do you get the live hovers when running boot projects with actuators?

**Comment by kdvolder** [comment] 2018-01-03 16:07
Because you see environment variable in your command-line terminal doesn't necessarily mean that it also set in the vscode process. I'm no expert on how exactly Mac OS sets environment variables for processes started from the GUI but it is very likely it doesn't run your bash profile when launching gui processes. So unless you actually launched vscode from the CLI (instead of clicking on a icon in the GUI) then checking env vars in the CLI isn't a good way to check the env var values.

**Comment by BoykoAlex** [comment] 2018-01-03 16:21
Launch your VSCode with Boot-Java extension, open Java file. I guess you'd see the `tools.jar` warning in your case.
Now launch `jconsole` it's under `JAVA_HOME/bin` and connect to JarLauncher process (hopefully there is only one). This should the language server process. Navigate to `VM Summary` tab and try to see which Java version has been used to run Language Server process... it might be that it is Java 9 used to launch the process... and if it is then it's this issue: https://github.com/spring-projects/sts4/issues/30 which should be fixed in the nightly build.

**Comment by danielludan** [comment] 2018-01-04 01:37
@BoykoAlex : Thanks for the info. I just tried to use jconsole to connect JarLauncher process(ensure it only one started by vscode) and got below info:


class path: /Users/daniel/.vscode/extensions/Pivotal.vscode-boot-java-0.1.2/jars/language-server.jar

lib path:  /Users/daniel/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.

loader class path: 
/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/sunrsasign.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/classes

I noticed that it use jre/lib to find loader jar so I also tried to copy tools.jar into this folder but warning message remained.

**Comment by danielludan** [comment] 2018-01-04 01:40
@kdvolder : It seemed vscode get JAVA_HOME correctly in my case since I checked vm info from Jconsole panel that show loader class path read from JDK1.8.

**Comment by danielludan** [comment] 2018-01-04 01:46
@martinlippert : Actually I'm just a new vs coder from this week and I'm keeping learning this amazing IDE which look very well until now. For me, I just create a task to package my spring boot project into executable jar and run it use java -jar cmd. Not sure if this is a best practice to run spring boot in vscode IDE because I usually use context menu to directly run spring boot app from Eclipse before.  Right now this way is enough good for me since it can use remote debug by used Debugger for java plugin although it can't support live class loading function well.

**Comment by martinlippert** [comment] 2018-01-04 11:48
@danielludan There are two extensions for Java around for VSCode:

- https://marketplace.visualstudio.com/items?itemName=redhat.java
- https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-debug

(there is also a pack that contains both: https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack)

In case you have the debug support installed, you get support for launching Java code (also Spring Boot apps) from within VSCode for free. That way you would not need to run a build and run the boot app from the command line, but you would get full launch and debug support.

**Comment by martinlippert** [comment] 2018-01-04 12:33
> class path: /Users/daniel/.vscode/extensions/Pivotal.vscode-boot-java-0.1.2/jars/language-server.jar

That is clearly missing the tools.jar. The boot-java extension adds the tools.jar to the classpath for me, but not for you. That is strange.

> loader class path:
/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/sunrsasign.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/classes

This one looks like fine and almost the same than for me. @BoykoAlex do you have an additional idea why the extension can't find the tools.jar ?

**Comment by BoykoAlex** [comment] 2018-01-04 18:28
The integrated terminal view in VScode seem to work similarly to opening a new terminal window... it  doesn't show the same `JAVA_HOME` env variable value as the one used to start the VS code extension process...
I think that the message about the missing `tools.jar` is correct... think that `JAVA_HOME` for the VScode extension process is set to `/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre` and not to `/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home` for some reason... this needs to be verified however because it's just a guess at the moment.
I can't reproduce it on my end... Wonder if @danielludan can debug it a bit on his end? You'd need to:
1. Clone sts4 repo
2. Navigate to `sts4/vscode-extensions/vscode-boot-java` in the terminal window
3. Execute `./scripts/preinstall.sh`
4. Execute `npm install`
5. Open `sts4/vscode-extensions/vscode-boot-java` folder in VSCode
6 Put a breakpoint in `./node_modules/commons-vscode/lib/launch-util.js` line 178 (should be inside the body of `function findJvmFile(folderPath, file)`)
7. Start debugging extension by pressing F5. Should open another VSCode window. Use it to open a Java file inside the Spring Boot project
8. Once the Java file opened it should stop at your breakpoint first to find Java executable file. Seond time it'll stop for `tools.jar`. Check the value of the `JAVA_HOME` when that happens.

**Comment by BoykoAlex** [comment] 2018-01-17 15:20
I think we may just look for `tools.jar` in `$JAVA_HOME/../lib/tools.jar` and that would solve your issue. I also saw this in IntelliJ and that fix worked for me. Don't want to overthink it.

**Comment by moyodiallo** [comment] 2018-01-24 02:22
I am in linux(ubuntu). I had same message and fixe, like this:
I copy all files in `java-8-openjdk-amd64/lib` to `java-8-openjdk-amd64/jre/lib`

**Comment by bkbonner** [comment] 2018-01-27 12:50
I"m having a similar experience.

Here's the output from boot-java-debug-log:

```
Activating 'boot-java' extension
Found java exe: /usr/bin/java
isJavaEightOrHigher => true
Redirecting server logs to /tmp/boot-java-1517056523255.log
CMD = /usr/bin/java -Dserver.port=45556 -Dsts.lsp.client=vscode -Dorg.slf4j.simpleLogger.logFile=/tmp/boot-java-1517056523255.log -cp /home/bbonner/.vscode/extensions/Pivotal.vscode-boot-java-0.1.3-201801270054/jars/language-server.jar org.springframework.boot.loader.JarLauncher
ERR: Redirecting log output to: /tmp/boot-java-1517056523255.log
ERR: 

Child process connected on port 45556
ERR: Exception in thread "Timer-0" 
ERR: java.lang.NoClassDefFoundError: com/sun/tools/attach/VirtualMachine
	at org.springframework.ide.vscode.commons.boot.app.cli.SpringBootAppCache.refresh(SpringBootAppCache.java:37)
	at org.springframework.ide.vscode.commons.boot.app.cli.SpringBootAppCache.getAllRunningJavaApps(SpringBootAppCache.java:31)
	at org.springframework.ide.vscode.commons.boot.app.cli.SpringBootApp.getAllRunningJavaApps(SpringBootApp.java:81)
	at org.springframework.ide.vscode.commons.boot.app.cli.SpringBootApp.getAllRunningSpringApps(SpringBootApp.java:87)
	at org.springframework.ide.vscode.boot.java.utils.SpringLiveHoverWatchdog.update(SpringLiveHoverWatchdog.java:168)
	at org.springframework.ide.vscode.boot.java.utils.SpringLiveHoverWatchdog$2.run(SpringLiveHoverWatchdog.java:108)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

ERR: WARNING	?	pool-2-thread-1	2018-01-27T12:35:29.048Z	org.eclipse.lsp4j.jsonrpc.RemoteEndpoint#handleNotification	Notification threw an exception: {
  "jsonrpc": "2.0",
  "method": "textDocument/didOpen",
  "params": {
    "textDocument": {
      "uri": "file:///home/bbonner/work/springbookdemo/server/src/main/java/com/bonner/brian/demo/DemoApplication.java",
      "languageId": "java",
      "version": 1,
      "text": "package com.bonner.brian.demo;\n\nimport org.springframework.boot.SpringApplication;\nimport org.springframework.boot.autoconfigure.SpringBootApplication;\n\n@SpringBootApplication\npublic class DemoApplication {\n\n\tpublic static void main(String[] args) {\n\t\tSpringApplication.run(DemoApplication.class, args);\n\t}\n}\n"
    }
  }
}
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:53)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:126)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:172)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:143)
	at org.springframework.ide.vscode.commons.languageserver.LaunguageServerApp.lambda$null$1(LaunguageServerApp.java:229)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:149)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:84)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:51)
	... 12 more
Caused by: java.lang.NoClassDefFoundError: com/sun/tools/attach/VirtualMachine
	at org.springframework.ide.vscode.commons.boot.app.cli.SpringBootAppCache.refresh(SpringBootAppCache.java:37)
	at org.springframework.ide.vscode.commons.boot.app.cli.SpringBootAppCache.getAllRunningJavaApps(SpringBootAppCache.java:31)
	at org.springframework.ide.vscode.commons.boot.app.cli.SpringBootApp.getAllRunningJavaApps(SpringBootApp.java:81)
	at org.springframework.ide.vscode.commons.boot.app.cli.SpringBootApp.getAllRunningSpringApps(SpringBootApp.java:87)
	at org.springframework.ide.vscode.boot.java.utils.SpringLiveHoverWatchdog.update(SpringLiveHoverWatchdog.java:145)
	at org.springframework.ide.vscode.boot.java.BootJavaLanguageServer.lambda$new$2(BootJavaLanguageServer.java:150)
	at org.springframework.ide.vscode.commons.languageserver.util.ListenerList.fire(ListenerList.java:24)
	at org.springframework.ide.vscode.commons.languageserver.util.SimpleTextDocumentService.didOpen(SimpleTextDocumentService.java:188)
	... 17 more
Caused by: java.lang.ClassNotFoundException: com.sun.tools.attach.VirtualMachine
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 25 more
```

I have java installed, but specified it in vs code at:
```
{
    "java.home": "/usr/lib/jvm/java-8-openjdk-amd64/",
    "java.trace.server": "verbose"
}
```

**Comment by martinlippert** [comment] 2018-01-30 09:26
I think the Spring Boot Java extension doesn't take the 'java.home' setting from the vscode-java extension into account yet and tries to find the JVM via the JAVA_HOME env variable instead. Can you try to set that to a JDK instal to see if that works?

**Comment by indrajeet4192** [comment] 2019-02-27 08:38
I am facing this issue in STS4 eclipse edition . Any suggestions for me ?

**Comment by martinlippert** [comment] 2019-02-28 10:31
@indrajeet4192 the important piece here is to identify the JDK/JRE you are using to run Eclipse or STS with. Did you configure anything special in the ini file? You can always double check by going to the `About` dialog, select the `Installation Details` and switch to the`Configuration` tab. There you should see the environment variables like `java.home` or `java.version`, etc.

In case there is a JRE defined and used, I would recommend to set the JVM to run the IDE to a JDK via the ini file (either `eclipse.ini` or `SpringToolSuite4.ini`, depending on your install). Details how to configure the JDK there can be found here: https://wiki.eclipse.org/Eclipse.ini

**Comment by indrajeet4192** [comment] 2019-03-02 08:03
Thanks Martin , I really appreciate your help !

Thanks and Regards,
Indrajeet Udawant

**Comment by martinlippert** [comment] 2021-02-23 14:46
I am closing this one here for now, looks like we fixed the issue with the VSCode extension looking for the `tools.jar` file in different locations. And it looks like we answered additional questions around that topic as well. If you are still coming across this issue, please comment and we can re-open.

**Closed by martinlippert** 2021-02-23 14:46 UTC
