### ISSUE TITLE
Getting Could not instrument class xxxxxx_$$_javassist_0: Class versions V1_5 or less must use F_NEW frames.. after upgrading from 4.5.0 to 4.6.1

### ISSUE THREAD

**Issue by karapapas** [spring-projects/sts4#456] opened 2020-05-03 15:43 UTC
Even though the project launches successfully, I'm getting a bunch of these warnings for my model classes. 

`Could not instrument class xxxx_$$_javassist_334: Class versions V1_5 or less must use F_NEW frames..
`

All I did was to upgrade STS4 from 4.5.0 to 4.6.1. So far, I've been reading about javaassist, m2e and other possible solutions but I really haven't made any progress. Please could someone explain to me, what exactly that error/warning means and how to avoid it, apart from switching back to the older version of STS. If you need more info about the installation please ask me. Thank you!

**Comment by karapapas** [comment] 2020-05-03 15:44
`Could not instrument class xxxx_$$_javassist_334: Class versions V1_5 or less must use F_NEW frames..
`

**Comment by martinlippert** [comment] 2020-05-04 07:55
As far as I remember, I haven't seen this before and I wonder how an upgrade of the IDE could cause this, so lets find out. Do you have a sample project and a few steps to reproduce this issue?

**Comment by karapapas** [comment] 2020-05-04 12:14
It's quite a massive project and it's also NDA protected so it's a bit hard to provide a sample. I have a suggestion though that might help to shed some light on the matter. 

Apart from my STS4 4.6.1 installation, I also have an Eclipse installation which has most of its Pivotal modules on version 4.5.0. and it doesn't have this behavior for the same project. I have attached the info for all installed modules for both of the IDEs and I hope this helps a little.

[modules_eclipse_450.txt](https://github.com/spring-projects/sts4/files/4574521/modules_eclipse_450.txt)
[modules_sts4_461.txt](https://github.com/spring-projects/sts4/files/4574522/modules_sts4_461.txt)

**Comment by kdvolder** [comment] 2020-05-04 16:28
As possible hint on what component is producing the error. Can you:

- tell us where you see this error (e,g, a popup, eclipse problems view, eclipse error log, application console output, ...)
- If there is a stack trace with the error, include the full text of the error including the stacktrace.

**Comment by karapapas** [comment] 2020-05-04 18:56
Thank you for the response!

It's on the STS console, it happens during the Tomcat launch, right after flyway completes the migration process and right before the initialization of "Spring FrameworkServlet".

I'm not sure if it's a warning or an error, but it reads exactly "Could not instrument class artifact/model/class_$$_javassist_347: Class versions V1_5 or less must use F_NEW frames..".

Also, the Tomcat launch completes successfully and the app works without any problem.

**Comment by martinlippert** [comment] 2020-05-05 11:22
So as far as I understand, this shows up in the console output of the tomcat launch while the app starts up, right? And doing the same with STS4 4.5.0 works just fine, while running the same with STS4 4.6.1 produces the output that you mentioned, right?

It also looks to me like the version 4.5.0 that you  mentioned got installed into a Eclipse Java package installation rather than a self-contained STS4 4.5.0 distribution, right? Our log output reveals something in that direction.

So it looks like we might need to debug this step by step. First thing to check would be whether the JDK that you configured to launch Tomcat is exactly the same JDK on both machines. Whenever those error messages contain anything about "class version" that makes me think about different JDK versions being used (for running, compiling, etc). Can you double check that?

The other next step could be to download a self-contained fresh distribution of STS4 4.5.0 to double check how that behaves (compared to your Eclipse-install-based version of it). Then we could try a version of STS4 4.6.1 which is based on the same Eclipse base version, just to see if the update of the underlying Eclipse platform causes this. An alternative way to do this would be to grab a latest Eclipse release of your choice, try to run the app without any Spring tooling involved, and if that succeeds, install the STS4 components on top of it to see if that changes anything.

Sounds a bit tedious to do, but that is the only idea I have at the moment to identify the area that causes this problem.

**Comment by kdvolder** [comment] 2020-05-06 18:33
As a possible way to determine without a doubt which JDK or JRE is actually being used for launching the process, you could use 'jconsole' commandline utility that comes with JDK. 

With that tool you can connect to the launched process and look at the 'VM summary' tab. There it will display exactly what JVM is being used and how it is being launched.

**Comment by karapapas** [comment] 2020-05-07 04:28
The JDK is exactly the same on both IDEs and it's the AdoptOpenJDK version 8.0.232.09. I have manually installed it and selected it as installed JRE. Also I have uninstalled any other JREs and JDKs on my machine. Finally again on both IDEs, I have selected it as the JRE for the project build path. So, I believe this rules out the jdk.

One more thing that I have tried is to remove any excess, compared to 4.5.0, installation from 4.6.1 in order to see if this is caused by any of these complementary programs, like m2e, oomph, etc. The result was that I have removed about 15 of these yet with no luck, the message remains.

There are two things that annoy me on this matter, the first is that I can't find any resource on what exactly class instrumentation is. And the second is that it's not clear which plugin is responsible for this task. The only thing that I have found regarding instrumentation is that EclEmma maybe plays such a role, you can search for it by "EclEmma will automatically instrument your class files". However, installing EclEmma doesn't make any difference.

So the next thought is to install what I have in 4.5.0 and is missing in 4.6.1

**Comment by BoykoAlex** [comment] 2020-05-07 13:20
Is the Spring app deployed to Tomcat or TC Server?

**Comment by martinlippert** [comment] 2020-05-07 13:41
Looks like the discussion/question is cross-posted on SO here: https://stackoverflow.com/questions/61649995/to-instrument-a-class-what-exactly-does-it-mean-which-software-is-responsible - we should work on one of those questions, not both in parallel

**Comment by karapapas** [comment] 2020-05-07 15:02
@BoykoAlex It's deployed on Tomcat v7.0

**Comment by kdvolder** [comment] 2020-05-07 17:02
TBH, also not sure what component is trying to instrument your classes. But since the error is appearing in tomcat console log (right?), then it seems that is probably something that is either part of your project itself or something that is part of tomcat.

BTW: 'Javassist' is a well-known byte-code instrumentation toolkit that is used by many things. 

Here's a nice article about it: https://www.baeldung.com/javassist

The error seems related to Javassist. Does your project have javassist on its classpath?

**Comment by kdvolder** [comment] 2020-05-07 17:07
Does this 'artifact/model/class_$$_javassist_347' seem like it relates to one of your classes? (I.e do you have classes who's name resembles this? Or maybe a package called 'artifact.model'? (I am trying to determine whether the class the error complains about comes from your project, or from something/somewhere else.

**Comment by karapapas** [comment] 2020-05-08 05:06
@kdvolder Great article on JavaAssist, thank you! The message is just an example, it looks like this `Could not instrument class com/company/project/model/subfolder/ClassName$$_javassist_346: Class versions V1_5 or less must use F_NEW frames..` and it's thrown for every class on my model folder.

**Comment by kdvolder** [comment] 2020-05-11 16:24
There's two questions that I would want to try and answer somehow... 

1. What thing/component is trying to intrument your classes. 
2. Why does it cause an error that seems to say the classes where compiled targetting a very old version of Java (i.e. it says V1_5 or less).

Re 1, I was asking whether your project has javassist as a dependency (maybe indirectly through another dependency). Or maybe there's a maven plugin your are using that makes use of it. If you could try to determine that somehow that would be great. A good place to start would be in the 'dependency tree' view that you can access from one of the editor tabs when you open a pom file.

Re 2: I would like to verify what the .class file looks (any one of the classes that gives you an error will do).

You can use command like `javap` (comes installed with JDK) to inspect the class content / details.

For example:

```
$ javap -v DemoApplication.class
Classfile /home/kdvolder/tmp/hello-world-service/target/classes/com/example/demo/DemoApplication.class
  Last modified 5-May-2020; size 733 bytes
  MD5 checksum d1ea3dcec738b71bedeb29c5d135199c
  Compiled from "DemoApplication.java"
public class com.example.demo.DemoApplication
  minor version: 0
  major version: 52
  flags: ACC_PUBLIC, ACC_SUPER
Constant pool:
```

What we are interested in specifically is the 'minor / major version' information. This indicates the version of Java bytecodes that was targetted by the compiler. 

See: https://en.wikipedia.org/wiki/Java_class_file

```
major version number of the class file format being used.
Java SE 14 = 58 (0x3A hex),
Java SE 13 = 57 (0x39 hex),
Java SE 12 = 56 (0x38 hex),
Java SE 11 = 55 (0x37 hex),
Java SE 10 = 54 (0x36 hex),[3]
Java SE 9 = 53 (0x35 hex),[4]
Java SE 8 = 52 (0x34 hex),
Java SE 7 = 51 (0x33 hex),
Java SE 6.0 = 50 (0x32 hex),
Java SE 5.0 = 49 (0x31 hex),
JDK 1.4 = 48 (0x30 hex),
JDK 1.3 = 47 (0x2F hex),
JDK 1.2 = 46 (0x2E hex),
JDK 1.1 = 45 (0x2D hex)
```

As you can see in my output, my project was targeting major version '52' which corresponds to Java 1.8. So how about your classes?

**Comment by kdvolder** [comment] 2020-05-11 16:35
BTW: What I'm thinking is that the problem is probably something misconfigured in the project, either a problem in the project pom itself, or something going wrong in how the tooling is mapping pom configuration onto Eclipse JDT configuration. 

From the looks of things (i.e. the error message), you classes are being targetted for running on a old JVM. Now... it is important to understand that new versions of the JRE / JDK and JDT compiler are perfectly capable of generating bytecodes that are compliant with old JRE versions. And its possible to configure projects in such a way that this is what it does. I am thinking that must be the case here (so you have only a new JRE/JDK, but... something is telling Eclipse or maven, or both to compile the code targeting an older JRE.

Some questions in that direction:

- does your pom have something like this:

```
	<properties>
		<java.version>1.8</java.version>
	</properties>
```

... or this: https://www.baeldung.com/maven-java-version

If no, try adding something like that. If yes... let's look at Eclipse settings...

- Right click on the project
- Select 'Properties'
- Select 'Java Compiler'
- Take screenshot and post here (similar to mine below)

![java-compiler-settings](https://user-images.githubusercontent.com/1002156/81586673-baeafc00-936a-11ea-8a5f-2d9d15861103.png)

**Comment by sro-orcasys** [comment] 2020-07-09 12:49
I have the same problem since I upgraded to STS 4.6.0.

Could not instrument class ch/orcasys/olo/model/permission/Permission_$$_javassist_61: Class versions V1_5 or less must use F_NEW frames..

I start the project from Eclipse with a maven goal using the jetty plugin.
I would be glad to assist in solving the problem, let me know what I should do.

**Comment by martinlippert** [comment] 2020-07-09 13:18
@sro-orcasys @karapapas I found something that might be related to this issue. There seems to be a javaagent-based bytecode modification that happens when you launch apps from the IDE (in order to improve source lookup functionality). I haven't looked into the details yet, but maybe it is worth a try. There is a preference in `Preferences -> Java -> Debug` that is called `Use advanced source lookup`. What happens if you disable that? Does that make a difference?

**Comment by sro-orcasys** [comment] 2020-07-09 14:39
Yes, it does make a difference: the log statements are now gone. 
If you have any more insights on the issue I would be glad if you would share them here.

Thank you very much for your help.

**Comment by martinlippert** [comment] 2020-07-10 09:15
More details on this can be found here:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=506149

Hope this helps! Further questions and investigations into this should probably go into comments to the mentioned bug at Eclipse or a new one over there.

Therefore closing this one here.

**Closed by martinlippert** 2020-07-10 09:15 UTC
