### ISSUE TITLE
Quick fix / hover help anomaly

### ISSUE THREAD

**Issue by SledgeHammer01** [spring-projects/sts4#580] opened 2020-12-30 17:43 UTC
Using STS 4.9.0 on Windows 10 Pro x64.

This is my playground project, so it has a bunch of different dependencies including Spring Data MongoDB and the MongoDB DSL support. But nothing crazy, the pom is only 375 lines.

I added the following line to a service layer class:

`BooleanBuilder builder = new BooleanBuilder();`

and got red squiggles on both sides as expected. By habit, I usually hover over the left side and use the hover tip to import the class.

In this particular case, the left side results in 1165 quick fixes and effectively kills the IDE performance wise. When I hover over the right side however, it narrowed it down to only 75. The IDE handles 75 just fine, its pretty instant. The 1165, not so much :).

By habit, I've always hovered over the left side and I've never ran into this before. Just odd to see such a big discrepancy between the left and right sides.

**Comment by martinlippert** [comment] 2021-01-11 10:31
I tried a simple project, but that doesn't seem to reproduce the issue. In order to further analyze this, it would be great if you could attach a simple sample project that reproduces this behavior.

Another interesting data point would be to see if the Eclipse IDE in general (the plain Eclipse Java package, for example) behaves the same when importing the project as a Maven project.

**Comment by SledgeHammer01** [comment] 2021-01-11 16:32
> I tried a simple project, but that doesn't seem to reproduce the issue. In order to further analyze this, it would be great if you could attach a simple sample project that reproduces this behavior.
> 
> Another interesting data point would be to see if the Eclipse IDE in general (the plain Eclipse Java package, for example) behaves the same when importing the project as a Maven project.

You can try with this pom. The left side suggests four BooleanBuilders, but then after that, it also suggests about 1000 Builders. The right side suggests only one BooleanBuilder (the right one) and some Bool* classes as well as some Builder classes, but only 75 quick fixes total on the right vs. 1175 on the left.

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>org.xxx</groupId>
	<artifactId>xxx</artifactId>
	<version>0.0.1</version>
	<name>xxx</name>
	<description>xxx</description>
	<packaging>war</packaging>
	<repositories>
		<repository>
			<id>central</id>
			<url>https://repo1.maven.org/maven2/</url>
		</repository>
		<!--
		<repository>
			<id>repository.spring.milestone</id>
			<url>https://repo.spring.io/milestone</url>
		</repository>
		-->
	</repositories>
	<profiles>
		<profile>
			<id>tomcat</id>
			<activation>
				<activeByDefault>false</activeByDefault>
			</activation>
			<properties>
				<spring.profiles.active>tomcat</spring.profiles.active>
			</properties>
		</profile>
		<profile>
			<id>docker</id>
			<activation>
				<activeByDefault>false</activeByDefault>
			</activation>
			<properties>
				<spring.profiles.active>docker</spring.profiles.active>
			</properties>
		</profile>
	</profiles>
	<properties>
		<java.version>11</java.version>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<tomcat.version>9.0.41</tomcat.version>
		<spring-cloud.version>3.0.0</spring-cloud.version>
		<graphql.version>8.1.1</graphql.version>
		<kafka.version>2.7.0</kafka.version>
		<hazelcast.version>4.1</hazelcast.version>
		<bucket4j.version>6.0.0</bucket4j.version>
	</properties>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.4.1</version>
		<relativePath /> <!-- lookup parent from repository -->
	</parent>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-cache</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-configuration-processor</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.data</groupId>
			<artifactId>spring-data-ldap</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-thymeleaf</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-tomcat</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.junit.vintage</groupId>
					<artifactId>junit-vintage-engine</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.vaadin.external.google</groupId>
					<artifactId>android-json</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-jwt</artifactId>
			<version>1.1.1.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.security.oauth.boot</groupId>
			<artifactId>spring-security-oauth2-autoconfigure</artifactId>
			<version>2.2.11.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>org.apache.tomcat</groupId>
			<artifactId>tomcat-dbcp</artifactId>
			<version>${tomcat.version}</version>
		</dependency>
		<dependency>
			<groupId>com.microsoft.sqlserver</groupId>
			<artifactId>mssql-jdbc</artifactId>
			<version>8.4.1.jre11</version> <!-- $NO-MVN-MAN-VER$ -->
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-jdbc</artifactId>
			<version>5.3.2</version> <!-- $NO-MVN-MAN-VER$ -->
		</dependency>
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-core</artifactId>
			<version>5.4.27.Final</version> <!-- $NO-MVN-MAN-VER$ -->
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-orm</artifactId>
			<version>5.3.2</version> <!-- $NO-MVN-MAN-VER$ -->
		</dependency>
		<dependency>
			<groupId>org.springframework.data</groupId>
			<artifactId>spring-data-elasticsearch</artifactId>
			<version>4.1.2</version> <!-- $NO-MVN-MAN-VER$ -->
		</dependency>
		<dependency>
			<groupId>org.springframework.data</groupId>
			<artifactId>spring-data-cassandra</artifactId>
			<version>3.1.2</version> <!-- $NO-MVN-MAN-VER$ -->
		</dependency>
		<dependency>
			<groupId>org.springframework.data</groupId>
			<artifactId>spring-data-mongodb</artifactId>
			<version>3.1.2</version> <!-- $NO-MVN-MAN-VER$ -->
		</dependency>
		<dependency>
			<groupId>org.mongodb</groupId>
			<artifactId>mongodb-driver-sync</artifactId>
			<version>4.1.1</version> <!-- $NO-MVN-MAN-VER$ -->
		</dependency>
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<version>8.0.22</version> <!-- $NO-MVN-MAN-VER$ -->
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-neo4j</artifactId>
			<version>2.4.1</version> <!-- $NO-MVN-MAN-VER$ -->
		</dependency>
		<dependency>
			<groupId>org.springframework.kafka</groupId>
			<artifactId>spring-kafka</artifactId>
			<version>2.6.4</version> <!-- $NO-MVN-MAN-VER$ -->
		</dependency>
		<dependency>
			<groupId>org.apache.kafka</groupId>
			<artifactId>kafka-streams</artifactId>
			<version>${kafka.version}</version> <!-- $NO-MVN-MAN-VER$ -->
		</dependency>
		<dependency>
			<groupId>org.apache.kafka</groupId>
			<artifactId>kafka-clients</artifactId>
			<version>${kafka.version}</version> <!-- $NO-MVN-MAN-VER$ -->
		</dependency>
		<dependency>
			<groupId>com.hazelcast</groupId>
			<artifactId>hazelcast-eureka-one</artifactId>
			<version>2.0.1</version>
		</dependency>
		<dependency>
			<groupId>com.giffing.bucket4j.spring.boot.starter</groupId>
			<artifactId>bucket4j-spring-boot-starter</artifactId>
			<version>0.2.0</version>
		</dependency>
		<dependency>
			<groupId>com.hazelcast</groupId>
			<artifactId>hazelcast</artifactId>
			<version>${hazelcast.version}</version> <!-- $NO-MVN-MAN-VER$ -->
		</dependency>
		<dependency>
			<groupId>com.hazelcast</groupId>
			<artifactId>hazelcast-spring</artifactId>
			<version>${hazelcast.version}</version> <!-- $NO-MVN-MAN-VER$ -->
		</dependency>
		<dependency>
			<groupId>com.github.vladimir-bukhtoyarov</groupId>
			<artifactId>bucket4j-core</artifactId>
			<version>${bucket4j.version}</version>
		</dependency>
		<dependency>
			<groupId>com.github.vladimir-bukhtoyarov</groupId>
			<artifactId>bucket4j-jcache</artifactId>
			<version>${bucket4j.version}</version>
		</dependency>
		<dependency>
			<groupId>com.github.vladimir-bukhtoyarov</groupId>
			<artifactId>bucket4j-hazelcast</artifactId>
			<version>4.10.0</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
			<version>${spring-cloud.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-bootstrap</artifactId>
			<version>${spring-cloud.version}</version>
		</dependency>
		<dependency>
			<groupId>com.github.ben-manes.caffeine</groupId>
			<artifactId>caffeine</artifactId>
			<version>2.8.8</version> <!-- $NO-MVN-MAN-VER$ -->
		</dependency>
		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>30.1-jre</version>
		</dependency>
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>2.8.6</version> <!-- $NO-MVN-MAN-VER$ -->
		</dependency>
		<dependency>
			<groupId>org.modelmapper</groupId>
			<artifactId>modelmapper</artifactId>
			<version>2.3.9</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-text</artifactId>
			<version>1.9</version>
		</dependency>
		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-ui</artifactId>
			<version>1.5.2</version>
		</dependency>
		<dependency>
			<groupId>org.zalando</groupId>
			<artifactId>logbook-spring-boot-starter</artifactId>
			<version>2.4.1</version>
		</dependency>
		<dependency>
			<groupId>com.graphql-java-kickstart</groupId>
			<artifactId>graphql-spring-boot-starter</artifactId>
			<version>${graphql.version}</version>
		</dependency>
		<dependency>
			<groupId>com.graphql-java-kickstart</groupId>
			<artifactId>altair-spring-boot-starter</artifactId>
			<version>${graphql.version}</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>net.sourceforge.tess4j</groupId>
			<artifactId>tess4j</artifactId>
			<version>4.5.4</version>
		</dependency>
		<dependency>
			<groupId>net.devh</groupId>
			<artifactId>grpc-server-spring-boot-starter</artifactId>
			<version>2.10.1.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>com.querydsl</groupId>
			<artifactId>querydsl-mongodb</artifactId>
			<version>4.4.0</version> <!-- $NO-MVN-MAN-VER$ -->
		</dependency>
		<dependency>
			<groupId>com.querydsl</groupId>
			<artifactId>querydsl-apt</artifactId>
			<version>4.4.0</version> <!-- $NO-MVN-MAN-VER$ -->
		</dependency>
	</dependencies>
	<build>
		<finalName>xxx</finalName>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>    
				<groupId>com.mysema.maven</groupId>
				<artifactId>apt-maven-plugin</artifactId>
				<version>1.1.3</version>
				<executions>
					<execution>
						<goals>
							<goal>process</goal>
						</goals>
						<configuration>
							<outputDirectory>target/generated-sources/java</outputDirectory>
							<processor>org.springframework.data.mongodb.repository.support.MongoAnnotationProcessor</processor>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.sonarsource.scanner.maven</groupId>
				<artifactId>sonar-maven-plugin</artifactId>
				<version>3.7.0.1746</version>
			</plugin>
		</plugins>
	</build>
</project>

```

**Comment by martinlippert** [comment] 2021-01-12 09:22
Thanks for the `pom.xml` file. I can reproduce the issue, in the latest release of the Spring Tools 4 distribution as well as the latest Eclipse 2020-12 release. I think the problem is located in the way JDT calculates the hover and the quick fix suggestions. Therefore I filed this bug at Eclipse JDT for this: https://bugs.eclipse.org/bugs/show_bug.cgi?id=570277 - and I am closing this one here as a duplicate of that new item at Eclipse. Please add yourself to the CC list if you want to follow up on the progress there.

**Closed by martinlippert** 2021-01-12 09:22 UTC
