### ISSUE TITLE
No content model found for

### ISSUE THREAD

**Issue by OverDrone** [spring-projects/sts4#706] opened 2021-11-12 06:28 UTC
Hello!
My STS xml content assist broken. When I try to press ctrl+space in xml with DTD reference, status bar reports in red:
`No content model found for -//mybatis.org//DTD Mapper 3.0//EN/http://nexus/repository/mybatis/dtd/mybatis-3-mapper.dtd`
Error log view doesn't contain any related messages.
I'm in a closed environment without access to internet, but url http://nexus/repository/mybatis/dtd/mybatis-3-mapper.dtd works if you ctrl+click it in eclipse.
Also I might mention that validation works correctly if you type xml file content manually. That means that dtd file is loaded by IDE.
I've seen some other ppl mentioned language servers in other post, I've tried disabling all checkboxes in window/preferences/language servers, enable all checkboxes - no effect. 
I've downloaded latest version of STS 4.12.1.RELEASE 202110260750. 
My other installation of STS which was upgraded from previous version to same latest version doesn't have such issue.

**Comment by martinlippert** [comment] 2021-11-26 19:53
Can you attach a sample project that helps us to reproduce this? What would be great.

**Comment by martinlippert** [comment] 2021-12-07 11:03
This sounds a lot like a duplicate of #701, so I am closing this one here as a duplicate. Please note that #701 contains a description of how to fix the missing content-assist.. :-)

**Closed by martinlippert** 2021-12-07 11:03 UTC
Labels: status: waiting-for-feedback, type: bug, for: eclipse
