### ISSUE TITLE
4.16 -4.18 maven  add dependencies cant search 

### ISSUE THREAD

**Issue by wash1983** [spring-projects/sts4#1020] opened 2023-03-29 13:28 UTC
**Describe the bug**
1.Starting with version 4.16, the Maven repository does not have a rebuild index menu. Search cannot be used when adding dependencies.
2.pom.xml  editor can't format

**Comment by BoykoAlex** [comment] 2023-03-29 21:39
This is likely an issue with M2E eclipse project (Maven integration into Eclipse). Any chance you try thise scenario with plain Eclipse with M2E installed in it?

**Comment by martinlippert** [comment] 2023-03-30 07:48
> 2.pom.xml editor can't format

This is most likely this issue: https://github.com/eclipse/lsp4e/pull/571 - you can see the format action in the context menu, but it is disabled, right?

**Comment by martinlippert** [comment] 2023-03-30 07:56
> 1.Starting with version 4.16, the Maven repository does not have a rebuild index menu. Search cannot be used when adding dependencies.

This is most likely related to https://github.com/eclipse-m2e/m2e-core/issues/930

So I am closing this issue as a duplicate of the other two mentioned issues. Please comment if you don't agree or have additional thoughts here and we can re-open anytime.

**Closed by martinlippert** 2023-03-30 07:56 UTC
Labels: status: waiting-for-triage, type: bug
