### ISSUE TITLE
console cannot print the result.

### ISSUE THREAD

**Issue by lelebuzaizhe** [spring-projects/sts4#121] opened 2018-10-24 02:40 UTC
I am using google to translate, I hope you can understand.
When the length of sts4 stringbuffer/stringbuilder exceeds a certain value, such as 7000, the console cannot print the result.
Sts3 is ok
Thank you.

**Comment by martinlippert** [comment] 2018-10-24 07:47
Can you elaborate and maybe attach a sample project that reproduces the problem? That would be great.

Since we don't do anything special with the console, it would be great if you could also give plain Eclipse a try to see if it has the same problem - and if so, report the issue directly to Eclipse... :-)

Can you double check?

**Comment by kdvolder** [comment] 2018-10-24 14:59
I'm not sure this is what you need, but there is a preference somewhere in Eclipse to confgure how much data the Eclipse console retains. See preference page under "Preferences >> Run Debug >> Console" There is a setting called 'Console buffer size' so you can try changing that setting and see if that helps at all.

**Comment by lelebuzaizhe** [comment] 2018-10-25 02:07
ok

> I'm not sure this is what you need, but there is a preference somewhere in Eclipse to confgure how much data the Eclipse console retains. See preference page under "Preferences >> Run Debug >> Console" There is a setting called 'Console buffer size' so you can try changing that setting and see if that helps at all.

Maybe my description has a problem, you are talking about the printing of debugging information, and I mean that only "system.out.println" can't print the result.

**Comment by lelebuzaizhe** [comment] 2018-10-25 02:31
> Can you elaborate and maybe attach a sample project that reproduces the problem? That would be great.
> 
> Since we don't do anything special with the console, it would be great if you could also give plain Eclipse a try to see if it has the same problem - and if so, report the issue directly to Eclipse... :-)
> 
> Can you double check?

When I use sts4 to print the results, it doesn't show up, like on this image.
[https://raw.githubusercontent.com/lelebuzaizhe/images/master/sts4.png](url)
But when I use sts3, the same code, and it shows up like this
[https://raw.githubusercontent.com/lelebuzaizhe/images/master/sts3.png](url)
Does this look like a bug?
Or is my operation not right?
I am sorry if you are in trouble.

**Comment by lelebuzaizhe** [comment] 2018-10-25 02:35
> > Can you elaborate and maybe attach a sample project that reproduces the problem? That would be great.
> > Since we don't do anything special with the console, it would be great if you could also give plain Eclipse a try to see if it has the same problem - and if so, report the issue directly to Eclipse... :-)
> > Can you double check?
> 
> When I use sts4 to print the results, it doesn't show up, like on this image.
> [https://raw.githubusercontent.com/lelebuzaizhe/images/master/sts4.png](url)
> But when I use sts3, the same code, and it shows up like this
> [https://raw.githubusercontent.com/lelebuzaizhe/images/master/sts3.png](url)
> Does this look like a bug?
> Or is my operation not right?
> I am sorry if you are in trouble.
The picture can't be opened, you can try to copy the link to the address bar to jump, O(∩_∩)O .

**Comment by kdvolder** [comment] 2018-10-25 16:36
It does look like that might be bug, but if so, then it is most likely a bug in Eclipse not a bug in STS itself. 

It could also be that there is some mistake in your code. It is hard to really tell.

I did try running something a bit similar to your example:

```
package test;

public class Main {

	public static void main(String[] args) {
		StringBuilder buf = new StringBuilder();
		String snippet = "snippet ";
		
		while (buf.length()<7017) {
			buf.append(snippet);
		}
		
		System.out.println("Hello");
		System.out.println(buf.toString());
		
	}
}
```

That worked fine for me and printed what I was expecting, even though the String being printed is also over 7000 characters in length.

If I could reproduce the problem it might be possible to determine if this really an Eclipse bug. And we could then file a bug report with Eclipse to report it. 

If can attach a complete project in a .zip file so that we can import it, run it, and see the problem happening we can try. As it is now there isn't much we can do.

**Comment by martinlippert** [comment] 2018-11-06 09:53
I am closing this one now. As soon as there is a complete project attached that helps us to reproduce this, we can re-open and re-analyze what the problem might be.

**Closed by martinlippert** 2018-11-06 09:53 UTC
