### ISSUE TITLE
[refactoring] open editors show outdated errors when converting project to Spring Boot 3

### ISSUE THREAD

**Issue by martinlippert** [spring-projects/sts4#866] opened 2022-11-04 08:31 UTC
I have a standard petclinic, I have `Vets.java` open in a Java source code editor (without any changes), and I convert the project to Spring Boot 3 using the OpenRewrite recipes.

As a result, the source code editor for `Vets.java` shows a bunch of errors around the changed imports and it looks like the errors are referring to the document content before the conversion (since the error complains about a missing `javax` dependency, which indeed doesn't exist anymore, but the editor content refers to `jakarta` packages already, so the error markers are misplaced and wrong).

The editor shows up in "dirty" mode and when I save the editor content, the errors go away and the editor is in a good state again.

- Question 1: do we want to have those open editors in a dirty state when they weren't dirty before? (I don't think so)
- Question 2: in case we keep them in dirty state (or they were dirty before the conversion), we need to tell the source code editor somehow to reconcile the content, so that now wrong and outdated errors show up

**Comment by BoykoAlex** [comment] 2022-11-04 17:12
Question 1: Opening editors for affected files in the behaviour of vscode language client. I recall we opened an issues against vscode language client and then were transferred to VSCode itself. Don't think this behaviour is going to change.

Question 2. Perhaps the Spring errors can be removed... probably something we should be able to do. POM isn't saved. Many AST element types aren't resolved anymore and hence reconciling isn't working. Once all files are saved all shows up fine.

**Comment by martinlippert** [comment] 2022-11-04 17:20
> Question 2. Perhaps the Spring errors can be removed... probably something we should be able to do. POM isn't saved. Many AST element types aren't resolved anymore and hence reconciling isn't working. Once all files are saved all shows up fine.

I tried all this in Eclipse (the latest Spring Tools 4 distribution build on Eclipse 2022-12) and the pom file wasn't opened when I tried this, so the project was already updated to the SB3 dependencies.

**Comment by BoykoAlex** [comment] 2022-11-04 21:51
Just looked at it more carefully... Those seem to be JDT validations showing up somehow... Seems like some work to do around lsp4e :-\ I'll see to it

**Comment by martinlippert** [comment] 2022-12-02 12:42
Something to investigate further in the 4.17.1 cycle.

**Comment by BoykoAlex** [comment] 2023-01-27 03:56
The issue is NPEs for calls on `cursor` in Rewrite while executing Recipes. The recipe that throws these NPEs is `FindDependency` (maven dependency). The result looks almost good though. There is one issue in the POM that triggers these outdated errors:
```
<!--~~(Cannot invoke "org.openrewrite.Cursor.firstEnclosing(java.lang.Class)" because "cursor" is null)~~>-->
```
The snippet appears at the top of the POM file. If removed and all files saved then everything looks as expected.

I've tried to use alternative recipes but still get this error once in a while.

I think #927 is the same issue but observed in VSCode client...

**Comment by BoykoAlex** [comment] 2023-01-27 04:58
My attempt fix (pushed) is rather than use Recipe instances from the Environment that for some reason throws NPE sometimes create new Recipe instances... no NPE but results are different... to be investigated further

**Comment by BoykoAlex** [comment] 2023-02-02 03:34
This is is likely to be fixed due to commits around clearing and sending diagnostics on the same thread as well as work arounds for rewrote recipes throwing NPEs.

**Closed by BoykoAlex** 2023-02-02 03:34 UTC
Labels: type: enhancement, for: eclipse, theme: refactoring
