### ISSUE TITLE
Regression: "Class not found" during spring boot test

### ISSUE THREAD

**Issue by bmaehr** [spring-projects/sts4#406] opened 2020-02-03 12:47 UTC
After upgrading for a 4.4 version of STS to the latest 4.5.1. version I get a class not found exception for the test class when trying to run tests. Going back to an older 4.3.2 version fixes this problem.
```
@RunWith(SpringRunner.class)
@ComponentScan(basePackages = {"de.something"})
@EnableAutoConfiguration
@SpringBootTest(webEnvironment = WebEnvironment.DEFINED_PORT)
public class LegacyServiceCommunicationTest extends AbstractSoapSetupTest {

 ```

**Comment by BoykoAlex** [comment] 2020-02-03 14:38
What was the underlying version of Eclipse for you STS 4.4? What does the upgrading to STS 4.5.1 mean exactly? Update site upgrade? Or have you downloaded a new STS 4.5.1 distribution and launched it? Same goes for STS 4.3.2... Unlikely you've downgraded to 4.3.2 using update site... Thus, it is a distribution most likely and if yes Eclipse version of that STS would be most interesting.
I suspect this issue has to do more with Eclipse JDT project rather than STS4... Very likely you can reproduce this issue using different versions of Eclipse 4.13, 4.14 (no STS on top) and probably 4.15 which is in development I think

**Comment by BoykoAlex** [comment] 2020-02-03 14:42
Try a new STS 4.5.2 distribution build based on Eclipse 4.15 http://dist.springsource.com/snapshot/STS4/nightly-distributions.html
(Maybe related to https://github.com/spring-projects/spring-ide/issues/406)

**Comment by dzdunn** [comment] 2020-02-03 20:58
We have also had this issue. I just logged in to raise it.

Just to confirm, I had a colleague install and got the same problem.

However, I checked out 4.5.1.RELEASE and built locally with e415. This version works fine.

I'm wondering if it could be related to the self-extracting jar personally, but just a guess.

**Comment by kdvolder** [comment] 2020-02-03 23:45
> I'm wondering if it could be related to the self-extracting jar personally, but just a guess.

I don't think it is likely. The issue is probably the same as the one that Alex linked to. I.e. a bug in Eclipse that:

- affects windows-based Java launches on Java 9 or above projects with large number of dependencies
- was fixed in Eclipse 4.15.

> ... and built locally with e415 ...

I think that part is the most telling/important. Since the bug in question was fixed in Eclipse 4.15 it makes sense that if you create something based on Eclipse 4.15 the problem goes away.

**Comment by dzdunn** [comment] 2020-02-03 23:54
Ah I didn't have time to read the whole link earlier. FYI, we're using JDK 8, which that link implies would not suffer from the problem. But I agree it does sound very similar and my local build was with 4.15, so fingers crossed the problem's gone with 4.15!

**Comment by bmaehr** [comment] 2020-02-05 23:42
> What was the underlying version of Eclipse for you STS 4.4? What does the upgrading to STS 4.5.1 mean exactly? Update site upgrade? 

Some working final release of the STS 4.4 branch, upgraded by update function in STS

> Or have you downloaded a new STS 4.5.1 distribution and launched it? 

Yes, same problem

> Same goes for STS 4.3.2... Unlikely you've downgraded to 4.3.2 using update site... 

No downgrade, just tested with an existing old 4.3.2 installation

**Comment by bmaehr** [comment] 2020-02-05 23:47
spring-tool-suite-4-4.5.2.CI-B2150-e4.15.0 solved it

**Comment by kdvolder** [comment] 2020-02-06 00:32
Okay, thanks for confirming that @bmaehr . So I think we can close this issue assuming that the problems are down to the above mentioned Eclipse bug. It can't be totally ruled out there are other causes of this error still, but for now it seems we have no evidence of other problems.

If someone still runs into this after upgrading to an Eclipse 4.15 based build, please provide some details for us to try and reproduce and debug and we can re-open this ticket (or you can create a new one also).

**Closed by kdvolder** 2020-02-06 00:32 UTC
