### ISSUE TITLE
STS Console hang issue in 4.12.0 RELEASE 

### ISSUE THREAD

**Issue by shankarwww** [spring-projects/sts4#689] opened 2021-09-19 08:23 UTC
The console is hanging too much in this 4.12.0 RELEASE. Even the scroll bar in console in not responding frequently or its too slow to respond.

**Comment by martinlippert** [comment] 2021-09-20 07:57
Hey @shankarwww, can you provide a few steps how to reproduce the issue or record a screencast that shows the steps and what happens?

**Comment by shankarwww** [comment] 2021-09-25 12:06
Whenever the statement to log is of long length(for example: log a json in console), the console starts hanging and does not respond. The scroll does nor respond.

**Comment by martinlippert** [comment] 2021-09-27 09:34
Can you disable the ANSI Console via the icon in the Console View to see if that makes a difference?

**Comment by martinlippert** [comment] 2021-09-28 11:12
I tried to reproduce this with the latest STS 4.12.0.RELEASE version on macOS, but I don't see a slowdown in the console view. I dumped about 30000 lines of output in there while keeping the ANSI Console on, but scrolling is still smooth and very responsive. I changed the settings on the preferences for the console to use an unlimited buffer, but that didn't change anything, still responsive and fast.

Can you provide a sample project that produces the output in the console that causes the issues on your end? Maybe that helps to reproduce this. You could also experiment with the ANSI Console setting (as mentioned before) and the buffer size for the Console in general in the preferences to see if that makes a difference (to get an idea about what is causing the slowdown on your end).

**Comment by martinlippert** [comment] 2021-10-11 14:47
@shankarwww @drc5521 Thanks for the additional details, so it looks like this problem comes up even without a very long content as the console output (from looking at the video). Does this happen on a plain Eclipse 2021-09 installation as well? Would be great if you could double check that to see if the problem is more with the underlying platform or the specifics in STS.

**Comment by drc5521** [comment] 2021-10-17 12:43
> @drc5521 That is a great comparison, so looks like this is indeed related to the ANSI Console. Therefore, I filed this issue: [mihnita/ansi-econsole#66](https://github.com/mihnita/ansi-econsole/issues/66) to let the project owners take a look at this as well.
> 
> I am still wondering why this seems to be specific for Windows...

Thank you very much friend. Hope it can be solved perfectly.

**Comment by sfksuperman** [comment] 2022-01-28 15:39
I have the same issue, check [here](https://stackoverflow.com/questions/70891865/why-console-is-lagging-like-anything-in-spring-tool-suite-sts-4-13-0-release-i/70896160#70896160).
I uninstalled the ANSI Console but it is still the same. Please help.

**Comment by martinlippert** [comment] 2022-01-28 15:57
@sfksuperman Can you try to reproduce this with a plain Eclipse 2021-12 installation?

**Comment by sfksuperman** [comment] 2022-01-28 18:06
Installed Eclipse 2021-12 and imported my projects and tried to run as Java Application >> Spring Boot Application but it's failing by saying `Sources must not be empty`.

And the console looks fine to me, it's not laggy. But I will try to fix the project and run it on Eclipse and let you by tomorrow.

**Comment by sfksuperman** [comment] 2022-01-31 16:54
@martinlippert, I tested it and Eclipse seems to be working fine without any console lag. SO, how to fix the STS console?

**Comment by martinlippert** [comment] 2022-02-01 17:49
@sfksuperman Can you capture a few thread dumps of the STS process while CPU is at 100%? And also when the console is lagging? In addition to that it might also be worth to startup a profiler, attach it to the process, and record a short profiling session while the CPU is running so high to gather more details about this.

I assume that you have your IDE running on your local SSD disc with the workspace and all the projects in your workspace also reside on the local SSD disc, so that nothing sits on a network-mounted drive?

**Comment by sfksuperman** [comment] 2022-02-01 19:21
> @sfksuperman Can you capture a few thread dumps of the STS process while CPU is at 100%? And also when the console is lagging? In addition to that it might also be worth to startup a profiler, attach it to the process, and record a short profiling session while the CPU is running so high to gather more details about this.
> 
> I assume that you have your IDE running on your local SSD disc with the workspace and all the projects in your workspace also reside on the local SSD disc, so that nothing sits on a network-mounted drive?

Yes, everything is on my SSD (C drive). But I don't know much about capturing thread dumps or starting up profiler etc. If you can provide me sufficient guide on how to do it, I might reproduce and record the bug.

**Comment by BoykoAlex** [comment] 2022-02-01 21:40
Win 10 VisualVM sampling snapshot of scrolling nasi console for 30 sec.

**Comment by BoykoAlex** [comment] 2022-02-01 21:45
OSX Visual VM sampling of scrolling ansi console for 27 sec
[osx-sampling.nps.zip](https://github.com/spring-projects/sts4/files/7982120/osx-sampling.nps.zip)

**Comment by shankarwww** [comment] 2022-03-19 15:24
STS 4.14 has been released and issue still remains. It's quite sad and annoying that I have to work with ansi console disabled

**Comment by martinlippert** [comment] 2022-03-23 09:08
We will dive deeper into this and try to find a solution here. Probably involves help from other projects as well, but we will try to get everybody together for this.

**Comment by BoykoAlex** [comment] 2022-03-24 00:52
@martinlippert The issue with the console is "escape sequences" parts of strings in the console that represent color/font etc stuff. Those strings are always present on on the `StyledText` control. There is a preferences that toggle's their visibility in the console view: **Show the escape sequences** under **ANSI Console** preferences. If shown "escape sequences" strings show up with some special font, otherwise they are made invisible with:
```java
range.metrics = new GlyphMetrics(0, 0, 0); // Hide the codes
```
The point is that these strings are always present on the `StyledText` control. If they are removed the scrolling performance is great again.
I'd direct this to someone on SWT Win team. I have an SWT code snippet to reproduce the issue.

**Comment by martinlippert** [comment] 2022-03-24 08:33
@BoykoAlex thanks for diving deeper into this. Please open a bug report for SWT for this and attach the SWT code snippet that reproduces the slowdown and add a link to that bugzilla issue here. I will let the SWT know about this then and hope to raise some interest in it... :-)

**Comment by BoykoAlex** [comment] 2022-03-24 14:12
@martinlippert here is the Eclipse SWT bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=579406

**Comment by BoykoAlex** [comment] 2022-03-24 16:29
@martinlippert should be fixed in Eclipse 4.24. Fixed in this build already: https://download.eclipse.org/eclipse/downloads/drops4/I20220324-0140/

**Comment by martinlippert** [comment] 2022-03-25 11:57
I've setup the build infrastructure to produce early-access builds of STS 4.14.1 CI builds on top of the early but latest Eclipse 2022-06 integration builds where this issue should be fixed.

@shankarwww Can you try the latest CI build from https://dist.springsource.com/snapshot/STS4/nightly-distributions.html for Eclipse 2022-06 builds to verify that this issue is fixed there?

**Comment by martinlippert** [comment] 2022-03-28 07:50
@shankarwww @drc5521 👆Maybe you want to give these CI builds on Eclipse 2020-06 a try, too?

**Comment by shankarwww** [comment] 2022-06-23 00:07
@martinlippert I have downloaded STS Version: 4.15.1.RELEASE. The console performance has improved on windows. But still its not that smooth as compared to the console of VSCode or IntelliJ IDEA. I still find some lag/hanging when there is little bit large json.

**Comment by martinlippert** [comment] 2022-07-01 12:07
I am closing this one here as a duplicate of https://github.com/mihnita/ansi-econsole/issues/66. Discussion should continue over there. If you are facing another issue unrelated to https://github.com/mihnita/ansi-econsole/issues/66, please create a new issue here.

**Closed by martinlippert** 2022-07-01 12:07 UTC
Labels: type: bug, theme: performance, for: eclipse, status: duplicate
