### ISSUE TITLE
Failed to refresh live data from process 12704 - com.xxxx.xx.xxx.BillingServiceApp after retries: 10

### ISSUE THREAD

**Issue by yaegar** [spring-projects/sts4#748] opened 2022-03-29 03:25 UTC
Failed to refresh live data from process 12704 - com.xxxx.xx.xxx.BillingServiceApp after retries: 10

visual studio code 1.65.2
windows 11
default JDK 17
runtime JDK 8

**Comment by martinlippert** [comment] 2022-03-29 09:48
This happens when the Spring Tools in VSCode try to fetch live information from the running app (in order to show live hovers): https://github.com/spring-projects/sts4/wiki/Live-Application-Information

With the latest update to the Spring Tools for VSCode, this is triggered automatically after you launched a Spring Boot application, but it looks like this doesn't work somehow.

In order to disable this automatic behavior, you can go to the preferences and disable `Live Information -> Automatic Tracking`.

In order to solve the underlying issue, we need a few more details here:
- does your project have Spring Boot Actuator on the dependency list?
- how does the beginning on the log output looks like when you start the application (the command that is executed including the JVM options set)

**Comment by yaegar** [comment] 2022-03-30 01:01
1. Spring Boot Actuator exists.

2. The beginning of the log is also normal.

**Comment by martinlippert** [comment] 2022-03-30 08:19
@yaegar Can you paste the beginning of the log when starting the app here (the section that contains the launch arguments)?

**Comment by martinlippert** [comment] 2022-03-30 08:21
@yaegar Maybe you can provide a small sample application that reproduces the behavior you are seeing?
And is there maybe a security setting on the machine that prevents the started app from being accessed va JMX from the tooling?

**Comment by sbreakey** [comment] 2022-05-26 08:40
I get this too.

Versions:
Version: 1.67.2 (Universal)
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:20:57.384Z (1 wk ago)
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 21.3.0

Launch args:
`cd /Users/me/my-proj ; /usr/bin/env 'SOME_VAR=someval' /usr/local/Cellar/openjdk/17.0.2/libexec/openjdk.jdk/Contents/Home/bin/java -agentlib:jdwp=transport=dt_socket,server=n,suspend=y,address=localhost:58218 -XX:+ShowCodeDetailsInExceptionMessages @/var/folders/d3/yzvcd0ws7nv56wfg9z_h7vtm0000gr/T/cp_15dsny3wqaz08lv5lggsbrp17.argfile com.example.myapp.MyAppServiceApplication --spring.profiles.active=local `

**Comment by sbreakey** [comment] 2022-05-31 11:41
>  How do you launch the app?

I use the vscode debugger (using the Microsoft "Debugger for Java" extension: vscjava.vscode-java-debug). My launch configuration is:

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "java",
      "name": "Launch MyApplication",
      "request": "launch",
      "mainClass": "com.whatever.myapp.MyApplication",
      "projectName": "myapp",
      "args": "--spring.profiles.active=local",
      "env": {
        "somekey": "someval"
      },
      "preLaunchTask": "Copy build-info from Gradle"
    }
}
```

> And can you provide a sample app and a few steps how to reproduce this?

Sure [here you go](https://github.com/sbreakey/spring-boot-demo). It's literally an absolute bare bones gradle based, springboot 2.7.0 app generated by [the initializer](https://start.spring.io/). Just open the "Run and Debug" screen in vscode and click "Run and Debug".

**Comment by BoykoAlex** [comment] 2022-05-31 14:34
Fixed with 24117a4cc01a46d5681440e6b6693e8bcef68410

**Closed by BoykoAlex** 2022-05-31 14:34 UTC
Labels: type: bug, status: needs-investigation, theme: live-data, for: vscode

**Comment by negwu01** [comment] 2022-11-10 15:50
Tried running a spring boot application on vscode and got `Failed to refresh live data from process 12243  after retries: 10 - Source spring boot tools extension`. Live hovers were not possible. I added actuator and also added 
`-Dspring.liveBeansView.mbeanDomain` and ` "vmArgs": "-Dspring.jmx.enabled=true" ` in the 'launch.json' file as described. But did not get any beans info or live hovers. It used to work on vscode 1.72 and spring boot 2.7.4.+

**Comment by jarhuba** [comment] 2022-11-14 10:15
Same problem here.
Spring Boot 3.0.0-RC2, vscode 1.73.1
Fedora 36, jdk 17
Failed to refresh live data from process 55015 after retries: 10

2022-11-14T11:00:39.055+01:00  INFO 55015 --- [           main] com.crud.tasks.TasksApplication          : Starting TasksApplication using Java 17.0.5 with PID 55015 (/home/jarek/Dokumenty/markownie-webserwis/module_19.2/tasks/bin/main started by jarek in /home/jarek/Dokumenty/markownie-webserwis/module_19.2/tasks)
2022-11-14T11:00:39.060+01:00  INFO 55015 --- [           main] com.crud.tasks.TasksApplication          : No active profile set, falling back to 1 default profile: "default"
2022-11-14T11:00:40.078+01:00  INFO 55015 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'management.metrics-org.springframework.boot.actuate.autoconfigure.metrics.MetricsProperties' of type [org.springframework.boot.actuate.autoconfigure.metrics.MetricsProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2022-11-14T11:00:40.396+01:00  INFO 55015 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2022-11-14T11:00:40.413+01:00  INFO 55015 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2022-11-14T11:00:40.414+01:00  INFO 55015 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.1]
2022-11-14T11:00:40.576+01:00  INFO 55015 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2022-11-14T11:00:40.576+01:00  INFO 55015 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1442 ms
2022-11-14T11:00:41.252+01:00  INFO 55015 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 1 endpoint(s) beneath base path '/actuator'
2022-11-14T11:00:41.328+01:00  INFO 55015 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2022-11-14T11:00:41.345+01:00  INFO 55015 --- [           main] com.crud.tasks.TasksApplication          : Started TasksApplication in 2.684 seconds (process running for 3.239)

**Comment by martinlippert** [comment] 2022-11-14 11:44
@jarhuba @negwu01 In case you are running a Spring Boot 3 application, you might run into this issue: https://twitter.com/springtools4/status/1589591973878714368. So can you add this additional config to your `application.properties` file?

`management.endpoints.jmx.exposure.include=*`

to see if that fixes the issue?

**Comment by jarhuba** [comment] 2022-11-15 06:40
After adding this line vscode works correctly. Thank you.

**Comment by iwangbowen** [comment] 2024-10-15 14:39
I encountered the same issue

**Comment by martinlippert** [comment] 2024-10-21 13:31
@iwangbowen We fixed this a while ago, the property is usually added automatically now when launching a Spring Boot app in VSCode (in case you have the Spring Boot Tools installed). Can you provide further details, maybe a sample app, and some steps how to reproduce this?

**Comment by BoykoAlex** [comment] 2024-10-21 14:27
@iwangbowen it be great if you could share your Eclipse workspace folder zip in the case of Eclipse :-)

**Comment by phamtranxuantan** [comment] 2025-01-09 23:49
i got a similar error Failed to refresh live data from process service:jmx:rmi:///jndi/rmi://127.0.0.1:45557/jmxrmi after retries: 10 when i am running api gateway , here is my config file :<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
<modelVersion>4.0.0</modelVersion>
<parent> 
<groupId>org.springframework.boot</groupId>
 <artifactId>spring-boot-starter-parent</artifactId>
 <version>2.1.5.RELEASE</version>
 <relatedPath /> 
 </parent>
 <groupId>com.rainbowforest</groupId>
 <artifactId>api-gateway</artifactId>
 <version>0.0.1-SNAPSHOT</version>
 <name>api-gateway</name>
 <description>Demo project for Spring Boot</description>

 <properties>
 <java.version>12</java.version>
 <spring-cloud.version>Greenwich.SR2</spring-cloud.version>
 </properties>

 <dependencies>
 <dependency>
 <groupId>org.springframework.boot</groupId>
 <artifactId>spring-boot-starter-actuator</artifactId>
 </dependency>

 <dependency>
 <groupId>org.springframework.boot</groupId>
 <artifactId>spring-boot-starter-data-redis</artifactId>
 </dependency>

 <dependency>
 <groupId>org.springframework.boot</groupId>
 <artifactId>spring-boot-starter-security</artifactId>
 </dependency>
 <dependency>
 <groupId>org.springframework.boot</groupId>
 <artifactId>spring-boot-starter-web</artifactId>
 </dependency>
 <dependency>
 <groupId>org.springframework.cloud</groupId>
 <artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
 </dependency>
 <dependency>
 <groupId>org.springframework.cloud</groupId>
 <artifactId>spring-cloud-starter-netflix-hystrix</artifactId>
 </dependency>
 <dependency>
 <groupId>org.springframework.cloud</groupId>
 <artifactId>spring-cloud-starter-netflix-ribbon</artifactId>
 </dependency>
 <dependency>
 <groupId>org.springframework.cloud</groupId>
 <artifactId>spring-cloud-starter-netflix-zuul</artifactId>
 </dependency>
 <dependency>
 <groupId>org.springframework.session</groupId>
 <artifactId>spring-session-data-redis</artifactId>
 </dependency>
 <dependency>
 <groupId>org.springframework.session</groupId>
 <artifactId>spring-session-jdbc</artifactId>
 </dependency>

 <dependency>
 <groupId>org.springframework.cloud</groupId>
 <artifactId>spring-cloud-starter-gateway</artifactId>
 </dependency>

 <dependency>
 <groupId>com.microsoft.sqlserver</groupId>
 <artifactId>mssql-jdbc</artifactId>
 <scope>runtime</scope>
 </dependency>
 <dependency>
 <groupId>org.projectlombok</groupId>
 <artifactId>lombok</artifactId>
 <optional>true</optional>
 </dependency>
 <dependency>
 <groupId>org.springframework.boot</groupId>
 <artifactId>spring-boot-starter-test</artifactId>
 <scope>test</scope>
 </dependency>
 <dependency>
 <groupId>org.springframework.security</groupId>
 <artifactId>spring-security-test</artifactId>
 <scope>test</scope>
 </dependency>
 
 <dependency>
 <groupId>redis.clients</groupId>
 <artifactId>jedis</artifactId>
 </dependency>

 </dependencies>

 <dependencyManagement>
 <dependencies>
 <dependency>
 <groupId>org.springframework.cloud</groupId>
 <artifactId>spring-cloud-dependencies</artifactId>
 <version>${spring-cloud.version}</version>
 <type>pom</type>
 <scope>import</scope>
 </dependency>
 </dependencies>
 </dependencyManagement>

 <build>
 <plugins>
 <plugins>
 <groupId>org.springframework.boot</groupId>
 <artifactId>spring-boot-maven-plugin</artifactId>
 </plugin>
 </plugins>
 </build>

</project>
 Someone please save me this error

**Comment by martinlippert** [comment] 2025-01-10 08:05
@phamtranxuantan This is related to the mechanism that automatically tries to connect the IDE to the running Spring Boot process to fetch live information from the running process. You can disable this mechanism. If you are using the Spring Tools in an Eclipse environment, you can uncheck the `Auto connect to fetch live data` option in the launch configuration of your Spring Boot app. If you are using Spring Tools in VSCode, there is a preference in the `live-information` category as well.

In addition to that, we could also try to find out why the IDE seems to fail to connect to your app. For that, it would be awesome if you could share a sample project that reproduces this.

Side note: the Spring Boot version that you are using (looks like you have `2.1.5` in use) is quite old and no longer maintained/supported, so I would recommend to upgrade to a more recent Spring Boot 3.4 version instead.
