### ISSUE TITLE
Running tests fails in large spring-boot project

### ISSUE THREAD

**Issue by per-steinar** [spring-projects/sts4#810] opened 2022-08-08 07:36 UTC
I have a multi module spring-boot project where I am not able to run tests from VS-Code. I am able to run the tests with maven.
I am able to run tests in other project with the same vs-code setup.

Versjons:
Junit: 5.8.2
Java: open-jdk 17
Spring-boot: 2.7.2

Stack trace from vscode-spring-boot-debug-log:
```
[Error - 9:22:03 AM] Request workspace/executeCommand failed.
  Message: Internal error.
  Code: -32603 
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.springframework.ide.vscode.commons.languageserver.util.ParentProcessWatcher.lambda$apply$0(ParentProcessWatcher.java:126)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor77.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 12 more
Caused by: java.lang.NoClassDefFoundError: org/springframework/ide/vscode/boot/java/livehover/v2/SpringProcessStatus
	at org.springframework.ide.vscode.boot.java.livehover.v2.SpringProcessCommandHandler.connect(SpringProcessCommandHandler.java:103)
	at org.springframework.ide.vscode.boot.java.livehover.v2.SpringProcessCommandHandler.lambda$new$1(SpringProcessCommandHandler.java:63)
	at org.springframework.ide.vscode.commons.languageserver.util.SimpleLanguageServer.executeCommand(SimpleLanguageServer.java:264)
	at org.springframework.ide.vscode.commons.languageserver.util.SimpleWorkspaceService.executeCommand(SimpleWorkspaceService.java:135)
	... 16 more
Caused by: java.lang.ClassNotFoundException: org.springframework.ide.vscode.boot.java.livehover.v2.SpringProcessStatus
	... 20 more
```

**Comment by martinlippert** [comment] 2022-08-09 11:18
Thanks @per-steinar for reporting this. It looks a lot like a duplicate of https://github.com/spring-projects/sts4/issues/812 (or vice versa), so closing this one to have just one open issue around this. Please subscribe to https://github.com/spring-projects/sts4/issues/812 to get notifications about updates here.

**Closed by martinlippert** 2022-08-09 11:18 UTC
Labels: type: bug, type: install-issue, status: duplicate, for: vscode
