### ISSUE TITLE
System CPU Utilization Maxed out

### ISSUE THREAD

**Issue by jedinite13** [spring-projects/sts4#214] opened 2019-03-08 02:49 UTC
We have been trying to leverage STS Eclipse in a VDI environment but when Eclipse launches the CPU spikes to nearly 100% and the system becomes unusable and only returns to normal system utilization after the Eclipse process is killed. 

What are the recommended system requirements to run Eclipse?

Are there any known issues with AV products such as McAfee interfering or causing an undo performance hit when Eclipse is running? Are there any recommendations for exclusions if so?

**Comment by kdvolder** [comment] 2019-03-08 17:48
> What are the recommended system requirements to run Eclipse?

A typical developer machine will probably be relatively high-end laptop, say less than 4 years old. With a good chunk of RAM. I'd say 16 Gb at least. This leads to a fairly comfortable work experience.

Now that being said, this is not just to run Eclipse/STS but other things at the same time, maybe even start VM etc. If all you want to do is run STS and nothing else you could get away with less. WE don't really have a 'minimum requirement' pinned down. This question rarely comes up. Also your requirement would really heavily depend on what you do. For example how many projects do you simultaneously import into your workspace. Memory and CPU utilisation will go up with a 'heavier' workspace that has more or larger projects.

> Are there any known issues with AV products such as McAfee

None that have been reported to us. But would certainly not rule out that AV products could seriously affect performance because a typical Eclipse process makes and changes lot of small files while it is building projects, for example. If all of those files are being subjected to virus scan, it would be significant.

> when Eclipse launches the CPU spikes to nearly 100%

Do you know precisely which processes are using the CPU? Is it the Eclipse process itself, or maybe another background process (possibly one started by the Eclipse process, or another process like the mentioned AV scanner).

It is hard to say why the CPU spikes without further investigation. Eclipse does tend to spike high CPU while it booting up, but if all working nicely it should quiet down after a while. 

All JVM processes tend to go high-CPU when they are hitting the limits of their allocated heap memory. Basically they get stuck in a endless 'GC loop' which utilises all of the CPU while doing very little 'useful work'.

My advice is to try and pin down first which exact process is eating most of the CPU, then we can try trouble shoot and determine if its mayby a memory issue, a bug, or whatever.

**Comment by jedinite13** [comment] 2019-03-08 19:31
@kdvolder Thanks for the detailed response, this is very helpful. My team supports the development machines that the developers use but not the application or projects directly. So your answers are very helpful in determining if we don't have VDIs that meet their requirements or if we have an issue with configurations or applications that may be interfering with these developer machines. 

For information, the developers are provisioned with a 2 vCPU @ 2.2 GHz and 8GB of RAM. I am thinking this might be an area of concern. On a few machines we bumped it to 4 vCPU and 16GB of RAM with some improvement, it still lags but is at least responsive if not slow.

**Comment by kdvolder** [comment] 2019-03-08 22:46
@jedinite13 You are probably aware of this. But just in case.... Note that JVM processes, including Eclipse/STS have startup parameters that define beforehand how much memory the JVM is allowed to use. These parameters can be changed by editing the `STS.ini` file or `eclipse.ini` file. The JVM will generally try to use more memory as seems necessary by what the application (i.e. STS) needs, but it is limited by these parameters. The CPU spike caused by infinite GC loop I mentioned earlier happens when the JVM hits that hard limit and is unable to grab more memory even though the application demands it. So if you haven't tried already... it may be worthwhile trying to experiment with them.

For reference, my copy of STS (4) which uses default 'out of the box' parameters has this:

```
-startup
plugins/org.eclipse.equinox.launcher_1.5.200.v20180922-1751.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.900.v20180922-1751
-product
org.springframework.boot.ide.branding.sts4
--launcher.defaultAction
openFile
-vmargs
-Dosgi.requiredJavaVersion=1.8
-Xms256m
-Xmx1024m
-XX:+UseG1GC
-XX:+UseStringDeduplication
--add-modules=ALL-SYSTEM
```

Note the heap size is set to a relatively modest 1024m. Unless you changed that, then it means your copies of STS will certainly not use all of that extra memory you added going from 8 -> 16G. 

BTW: 1024m is the size of the heap in terms of what is usable to store java objects. The actual amount of system memory that this process will actually use when it is at 'maximum capacity' will be far greater because there's a bunch of overhead how the JVM manages the heap. Even so this process probably won't take more than about 2G or 2.5G os-level memory.

So before you increase the size of VDI's to 16G you might first try to adjust the -Xmx to a bigger value maybe 2 or 3G. 

The 1G limit is fine for myself. But some of our user's have massive workspaces and they do need to bump that up a notch.

Also we have had someone reporting: https://github.com/spring-projects/sts4/issues/212
that for big workspaces one of the helper processes that STS starts is running up agains its memory limit and eating lots of CPU.

So... please keep us posted on what you find and don't hesitate to get us involved somehow to help you trouble-shoot. We would like to know why you are having this issue and what we could do to help avoid this.

**Comment by martinlippert** [comment] 2021-02-23 16:25
Looks like there is no further feedback provided here, so closing this one here for now. If you come across issues in the environment that you describe, please comment and we can re-open or raise a new issue and we can dive into more details from there. My hope is that some of the improvements that got implemented since then also solved this issue here. If not, let us know.

**Closed by martinlippert** 2021-02-23 16:25 UTC
Labels: status: waiting-for-feedback
