### ISSUE TITLE
Support for Spring Boot properties in YAML

### ISSUE THREAD

**Issue by dsyer** [spring-projects/sts4#15] opened 2017-11-13 06:43 UTC
I don't seem to see any "magic" in VSCode for `application.yml`. Am I missing something?

**Comment by kdvolder** [comment] 2017-11-14 16:42
You have to install the vscode extension. There are two extensions one for 'java' and another for the properties support (supports both .yml and .properties).

On this page you can download snapshots of the extensions: 

http://dist.springsource.com/snapshot/STS4/nightly-distributions.html

The one you want is a file called `vscode-boot-properties`.

Our efforts are most focussed on the Java support because in STS/Eclipse environment, the features it adds are complementary to what STS 3 already offers, whereas the .properties support is actually just replacing something we already have (and in fact works a little better because due to some limitations of the LSP protocol there are some things that don't work quite as well, especially in the .yml props editor). 

Anyhoo... yes, you can have .properties / .yml editor support in atom/vscode if you install the right extension and it should be usable / functional.

**Comment by dsyer** [comment] 2017-11-14 17:57
I installed that already. It worked fine with properties files. Doesn't seem to do anything for YAML. What should I be looking for to verify that it works?

**Comment by kdvolder** [comment] 2017-11-14 20:27
Its not working for me either. Not sure why.. yet. In my case its not even working for .properties files.

I am getting some errors in the `vscode-boot-properties-debug-log` (which you can access from vscode's output view.

I'll debug it a bit and see if I can fix it.

**Comment by kdvolder** [comment] 2017-11-14 21:48
I got it working on my machine. Turns out that my problem was actually my test project had a bad `pom.xml` causing the classpath to go missing so no properties where being indexed.

There are some other things I ran into along the way which make this worse / hard to trouble-shoot as a user.

 - the 'progress' report when indexing does not seem to be working.
 - if it would work... it probably wouldn't have reported anything helpful about the broken pom.
 - the properties index does not refresh when project config is changed (so after fixing pom, need to restart the editor).

I'm not really sure your problem was something similar or not though.

BTW: There is a reason why we didn't include the properties/yaml extension in the announcement of the internal STS 4 release. I think for the time being you are better of sticking with the 'old' yml and props editor from STS3 (which are also what's going to be included with STS4 eclipse distro, not the LSP-based implementation). Consider this very very Beta (or even 'Alpha').

**Comment by kdvolder** [comment] 2017-11-14 21:55
>  What should I be looking for to verify that it works?

If it works... you would see stuff like the following:

- hover over property keys -> shows doc string of that property
- wrong spelling of properties highlighted with a warning
- content assist when typing property keys

If you still feel up to it, give it another shot. My guess is the problem was probably a borked pom. It would be nice to confirm and close this ticket. (But I will create some tickets around the 'poor user experience around this 'broken pom' scenarario in Pivotal tracker).

**Comment by dsyer** [comment] 2017-11-15 07:10
The only autocompletes I see are "obvious" ones (from context in the file). Nothing based on spring metadata. And I don't see any hovers. Or spelling mistakes. Clearly I did something wrong. Lots of these if it's relevant:

```
ERR: [Timer-0] ERROR org.springframework.ide.vscode.commons.util.Log - Error

ERR: com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file: target process not responding or HotSpot VM not loaded
	at sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:106)
	at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:78)
	at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:250)
	at org.springframework.ide.vscode.commons.boot.app.cli.SpringBootApp.<init>(SpringBootApp.java:101)
	at org.springframework.ide.vscode.commons.boot.app.cli.SpringBootAppCache.refresh(SpringBootAppCache.java:49)
	at org.springframework.ide.vscode.commons.boot.app.cli.SpringBootAppCache.getAllRunningJavaApps(SpringBootAppCache.java:33)
	at org.springframework.ide.vscode.commons.boot.app.cli.SpringBootApp.getAllRunningJavaApps(SpringBootApp.java:90)
	at org.springframework.ide.vscode.commons.boot.app.cli.SpringBootApp.getAllRunningSpringApps(SpringBootApp.java:96)
	at org.springframework.ide.vscode.boot.java.utils.SpringLiveHoverWatchdog.update(SpringLiveHoverWatchdog.java:143)
	at org.springframework.ide.vscode.boot.java.utils.SpringLiveHoverWatchdog.update(SpringLiveHoverWatchdog.java:158)
	at org.springframework.ide.vscode.boot.java.utils.SpringLiveHoverWatchdog$2.run(SpringLiveHoverWatchdog.java:108)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

```

**Comment by kdvolder** [comment] 2017-11-15 16:43
The logged errors are from the boot-java extension, not the properties/yml one. Those are coming from a polling loop that tries to update 'live hover' metadata from actuator endpoint of running boot apps. Those are probably nothing to worry about and certainly not related to why .yml editor doesn't seem to be working for you at all.

**Comment by KobayashiRo** [comment] 2017-12-10 08:51
I have same problem. it does worked in .properties files but doesn't worked in .yml files.

**Comment by martinlippert** [comment] 2017-12-11 07:34
@KobayashiRo what is the file type that shows up in VSCode (in the bottom right corner)? Does it say "Spring Boot Properties Yaml" when you open the project?

**Comment by dsyer** [comment] 2017-12-11 09:22
It works up to a point for me. Sometimes I get autocomplete suggestions, and sometimes I see this in the `vscode-boot-properties-debug` log when I hit CTRL-SPACE

```
Activating 'vscode-boot-properties' extension
Found java exe: /home/dsyer/.sdkman/candidates/java/current/bin/java
isJavaEightOrHigher => true
Redirecting server logs to /tmp/vscode-boot-properties-1512983729706.log
CMD = /home/dsyer/.sdkman/candidates/java/current/bin/java -Xmx160m -Dserver.port=45556 -Dorg.slf4j.simpleLogger.logFile=/tmp/vscode-boot-properties-1512983729706.log -jar /home/dsyer/.vscode/extensions/Pivotal.vscode-boot-properties-0.1.0/jars/language-server.jar
ERR: Redirecting log output to: /tmp/vscode-boot-properties-1512983729706.log

Child process connected on port 45556
ERR: SEVERE	?	elastic-3	2017-12-11T09:20:39.783Z	org.eclipse.lsp4j.jsonrpc.RemoteEndpoint#lambda$static$0	Internal error: java.lang.NullPointerException
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at reactor.core.publisher.MonoToCompletableFuture.onError(MonoToCompletableFuture.java:68)
	at reactor.core.publisher.FluxSubscribeOnCallable$CallableSubscribeOnSubscription.run(FluxSubscribeOnCallable.java:202)
	at reactor.core.scheduler.ElasticScheduler.lambda$schedule$1(ElasticScheduler.java:164)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.springframework.ide.vscode.commons.yaml.structure.YamlDocument.isCommented(YamlDocument.java:107)
	at org.springframework.ide.vscode.commons.yaml.completion.YamlCompletionEngine.getCompletions(YamlCompletionEngine.java:84)
	at org.springframework.ide.vscode.boot.BootPropertiesLanguageServer.lambda$getCompletionEngine$1(BootPropertiesLanguageServer.java:129)
	at org.springframework.ide.vscode.commons.languageserver.completion.VscodeCompletionEngineAdapter.lambda$getCompletionsMono$0(VscodeCompletionEngineAdapter.java:137)
	at reactor.core.publisher.MonoCallable.call(MonoCallable.java:94)
	at reactor.core.publisher.FluxSubscribeOnCallable$CallableSubscribeOnSubscription.run(FluxSubscribeOnCallable.java:199)
	... 6 more
```

**Comment by dsyer** [comment] 2017-12-11 09:24
Also, the "language type" for a file seems to be volatile - it forgets if I close the file and open it again. Only files called "application.yml" seem to have the right Spring Boot language type when first opened.

**Comment by dsyer** [comment] 2017-12-11 09:32
I think the error above only happens if the project is a sub-directory of the root (i.e. a multi-module project in Maven terms). The classpath is probably difficult (but the Java editor works).

Even with a single module (a la petclinic) I don't get the right autocomplete suggestions. E.g. type "cloud" and hit CTRL-SPACE and nothing comes up from Spring Cloud, even if it is on the classpath (whereas it does in Eclipse).

**Comment by kdvolder** [comment] 2017-12-11 16:21
> Also, the "language type" for a file seems to be volatile - it forgets if I close the file and open it again. Only files called "application.yml" seem to have the right Spring Boot language type when first opened.

I think that's just how vscode works, but we could raise bug against them and see if they want to make it remember that somehow.

However, as a user you do have full control in vscode on exactly what file-name patterns the editor responds to. There a short not about this in the editor's readme and more details in vscode documentation. https://code.visualstudio.com/Docs/languages/overview#_adding-a-file-extension-to-a-language

**Comment by kdvolder** [comment] 2017-12-11 16:24
BTW: The default patterns are "application*.yml" and "application*.properties" (also mentioned in the editor's readme).

**Comment by kdvolder** [comment] 2017-12-11 16:36
BTW: These default patterns are easy to change for us, so let us know if you think there's a better default.

**Comment by kdvolder** [comment] 2017-12-11 16:43
> Even with a single module (a la petclinic) I don't get the right autocomplete suggestions. E.g. type "cloud" and hit CTRL-SPACE and nothing comes up from Spring Cloud, even if it is on the classpath (whereas it does in Eclipse).

There is a known issue in vscode editor that it is more 'finicky'. You won't get suggestions that can't be completed right at the cursor (i.e for example if you are in a file like this:

```
spring:
   ...
server:
  port: 1111
cloud<CTRL-SPACE>
```
You will not get suggestions from `spring.cloud....`. Allthough our languuage server does produce those completions, the vscode language server client rejects them because it has constraints on the complexitity of the edits. It doesn't like our edits which attempt to move the changes and cursor position into the `spring` section.

Perhaps this is what is happening for you, though it is hard to be sure unless you provide specific examples of what you tried and what doesn't work.

**Comment by dsyer** [comment] 2017-12-11 16:46
> provide specific examples of what you tried and what doesn't work.

It wasn't as complicated as your example. I just typed "cloud" in an empty file and hit CTRL-SPACE. I don't know if that breaks any "complexity" threshold (can't see how it could).

**Comment by dsyer** [comment] 2017-12-11 16:47
> These default patterns are easy to change for us, so let us know if you think there's a better default.

Including `bootstrap*.yml` would help. How come the existing settings from STS don't show up in the `files.associations` though (per the link you posted above)?

**Comment by kdvolder** [comment] 2017-12-11 17:15
I've added `bootstrap*.yml` and `bootstrap*.properties` as patterns for spring-boot-properties-yaml and spring-boot-properties languages respectively.

> How come the existing settings from STS don't show up in the files.associations though (per the link you posted above)?

Not sure, but I think the default values that you see in the vscode editor when editing workspace or user settings are probably just not including things that are coming from extensions.

**Comment by kdvolder** [comment] 2017-12-11 17:29
> It wasn't as complicated as your example. I just typed "cloud" in an empty file and hit CTRL-SPACE. I don't know if that breaks any "complexity" threshold (can't see how it could).

No, that doesn't sound like its the 'edit is too complex' case. (And its good to rule that out).

I tried with a 1.5.9 project created with start.spring.io, and added spring-cloud stream rabbit dependency (just a random pick). Seems to work for me.

![spring-cloud-stream-completions](https://user-images.githubusercontent.com/1002156/33844558-7a3e65b0-de55-11e7-8b13-5d31460e36bf.png)

Not saying there's no problem, just that I can't reproduce it or guess why it happens. I'll need more specific details. You have a sample project or pom? That might help.

**Comment by kdvolder** [comment] 2017-12-11 17:38
I did something about the NPE posted above as well. Though that one is most probably mostly harmless. It was a good to add an extra null check and avoid littering the logs with NPEs.

**Comment by KobayashiRo** [comment] 2017-12-12 04:53
@martinlippert problem solved. i choice the Spring-Boot-Properties ,It worked  in .yml files.

**Closed** 2017-12-12 18:52 UTC
