### ISSUE TITLE
STS freezes during code autocomplete when running under OpenJDK 11 and Windows

### ISSUE THREAD

**Issue by logicg8** [spring-projects/sts4#140] opened 2018-11-15 19:44 UTC
Steps to reproduce:

(Preconditions - Windows 7 with latest patches installed and running; Oracle's Open JDK 11 downloaded and on local file system; Oracle's JDK 1.8.0_191 downloaded and on local file system)

1. In SpringToolSuite4.ini, enter line -vm <path-to-Oracle-OpenJDK11.0.1> or set as Windows' default JDK via PATH and JAVA_HOME environment variables.
2. Execute SpringToolSuite4.exe
3. Add another JRE to STS
   a. Click Window->Preferences
   b. Click Java->Installed JREs
   c. Click Add...
   d. Click Standard VM
   e. Click Next>
   f. Click Directory and navigate to bin directory of Oracle's JDK 1.8.0_191 
   g. Click Finish
   h. Click Apply and Close
4. Create a Java project 
    a. Click File->New->JavaProject
    b. Click "Use a project specific JRE"  
    c.  Select the jdk1.8.0_191 added in step 3.
    c. Click Finish
5. Create a Class
    a. Right click on project
    b.  Click New->Class
    c. Enter a class name
     d. Click Finish
6. In the editor, type in the full package name of a class.  
7. Use backspace and change to a different.
8. Repeat step 7 several times.

At step 7, system starts to lag and eventually freezes. Note: Issue occurs more rapidly if Java 11 Support for Eclipse 2018-09 is installed. Consistently reproduced on Windows 7. Unable to reproduce on a Mac High Sierra.

**Comment by logicg8** [comment] 2018-11-15 20:53
Also reproduced on Windows 10

**Comment by kdvolder** [comment] 2018-11-23 21:17
> Step 6: In the editor, type in the full package name of a class.

Type it where exactly? If this bug has something to do with content assist processing, which seems likely, I'd expect it really matter where exactly in the file we are typing because this sort of functionality is very context sensitive.

**Comment by kdvolder** [comment] 2018-11-23 21:55
Can't reproduce this on Windows 10 either.  I followed instructions to the letter. 

For the part where we type package name repeatedly I tried both in the place where we declare package, as well as in the class body. I didn't experience any ui freezes.

If you can please add some details / clariication around exactly what I'm supposed to do for steps 7 and 8, that would be nice. For example:

- where exactly are we typing
- are we typing existing package names, or new package names, or just whatever.
- are we keeping content assist active while typing.
- are we keeping content assist active while backspacing.
- are we typing every letter or using content assist to complete (parts of) the package names

I did try a bit with different variations like that but no freezes / slowdowns where observed. 

Still, knowing exactly what it is you do might help and I could give it another.

**Comment by kdvolder** [comment] 2018-11-23 21:58
Another question. Have you tried reproducing this on a Vanilla Eclipse 4.9? It seems likely this not specifically an STS bug. By trying it with a plain Eclipse this could be confirmed. If I could reproduce it myself, I would try Vanilla Eclipse myself, but since I am not yet able to reproduce it at all...

**Comment by logicg8** [comment] 2018-11-26 02:48
This occurs in the editor view. For example, suppose I have this already in
a file, Person.java.:

public class Person {

}

If I open in the editor and start to type inside the class such as "com.su"
as follows:

public class Person {

   com.su

           }

Note: You must change the text a few times say from com.su to
org.something.somethingelse and then you should see the lag and eventually
cause the application to freeze.

**Comment by logicg8** [comment] 2018-11-26 02:49
Yes. I've tried. I can only reproduce in Vanilla Eclipse 4.9 after
installing the Spring Tools 4 plugin.

**Comment by logicg8** [comment] 2018-11-26 02:53
Thanks for looking into this. To answer your questions:


   - where exactly are we typing. Inside a class. See previous response.
   - are we typing existing package names, or new package names, or just
   whatever.  Seems to be whatever.
   - are we keeping content assist active while typing. Yes.
   - are we keeping content assist active while backspacing. Yes
   - are we typing every letter or using content assist to complete (parts
   of) the package names I was able to reproduce with both. I will take some
   video and post.

**Comment by kdvolder** [comment] 2018-11-26 17:20
I did pretty much what you describe. I.e. keeping content assist active while typing and backspacing. I repeated it quite a few times typing different things but everything worked fine for me.

Since you say this is not reproducible in Eclipse vanilla, that's more worrysome to us because that seems to make it an STS specific issue.

There is a chance that maybe this problem is already fixed in the latest snapshot of STS 4 (though we didn't really fix this specific problem). 

Since you say this is not reproducible in Eclipse vanilla, that's more worrysome to us because that seems to make it an STS specific issue.

But since I can't reproduce it (yet). Maybe you can try a few things to help:

1. Can you try the latest snapshot of STS from here: http://dist.springsource.com/snapshot/STS4/nightly-distributions.html

2. If you are able to reproduce it still, can you try and use jps and jstack to collect stackdumps of active java processes? We'd be interested in seeing both a dump from the Eclipse/STS process itself, as well as the spring boot language server process.

The stackdump might give us a hint about what's causing the freezes. (It is important to get a dump *while* it is stuck.

**Comment by logicg8** [comment] 2018-11-26 19:03
Using the latest snapshot, I'm not able to reproduce such that the application freezes. I still see a lag though. Would you still like for me to collect stackdumps?

**Comment by kdvolder** [comment] 2018-11-26 19:11
> Would you still like for me to collect stackdumps?

Unfurtunately meaningful stackdump are not quite as easy to collect for a 'lag'. If something is totally stuck then the dump will usually show where. But if its lagging its a bit more 'luck of the draw'. And when you see a trace its not as clear if its one that was caught during the lag. 

Might be worth a try, but its hard timing wise.

**Comment by spring-issuemaster** [comment] 2018-11-27 17:22
(comment in Pivotal Tracker added by Alex Boyko:) 

Followed the steps on Win 10... Can't reproduce... Maybe on Win 7 this indeed happens, but think Win 7 isn't supported anymore (?)

**Comment by cyril-gambis** [comment] 2019-01-11 10:40
Hi,

I also have these problems now: when I press the autocompletion shortcut, the fan of my laptop starts being noisy, the IDE becomes unresponsive, and a process of Spring Tool Suite consumes a lot of resources in the task manager.

I use OpenJDK 11.0.1 with Spring Tool Suite 4 Version: 4.1.0.RELEASE Build Id: 201812201400.

It doesn't happen everytime. I am not sure of what trigger this behaviour.

I will try to switch to Oracle JDK, in order to see if it resolves the issues.

Cyril

**Comment by martinlippert** [comment] 2019-01-11 11:41
Hey @cyril-gambis, checking with Oracle JDK would indeed be interesting, but also a few thread dumps would be great to see, so would be awesome if you could capture a few thread dumps while STS4 is freezing. Note that there might also be another process involved which you can find when typing in the `jps` command. It will be called something like `spring-boot-language-server...` and it would be extremely interesting to see a few thread dumps of that process, too (while the freeze happens).

**Comment by cyril-gambis** [comment] 2019-01-14 17:08
Hi @martinlippert ,

Thanks for your answer.

I will continue my tests. I am not sure from where I have my issues, but it seems indeed to be linked to spring-boot-language-server.

This is an image of the process "1.2.0.201812201040-spring-boot-language-server-1.2.0-SNAPSHOT.jar" when I have lagging issues. I have an Spring Cloud Eureka server running in the background, the fan of my laptop indicates some work.

![image](https://user-images.githubusercontent.com/37664900/51127563-07313500-1826-11e9-8e45-9cca77537022.png)

When I exit from STS and restart it, with my Eureka app also, I have the following chart:

![image](https://user-images.githubusercontent.com/37664900/51127674-58d9bf80-1826-11e9-8f9f-965e74b0b5d7.png)

The fan is silent.

I have not been coding a lot today, and didn't get the freezes I had previously, but I will continue to monitor it.

As complementary information, I join 

[jstack.txt](https://github.com/spring-projects/sts4/files/2756202/jstack.txt)

a dump of the spring-boot-language-server process when it consumes my cpu.

**Comment by kdvolder** [comment] 2019-01-14 17:33
0.02% CPU usage doesn't seem like a hole lot. Is that really problematic? The language server will consume some amount of CPU continually because it periodically polls for local boot processes to scrape for live hover information. You could try disabling the live hovers to see if it makes a difference.

See here on the wiki for some instructions how:

https://github.com/spring-projects/sts4/wiki/Live-Application-Information#completely-disabling-this-feature

**Comment by cyril-gambis** [comment] 2019-01-14 17:49
Hi!

Yes, of course 0,02% is absolutely not an issue; the problem is complete freezes I get under  circumstances I have to find, that makes STS barely useable. 

I will keep investigating ; the issue I try to show on the first screenshot is the regular bumps of 10% cpu usage (my cpu is quite powerful) even when I nearly don’t do anything, in comparison to the second screenshot, where I don’t have these bumps. I thought it could be a clue. 

Best

**Comment by kdvolder** [comment] 2019-01-14 18:01
> the problem is complete freezes 

Okay, yes of course, that's very bad :-)

Hopefully next time it happens you can capture some thread dumps. My guess is language server is 'stuck' somehow. The stackdump might give hints why. Unfortunately I think the dump in your previous message doesn't (but I gather this was because there wasn't a problem happening when you took it).

**Comment by cyril-gambis** [comment] 2019-01-22 12:13
Hi!

I have barely been able to reproduce the issues I had. Even with detailed monitoring, the lagging issues wasn't as important as it was before.
When I followed the advice given above and unchecked "language server" in the preferences, it removed the lags completely.

Thank you!
Cyril

**Comment by martinlippert** [comment] 2019-01-22 15:23
@cyril-gambis first of all, I am glad to hear that you don't see the issue anymore. Nevertheless I would love to investigate the root cause of this in more detail, especially if the issue goes away by disabling the language servers. Would you be willing to help here a bit?

If so, it would be awesome if you could install the latest distribution of STS4 from the nightly download page first: http://dist.springsource.com/snapshot/STS4/nightly-distributions.html, best would be the one on Eclipse 4.10. Then continue without disabling the language servers for the moment.

Once a freeze or extreme lag occurs, take a thread dump of the STS4 process itself and attach it here. If the freeze occurs again, take a few additional thread dumps and attach them here, too. Please note that these are thread dumps of the STS4 process itself, not the language server process.

**Comment by cyril-gambis** [comment] 2019-01-31 10:18
Hi @martinlippert ,

I will try to help the best I can; not so easy currently since I have a lot of work.

I reactivated language server hints on my current install of STS (I am downloading the nightly distribution you point me to, I will test it also).
I have 3 spring boot apps that are running, they use Spring Cloud but it is a dev environment (so very few hits on the server). They started yesterday.

I can see a regular usage of 10-15% of my CPU, which is quite high for apps that don't do anything:
![image](https://user-images.githubusercontent.com/37664900/52047638-b9b50780-2549-11e9-8b06-4c275da2f6e3.png)

I also took 3 thread dumps that I hope could lead you to a clue:
[threaddumps.log](https://github.com/spring-projects/sts4/files/2816673/threaddumps.log)
[threaddumps2.log](https://github.com/spring-projects/sts4/files/2816674/threaddumps2.log)
[threaddumps3.log](https://github.com/spring-projects/sts4/files/2816675/threaddumps3.log)

Is it of any help?
I disable again the language server, since right now, my computer fan is constantly at high speed when it is enabled.

Best

**Comment by cyril-gambis** [comment] 2019-01-31 10:21
When I disable the "Live boot hint decorators", the CPU comes back to nearly 0% and the fan of the computer stops:

![image](https://user-images.githubusercontent.com/37664900/52047917-57a8d200-254a-11e9-9320-0519db22fd6f.png)

**Comment by martinlippert** [comment] 2019-01-31 15:14
Thanks for your time and help here, much appreciated. The live boot hints are indeed something that is  running inside of a polling loop every 5 seconds (to update live data from running apps), so I am not surprised to see the 10%-12% CPU consumption every 5 seconds (I guess) and that CPU being consumed by the language server process, not your own app that you started.

However, I would have guessed that the CPU is being consumed on the language server side while trying to identify the running Java processes (this is what usually happens on my machine when I measure the performance of that), but your thread dumps look different. Seems like time is being consumed identifying the matching project and accessing the disc while doing that. We need to investigate that piece in more depth.

Nevertheless, this CPU consumption from the language server doing the live boot hints in the background should not really affect the user experience in your IDE and it should definitely not freeze the IDE for some period of time. Do you still experience those freezes using the nightly distribution?

**Comment by martinlippert** [comment] 2019-02-06 17:00
I worked on the performance issues that your thread dumps seemed to reveal and was able to make some progress, I think. I removed a lot of duplicate internal calculations from the mechanism that updates the live hovers every 5 sec, so using these fixes should show up in lower CPU consumption on your end.

It would be great if you could give it a shot to see if that lowers the CPU utilization on your end (and in your case) too. So if you have a moment, please download the latest CI builds for SZS 4.1.2 and Eclipse 4.10 from the nightly download page: http://dist.springsource.com/snapshot/STS4/nightly-distributions.html

There are builds for Eclipse 4.11 already, but I would recommend to use the one for Eclipse 4.10.

**Closed** 2019-02-07 10:00 UTC
Labels: delivered

**Comment by mohyeid** [comment] 2019-05-06 17:58
This issue for me was because of STS plugin (Spring Tools 4) and once removed, all is good now.

**Comment by BoykoAlex** [comment] 2019-05-06 19:40
@mohyeid If you have a lot of projects in the workspace it might have been due to #282

**Comment by mohyeid** [comment] 2019-05-06 19:59
Yes, that might be the case. I have 11 projects and 4 of them were open, but they are kinda big in the size. Thanks for pointing the other issue out

**Comment by martinlippert** [comment] 2019-05-07 16:01
@mohyeid I would be quite interested to learn more about the slowness that you observe when running the Spring Tools 4 in your Eclipse IDE together with your workspace. Would you be interested in a bit of collaboration to investigate this issue? That would be awesome.

First thing to try would be a nightly distribution of STS 4.2.2 (based on Eclipse 2019-03, 4.11) to see if that behaves differently when working with your workspace. We worked quite a bit on performance and memory footprint over the last couple of releases and CI builds, so depending on the version that you used there might be a noticeable difference.

So the first question would be: does using the latest CI build still slows down your workflow with the IDE? If so, in which situations? If you have a reproducible setting where the slowness occurs, would it be possible for your to take a thread dump of the JVM? Or look at the processes (the IDE and the language server) with jconsole to get a rough impression about what is going on?

You could also enable the log output for the Spring Boot language server (in the preferences) to see if there is anything strange going on on the language server side. Once enabled, it will open a console area that shows all the internal logs of the language server process.

Would love to hear more details from you.

**Comment by panamacheng** [comment] 2019-10-08 08:11
Correctly, I had god same terrible on my Ubuntu19.4 vm, currently I am working on Spring Boot project with beginner, so I don't know what exactly happend around my setting.
My ubuntu spec like this:
Cpu: 2.4G(4)
Ram: 6GB
HardDisk: 160GB
I really want to know what exactly wrong on my steps
