### ISSUE TITLE
java.lang.module.FindException: Module not found

### ISSUE THREAD

**Issue by heruan** [spring-projects/sts4#336] opened 2019-08-07 08:52 UTC
When trying to run a Spring Boot app from Eclipse Boot Dashboard, I get this error message:

```
Error occurred during initialization of boot layer
java.lang.module.FindException: Module axians.time.flow not found, required by axians.demo
```

while running `mvn spring-boot:run` from the command line succeeds.

**Comment by martinlippert** [comment] 2019-08-08 08:44
Looks like something is wrong with the classpath of the app and that is somewhat hard to identify. Could be a huge number of things that went wrong here. Did you import the project as an existing Maven project, so that m2e manages the dependencies? What happens if you run the app via a regular Java Application launch config? Does that work? Is `axians.time.flow` a separate project? Do use use Java 9 module definitions and/or running on JDK9+?

Might be useful if you could share the project with us, so that we can reproduce this issue here and see what is wrong.

**Comment by Sae1962** [comment] 2019-12-08 22:46
I have the same issue. For details, please check the attached files.

[workspace.zip](https://github.com/spring-projects/sts4/files/3937268/workspace.zip)

**Comment by kdvolder** [comment] 2019-12-10 23:15
@Sae1962 I've tried to make sense of your `workspace.zip` folder to try to reproduce this. But I don't understand how to use them. 

The eclipse metadata in the two projects inside 'workspace.zip' appears to be incomplete. When importing these projects as 'existing project' it ends up with some broken project setup that doesn't even have correct sourcefolder configured (I gather this is because the .classpath file and possibly other metadata files are not included). 

On the other hand, when importing them as 'existing maven project' (so as to let m2e setup the project from maven config instead of using included eclipse metadata)... then I have two other issues:

1. I can only import the `WShop` project as that is the only one that has a 'pom.xml'. So not sure what to do with the other one.
2. The project has invalid dependency:

```
		<dependency>
			<groupId>org.springframework.context.support</groupId>
			<artifactId>spring-context</artifactId>
			<version>3.1.0.RELEASE</version>
		</dependency>
```

Is it meant to be this perhaps: https://mvnrepository.com/artifact/org.springframework/spring-context/3.1.0.RELEASE ? Hard for me to be sure.

This sounds like a bad and annoying problem, so I would like really like to reproduce it so we can debug and possibly fix it. It would be really nice if someone provided the following:

- zip file with sample projects
- detailed instructions on how to setup a workspace with these projects.
- detailed steps on what to do to cause the error to appear.

Perhaps the 'workspace.zip' that you @Sae1962  have attached is a good 'sample', but you will have to provide some instructions what I should do with it, as it really isn't obvious just looking at the contents.

BTW: I see that your project is using lombok. If possible, it would be nice to have a sample without lombok (setting up lombok is a PITA, also, if we include lombok in the mix we cannot easily rule out whether it responsible for the problem).

**Comment by kdvolder** [comment] 2019-12-10 23:19
Another thought... the pom.xml seems to be for a project intented to run on and use Java 8 as per this:

```
	<properties>
		<java.version>1.8</java.version>
	</properties>
```

But the error seems to be something that would only be reported from a more recent Java runtime (i.e. 'modules' where not introduced until Java 9 see: https://docs.oracle.com/javase/9/docs/api/java/lang/module/FindException.html). I wonder if this might have something to do with the problem. Perhaps it would be good to try to make sure you are running everything with Java 8 and check if perhaps this solves the problem.

**Comment by Sae1962** [comment] 2019-12-11 12:23
Thank you for taking care of my issue! The `WSShop` project is a Web service project that can be started by running the `WSShopApplication` file. However, when trying to include the `Utilities` project, I get the mentioned error message above:
`Error occurred during initialization of boot layer`
`java.lang.module.FindException: Module Utilities not found, required by WSShop`

Without the `requires Utilities;` entry in `module-info.java` file, there are statical errors, and it is not possible to run the project at all:

![20191211 Statical errors](https://user-images.githubusercontent.com/686084/70620438-9651f300-1c17-11ea-9392-2082ae4e01cd.png)

With this entry, a warning resides:

![2019-12-11](https://user-images.githubusercontent.com/686084/70620588-f779c680-1c17-11ea-8105-1609eb688ca6.png)

Ignoring the warning, you get the error above. Here is the last state I have:
[workspace.zip](https://github.com/spring-projects/sts4/files/3950253/workspace.zip)

I had to remove all `*.jar` & `*.zip` files, as the `workspace.zip` exceeds the maximum allowed size.

**Comment by kdvolder** [comment] 2019-12-16 17:55
If the utilities project is meant to be a dependency of your main project, shouldn't it have a pom.xml file so that you can reference it as a maven dependency from your main project? 

I'm sorry but I still don't quite understand what you are trying to do. It looks a bit strange to me that you have a project dependency that doesn't have a pom.xml, I have never seen people do it quite this way.  Or did you forget to include the Utilities project's maven pom?

Here's what people typically do in this kind of situation:

- main project and dependency (Utiliy) have a pom.xml
- main project pom.xml references the group-id, artifact-id and version of the dependent project from its `<dependencies>` section.

When setup this way then maven knows that you want the dependency project on the main project's classpath. Thanks to Eclipse maven tooling, also Eclipse knows this. 

=> Everything works properly both in Eclipse and running maven on commandline.

**Comment by SuYin2096** [comment] 2020-11-05 20:30
Error occurred during initialization of boot layer
java.lang.module.FindException: Module javafx.controls.javafx.fxml not found

I'm getting this error. I use eclipse 2020.

**Comment by kdvolder** [comment] 2020-11-05 22:43
@SuYin2096 There's not really enough information to help you in any useful way. I do recall that javafx was removed from JDK a while back (see: https://www.oracle.com/java/technologies/javase/jdk-11-relnote.html#:~:text=JavaFX%20is%20no%20longer%20included,is%20now%20a%20separate%20download.).

Maybe your problem has something to do with that. So maybe you can try:

- using JDK 8 as a runtime explicitly.
- googling for instructions on how to setup a project using javafx in Java 11 and later.

**Comment by martinlippert** [comment] 2021-02-23 13:13
Any updates on this @Sae1962, @heruan, @SuYin2096 ?

**Comment by Sae1962** [comment] 2021-02-23 14:52
No! That are projects from old times...


Holen Sie sich Outlook für Android

**Comment by martinlippert** [comment] 2021-02-23 16:10
Okay, thanks for the quick response @Sae1962, much appreciated. So let me close this one here. Please open a new issue (or comment on this to be re-opened) if you hit something like this again.

**Closed by martinlippert** 2021-02-23 16:10 UTC
Labels: status: waiting-for-feedback, theme: boot-dashboard, type: bug

**Comment by Rid-cod** [comment] 2022-01-26 20:25
Hi! I have a problem:
Error occurred during initialization of boot layer
java.lang.module.FindException: Module com.example.demoapp not found
I use Intellij IDEA.

**Comment by martinlippert** [comment] 2022-01-27 08:27
@Rid-cod Please note that this issue tracker is around the Spring Tools for Eclipse, VSCode, Theia, Codespaces, etc. If you have trouble while using IntelliJ, you should reach out to them on their issue tracker or forum. Thanks!

**Comment by Rid-cod** [comment] 2022-01-27 18:20
Ok. Thank you!

**Comment by Rkishore1999** [comment] 2023-06-13 09:57
1
