### ISSUE TITLE
SpringToolSuite4 is keeping crashing on MacOS 13.0.1 when pom.xml editor is using

### ISSUE THREAD

**Issue by CrisLi** [spring-projects/sts4#890] opened 2022-11-11 16:27 UTC
**Describe the bug**
After I upgrade my MacOS to 13.01, my SpringToolSuite is keeping crashing when I edited a pom.xml file.
I was even can't open the STS4 after I run the command `sudo codesign --force --sign -  /Applications/SpringToolSuite4.app` I can open the STS4. But I can't use it to edit a pom.xml file via the new default pom editor.

I have installed Lombok plugin and changed the -Xmx2048m in `SpringToolSuite4.ini` file.

Report Info

```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               SpringToolSuite4 [3749]
Path:                  /Applications/SpringToolSuite4.app/Contents/MacOS/SpringToolSuite4
Identifier:            org.springframework.boot.ide.branding.sts4
Version:               4.16.1 (4.16.1.202210240748)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-11-12 00:08:11.8636 +0800
OS Version:            macOS 13.0.1 (22A400)
Report Version:        12
Bridge OS Version:     7.0 (20P420)
Anonymous UUID:        CC7CEA3D-4716-FA30-DCD9-FCAEF9DCB3A2

Sleep/Wake UUID:       24CDBC9A-4703-4E8A-A7BC-AF368627504A

Time Awake Since Boot: 860 seconds
Time Since Wake:       638 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [3749]

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   ???                           	    0x5b8c994c0255 ???
1   ???                           	               0x0 ???
2   ???                           	    0x5b8c994b4a74 ???
3   ???                           	    0x5b8c9945839a ???
4   JavaScriptCore                	    0x7ff82618b341 llint_entry + 119063
5   JavaScriptCore                	    0x7ff82618b341 llint_entry + 119063
6   JavaScriptCore                	    0x7ff82618b341 llint_entry + 119063
7   ???                           	    0x5b8c9945839a ???
8   JavaScriptCore                	    0x7ff82618b341 llint_entry + 119063
9   JavaScriptCore                	    0x7ff82618b341 llint_entry + 119063
10  JavaScriptCore                	    0x7ff82618b341 llint_entry + 119063
11  ???                           	    0x5b8c9945839a ???
12  JavaScriptCore                	    0x7ff82618b341 llint_entry + 119063
13  JavaScriptCore                	    0x7ff82618b3b8 llint_entry + 119182
14  ???                           	    0x5b8c9945839a ???
15  JavaScriptCore                	    0x7ff82618b341 llint_entry + 119063
16  JavaScriptCore                	    0x7ff82618b3b8 llint_entry + 119182
17  ???                           	    0x5b8c9946143f ???
18  JavaScriptCore                	    0x7ff82618b3b8 llint_entry + 119182
19  JavaScriptCore                	    0x7ff82618b3b8 llint_entry + 119182
20  ???                           	    0x5b8c9945839a ???
21  JavaScriptCore                	    0x7ff82618b3b8 llint_entry + 119182
22  JavaScriptCore                	    0x7ff82618b3b8 llint_entry + 119182
23  JavaScriptCore                	    0x7ff82616e027 vmEntryToJavaScript + 216
24  JavaScriptCore                	    0x7ff82690f161 JSC::Interpreter::executeCall(JSC::JSGlobalObject*, JSC::JSObject*, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 545
25  JavaScriptCore                	    0x7ff826b775cb JSC::profiledCall(JSC::JSGlobalObject*, JSC::ProfilingReason, JSC::JSValue, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&, WTF::NakedPtr<JSC::Exception>&) + 107
26  WebCore                       	    0x7ff82a5ecc0b WebCore::JSExecState::profiledCall(JSC::JSGlobalObject*, JSC::ProfilingReason, JSC::JSValue, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&, WTF::NakedPtr<JSC::Exception>&) + 107
27  WebCore                       	    0x7ff82a604a61 WebCore::JSEventListener::handleEvent(WebCore::ScriptExecutionContext&, WebCore::Event&) + 849
28  WebCore                       	    0x7ff82a961736 WebCore::EventTarget::innerInvokeEventListeners(WebCore::Event&, WTF::Vector<WTF::RefPtr<WebCore::RegisteredEventListener, WTF::RawPtrTraits<WebCore::RegisteredEventListener>, WTF::DefaultRefDerefTraits<WebCore::RegisteredEventListener> >, 1ul, WTF::CrashOnOverflow, 2ul, WTF::FastMalloc>, WebCore::EventTarget::EventInvokePhase) + 310
29  WebCore                       	    0x7ff82a961336 WebCore::EventTarget::fireEventListeners(WebCore::Event&, WebCore::EventTarget::EventInvokePhase) + 342
30  WebCore                       	    0x7ff82a957ee7 WebCore::dispatchEventInDOM(WebCore::Event&, WebCore::EventPath const&) + 215
31  WebCore                       	    0x7ff82a957221 WebCore::EventDispatcher::dispatchEvent(WebCore::Node&, WebCore::Event&) + 689
32  WebCore                       	    0x7ff8295397e1 WebCore::Document::finishedParsing() + 497
33  WebCore                       	    0x7ff829533003 WebCore::HTMLDocumentParser::prepareToStopParsing() + 227
34  WebCore                       	    0x7ff8295a709a WebCore::HTMLDocumentParser::resumeParsingAfterScriptExecution() + 90
35  WebCore                       	    0x7ff82ac5e736 WebCore::HTMLDocumentParser::notifyFinished(WebCore::PendingScript&) + 54
36  WebCore                       	    0x7ff82a995fc8 WebCore::PendingScript::notifyClientFinished() + 40
37  WebCore                       	    0x7ff82a97d0dc WebCore::LoadableScript::notifyClientFinished() + 284
38  WebCore                       	    0x7ff82a97c8f1 WebCore::LoadableClassicScript::notifyFinished(WebCore::CachedResource&, WebCore::NetworkLoadMetrics const&) + 177
39  WebCore                       	    0x7ff82aeb72f7 WebCore::CachedResource::checkNotify(WebCore::NetworkLoadMetrics const&) + 167
40  WebCore                       	    0x7ff82aecc45b WebCore::CachedScript::finishLoading(WebCore::FragmentedSharedBuffer const*, WebCore::NetworkLoadMetrics const&) + 91
41  WebCore                       	    0x7ff82ae8838b WebCore::SubresourceLoader::didFinishLoading(WebCore::NetworkLoadMetrics const&) + 699
42  WebCore                       	    0x7ff82b8692d4 WTF::Detail::CallableWrapper<-[WebCoreResourceHandleAsOperationQueueDelegate connectionDidFinishLoading:]::$_7, void>::call() + 388
43  JavaScriptCore                	    0x7ff825e13acf WTF::RunLoop::performWork() + 431
44  JavaScriptCore                	    0x7ff825e143ba WTF::RunLoop::performWork(void*) + 26
45  CoreFoundation                	    0x7ff80c286bc8 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
46  CoreFoundation                	    0x7ff80c286b77 __CFRunLoopDoSource0 + 157
47  CoreFoundation                	    0x7ff80c286951 __CFRunLoopDoSources0 + 212
48  CoreFoundation                	    0x7ff80c2855cb __CFRunLoopRun + 929
49  CoreFoundation                	    0x7ff80c284bb0 CFRunLoopRunSpecific + 560
50  Foundation                    	    0x7ff80d0dd49a -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 216
51  libswt-pi-cocoa-4954r7.jnilib 	        0x28e08b29 Java_org_eclipse_swt_internal_cocoa_OS_objc_1msgSend_1bool__JJJJ + 57
52  ???                           	        0x18c24ee7 ???
53  ???                           	        0x132a536c ???
54  ???                           	        0x10b0f862 ???
55  ???                           	        0x10b0f410 ???
56  ???                           	        0x10b0f410 ???
57  ???                           	        0x10b0f410 ???
58  ???                           	        0x10b0f410 ???
59  ???                           	        0x10b0f410 ???
60  ???                           	        0x10b0f410 ???
61  ???                           	        0x10b0f410 ???
62  ???                           	        0x10b0f410 ???
63  ???                           	        0x10b0f410 ???
64  ???                           	        0x10b0f410 ???
65  ???                           	        0x112cc25c ???
66  ???                           	        0x10b0f862 ???
67  ???                           	        0x10b0f410 ???
68  ???                           	        0x10b0f67e ???
69  ???                           	        0x10b0f410 ???
70  ???                           	        0x10b0f410 ???
71  ???                           	        0x10b0f862 ???
72  ???                           	        0x10b0f410 ???
73  ???                           	        0x10b0f2fc ???
74  ???                           	        0x10b0f2fc ???
75  ???                           	        0x10b0f67e ???
76  ???                           	        0x10b0f67e ???
77  ???                           	        0x10b0f22c ???
78  ???                           	        0x10b0f22c ???
79  ???                           	        0x10b0f22c ???
80  ???                           	        0x10b06cc9 ???
81  libjvm.dylib                  	         0xc894c86 JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, JavaThread*) + 694
82  libjvm.dylib                  	         0xcc9bac0 invoke(InstanceKlass*, methodHandle const&, Handle, bool, objArrayHandle, BasicType, objArrayHandle, bool, JavaThread*) + 2576
83  libjvm.dylib                  	         0xcc9b05b Reflection::invoke_method(oopDesc*, Handle, objArrayHandle, JavaThread*) + 347
84  libjvm.dylib                  	         0xc943c13 JVM_InvokeMethod + 819
85  ???                           	        0x10b134da ???
86  ???                           	        0x10b0f22c ???
87  ???                           	        0x10b0f22c ???
88  ???                           	        0x10b0f67e ???
89  ???                           	        0x10b0f22c ???
90  ???                           	        0x10b0f410 ???
91  ???                           	        0x10b0f410 ???
92  ???                           	        0x10b06cc9 ???
93  libjvm.dylib                  	         0xc894c86 JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, JavaThread*) + 694
94  libjvm.dylib                  	         0xc8ef9b5 jni_invoke_nonstatic(JNIEnv_*, JavaValue*, _jobject*, JNICallType, _jmethodID*, JNI_ArgumentPusher*, JavaThread*) + 725
95  libjvm.dylib                  	         0xc8f16e0 jni_CallIntMethod + 416
96  eclipse_11700.so              	         0x9c99fca startJavaJNI + 1946
97  eclipse_11700.so              	         0x9c95eb0 _run + 6016
98  eclipse_11700.so              	         0x9c9427a run + 426
99  SpringToolSuite4              	         0x7e1abed original_main + 1245
100 SpringToolSuite4              	         0x7e1b521 main + 1665
101 dyld                          	    0x7ff80be7b310 start + 2432

```
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/360767/201385606-dc992c39-a52c-439a-a7ec-d8e02abe7f77.png">

**To Reproduce**
Open STS4 and edit a pom file. Once some assist prompts were going to popup, then STS crashed.

**Comment by martinlippert** [comment] 2022-11-11 16:49
Closing as a duplicate of https://github.com/spring-projects/sts4/issues/888, which points to the underlying issue at https://github.com/eclipse-platform/eclipse.platform.swt/issues/452

**Closed by martinlippert** 2022-11-11 16:49 UTC
Labels: type: bug, for: eclipse, status: duplicate

**Comment by martinlippert** [comment] 2023-01-24 10:39
Quick update on this: macOS Venture 13.2 seems to fix this problem, according to https://github.com/eclipse-platform/eclipse.platform.swt/issues/452#issuecomment-1400972852

**Comment by CrisLi** [comment] 2023-02-06 16:59
> Quick update on this: macOS Venture 13.2 seems to fix this problem, according to [eclipse-platform/eclipse.platform.swt#452 (comment)](https://github.com/eclipse-platform/eclipse.platform.swt/issues/452#issuecomment-1400972852)

thanks for the update. the issus is fixed
