### ISSUE TITLE
STS locks jar files in the target platform

### ISSUE THREAD

**Issue by FelixJongleur42** [spring-projects/sts4#416] opened 2020-03-10 15:41 UTC
Something strange about the class loader.
We have a Eclipse RCP Target Platform (.target file) referencing jar files as the active target platform.

**STS installed:**
cannot overwrite existing  jar files (locked)

**STS not installed:**
overwrite of existing jar files is possible, as long as no launch is running

**Expected Behaviour:**
STS should not lock any jar files in the target platform.

If you have an idea where I could into, I'll be glad to help.

**Comment by kdvolder** [comment] 2020-03-10 15:55
I assume you are on Windows? 

Can you please describe in a bit more detail the different setups? 

What do you mean, for example with 'STS not installed' vs 'STS installed'. Can you explain what exactly you have installed? How you install STS, and what we need to do to reproduce the problem. It would be useful for us to have a set of precise steps to follow. Please be as precise as possible. E.g. which exact jar file(s) cannot be deleted.

**Comment by kdvolder** [comment] 2020-03-10 16:12
I'm not all that familar with Windows. But there are some tools that may help determine what process is responsible for 'locking' a file. It may be interesting to try this. E.g. we may learn whether it is really the STS process itself that is locking the file, or perhaps the separate language server spawned by STS. Or maybe it is another process entirely (probably not likely, but it is allways good to be sure).

Googling a bit I found this: 

https://superuser.com/questions/117902/find-out-which-process-is-locking-a-file-or-folder-in-windows

Can you try this? (E.g. the second answer using 'Resource Monitor' tool).

**Comment by FelixJongleur42** [comment] 2020-03-10 22:36
Thanks for the quick reply.
"STS Installed" means I installed STS in Eclipse and then the problems started.
As for the locking process I am pretty much sure it's Eclipses JVM but I will check.
I will also check if it's a special Jar file that is locked.
To reproduce it's quite tricky. I should be able to provide a target file. 
Maybe another approach is to review whether STS is using some special mechanisms for looking at jar files (or maybe some classloader),
Something along the lines of this https://bugs.eclipse.org/bugs/show_bug.cgi?id=543506

**Comment by BoykoAlex** [comment] 2020-03-10 22:56
Try disabling Spring Boot Language Server by opening Preferences -> Language Servers preference page and uncheck all entries in the table where you see "Spring Boot Language Server", apply and restart STS.

**Comment by FelixJongleur42** [comment] 2020-03-10 22:57
Ok thank you for the hint - I will try that!

**Comment by kdvolder** [comment] 2020-03-11 15:04
What I'm not understanding here is the details of your setup. Typically what we mean by 'target platform' is the collection of Eclipse plugins that we use to compile other Eclipse plugins against. So is it correct to assume that your are developing some Eclipse plugins (rather than spring boot apps?)

If so (?), a typical setup would be that the Eclipse instance is what we call 'self-hosting' which means the target platform is the currently running Eclipse instance itself.

You seem to be saying that you are having trouble deleting target platform files, but in the 'typical' setup that I just described that would be your Eclipse instance itself that you are currently running. And so it seems a bit odd that you would be trying to delete any part of that while you are actually running it.

Something here doesn't make sense...

So either we have some misunderstanding here of what you mean by 'target platform', or your setup is not like the typical one that I have in mind, or... I'm not really sure. 

So please, try and be precise on what you are doing. It may seem obvious to you, but I assure you it isn't obvious to us.

**Comment by martinlippert** [comment] 2020-03-30 08:49
@FelixJongleur42 What is the status of this issue here? Did you disable the Spring Boot Language Server, as Alex recommended, and then the problem went away? Or do you have any other details for us?

**Comment by FelixJongleur42** [comment] 2020-04-02 09:03
Sorry, yet to test that.

**Comment by martinlippert** [comment] 2020-04-02 13:21
@FelixJongleur42 yeah, would be awesome to gain more insights here to avoid the issues in the future as best as we can, so your help with this would be much appreciated. Let us know when you have any more details and insights.

**Comment by martinlippert** [comment] 2021-02-16 13:38
@FelixJongleur42 Are you still observing this issue? There hasn't been any activity on this one here for quite some time. While I am definitely not sure that there is no locking of a JAR file caused by the Spring tooling somewhere, it is hard to identify exactly where that might come from without any further details or sample projects.

Would be good to hear from you @FelixJongleur42 whether this is still an issue and in that case, maybe you could even provide a sample project that helps us to reproduce this.

**Comment by martinlippert** [comment] 2021-05-26 09:53
Closing this one now due to no additional feedback being provided here. If you find the time to take a look at the previous comments @FelixJongleur42, your insights would be much appreciated and we can re-open the item anytime.

**Closed by martinlippert** 2021-05-26 09:53 UTC
Labels: status: waiting-for-feedback, type: bug
