### ISSUE TITLE
Duplicate "Source" menu on Eclipse

### ISSUE THREAD

**Issue by mateusbandeiraa** [spring-projects/sts4#1111] opened 2023-09-19 21:21 UTC
**Describe the bug**
After installing the latest version of the Spring Tools 4 plugin on Eclipse 2023-09, the "Source" menu is duplicated when a Java source file is opened.

I was able to reproduce the issue on Windows 11 and MacOS 13.5.2

**First menu**

![Screenshot of the Eclipse top menus, with the two Source menus displayed. The first Source menu is opened, displaying all expected options, like "Toggle comment", "Add block comment", "Format", etc.](https://i.stack.imgur.com/EkdOT.png)

**Second menu**
![Screenshot of the Eclipse top menus, with the two Source menus displayed. The second Source menu is opened, displaying only the option, "Format", that is also disabled](https://i.stack.imgur.com/FAmpB.png)

**To Reproduce**
1. On a fresh installation of [Eclipse IDE for Enterprise Java and Web Developers 2023-09](https://www.eclipse.org/downloads/packages/release/2023-09/r/eclipse-ide-enterprise-java-and-web-developers), open the Eclipse Marketplace and install [Spring Tools 4](https://marketplace.eclipse.org/content/spring-tools-4-aka-spring-tool-suite-4).
2. Open a Java source file

**Sample**

n/a

**Comment by BoykoAlex** [comment] 2023-09-20 02:43
Hmm... very interesting... don't think I've seen anything like it yet... I suspect this has something to do when installed from an update sitr as Distro looks good. I'll try to reproduce this

**Comment by martinlippert** [comment] 2023-09-20 11:33
Actually, I can reproduce that with both, the latest Spring Tools for Eclipse distribution as well as a plain Eclipse installation with Spring Tools added to it. It appears as soon as you open a Java source file in an editor.

I haven't analyzed the root cause in detail yet, but I guess this is related so some LSP-related format action showing automatically due to the fact that we have the Spring Boot language server registered for the Java source content type.

**Comment by BoykoAlex** [comment] 2023-09-20 12:27
Yes, i saw this as well... java editor needs to be active...

**Comment by BoykoAlex** [comment] 2023-09-25 16:19
Should be resolved in LSP4E project: https://github.com/eclipse/lsp4e/issues/822

**Comment by BoykoAlex** [comment] 2024-01-30 15:36
Fixed in lsp4e. Should be fixed on our side as well once we consume the latest lsp4e snapshot.

**Comment by martinlippert** [comment] 2024-01-31 19:05
Since we are not going to ship the upcoming 4.21.1 release with a snapshot version of lsp4e, I moved the target milestone of this to the 4.22.0 release. If you would like to get this fix early, please install/update lsp4e manually from the lsp4e snapshot update site.

**Comment by martinlippert** [comment] 2024-02-04 18:14
4.21.1 release will include a new release of lsp4e that includes the fix, therefore closing this as fixed for 4.21.1 here.

**Closed by martinlippert** 2024-02-04 18:14 UTC
Labels: type: bug, for: eclipse
