### ISSUE TITLE
txt files are being validated by lsp4e

### ISSUE THREAD

**Issue by ewrdk** [spring-projects/sts4#343] opened 2019-08-15 09:51 UTC
STS version: 4.3.1.RELEASE

I have a file with an txt-extension in the main/resources folder. The file consists of numbers (one number per line). If I open the file it is being validated and an error is generated:

Description: Expecting a 'Map' but found a 'Scalar'
Location: line 1
Type: org.eclipse.lsp4e.diagnostics

I would expect that no validation at all takes place for an txt-file.

**Comment by martinlippert** [comment] 2019-08-15 09:53
I think this is caused by a wrong content-type association and should be fixed in the already released STS 4.3.2. Please update. In case the update doesn't fix the issue, please let us know and we can re-open the issue.

**Closed by martinlippert** 2019-08-15 09:53 UTC

**Comment by ewrdk** [comment] 2019-08-15 10:23
I can confirm that the 4.3.2.RELEASE has solved the problem.

**Comment by martinlippert** [comment] 2019-08-15 10:43
Awesome, glad to hear that and thanks for letting us know.
