### ISSUE TITLE
4.8.0 StringIndexOutOfBoundsException in Lambda expressions with minor syntax errors

### ISSUE THREAD

**Issue by 0xABCDFFFF** [spring-projects/sts4#540] opened 2020-09-24 20:10 UTC
I installed 4.8.0 a few days back and like it a lot. I have only one issue.

While editing a Java class when certain Lambda expressions are incomplete or have small syntax errors, saving the file (automatically or manually) fails and building the project terminates with StringIndexOutOfBoundsException 

In my case, this incomplete statement triggers the issue:
```
        public final ABBackToBack<RtDataTickByTickBidAsk> tbtABBackToBack = new ABBackToBack(
                o -> o.
        );
```
or the complete statement with an extra comma at the end
```
	public final ABBackToBack<RtDataTickByTickBidAsk> tbtABBackToBack = new ABBackToBack<>(
		o -> this.ticks.ticks( o.data().askPrice() ),
		o -> o.data().askSize(),
		o -> this.ticks.ticks( o.data().bidPrice() ),
		o -> o.data().bidSize(),
	);
```

The editor shows no errors or warnings at the point of syntax error and the error log shows entries similar to this (depending on whether ythe file save or build crashed)
```
Created Time: 2020-09-24 14:10:15.250

org.eclipse.jdt.core
Error
Thu Sep 24 14:10:32 CDT 2020
offset 11548, count -4809, length 18024

java.lang.StringIndexOutOfBoundsException: offset 11548, count -4809, length 18024
        at java.base/java.lang.String.checkBoundsOffCount(String.java:3741)
        at java.base/java.lang.String.rangeCheck(String.java:298)
        at java.base/java.lang.String.<init>(String.java:294)
        at org.eclipse.jdt.internal.compiler.parser.Scanner.disambiguatedToken(Scanner.java:5491)
        at org.eclipse.jdt.internal.compiler.parser.Scanner.getNextToken(Scanner.java:1461)
        at org.eclipse.jdt.internal.compiler.parser.diagnose.LexStream.readTokenFromScanner(LexStream.java:84)
        at org.eclipse.jdt.internal.compiler.parser.diagnose.LexStream.token(LexStream.java:154)
        at org.eclipse.jdt.internal.compiler.parser.diagnose.LexStream.kind(LexStream.java:194)
        at org.eclipse.jdt.internal.compiler.parser.diagnose.DiagnoseParser.diagnoseParse(DiagnoseParser.java:312)
        at org.eclipse.jdt.internal.compiler.parser.Parser.reportSyntaxErrors(Parser.java:14004)
        at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:12857)
        at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:13051)
        at org.eclipse.jdt.internal.compiler.parser.Parser.parse(Parser.java:13008)
        at org.eclipse.jdt.internal.compiler.SourceElementParser.parseCompilationUnit(SourceElementParser.java:1048)
        at org.eclipse.jdt.internal.core.CompilationUnitProblemFinder.process(CompilationUnitProblemFinder.java:271)
        at org.eclipse.jdt.internal.core.CompilationUnit.buildStructure(CompilationUnit.java:192)
        at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:268)
        at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:596)
        at org.eclipse.jdt.internal.core.CompilationUnit.makeConsistent(CompilationUnit.java:1141)
        at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.makeConsistent(ReconcileWorkingCopyOperation.java:173)
        at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.executeOperation(ReconcileWorkingCopyOperation.java:94)
        at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:736)
        at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:802)
        at org.eclipse.jdt.internal.core.CompilationUnit.reconcile(CompilationUnit.java:1318)
        at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:131)
        at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.access$0(JavaReconcilingStrategy.java:113)
        at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy$1.run(JavaReconcilingStrategy.java:93)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
        at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:90)
        at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:157)
        at org.eclipse.jdt.internal.ui.text.CompositeReconcilingStrategy.reconcile(CompositeReconcilingStrategy.java:94)
        at org.eclipse.jdt.internal.ui.text.JavaCompositeReconcilingStrategy.reconcile(JavaCompositeReconcilingStrategy.java:107)
        at org.eclipse.jface.text.reconciler.MonoReconciler.process(MonoReconciler.java:76)
        at org.eclipse.jface.text.reconciler.AbstractReconciler$BackgroundThread.run(AbstractReconciler.java:210)
```
![STS4sc1](https://user-images.githubusercontent.com/71849281/94194827-d79a5300-fe77-11ea-8584-d1c43524adf8.png)
![STS4sc2](https://user-images.githubusercontent.com/71849281/94194833-da954380-fe77-11ea-9485-e4515049c948.png)
[STS4log.txt](https://github.com/spring-projects/sts4/files/5278923/STS4log.txt)

**Comment by martinlippert** [comment] 2020-09-29 12:51
Great to hear that you like the tooling and thanks for that feedback!!!

With regards to the error, it looks to me a lot like a core Java compiler issue. That should be reported to https://bugs.eclipse.org/bugs/enter_bug.cgi?product=JDT, then select the "Core" component and describe the issue. It would help those guys a lot if you could attach a small sample project that reproduces the issue. That would be awesome.

So closing this item here, since it belongs to Eclipse JDT.

**Closed by martinlippert** 2020-09-29 12:51 UTC
