### ISSUE TITLE
设置成eclipse默认空间有几个问题

### ISSUE THREAD

**Issue by lelebuzaizhe** [spring-projects/sts4#104] opened 2018-10-08 02:00 UTC
在spring的properties文件中或者是yml文件中，ctrl+/或者ctrl+shift+/的注释都不起作用。我尝试设置快捷键了，也无效。能否修复一下。非常感谢

**Comment by martinlippert** [comment] 2018-10-08 06:46
My Chinese language skills are quite limited, so an english version would be awesome. As far as Google translate helps here, I think it could be a duplicate of https://github.com/spring-projects/sts4/issues/100. If not, please comment and we can re-open this one.

**Closed by martinlippert** 2018-10-08 06:46 UTC
