### ISSUE TITLE
Spring Tool Suite 17 with maven no longer copies application.properties file to the target folder

### ISSUE THREAD

**Issue by marcgemis** [spring-projects/sts4#929] opened 2022-12-19 07:58 UTC
**Describe the bug**
When you create a new Spring Boot project (2.76, Maven, Java 17) with Spring Web an application.properties file gets created. When you edit this file, e.g. add server.port=8888 and save the file, the file never appears in the target folder of the project.
This also means that the web application still starts at the default port 8080.

There is no problem with the same project is created with gradle.

Platform MacOS Monterey 12.5.1 Apple M1 chip - Eclipse STS 17.0

**To Reproduce**
See above

Problem does not occur in STS 14

A non-working maven project, and a working gradle project
[sounds-of-animals-maven.zip](https://github.com/spring-projects/sts4/files/10257017/sounds-of-animals-maven.zip)
[sounds-of-animals.zip](https://github.com/spring-projects/sts4/files/10257018/sounds-of-animals.zip)

**Comment by martinlippert** [comment] 2022-12-19 17:38
I can reproduce this and I think this is a problem with the m2e integration in Eclipse (since I can reproduce this with Eclipse 2022-12 RC1 JEE package as well), therefore I reported this issue via https://github.com/eclipse-m2e/m2e-core/issues/1148 to the m2e project.

**Comment by martinlippert** [comment] 2023-01-01 17:52
Here is the issue from the m2e project where this got fixed: https://github.com/eclipse-m2e/m2e-core/issues/1150 - now waiting for a new release of m2e to be published that includes this fix.

**Comment by marcgemis** [comment] 2023-01-02 04:52
thanks for keeping me updated

**Comment by martinlippert** [comment] 2023-01-05 07:55
In case you want to try the fix early, you can add the m2e snapshots update site to the preferences (`Preferences -> Install/Update -> Available Update Sites`, then add `https://download.eclipse.org/technology/m2e/snapshots/latest/`) and run a `Check for Updates`.

Feel free to uncheck the JustJ JRE update, but keep everything else selected and run the update. It includes the fix for this issue.

**Comment by martinlippert** [comment] 2023-01-25 16:11
Unfortunately the workaround doesn't seem to work anymore due to a new dependency being required from the latest m2e snapshot builds. I am looking into this to see what we can do here. In the meantime, run a regular maven build on the command line or via the `Run As -> Maven Install` menu item whenever you change those resource files.

**Comment by CrisLi** [comment] 2023-02-16 12:05
this issue is still here, is there any hotfix?

**Comment by martinlippert** [comment] 2023-02-16 12:34
@CrisLi The workaround described above (running stuff manually) should work, the fix for the underlying issue is implemented in the corresponding component (the Maven Integration, m2e) and we are waiting for a new release of m2e to include this fix (I guess on-time for the next major Eclipse release, coming in mid March).

In the meantime, we have fixed the issues that were preventing us from installing the latest m2e snapshot CI builds, that works again with our latest snapshot CI builds. So if you would like to, you could go to https://dist.springsource.com/snapshot/STS4/nightly-distributions.html, download and install this latest CI build (on top of Eclipse 4.26 or 4.27, whatever you prefer) and then install the latest m2e snapshot to it (as described above). That would result in an STS environment with the m2e fix included, but would also mean to run on the latest CI builds of STS as well as m2e.

**Comment by CrisLi** [comment] 2023-02-16 14:50
> 

thanks for the reply. let me try the workaround

**Comment by martinlippert** [comment] 2023-02-24 15:26
Closing this from the Spring Tools perspective now, the updates to m2e will be included on the upcoming 4.18.0 release (from what I can see at the moment).

**Comment by cypher256** [comment] 2023-03-01 00:31
Note: To be supported in Eclipse SimRel  2023-03
https://github.com/eclipse-m2e/m2e-core/pull/1279

**Comment by arimeyer** [comment] 2023-03-22 01:07
I'm still seeing the problem, getting:
`Exception in thread "main" org.springframework.beans.factory.BeanDefinitionStoreException: IOException parsing XML document from class path resource [applicationContext.xml]
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:342)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:310)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:184)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:220)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:191)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:253)
	at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:128)
	at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:94)
	at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:130)
	at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:672)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:144)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:85)
	at Driver.main(Driver.java:11)
Caused by: java.io.FileNotFoundException: class path resource [applicationContext.xml] cannot be opened because it does not exist
	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:211)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:333)
	... 13 more
`

I reverted to 4.16.1, and the problem is gone.

**Comment by martinlippert** [comment] 2023-03-23 12:15
@arimeyer Can you attach a small sample project that reproduces this issue? And can you double check which version of the m2e plugins you have installed in your environment that doesn't work? The version that are ship and which should include a fix for this is: `org.eclipse.m2e.core_2.0.7.20230307-1553`

**Comment by arimeyer** [comment] 2023-03-28 02:51
Hi @martinlippert -- will try to do so this weekend.  Best, Ari

**Comment by pcdavid** [comment] 2023-03-29 14:33
FYI, I'm on STS 4.18.0 with `org.eclipse.m2e.core` 2.0.7.20230307-1553 and am still seeing the issue. Doing a full build (Project > Clean... > Clean all projects) seems to fix it, but it tends to re-appear once in a while.

**Comment by martinlippert** [comment] 2023-03-30 07:17
> FYI, I'm on STS 4.18.0 with `org.eclipse.m2e.core` 2.0.7.20230307-1553 and am still seeing the issue. Doing a full build (Project > Clean... > Clean all projects) seems to fix it, but it tends to re-appear once in a while.

Hey @pcdavid, I also have a colleague who reports the same, but I am not able yet to reproduce it. Do you have a sample project and/or a few steps how to reproduce this. The steps that I tried don't trigger the issue yet. Many many thanks for your help!

**Comment by pcdavid** [comment] 2023-03-31 06:57
I don't understand yet what triggers it but I'll comment here if I find more.

**Comment by martinlippert** [comment] 2023-03-31 08:03
> I don't understand yet what triggers it but I'll comment here if I find more.

That would be great, looking forward to hearing more details from your side. Also in case you have a project that you can share, let us know.

**Comment by pcdavid** [comment] 2023-03-31 08:10
> Also in case you have a project that you can share

Well, in my case it's on https://github.com/eclipse-sirius/sirius-components, but that's 320 kSLOCs of Java across 57 Maven modules, so as far as a minimal repro case as can be...

**Comment by pmar0** [comment] 2023-06-02 16:19
I don't believe this issue should be closed, as the results in 4.18.1 are spotty, at best. Has there any update here @martinlippert ? Eg. ability to replicate with some of these other projects.

I've had to use 4.16.1 to avoid issues and I have many other users saying the same.

**Comment by pcdavid** [comment] 2023-06-02 17:15
I still get it regularly even with m2e 2.3.0 (on STS 4.18.1).

Sometimes I try to identify what triggers the problem, but its not very clear yet. What I've noticed is that depending on whether a project is rebuilt/cleaned by itself or as part of cleaning/rebuilding mutiple projets, I don't get the same results. Here I use "project" in the Eclipse meaning, and by "Cleaning" I mean "Project > Clean...".

With a terminal watching on the output folder of a specific project where the bug occurs (`watch -n ls target/classes`), here's what I noted for the moment.

#### Cleaning the working set which contains the project (and a few others):

1. output folder is cleaned (empty)
2. the resources appear in it
3. then the resources disappear and are replaced by the class files only; the final state is KO

#### Cleaning the individual project:

1. class files appear
2. then the ressource files are added; the final state is OK

#### Cleaning the whole workspace:

1. output folder is cleaned (empty)
2. the resources appear in it
3. resources disappear and are replaced by the class files only; the final state is KO
4. edit a file, save => incremental rebuild => the ressources reappear

No source or configuration changes between the different tests. Nothing in the Error Log. I have not enabled parallel builds ("Max simultaneous project builds" is at 1), nor customized the build order.

This is on a relatively large multi-module project (https://github.com/eclipse-sirius/sirius-components) with 60 projects/Maven modules in the workspace. 
I have a few plug-ins installed in addition to the default STS 4.18.1, but I can't see any of them causing this (CheckStyle particpates in the build, but is pretty standard and I don't think it modifies the build output? Acceleo 3.7.12 is the only one the includes a builder but no project in the workspace has the corresponding nature/builder enabled).

![screenshot-2023-06-02_19-08](https://github.com/spring-projects/sts4/assets/10608/e25507f5-ea00-44cb-a479-6b1fd1e07c78)

I'm on Linux (Fedora 38 or Ubuntu 23.4, the problems occurs on both). STS runs with the embedded JustJ JRE.

**Comment by martinlippert** [comment] 2023-06-05 11:57
Based on the recent comments, I am re-opening this for further investigations. Probably something that needs to be reported and fixed on the m2e codebase, but nevertheless re-opening this one here to track progress and cross references.

**Comment by BoykoAlex** [comment] 2023-06-07 22:30
@pcdavid @pmar0 Not sure what to go with and how to reproduce this issue. Since I wasn't able to see the issue with my own workspaces I've decided to create **sirius-components** workspace. I've created an `application.properties` file inside **sirius-web-sample-application** added `server.port` property and trying clean-build workspace then launch app and check if port is correct during the launch... so far the port value has been always correct.
Is there anything particular i can do in the sirius workspace to reproduce the issue?

**Comment by BoykoAlex** [comment] 2023-06-26 19:08
@pcdavid let me have another look at this as I moved to other tasks and forgot about this issue...

**Comment by BoykoAlex** [comment] 2023-06-26 22:14
@pcdavid most of the time it works for me... and I have a suspicion that i forgot to turn on "Build Automatically" when it didn't work, i.e. i had just the empty `META-INF` folder...

Debugging this involves both M2E and JDT i think. As far as I know M2E is in charge of resolving classpath, figuring out output folder etc., so essentially building the `.classpath` file. Then it is Eclipse build infrastructure and events triggering the build from the Eclipse side that drive the build and populate the output folder... At least from what I know about this topic.
I'd debug:
- `org.eclipse.jdt.internal.core.builder.JavaBuilder` the `build(...)` method as i think this is what creates the .class files in the output folder (likely this stuff is never executed for you, so it might make sense to go up to `org.eclipse.core.internal.events.BuildManager` or `org.eclipse.core.internal.events.AutoBuildJob` or even `Workspace#ebdOperation(...)` method bottom line `buildManager` call with `needsBuild` == `true`)
- `org.eclipse.m2e.core.internal.builder.MavenBuilder` various mojo add-ons for the builds... not sure these would be of any interest.

I have to admit I'm not sure which build participant copies resources into the target folder... at least yet...

**Comment by BoykoAlex** [comment] 2023-06-27 00:25
I do see that resources are not copied over to the target folder sometimes as well as the java .class files which happens less often. When I debug the code everything starts working thus i suspect it is some kind of a timing issue... For example down stream projects starts being compiled before upstream projects are compiled... likely something around the scheduling rule.

**Comment by pcdavid** [comment] 2023-07-17 14:40
So, I now have a *much* simpler scenario to reproduce. I don't think it's possible to do simpler.

1. Still using a unmodified STS 4.18.1 (this time under Ubuntu 23.4 instead of Fedora 38, but I don't think it's relevant).
2. Import in the workspace the simplest demo project created from start.spring.io (attached for convenience).
3. Make sure Eclipse/STS is in automatic build mode.
4. Watch the project's output folder (`demo/target/classes`).
5. Open the project's `pom.xml`.
6. Initially (00:04s in the video), everyhting is fine. The output folder contains `META-INF`, `application.properties`, and the `com` folder with the main `.class` file.
7. Make a change in the POM which breaks its syntax. Save.
8. We see a rebuild hapening, with only the `com` folder available (00:15s).
9. Fix the typo in the POM. Save.
10. New rebuild. Initially we see all 3 entries (`META-INF`, `application.properties` and `com`) appearing (00:21s), but then `META-INF` and `application.properties` disappear in the final (broken) state.

We're back to a valid state where everything compiles without error, but `META-INF` and `application.properties` are missing from the output folder.

Not shown on the video: doing a "Project > Clean... > Clean all projects" afterwards fixes the issue (in this very simple case).

https://github.com/spring-projects/sts4/assets/10608/cc1d0bc7-c7a5-4574-871d-036bb8459bde

Sample project used: [demo.zip](https://github.com/spring-projects/sts4/files/12070418/demo.zip)

The m2e issue https://github.com/eclipse-m2e/m2e-core/issues/1150 linked above mentioned that it may be related to the presence of the `.mvn` folder. It's present in the `demo.zip` attached as start.spring.io creates it, but I also tested without the folder and get the same result.

**Comment by BoykoAlex** [comment] 2023-07-18 03:24
@pcdavid Thanks very much for the simpler instructions to reproduce this issue. I have attempted a JUnit test for this in M2E-Core. It has a few `Thread.sleep(...)` calls in it but hope it'd be enough for M2E team to take over this. See https://github.com/eclipse-m2e/m2e-core/issues/1302#issuecomment-1639269877

**Comment by BoykoAlex** [comment] 2023-09-07 12:47
This is the m2e issue we are waiting on to be fixed: https://github.com/eclipse-m2e/m2e-core/issues/1511

**Comment by BoykoAlex** [comment] 2023-11-29 22:45
@martinlippert I've installed the latest M2E 2.5.0 which came out on 2023-11-27 and I still observe the issue. Moving to 4.21.1

**Comment by pcdavid** [comment] 2023-11-30 07:29
There's some activity on https://github.com/apache/maven-filtering/pull/77#issuecomment-1833089113 which seems to be the root cause. No idea how long it would take, once merged there (and assuming this indeed fixes the issue) to be available in STS. It looks like it would need a new Maven release?

It's been reported multiple times on m2e (https://github.com/eclipse-m2e/m2e-core/issues/1585 and https://github.com/eclipse-m2e/m2e-core/issues/1511 for example).
I've not tested it yet, but [this comment](https://github.com/eclipse-m2e/m2e-core/issues/1585#issuecomment-1820439783) mentions that a workaround is "to have a Maven launcher in Eclipse running "resources:resources" each time before launching my software."

**Comment by goodale** [comment] 2023-12-04 18:25
@pcdavid any update on this issue?  the stated workaround is untenable for enterprise projects with many applications in your workspace

**Comment by pcdavid** [comment] 2023-12-20 08:28
A fix for the (potential) underlying issue in Maven has just been merged: https://github.com/apache/maven-filtering/pull/77.
There are exchanges ongoing on https://github.com/eclipse-m2e/m2e-core/issues/1511 to see how this can be tested in the context of m2e and confirm.
Not sure if this will require a new release of Maven Filtering and/or Maven itself.

**Comment by pcdavid** [comment] 2023-12-22 15:05
A potential fix has just been merged in m2e itself via https://github.com/eclipse-m2e/m2e-core/pull/1629
It can be tested by updating m2e from https://download.eclipse.org/technology/m2e/snapshots/latest/ and getting `org.eclipse.m2e.feature` 2.4.300.20231222-1142 (or more recent).

**Comment by martinlippert** [comment] 2024-01-02 13:22
Thanks a lot @pcdavid for this update, that sounds indeed quite promising. I will include the m2e snapshot update site in our builds, so that we could get a few nightly builds of STS that include this fix right away for further testing here. Will keep you posted here once those builds are around.

**Comment by martinlippert** [comment] 2024-01-02 15:21
Builds that include the m2e fix are available now from here:
https://cdn.spring.io/spring-tools/snapshot/STS4/nightly-distributions.html

It is included in builds based on Eclipse 2023-12 (e4.30) as well as the early access builds for Eclipse 2024-03 (e4.31).

**Comment by martinlippert** [comment] 2024-01-02 15:23
@pcdavid Do you think that this fixes the issue for all the cases you observed?
@BoykoAlex Probably worth a try to double check from your end as well

**Comment by martinlippert** [comment] 2024-01-08 13:40
> > @pcdavid Do you think that this fixes the issue for all the cases you observed?
> 
> I have not experienced the bug since I updated, but I've not used STS much these last few days and the bug was not systematic. It looks good, but it's difficult to be sure.

Thanks for the update, much appreciated. Let's keep an eye on this for a little longer before we finally close this item here.

**Comment by OLibutzki** [comment] 2024-01-10 05:59
As [this comment](https://github.com/eclipse-m2e/m2e-core/issues/1511#issuecomment-1869996917) states there is some relationship to https://github.com/apache/maven-filtering/pull/77, too.

So maybe we need a maven-filtering release including https://github.com/apache/maven-filtering/pull/77 before this issue can be closed?

**Comment by BoykoAlex** [comment] 2024-01-29 21:24
@martinlippert are we moving this to 4.22.0  to include new eclipse release with new m2e release?

**Comment by martinlippert** [comment] 2024-01-31 19:04
Yes, since we don't have a new release of m2e yet that includes this and we will not ship the Spring Tools 4.21.1 release with an snapshot version of m2e, we will move the target milestone for this to the 4.22.0 release.

If you would like to get this into the upcoming 4.21.1 release, please install the latest m2e milestone manually into the Spring Tools distribution.

**Comment by pcdavid** [comment] 2024-02-21 07:52
m2e has just released a version with a fix on their side: https://github.com/eclipse-m2e/m2e-core/issues/1511#issuecomment-1955946862
It looks like a *complete* fix of the underlying problem will also require a new release of maven-filtering with https://github.com/apache/maven-filtering/pull/77 (which has been merged), but personally I've been using m2e snapshots for a while and do not see the bug anymore.

**Comment by martinlippert** [comment] 2024-02-26 12:28
Awesome, thanks a lot @pcdavid for the continuous feedback here, much appreciated. With that, I will close this item and mark it as solved for now. We will include the m2e 2.6 release in our upcoming Spring Tools `4.22.0` release.

**Closed by martinlippert** 2024-02-26 12:28 UTC
Labels: type: bug, status: needs-investigation, for: eclipse, status: duplicate
