### ISSUE TITLE
Rename is not working after installing lombok on STS4

### ISSUE THREAD

**Issue by nitinkumar328** [spring-projects/sts4#767] opened 2022-04-19 17:44 UTC
**Describe the bug**
Rename is not working after installing lombok on STS4

**To Reproduce**
1. Install lombok in STS4
2. Try rename method name, variable name, class name, etc...

**Expected**
It should allow to rename as it allows without lombok.

**Actual**
Rename feature gets disabled after installing lombok.

**Sample**
A link to a GitHub repository with a [minimal, reproducible sample](https://github.com/ayonious/lombok-examples).

**Comment by cypher256** [comment] 2022-04-20 01:39
Related Issue
https://github.com/projectlombok/lombok/issues/3134
https://projectlombok.org/changelog

**Comment by martinlippert** [comment] 2022-04-20 07:10
Thanks @cypher256 for the links to the related issues, I will close this one here as a duplicate of the mentioned issue on the Lombok issue tracker.

**Closed by martinlippert** 2022-04-20 07:10 UTC
Labels: type: bug, for: eclipse, status: duplicate

**Comment by user20161119** [comment] 2022-04-22 07:01
after i tested with [1.18.24](https://projectlombok.org/downloads/lombok.jar) and sts Version: 4.14.0.RELEASE
Build Id: 202203131612

the rename not working,
![image](https://user-images.githubusercontent.com/123967/164621989-87403488-7dae-48c1-ad23-beff84c00c1f.png)


and then i uninstall lombok,rename work again
![image](https://user-images.githubusercontent.com/123967/164619127-ebb40c32-0655-4e86-b33a-05aa782cad41.png)

**Comment by martinlippert** [comment] 2022-05-31 08:26
@user20161119 If the latest Lombok release is still causing this issue, I would recommend to follow-up on this on the Lombok issue tracker, as mentioned above.
