### ISSUE TITLE
unable to extract the zip. file path too long

### ISSUE THREAD

**Issue by nitsmrinal** [spring-projects/sts4#349] opened 2019-08-24 15:47 UTC

**Comment by BoykoAlex** [comment] 2019-08-25 14:35
This duplicate of #304 Have a look at it - there plenty of workarounds. Also have a look at the FAQ here for a workaround: https://github.com/spring-projects/sts4/wiki/FAQ#path-too-long-while-expanding-sts4-zip-on-windows

**Closed by BoykoAlex** 2019-08-25 14:35 UTC
