### ISSUE TITLE
[vscode] Extension issue - code completion in application.properties not working

### ISSUE THREAD

**Issue by subho2810** [spring-projects/sts4#796] opened 2022-07-07 17:14 UTC
- Issue Type: `Bug`
- Extension Name: `vscode-spring-boot`
- Extension Version: `1.36.0`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.68.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by martinlippert** [comment] 2022-07-08 20:03
Can you provide a few more details on this? Do you have a sample project and a few steps to reproduce this?

**Comment by subho2810** [comment] 2022-07-08 22:43
Actually this problem came to me suddenly so it can be a problem of vs code
but yes code completion provided by spring boot tools extension of vs code
is not working at all for application.properties

**Comment by martinlippert** [comment] 2022-07-26 10:01
Ok, let's try to see if we can identify the underlying issue somehow. A few more questions to help with diagnosing this:

- does the Java language support work just fine in your VS Code installation for the same project (including code completion, problem markers, etc.)?
- if you open the "Output" tab, is there an entry in the dropdown showing `vscode-spring-boot-debug-log`? And if so, can you share the output that shows up there?
- if you open the `application.properties` file, does it show up as `Spring Boot Properties` file type in the status bar (on the right side)?

P.S.: And sorry for the late reply here (due to vacations)...

**Comment by zwssunny** [comment] 2022-10-15 01:48
code completion for application.properties ,application.yml is not enabled

**Comment by martinlippert** [comment] 2022-11-04 08:54
@zwssunny can you provide more details on this, we described in the above comment?

**Comment by ShuFengMuYu** [comment] 2022-12-07 12:52
> @zwssunny can you provide more details on this, we described in the above comment?

I  encountered the same problem. But mine doesn't work both in application.properties and application.yml.
I will try to provide some details. I am not good at english, so some spelling and grammer mistakes may occurred.

Extension Name: Spring Boot Tools
Extension Version: v1.41.0
OS Version: Windows_NT x64 10.0.19044
VS Code version: 1.73.1

Does the Java language support work just fine in your VS Code installation for the same project (including code completion, problem markers, etc.)?
Yes.
If you open the "Output" tab, is there an entry in the dropdown showing vscode-spring-boot-debug-log? And if so, can you share the output that shows up there?
Yes. Here are the files. [completion-doesnot-work.log](https://github.com/spring-projects/sts4/files/10176046/completion-doesnot-work.log) [completion-is-fine.log](https://github.com/spring-projects/sts4/files/10176052/completion-is-fine.log)
If you open the application.properties file, does it show up as Spring Boot Properties file type in the status bar (on the right side)?
Yes.

In fact, I detected some interesting phenomenon. **Code completion works well after I delete the content in ~/.m2/repository and open vscode again.** The dependencies will be installed automatically, and the code completion will work.
**However, After I close it and open it again, the code completion does not work again.**

**Comment by BoykoAlex** [comment] 2022-12-07 22:26
@ShuFengMuYu Another workaround that should probably help you is go in VSCode settings and find under **Java** settings:
**Java > Server : Launch Mode** and switch it to **Standard** then reload the window

**Comment by BoykoAlex** [comment] 2022-12-07 23:48
@ShuFengMuYu I suspect that you've encountered this #919. If the workaround of switching Java LS launch mode to **Standard** works then it must be it.

**Comment by ShuFengMuYu** [comment] 2022-12-08 07:33
@BoykoAlex Thank you very much. The workaround of switching Java LS launch mode to Standard works. I can continue to learn springboot with vscode.

**Closed** 2022-12-08 07:38 UTC
Labels: type: bug, theme: property-editing-support, for: vscode

**Comment by mesnuuu** [comment] 2022-12-25 11:21
> @ShuFengMuYu Another workaround that should probably help you is go in VSCode settings and find under **Java** settings: **Java > Server : Launch Mode** and switch it to **Standard** then reload the window

i am facing same issue and this workaround did not work. :(

**Comment by martinlippert** [comment] 2023-01-12 14:31
@mesnuuu Can you provide a few more details what exactly is not working, maybe attach a sample project and a few steps that you tried? Since there are various reasons why this may not work for you, I am not 100% sure that you are hitting the exact same issue or a slightly different one.
