### ISSUE TITLE
Support for Spring Boot app with Kotlin

### ISSUE THREAD

**Issue by pedromassango** [spring-projects/sts4#556] opened 2020-10-24 12:00 UTC
Does this plugin supports Spring Apps with Kotlin instead of java?

I used https://start.spring.io/ to generate an initial app using Kotlin but there is no way to activate/use this plugin while using Kotlin.

Note: I'm new here so, if it is currently possible just show me the way to go.

If not, is there any plans to support Kotlin projects?

**Comment by martinlippert** [comment] 2020-10-24 15:10
This is a duplicate of #163, which discusses the support of Kotlin. At the moment, Kotlin-based projects are not supported (yet).

**Closed by martinlippert** 2020-10-24 15:10 UTC
