### ISSUE TITLE
Plug-in org.springframework.ide.eclipse.boot.dash was unable to load class org.springframework.ide.eclipse.boot.dash.views.BootDashTreeView.

### ISSUE THREAD

**Issue by user20161119** [spring-projects/sts4#153] opened 2018-12-01 02:28 UTC
Boot Dashboard error when re-start spring tool suite.
error detail
```
org.eclipse.core.runtime.CoreException: Plug-in org.springframework.ide.eclipse.boot.dash was unable to load class org.springframework.ide.eclipse.boot.dash.views.BootDashTreeView.
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:200)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:182)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:934)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:246)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
	at org.eclipse.ui.internal.registry.ViewDescriptor.createView(ViewDescriptor.java:62)
	at org.eclipse.ui.internal.ViewReference.createPart(ViewReference.java:104)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPart(CompatibilityPart.java:305)
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:343)
	at sun.reflect.GeneratedMethodAccessor143.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
````

spring tool suite version

![image](https://user-images.githubusercontent.com/123967/49323269-d934b180-f553-11e8-8e24-c89084c8c2a2.png)

**Comment by kdvolder** [comment] 2018-12-03 18:18
I notice you have installed lombok. Does this problem also happen if you don't have lombok installed? If not, then its probably a lombok issue and should be reported with them.

**Comment by martinlippert** [comment] 2018-12-04 11:47
Beyond the observation and comment from Kris about Lombok, you also might want to try to start STS4 with the `-clean` option from the command line. Sometimes that helps in those situation. If not (and Lombok is not the cause), we would need to dive deeper into this (or you could try a fresh distribution install and double check that).

Do you have any other add-ons installed?

**Comment by user20161119** [comment] 2018-12-05 03:34
I forgot about STS 4 right now.switch to sts 3.x.
1. not compatible with legacy web projects and spring mvc based maven project
2. crash often especially after install some add-ons

**Comment by martinlippert** [comment] 2018-12-14 08:58
@user20161119 thanks for letting us know that Lombok was the root of the original issue reported here, this is indeed quite useful information. Looks like other people are suffering from similar issues when having the Lombok agent installed... :-(

(therefore also closing this item)

Regarding your last comment:
- what do you mean with "not compatible with legacy web projects and spring mvc maven projects"? What exactly are you missing or is not working as you would expect/need it?
- do you have any reproducible scenarios in which the IDE crashes? Or any crash reports? Is the JVM dying in those cases or is the IDE hanging or otherwise not working?

Would love to hear those details in order to improve the experience and fix those issues. Would you mind open new issues for that with some more details? That would be awesome!!!

**Closed by martinlippert** 2018-12-14 08:58 UTC

**Comment by martinlippert** [comment] 2018-12-14 09:00
I guess one of the issues with your legacy web projects is this one, right?
https://github.com/spring-projects/sts4/issues/154
