### ISSUE TITLE
In the process of writing Java code, if the speed of writing code is too fast, the following prompt will appear after the editor is stuck for a while!

### ISSUE THREAD

**Issue by 395053994** [spring-projects/sts4#435] opened 2020-04-04 12:15 UTC
In the process of writing Java code, if the speed of writing code is too fast, the following prompt will appear after the editor is stuck for a while!

In the process of writing Java code, if the speed of writing code is too fast, the following prompt will appear after the editor is stuck for a while!
Windows10 Enterprise Edition-x64
Spring Dev Toots 4 x64
System memory 8G
5400 RPM mechanical hard drive
![Eclipse bug](https://user-images.githubusercontent.com/27546390/78450377-be76cd80-76b0-11ea-85dc-416de35284e6.png)
![Snipaste_2020-04-04_20-13-49](https://user-images.githubusercontent.com/27546390/78450392-dfd7b980-76b0-11ea-9686-cf61c88956b2.png)

**Comment by 395053994** [comment] 2020-04-04 12:26
![Snipaste_2020-04-04_20-22-54kkkkkkkk](https://user-images.githubusercontent.com/27546390/78450620-85d7f380-76b2-11ea-980f-0acf2ec1f643.png)

**Comment by 395053994** [comment] 2020-04-04 12:28
This problem occurs frequently and is very frustrating!

**Comment by martinlippert** [comment] 2020-04-06 14:11
@395053994 I agree, sounds indeed frustrating to see that error dialog over and over again, we need to solve that. You can provide a simple sample project that could help us to reproduce the issue in order to analyze this in more detail? Also, if possible, it would be interesting to hear whether a plain Eclipse install behaves differently.

**Comment by 395053994** [comment] 2020-04-06 17:27
I have not tried ordinary Eclipse installation, but in the latest version of STS4, as long as you enter the code too fast, then STS4 will freeze for a while and then the error window pops up, the entire error process is generated in this way, you can also Try using a Maven multi-module project, I think the situation should be the same. I installed a codemix extension.

**Comment by 395053994** [comment] 2020-04-06 17:50
I think it has something to do with STS4 ’s slow and slow response.

**Comment by 395053994** [comment] 2020-04-06 18:56
Eclipse JavaEE version also has this problem after installing STS4 extension
![image](https://user-images.githubusercontent.com/27546390/78594545-16613000-787b-11ea-9434-1d07297d4c9c.png)
![Eclispe -2](https://user-images.githubusercontent.com/27546390/78594605-31cc3b00-787b-11ea-8087-7bf97b62a8e5.png)
Windows10 Enterprise Edition-x64
Spring Dev Toots 4 x64
System memory 8G
5400 RPM mechanical hard drive

**Comment by martinlippert** [comment] 2020-04-06 18:58
OK, one more check on this: can you go to the `Preferences -> Language Servers` and disable all four entries for the `Spring Boot Language Server`? Would be interesting to see if this makes a difference.

**Comment by 395053994** [comment] 2020-04-06 19:03
![image](https://user-images.githubusercontent.com/27546390/78595233-4230e580-787c-11ea-842f-f9dab8c07750.png)
What do you mean? not understand?

**Comment by 395053994** [comment] 2020-04-06 19:04
This is the default behavior

**Comment by 395053994** [comment] 2020-04-06 19:05
You can write your thoughts below, I will rest

**Comment by 395053994** [comment] 2020-04-06 19:06
goodbye friend!

**Comment by martinlippert** [comment] 2020-04-06 19:06
Click on the top-level node `Language Servers`, there you will see the four entries I was talking about... ;-)

**Comment by martinlippert** [comment] 2020-04-09 11:55
Any news here with regards to disabling the Spring Boot Language Server in the preferences? We also recently found an important issue that could cause slowdowns across the place, so maybe this was related to the issue that you were observing.

If you want to give it a try, you can grab the latest CI builds from here:
https://dist.springsource.com/snapshot/STS4/nightly-distributions.html

If the issue persists, it would be great if you could try the "disable the language server" advice to see if that changes anything.

In addition to that it would be good to take a look inside the Error Log View to see if there is anything related to this issue with maybe more details. In case you find something, please post the details here.

**Comment by martinlippert** [comment] 2020-04-29 13:19
We implemented a bunch of improvements and fixed in this area, so I expect the overall Java editing experience to be vastly improved with regards to the language-server-caused issues that we had in the past. Therefore I am closing this one here. Please feel free to give the latest CI build a try: https://dist.springsource.com/snapshot/STS4/nightly-distributions.html

And please comment if this issue re-appears using those nightly builds or beyond the upcoming 4.6.2 release and we can re-open this issue.

**Closed** 2020-04-29 13:20 UTC
Labels: accepted

**Comment by 395053994** [comment] 2020-04-30 06:48
Hello! Sir, I would like to ask, can STS4 UI interactive response speed be the same as IDEA or VsCode? STS4 is functionally perfect, but the response speed of UI interaction is not as smooth as IDEA or VsCode, and it will always be inadvertently stuck. Why is this? Can you find a clear reason? Because we really like to use Eclipse and STS4 to develop SpringCloud or SpringBoot applications.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Martin Lippert"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月29日(星期三) 晚上9:23
收件人:&nbsp;"spring-projects/sts4"<sts4@noreply.github.com&gt;;
抄送:&nbsp;"青春！"<395053994@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [spring-projects/sts4] In the process of writing Java code, if the speed of writing code is too fast, the following prompt will appear after the editor is stuck for a while! (#435)





 
We implemented a bunch of improvements and fixed in this area, so I expect the overall Java editing experience to be vastly improved with regards to the language-server-caused issues that we had in the past. Therefore I am closing this one here. Please feel free to give the latest CI build a try: https://dist.springsource.com/snapshot/STS4/nightly-distributions.html
 
And please comment if this issue re-appears using those nightly builds or beyond the upcoming 4.6.2 release and we can re-open this issue.

**Comment by 395053994** [comment] 2020-04-30 06:48
Hello! Sir, I would like to ask, can STS4 UI interactive response speed be the same as IDEA or VsCode? STS4 is functionally perfect, but the response speed of UI interaction is not as smooth as IDEA or VsCode, and it will always be inadvertently stuck. Why is this? Can you find a clear reason? Because we really like to use Eclipse and STS4 to develop SpringCloud or SpringBoot applications.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Spring Issuemaster"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月29日(星期三) 晚上9:22
收件人:&nbsp;"spring-projects/sts4"<sts4@noreply.github.com&gt;;
抄送:&nbsp;"青春！"<395053994@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [spring-projects/sts4] In the process of writing Java code, if the speed of writing code is too fast, the following prompt will appear after the editor is stuck for a while! (#435)





 
Closed #435.

**Comment by 395053994** [comment] 2020-04-30 06:52
Or is there any way for me to optimize the UI response speed of STS4 to improve the programming experience developed in Java?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Martin Lippert"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月29日(星期三) 晚上9:23
收件人:&nbsp;"spring-projects/sts4"<sts4@noreply.github.com&gt;;
抄送:&nbsp;"青春！"<395053994@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [spring-projects/sts4] In the process of writing Java code, if the speed of writing code is too fast, the following prompt will appear after the editor is stuck for a while! (#435)





 
We implemented a bunch of improvements and fixed in this area, so I expect the overall Java editing experience to be vastly improved with regards to the language-server-caused issues that we had in the past. Therefore I am closing this one here. Please feel free to give the latest CI build a try: https://dist.springsource.com/snapshot/STS4/nightly-distributions.html
 
And please comment if this issue re-appears using those nightly builds or beyond the upcoming 4.6.2 release and we can re-open this issue.

**Comment by 395053994** [comment] 2020-04-30 06:52
Or is there any way for me to optimize the UI response speed of STS4 to improve the programming experience developed in Java?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Spring Issuemaster"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月29日(星期三) 晚上9:22
收件人:&nbsp;"spring-projects/sts4"<sts4@noreply.github.com&gt;;
抄送:&nbsp;"青春！"<395053994@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [spring-projects/sts4] In the process of writing Java code, if the speed of writing code is too fast, the following prompt will appear after the editor is stuck for a while! (#435)





 
Closed #435.

**Comment by martinlippert** [comment] 2020-04-30 07:22
@395053994 Somehow your comments here appeared twice, so I deleted the duplicates.

With regards to your performance-related question, I don't see a clear reason why the interactive response speed in STS4 has to be slow or sluggish. But we should investigate why this is the case for you and identify the reasons, but this will require a bit of research and help from your side - and it would be awesome if you could help us with that.

How can you do that? First, grab the latest nightly build from https://dist.springsource.com/snapshot/STS4/nightly-distributions.html and use that for further testing and research. Then, please describe in more detail what you mean by the response speed of UI interaction specifically. What exactly is slow? Can you maybe record a screencast video, showing us what exactly is slow? And when this slowness happens?

Then, can you go to the `Preferences -> Language Server` and disable all the listed language servers by unchecking them in there. Does that make a difference?

**Comment by 395053994** [comment] 2020-05-01 03:54
In the process of writing Java code, in the process of constantly switching the tabs, I found that STS or Eclipse will have this problem. There is no idea and vscode smooth and lightweight, and there will always be a phenomenon of lag


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Martin Lippert"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月30日(星期四) 下午3:22
收件人:&nbsp;"spring-projects/sts4"<sts4@noreply.github.com&gt;;
抄送:&nbsp;"青春！"<395053994@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [spring-projects/sts4] In the process of writing Java code, if the speed of writing code is too fast, the following prompt will appear after the editor is stuck for a while! (#435)





 
@395053994 Somehow your comments here appeared twice, so I deleted the duplicates.
 
With regards to your performance-related question, I don't see a clear reason why the interactive response speed in STS4 has to be slow or sluggish. But we should investigate why this is the case for you and identify the reasons, but this will require a bit of research and help from your side - and it would be awesome if you could help us with that.
 
How can you do that? First, grab the latest nightly build from https://dist.springsource.com/snapshot/STS4/nightly-distributions.html and use that for further testing and research. Then, please describe in more detail what you mean by the response speed of UI interaction specifically. What exactly is slow? Can you maybe record a screencast video, showing us what exactly is slow? And when this slowness happens?
 
Then, can you go to the Preferences -&gt; Language Server and disable all the listed language servers by unchecking them in there. Does that make a difference?

**Comment by 395053994** [comment] 2020-05-01 03:57
Another problem is that "" double quotes cannot be automatically completed during the encoding process. If this problem can be improved, the encoding experience will be better




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Martin Lippert"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月30日(星期四) 下午3:22
收件人:&nbsp;"spring-projects/sts4"<sts4@noreply.github.com&gt;;
抄送:&nbsp;"青春！"<395053994@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [spring-projects/sts4] In the process of writing Java code, if the speed of writing code is too fast, the following prompt will appear after the editor is stuck for a while! (#435)





 
@395053994 Somehow your comments here appeared twice, so I deleted the duplicates.
 
With regards to your performance-related question, I don't see a clear reason why the interactive response speed in STS4 has to be slow or sluggish. But we should investigate why this is the case for you and identify the reasons, but this will require a bit of research and help from your side - and it would be awesome if you could help us with that.
 
How can you do that? First, grab the latest nightly build from https://dist.springsource.com/snapshot/STS4/nightly-distributions.html and use that for further testing and research. Then, please describe in more detail what you mean by the response speed of UI interaction specifically. What exactly is slow? Can you maybe record a screencast video, showing us what exactly is slow? And when this slowness happens?
 
Then, can you go to the Preferences -&gt; Language Server and disable all the listed language servers by unchecking them in there. Does that make a difference?

**Comment by 395053994** [comment] 2020-05-01 03:59
Another problem is that "" double quotes cannot be automatically completed during the encoding process. If this problem can be improved, the encoding experience will be better
That is to say, "" double quotes cannot be automatically matched and completed once. You need to enter double quotes twice ...






------------------ 原始邮件 ------------------
发件人:&nbsp;"Martin Lippert"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月30日(星期四) 下午3:22
收件人:&nbsp;"spring-projects/sts4"<sts4@noreply.github.com&gt;;
抄送:&nbsp;"青春！"<395053994@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [spring-projects/sts4] In the process of writing Java code, if the speed of writing code is too fast, the following prompt will appear after the editor is stuck for a while! (#435)





 
@395053994 Somehow your comments here appeared twice, so I deleted the duplicates.
 
With regards to your performance-related question, I don't see a clear reason why the interactive response speed in STS4 has to be slow or sluggish. But we should investigate why this is the case for you and identify the reasons, but this will require a bit of research and help from your side - and it would be awesome if you could help us with that.
 
How can you do that? First, grab the latest nightly build from https://dist.springsource.com/snapshot/STS4/nightly-distributions.html and use that for further testing and research. Then, please describe in more detail what you mean by the response speed of UI interaction specifically. What exactly is slow? Can you maybe record a screencast video, showing us what exactly is slow? And when this slowness happens?
 
Then, can you go to the Preferences -&gt; Language Server and disable all the listed language servers by unchecking them in there. Does that make a difference?

**Comment by martinlippert** [comment] 2020-05-01 20:05
> Another problem is that "" double quotes cannot be automatically completed during the encoding process. If this problem can be improved, the encoding experience will be better That is to say, "" double quotes cannot be automatically matched and completed once. You need to enter double quotes twice ...

I've seen that you filed a separate issue for this and I commented on that one to file a bug at Eclipse for this improvement.

> In the process of writing Java code, in the process of constantly switching the tabs, I found that STS or Eclipse will have this problem. There is no idea and vscode smooth and lightweight, and there will always be a phenomenon of lag

Do you mean switching between different open files if you have multiple editors open? I can usually switch between them without any lag or performance issue. So if you observe a lag when doing that, there definitely seems to be something wrong. In that case, I would like to ask you to maybe try and record a profiling session while doing this switching multiple times and send us that profiling data (e.g. using YourKit, JProfiler, VisualVM). That way, we could see what is going on and maybe even what is causing the lag. That would be awesome.
