### ISSUE TITLE
User operation after every save action

### ISSUE THREAD

**Issue by d2k2-git** [spring-projects/sts4#1290] opened 2024-07-10 20:35 UTC
**Describe the bug**
When editing any class file. the IDE is doing "invoking 'maven project builder on...' in the progress tab. the "user operation" dialog is preventing me from working on the sourcecode after every save action for a couple of seconds.

In the console you can see that something is executed on language server:

`
[Simple-Language-Server main thread] INFO  o.s.i.v.c.l.u.SimpleWorkspaceService - file changed event:`

**To Reproduce**
change and save any java class file.

**Sample**
-

**Comment by martinlippert** [comment] 2024-07-11 07:17
@d2k2-git I assume you mean editing a Java source file (not the class file directly), right? If you can create a small sample project that reproduces this behavior on a plain STS install, we can have a look as well, just to verify whether this is related to the parent pom as you mentioned or something else.

**Comment by BoykoAlex** [comment] 2024-07-11 17:08
Hmm... I'd recommend to follow up with vaadin plugin... STS isn't in charge of triggering maven builds on file changes or maven builds on workspace builds if memory serves me well... The file change event recieved by the Boot LS is expected. It triggers compilation unit cache entry invalidation, reconciling on the file etc., so some IDE features re-computation but Boot LS cannot trigger Eclipse workspace build, this is on the IDE client only.

**Comment by martinlippert** [comment] 2024-07-12 08:18
Since this seems to be clearly related to https://github.com/vaadin/platform/issues/6590, I am closing this one here. Please follow-up on https://github.com/vaadin/platform/issues/6590 as well as https://github.com/vaadin/platform/issues/6562.

**Closed by martinlippert** 2024-07-12 08:18 UTC
Labels: status: waiting-for-feedback, type: bug, for: eclipse
