### ISSUE TITLE
Eclipse crashes with webkit2gtk 2.36.5

### ISSUE THREAD

**Issue by 4javier** [spring-projects/sts4#804] opened 2022-08-01 16:27 UTC
I'm opening this ticket more as a link to an ugly bug that arose on mainline Eclipse with the last update of webkit2gtk in its 4.0 branch, used by the IDE.

Basically everytime STS tries to use webkit, like opening javadoc or editing some scss files, the system will freeze for a while then core dump.

That version of the library landed in stable repos in Arch and Fedora too.

Here the link to keep track of the issue
https://github.com/eclipse-platform/eclipse.platform.swt/issues/281

**Comment by cherio** [comment] 2022-08-01 20:35
I confirm. With the latest Arch Linux updates Eclipse crashes all the time. "Eclipse Marketplace" dialog reliably crashes the IDE

[eclipse-systemd-coredump.txt](https://github.com/spring-projects/sts4/files/9237279/eclipse.coredump.txt)

**Comment by martinlippert** [comment] 2022-08-02 06:40
Thanks @4javier for making us aware here, much appreciated.

Looks like we need to wait for a fix in Platform/SWT for this.

@cherio Please post your additional input to the above mentioned platform.swt issue.

**Comment by 4javier** [comment] 2022-08-02 10:03
Actually, it's been considered a regression in Webkit code.
https://github.com/WebKit/WebKit/pull/2904
Arch already rolled out a patched version of webkit2gtk, I think other major distros will do the same soon.

**Comment by martinlippert** [comment] 2022-08-02 10:40
@4javier Thanks for the update, much appreciated !!!

**Comment by martinlippert** [comment] 2023-02-24 15:05
I am closing this one as a duplicate of the mentioned issues in SWT and WebKit.

**Closed by martinlippert** 2023-02-24 15:05 UTC
Labels: type: bug, for: eclipse, status: duplicate
