### ISSUE TITLE
vscode-spring-boot "Code Completion" is invalid when editing application.yml 

### ISSUE THREAD

**Issue by xray2100** [spring-projects/sts4#55] opened 2018-05-04 08:55 UTC
It works for application.properties file, but there is no tip window when i edit application.yml .
Visual Studio Code version is 1.23.0
vscode-spring-boot version is 0.20-RC.1

**Comment by kdvolder** [comment] 2018-05-04 18:10
It seems to works for me. I used the same version as you mentioned.

Let's try to get a bit more info on your problem as really don't know right now why it wouldn't be working for you.

First, can you check what language vscode detects for your `application.yml` file? It should be shown in the lower right corner of the screen. (when I have 'application.properties' open it says 'Spring Boot Properties', when I have 'application.yml' open it says 'Spring Boot Properties Yaml').

If that looks fine...

Second let's check the log from the language server like this:

1. Use menu 'View >> Output' to show the 'output' view (if isn't shwn already)
2. Select 'Output' tab. And from the pulldown menu in top right area select 'vscode-spring-boot-debug-log'.
3. Copy and paste any output from there into this ticket.
4. The output will have a message shortly after starting the language server where it redirected the language-servers's logs. Something like this ` Redirecting log output to: /tmp/vscode-spring-boot-1525456631832.log`. Find that log file and attach its contents as well.

**Comment by kdvolder** [comment] 2018-05-08 22:42
Closing this ticket because I cannot reproduce the problem. If you find the time to try some of my suggestions and report back we can re-open the ticket and try to investigate more.

**Closed by kdvolder** 2018-05-08 22:42 UTC
