### ISSUE TITLE
Spring Tool Suite 4 is very slow on windows 10

### ISSUE THREAD

**Issue by archana-acharya** [spring-projects/sts4#321] opened 2019-07-12 15:30 UTC
Spring Tool Suite 4 

Version: 4.1.1.RELEASE
Build Id: 201901241133

This is very slow. I have increased memory, turned of validators and autobuild feature. STS.ini looks like this.

-startup
plugins/org.eclipse.equinox.launcher_1.5.200.v20180922-1751.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.1.900.v20180922-1751
-product
org.springframework.boot.ide.branding.sts4
--launcher.defaultAction
openFile
-vm
C:\Program Files\Java\jdk1.8.0_211\bin
-vmargs
-Dosgi.requiredJavaVersion=1.8
-Xms512m
-Xmx2048m
-XX:+UseG1GC
-XX:+UseStringDeduplication
--add-modules=ALL-SYSTEM
-javaagent:lombok.jar

Please help.

**Comment by BoykoAlex** [comment] 2019-07-12 15:51
Did you try switching to Spring Tool Suite 4 Version 4.3.1?

**Comment by archana-acharya** [comment] 2019-07-12 16:08
@BoykoAlex, STS 4.3.1 has the same issue.

**Comment by martinlippert** [comment] 2019-07-12 16:11
Can you give it a try without the lombok agent? Just to verify that this is or is not related to Lombok.

**Comment by BoykoAlex** [comment] 2019-07-12 16:42
BTW Is there something slow in particular? (i.e. Content-assist, typing is laggy, etc.) What do you compare it against? Plain Eclipse (4.12) without STS4 bits?

**Comment by spring-issuemaster** [comment] 2019-07-17 22:15
(comment in Pivotal Tracker added by Alex Boyko:) 

@archana-acharya are you still experiencing the issue with running STS 4.3.1 in Windows? If yes, would you be able to capture a Visual VM CPU Sampling snapshot while STS is slow for you?
You can download VisualVM for free here: https://visualvm.github.io/download.html. Pick a Java process and run CPU sampling and then stop it when something slow has been recorded...

**Comment by martinlippert** [comment] 2019-08-01 08:36
One more comment: you have to specify the `-vm` option in the first lines of the ini file, not somewhere in between.

Without further information, there is not much that we can do here to investigate the issue. Therefore I will close the issue for now. If you are still experiencing the performance issue (which would be very important to us), please let us know and provide more details and we can re-open this.

**Closed by martinlippert** 2019-08-01 08:36 UTC
Labels: started

**Comment by coolkanchan** [comment] 2021-04-29 19:56
Hi Team STS 4.10.0 responding very slow, when i click on any java class its seems to hang after 20 to 30 second it will become normal state. below is my .ini file

-startup
plugins/org.eclipse.equinox.launcher_1.6.100.v20201223-0822.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.2.100.v20210209-1541
-product
org.springframework.boot.ide.branding.sts4
--launcher.defaultAction
openFile
-vm
plugins/org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_15.0.2.v20210201-0955/jre/bin
-vmargs
-Dosgi.requiredJavaVersion=11
-Dosgi.dataAreaRequiresExplicitInit=true
-Xms256m
-Xmx2048m

**Comment by martinlippert** [comment] 2021-04-30 09:08
See https://github.com/spring-projects/sts4/issues/632

**Comment by hinorashi** [comment] 2021-05-27 17:48
it's slow on my ubuntu 20.10 as well, I'm using sts-4.10.0, could you please list out some settings/features that consume much resources so that we could choose which to be disabled 🐧 
my `.ini`:
```
-startup
plugins/org.eclipse.equinox.launcher_1.6.100.v20201223-0822.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.100.v20210209-1541
-product
org.springframework.boot.ide.branding.sts4
--launcher.defaultAction
openFile
-vm
plugins/org.eclipse.justj.openjdk.hotspot.jre.full.linux.x86_64_15.0.2.v20210201-0955/jre/bin
-vmargs
-Dosgi.requiredJavaVersion=11
-Dosgi.dataAreaRequiresExplicitInit=true
-Xms256m
-Xmx2048m
--add-modules=ALL-SYSTEM
-javaagent:/opt/sts-4.10.0.RELEASE/lombok.jar
```

**Comment by martinlippert** [comment] 2021-05-28 05:40
@hinorashi It is hard to say from the distance what exactly is slowing down your install. This comment provides some questions that would be useful to take a look at and provide more insights: https://github.com/spring-projects/sts4/issues/632#issuecomment-829973181.

I also see Lombok being installed into your STS, so removing that to see if that makes a difference is also worth a try.

**Comment by walturenamdev555** [comment] 2022-08-05 05:27
when i am trying to open properties or any other files its taking more that 5 min, could you please look in to this
below is my ini file

-startup
plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.2.500.v20220509-0833
-product
org.springframework.boot.ide.branding.sts4
--launcher.defaultAction
openFile
-vm
plugins/org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.3.v20220515-1416/jre/bin
-vmargs
--add-opens=java.base/java.io=ALL-UNNAMED
--add-opens=java.base/sun.nio.ch=ALL-UNNAMED
--add-opens=java.base/java.net=ALL-UNNAMED
--add-opens=java.base/sun.security.ssl=ALL-UNNAMED
-Dosgi.requiredJavaVersion=11
-Dosgi.dataAreaRequiresExplicitInit=true
-Xms256m
-Xmx2048m
--illegal-access=permit
--add-modules=ALL-SYSTEM

**Comment by martinlippert** [comment] 2022-08-05 07:44
@walturenamdev555 Opening any file is taking more than 5min? That sounds like something serious is broken. Let's try to see if we can find out what is going wrong here. A few things to investigate:

- Can you capture a thread dump while it takes so long (and attach it here)? Would be good to have a thread dump of the main IDE process AND any `BootLanguageServerBootApp` process, if there is any
- Can you disable the Spring Boot Language Server in the preferences (`Preferences -> Language Servers`, then disable it for all four file types it is configured for) and then see if that makes a difference

From whatever comes out of this, we can continue to investigate deeper.
Thanks @walturenamdev555 for your help with this!

**Comment by rakeshverizon** [comment] 2023-05-22 18:06
Hi, It's taking more than 30sec-1min when I try to open a method by clicking ctrl + left click, or copy paste takes lot more than that. Earlier version 4.5.1.release was much better and faster I think. This new version 4.18.0.release takes lot more time to code and it's very frustrating. Please let me know if something has to be changed within .ini file for this to work quicker.

**Comment by martinlippert** [comment] 2023-05-23 08:08
@rakeshverizon The numbers that you mention are indeed totally beyond what seems to be usable, completely understand that this is a frustrating experience. Let us try to find out what is going wrong here to see how we can improve the situation going forward. Hope you are up for a little help here.

First thing to look into would be:
- connect to the Spring Tool Suite process via jconsole and tell us about the CPU and memory consumption
- connect to the Spring Boot language server process using jconsole and tell us about the CPU and memory consumption
- enable the logging from the Spring Boot language server via `Preferences -> Language Servers -> Spring Language Server` and send us the log output of the language server

In case you see high CPU utilization in one of those two processes while the IDE is extremely slow in responding, feel free to capture a CPU profiling (e.g. using VisualVM or YourKit or similar) of that process during that time. Would be interesting to see what is going on under the hood.

If you have a sample project that you could put on GitHub for us in order to reproduce the issue, that would be great as well, but it depends on whether you can reproduce the slow behavior using a small workspace with a sample project or not. Sometimes those issues only appear when working with a larger workspace or specific projects. But let's see what is possible here.
