### ISSUE TITLE
Spring Tools 4 does not generate "additional-spring-configuration-metadata.json"

### ISSUE THREAD

**Issue by rodrigo-rassystem** [spring-projects/sts4#780] opened 2022-06-03 21:02 UTC
I am using STS4 release 4.14.1 on Eclipse Version: 2021-12 (4.22.0) Build id: 20211202-1639.
Spring project is using Maven and I added this dependency:

```
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-configuration-processor</artifactId>
			<optional>true</optional>
		</dependency>
```
And this class (_ExampleProperties.java_):
```
@Configuration
@ConfigurationProperties(prefix = "spep")
@Getter
@Setter
public class ExampleProperties {

    /**
     * Simple test.
     */
    String test;
}
```

It is expected that Eclipse could identify this new property "spep.test", but it doesn´t (as you can see below):
![image](https://user-images.githubusercontent.com/83311863/171950705-850394fa-2198-41e3-9163-5cebe62733a9.png)

I noticed that the plugin is not creating _META-INF/additional-spring-configuration-metadata.json_.

Here is a github repo whit example code to help diagnose this issue: 
https://github.com/rodrigo-rassystem/sts-processor-eclipse-problem

BTW: if I Run "Maven install", the file _./target/classes/META-INF/spring-configuration-metadata.json_ is generated and the problem goes away, but it is not a real solution.

**Comment by kdvolder** [comment] 2022-06-10 17:37
This might be because you are using lombok. We don't really support Lombok. It could also depend on whether the JDT apt has been configured properly. Normally this will be done automatically by m2e (m2e-apt extensio). But it may require that you force maven to 'update' project config by selecting 'Maven >> Update Project' from the 'right click' context menu on the project.

**Comment by kdvolder** [comment] 2022-06-10 17:52
Trying this out I ran into another problem. The quickfix for missing '@ConfigurationProperties' automatically triggeres a 'Update maven project'. However unfortunately that doesn't seem to work and it essentially deadlocks / gets stuck. Then I have to kill STS to get out of it. That seems to be a regression of sorts as this used to work for me. Maybe something changed in how m2e implemented this functionality.

**Comment by kdvolder** [comment] 2022-06-10 17:54
Attaching a stack dump of stuck process for later reference
[jps-update-maven-project-stuck.txt](https://github.com/spring-projects/sts4/files/8881088/jps-update-maven-project-stuck.txt)

**Comment by kdvolder** [comment] 2022-06-10 18:05
So besides the deadlock I mentioned above, (which I think is a serious/blocker issue), it seems to work fine when I manually do a maven project update. It is only the update triggered via the quickfix that has this problem.

When I do a manual update then JDT apt gets configured by m2e-apt, and the configuration metadata file is generated and then the warning disapears as expected.

**Comment by kdvolder** [comment] 2022-06-10 18:14
@rodrigo-rassystem Can you please try the following for trouble-shooting:

- Right click project. Select 'Properties >> Java Compiler >> Annotation Processing
- Compare to this screenshot:
![image](https://user-images.githubusercontent.com/1002156/173125873-5f26afc9-f7a6-436f-9830-76fd808e8e61.png)

Note: you shouldn't have to modify this yourself, it should get configured automatically by m2e-apt. We are simply trying to see if that is the problem. The reason for this is probably that when you add the dependency to your pom, m2e does not automatically trigger an update of the project. This is something you have to do manually, and I believe that is most likely by design (because it is an expensive operation).

**Comment by kdvolder** [comment] 2022-06-10 20:03
I've pushed a fix for the deadlock issue: https://github.com/spring-projects/sts4/commit/31e7ca43bfac191bb6430d467350941fc42cc663

Still waiting to close this issue to let @rodrigo-rassystem  have a chance to try whether 'Maven update project' makes it work for him.

**Comment by rodrigo-rassystem** [comment] 2022-06-10 20:38
> @rodrigo-rassystem Can you please try the following for trouble-shooting:
> 
> * Right click project. Select 'Properties >> Java Compiler >> Annotation Processing
> * Compare to this screenshot:
>   ![image](https://user-images.githubusercontent.com/1002156/173125873-5f26afc9-f7a6-436f-9830-76fd808e8e61.png)
> 
> Note: you shouldn't have to modify this yourself, it should get configured automatically by m2e-apt. We are simply trying to see if that is the problem. The reason for this is probably that when you add the dependency to your pom, m2e does not automatically trigger an update of the project. This is something you have to do manually, and I believe that is most likely by design (because it is an expensive operation).

Hello @kdvolder, here is the screen snapshot:
![image](https://user-images.githubusercontent.com/83311863/173146401-8abae70d-4f9d-4648-bd59-d9daec61e00d.png)

**Comment by kdvolder** [comment] 2022-06-10 20:48
That looks like expected. And still you don't get the generated config properties metadata?

**Comment by rodrigo-rassystem** [comment] 2022-06-10 20:49
No metadata generated.

**Comment by kdvolder** [comment] 2022-06-10 20:50
Another thing to check. Disable the '. files' filter. Then check the contents of `.factorypath` file.

**Comment by kdvolder** [comment] 2022-06-10 20:52
Note the `spring-boot-configuration-processor` depency is part of the factorypath. That's how m2e knows to execute the processing that generates this metadata.=

**Comment by rodrigo-rassystem** [comment] 2022-06-10 20:57
@kdvolder I could not find '.files' filter to disable here:
![image](https://user-images.githubusercontent.com/83311863/173150009-874afbb8-66ea-4e5e-922c-775ad7abefec.png)

**Comment by kdvolder** [comment] 2022-06-10 20:58
Sorry, it is actually called '. resources'.

**Comment by rodrigo-rassystem** [comment] 2022-06-10 21:01
Ok, but I could not find '.factorypath' neither in root paht nor inside any other path of the project.

**Comment by kdvolder** [comment] 2022-06-10 21:02
Tried one more time here and it works fine for me:
- paste in the `spring-boot-configuration-processor` in the pom
- m2e / maven does *not* automatically update project, so annotation processors remain disabled / not configured.
- Do 'Update Maven Project'
- APT gets configured.
- metadata gets generated as expected.

**Comment by kdvolder** [comment] 2022-06-10 21:03
> Ok, but I could not find '.factorypath' neither in root paht nor inside any other path of the project.

I would expect that would be the case until you do a 'Maven >> Update Project'.

**Comment by kdvolder** [comment] 2022-06-10 21:04
![image](https://user-images.githubusercontent.com/1002156/173150900-e7fb0c38-2b48-4f25-a13f-56210180ac7c.png)

**Comment by rodrigo-rassystem** [comment] 2022-06-10 21:06
@kdvolder did you clone the project that I uploaded in github?
https://github.com/rodrigo-rassystem/sts-processor-eclipse-problem

Here is the pom.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.7.0</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>br.com.example</groupId>
	<artifactId>sts-processor-eclipse-problem</artifactId>
	<version>1.0.0</version>
	<name>sts-processor-eclipse-problem</name>
	<description>sts-processor-eclipse-problem</description>
	<properties>
		<java.version>11</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-configuration-processor</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<excludes>
						<exclude>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
						</exclude>
					</excludes>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>
```

**Comment by kdvolder** [comment] 2022-06-10 21:07
No I didn't like I said your project uses Lombok and STS doesn't have lombok support so it wouldn't work.

**Comment by rodrigo-rassystem** [comment] 2022-06-10 21:09
Ok, I will try without lombok in another project and I will report next week. Thank you and see you soon!

**Comment by rodrigo-rassystem** [comment] 2022-06-10 21:11
@kdvolder another question: the problem with lombok occurs if I put lombok in the pom.xml or if Eclipse has lombok.jar installed?

**Comment by kdvolder** [comment] 2022-06-10 21:11
If you are using Lombok, did you install Lombok support into your version of STS? It isn't included with STS out of the box, and even if you did install Lombok support yourself, which you can do, I am not so sure if that would work in this particular case.

**Comment by rodrigo-rassystem** [comment] 2022-06-10 21:11
Yes, lombok is installed in Eclipse.

**Comment by kdvolder** [comment] 2022-06-10 21:20
Okay my guess is that Lombok annotations aren't processed before the spring-boot-processor, and that is probably why the metadata isn't being generated (i.e. spring-boot annotation processor doesn't see any getters and setters so it doesn't think there are any properties to generate metadata for). 

This is just a guess though, I'd need to figure out some way to debug it. Debugging an Eclipse modified by Lombok is somewhat tricky.

**Comment by rodrigo-rassystem** [comment] 2022-06-10 21:22
Ok, I will try without lombok, but at Lombok Project´s page it says that lombok is compatible with STS: https://projectlombok.org/setup/eclipse

**Comment by kdvolder** [comment] 2022-06-10 21:23
> @kdvolder another question: the problem with lombok occurs if I put lombok in the pom.xml or if Eclipse has lombok.jar installed?

So my understand of what you should do 'in theory' to make everything work:

- lombok must be in your pom. Otherwise lombok won't work for CLI builds
- you have to install the lombok agent into Eclipse STS in the way that lombok tells you to do it. This is needed because it modifies some internals of the Eclipse JDT compiler which makes it so Eclipse understand the meaning of Lombok annotations (otherwise you end up with compiler errors in Eclipse when you use the stuff lombok generates).

**Comment by rodrigo-rassystem** [comment] 2022-06-10 21:24
> > @kdvolder another question: the problem with lombok occurs if I put lombok in the pom.xml or if Eclipse has lombok.jar installed?
> 
> So my understanding of what you should do 'in theory' to make everything work:
> 
> * lombok must be in your pom. Otherwise lombok won't work for CLI builds
Yes, it is.

> * you have to install the lombok agent into Eclipse STS in the way that lombok tells you to do it. This is needed because it modifies some internals of the Eclipse JDT compiler which makes it so Eclipse understand the meaning of Lombok annotations (otherwise you end up with compiler errors in Eclipse when you use the stuff lombok generates).
Yes, it was.

**Comment by kdvolder** [comment] 2022-06-10 21:26
> Ok, I will try without lombok, but at Lombok Project´s page it says that lombok is compatible with STS:

For the most part I think it is. But when you start mixing lombok with other annotion processors then you are starting to venture onto thin ice, and I wouldn't be surprised that these things do not work nicely together. In that case perhaps it is a good idea to raise a but with Lombok and see what they think. If you decide to do that, be sure to put a link here so we can follow the discussion.

**Comment by rodrigo-rassystem** [comment] 2022-06-10 21:28
@kdvolder to sum up the problem may be related to the fact that Lombok changes some inner working of Eclipse annotation processor. I will open an issue there.

**Comment by kdvolder** [comment] 2022-06-10 21:30
It's probably not so much that Lombok changes the inner workings that is a problem. It is more like Lombok agent doesn't actually change the inner workings quite enough :-). I.e. the spring-boot-config processor seems to be unaware of the things that lombok is generating, and so it doesn't work as expected.

**Comment by kdvolder** [comment] 2022-06-13 21:33
Since I am assuming for now that STS is working properly, I am closing this for now. We can allways re-open it later if there's more info from Lombok that indicates STS  may need to do something to accomodate lombok better.

**Closed by kdvolder** 2022-06-13 21:33 UTC
Labels: status: waiting-for-triage, type: bug
