### ISSUE TITLE
STS Crash on Save event

### ISSUE THREAD

**Issue by akhilsharma2234** [spring-projects/sts4#868] opened 2022-11-06 16:14 UTC
I tried running multiple sub-version of STS4 but all are having same issue.

Whenever i save by pressing Ctrl-s or paste something by pressing Ctrl-v STS got crashed and some error file gets created on the home path of STS and the file named as something like : hs_err_pid244936.log

Kindly refer to the error files may be you will get some more information.
[File-1](https://drive.google.com/file/d/1Y9idjTF6bB4Qd3Gm5QFN02GGFJ6qKP4N/view?usp=share_link)
[File-2](https://drive.google.com/file/d/1ci8GwdP92Mp9R-dlIAo9JkL-DSwj6WRa/view?usp=share_link)

NOTE : I have enabled my save-action as below
![Screenshot from 2022-11-06 21-42-33](https://user-images.githubusercontent.com/35307766/200181780-03908135-0b96-416d-a800-4cdae3f8c11b.png)

I have also installed lombok library.

Please fix this ASAP because i can't handle this. It is too annoying when suddenly it gets crashed, my things are not saved sometimes and i have to re-do the work.

**Comment by martinlippert** [comment] 2022-11-06 17:14
Thanks @akhilsharma2234 for filing this issue and for attaching the log files. It looks like that indeed the JVM crashes in those situations.

It is very hard to say why the JVM crashes here, but I've seen two things that I would like to try to - at least - make sure that they are not related to the crash.

- it looks like (for some reason) that a JDK 18 is being used to run the IDE. Can you configure the `SpringToolSuite4.ini` to use a JDK17 instead to see if that makes a difference?

- it looks like you have Lombok installed, Can you try to run the IDE without that agent being configured in the `SpringToolSuite4.ini` file? I doubt that this is related to the crash, but it would be good to make sure that this is indeed not related.

The crashes also seem to happen in native code running on the linux platform, which might require us to report this against the underlying Eclipse platform. Can you elaborate a bit more on the exact system and versions you are running the IDE on?

**Comment by akhilsharma2234** [comment] 2022-11-06 17:20
HI @martinlippert 

Kindly refer the details below : 
![Screenshot from 2022-11-06 22-48-11](https://user-images.githubusercontent.com/35307766/200185091-7f445151-10f0-41fa-9207-ab34d1b52318.png)

Also, i will try to run the STS without the lombok agent.

My JDK version is : 
```
openjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)
```

Please let me know if you need more details.

Thanks.

**Comment by adarshgoyal1** [comment] 2022-11-07 10:57
HI @martinlippert 
I am also facing the same issue. I am using the same version of Ubuntu as @akhilsharma2234  is having. 
Please look into the matter.

**Comment by martinlippert** [comment] 2022-11-07 11:37
> My JDK version is :
> 
> ```
> openjdk version "11.0.16" 2022-07-19
> OpenJDK Runtime Environment (build 11.0.16+8-post-Ubuntu-0ubuntu122.04)
> OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)
> ```
> 

This might be the JDK that you have on your system running, but it is not the JDK that is used to run the IDE. The log files reveals that there is a specific, embedded version of the JDK being used from inside of the STS4 installation. You can switch that by changing the `-vm` value in the `SpringToolSuite4.ini`. Please point to a JDK17 and try again.

The easiest way to try that might be to download a fresh copy of STS 4.16.1 from https://spring.io/tools, extract that, and use that without any modifications, updates, or additions.

**Comment by martinlippert** [comment] 2022-11-07 12:53
I think this might be a duplicate of this:
https://github.com/eclipse-platform/eclipse.platform.swt/issues/158

There is a workaround mentioned at the end, so would be great if you could give that a try to let us know if that works around the issue. If not, it might make sense to jump on that report and add more details to that discussion.

**Comment by martinlippert** [comment] 2023-01-02 08:03
Closing this as a duplicate of https://github.com/eclipse-platform/eclipse.platform.swt/issues/158

**Closed by martinlippert** 2023-01-02 08:03 UTC
Labels: status: waiting-for-feedback, type: bug, for: eclipse

**Comment by akhilsharma2234** [comment] 2023-01-23 05:02
This is not fixed yet, and day by day it is becoming too annoying for me to do work on STS. I really don't want to switch to any other IDE but if you guys can't fix this issue then let me know so that me and my team can start using any other IDE.

**Comment by martinlippert** [comment] 2023-01-23 08:26
@akhilsharma2234 Since this is an issue with the underlying platform, I think it is best to ask those questions on the issue that you mentioned.

Did you see the comments about working around this issue by disabling Wayland and use X11 instead (at least until the underlying problem go fixed)? https://github.com/eclipse-platform/eclipse.platform.swt/issues/158#issuecomment-1235827515

**Comment by martinlippert** [comment] 2023-01-23 08:28
Here is another issue that covers this topic (for the reference): https://github.com/eclipse-platform/eclipse.platform.swt/issues/179
