### ISSUE TITLE
code completion is not work in vscode

### ISSUE THREAD

**Issue by msdemt** [spring-projects/sts4#290] opened 2019-05-14 07:17 UTC
my environment: 
os: win10
vscode: 1.33.1
jdk: jdk1.8.0_212
vscode extensions: 
      Language Support for Java(TM) by Red Hat: 0.44.0
      Spring Boot Tools: 1.6.0

I create a springboot project and open with vscode, when I edit the application.properties or application.yml, the code completion is not shown。and no Validation or Information Hovers。

![image](https://user-images.githubusercontent.com/38455670/57676623-81988700-7657-11e9-9935-f422953d8054.png)

And in .java file ,**Smart code completions** is also not work.
![image](https://user-images.githubusercontent.com/38455670/57676845-0c798180-7658-11e9-97d8-c28e859ba07d.png)

when I enable all vscode extensions, it is also not work.
![image](https://user-images.githubusercontent.com/38455670/57678584-1bfac980-765c-11e9-9a3b-cda51c33b5a7.png)

what else can I supply to solve the problem? thanks

**Comment by msdemt** [comment] 2019-05-14 07:30
I also tried the newer version EXTENSIONS, but also not work
![image](https://user-images.githubusercontent.com/38455670/57679091-181b7700-765d-11e9-8867-3f56b523488e.png)

**Comment by msdemt** [comment] 2019-05-14 08:28
the logs shown below
![image](https://user-images.githubusercontent.com/38455670/57682922-4f8e2180-7665-11e9-8440-09d547fba0cd.png)

**Comment by msdemt** [comment] 2019-05-14 08:30
the **vscode-spring-boot-1557822331183.log** shown below
![image](https://user-images.githubusercontent.com/38455670/57682976-6b91c300-7665-11e9-98c7-a4cf320caa20.png)
![image](https://user-images.githubusercontent.com/38455670/57683008-777d8500-7665-11e9-958f-31de57326d05.png)
![image](https://user-images.githubusercontent.com/38455670/57683030-83694700-7665-11e9-96cd-975ddd5beb35.png)
![image](https://user-images.githubusercontent.com/38455670/57683064-8ebc7280-7665-11e9-828a-f8993afef0fe.png)

**Comment by martinlippert** [comment] 2019-05-14 14:16
Would it be possible to share the project or a stripped down version of it that could help to reproduce the issue?

**Comment by msdemt** [comment] 2019-05-14 14:23
> Would it be possible to share the project or a stripped down version of it that could help to reproduce the issue?

[eureka.zip](https://github.com/spring-projects/sts4/files/3178213/eureka.zip)

this is my project, thanks for help

**Comment by kdvolder** [comment] 2019-05-14 16:04
I've tried it (not on Windows though, on Linux). It works fine for me. The log output that was posted by @msdemt looks pretty normal to me as well. So I really have no idea why it wouldn't be working for him.

**Comment by BoykoAlex** [comment] 2019-05-14 16:09
I have tried Win 10 (JDK 1.8.0_191) and seems to work fine for me. Maybe try a fresh copy of VSCode with only RedHat Java extension and Spring Boot Tools?

**Comment by msdemt** [comment] 2019-05-15 00:47
@martinlippert @kdvolder @BoykoAlex 
I unistall the vscode compelety then install vscode and spring boot tools extension，the code completion function is work well.
But when I install yaml extension，the code completion function in yml file is not work. I think maybe the spring boot tools extension can not compatible with yaml extension

**Comment by kdvolder** [comment] 2019-05-15 15:52
@msdemt Not sure what yaml extension you are referring to. So I have no idea if it is compatible or not. Let us know which extension exactly this is and then we can try it out and see if there is anything we can do to avoid the incompatibility problem.

**Comment by msdemt** [comment] 2019-05-15 15:55
@kdvolder 
this one, I install it because it is combine with kubernetes extension
![image](https://user-images.githubusercontent.com/38455670/57790168-c6faa880-776c-11e9-9d99-626544e61a27.png)

**Comment by kdvolder** [comment] 2019-05-15 20:58
@msdemt I installed the Yaml extension. No problem for me. The completions still work like before in `application.yml` file.

**Comment by kdvolder** [comment] 2019-05-15 21:02
Just a thought. Can you check and make sure that the 'language' which is showing in the status bar (bottom right corner below the editor) shows the correct language "Spring Boot Properties Yaml".

![status-bar](https://user-images.githubusercontent.com/1002156/57809242-e9170b00-7719-11e9-9088-3515986f7d43.png)

If the language there's not correct, you can click on it to change it. Whatever it shows there will determine what extensions are going to be asked to provide completions.

**Comment by msdemt** [comment] 2019-05-16 02:17
@kdvolder 
the 'language' in the status bar shows the "Spring Boot Properties Yaml" 
![image](https://user-images.githubusercontent.com/38455670/57820953-516cf780-77c1-11e9-8074-63cae63a9898.png)
![image](https://user-images.githubusercontent.com/38455670/57820958-5762d880-77c1-11e9-927b-cfd7c7d2127b.png)

I tested it on my two win10 computers and got the same result.
maybe it exists on the win10 system, or  maybe my win10 system has a problem.

**Comment by kdvolder** [comment] 2019-05-16 16:25
Okay, I think I have reproduced this. The completions *do* actually work both with and without the Redhat Yaml extension installed. However, when Yaml extension is installed then I have to invoke it explicitly by pressing CTRL-space, it doesn't auto-trigger as you type. 

I think Yaml extension is interferring with the auto-trigger. 

I have actually seen a similar problem before. See: https://github.com/spring-projects/sts4/issues/193

Not sure yet if there's much we can do about it ourselves. I think it has something todo with the fact that both redhat Yaml and our extension are being activated for the `application.yml` file. And redhat Yaml's sets trigger characters that interfere with the completion auto-triggering.

When I worked on addressing the above linked bug, we really went out of our way to make sure that 'Spring Boot Properties Yaml' was defined as a separate language-id and doesn't set it's own trigger characters but rather relies solely on the textmate grammar to make auto-triggers happen. 

In essence, the Redhat Yaml extension shouldn't do anything when you have selected language id as 'Spring Boot Properties Yaml' in the editor... since, technically, vscode doesn't or shouldn't consider the editor's content it be 'Yaml' at all. But... it seems that Redhat yaml does interfere with our code auto-completion triggers. So, that's probably a bug to be fixed in Redhat Yaml, or maybe even a bug in vscode itself.

Should investigate this more somehow.

**Comment by msdemt** [comment] 2019-05-17 00:05
@k

> Okay, I think I have reproduced this. The completions _do_ actually work both with and without the Redhat Yaml extension installed. However, when Yaml extension is installed then I have to invoke it explicitly by pressing CTRL-space, it doesn't auto-trigger as you type.
> 
> I think Yaml extension is interferring with the auto-trigger.
> 
> I have actually seen a similar problem before. See: #193
> 
> Not sure yet if there's much we can do about it ourselves. I think it has something todo with the fact that both redhat Yaml and our extension are being activated for the `application.yml` file. And redhat Yaml's sets trigger characters that interfere with the completion auto-triggering.
> 
> When I worked on addressing the above linked bug, we really went out of our way to make sure that 'Spring Boot Properties Yaml' was defined as a separate language-id and doesn't set it's own trigger characters but rather relies solely on the textmate grammar to make auto-triggers happen.
> 
> In essence, the Redhat Yaml extension shouldn't do anything when you have selected language id as 'Spring Boot Properties Yaml' in the editor... since, technically, vscode doesn't or shouldn't consider the editor's content it be 'Yaml' at all. But... it seems that Redhat yaml does interfere with our code auto-completion triggers. So, that's probably a bug to be fixed in Redhat Yaml, or maybe even a bug in vscode itself.
> 
> Should investigate this more somehow.

thanks for the confirm, I decided to temporarily not use the yaml extension.
Am I closing this issue or letting it open?

**Comment by kdvolder** [comment] 2019-05-17 02:11
> Am I closing this issue or letting it open?

While I don't think there is much STS can do to address this... 
I don't think the issue is really resolved yet, so we should leave it open. 

We may decide to raise a bug against vscode and/or the Redhat Yaml extension, but it needs a little more investigation first.

**Comment by kdvolder** [comment] 2019-05-21 18:50
I raised a ticket against the LSP protocol around specifying trigger characters per language: 

https://github.com/microsoft/language-server-protocol/issues/751

Some feedback on the ticket pointed out that it is already possible, using the dynamic registration, to set trigger characters specifically for a language. This is because it's possible to make multiple dynamci registration requests, each one with a different document filter.

This mechanism might allow us to address both #193 and this one at the same time.

I.e. to avoid interferring with auto-trigger in the Java case, we register java completions without trigger characters. And we can try setting trigger characters for yaml explicitly. 

I am exploring that option a bit right now.

**Comment by kdvolder** [comment] 2019-05-22 18:25
I've pushed a fix as described above and it appears to be working to solve this issue for vscode.

**Closed** 2019-05-23 11:38 UTC
Labels: delivered

**Comment by jagankanipakam** [comment] 2022-03-17 22:38
is this issue resolved?

**Comment by jagankanipakam** [comment] 2022-03-17 22:39
<img width="571" alt="Capture" src="https://user-images.githubusercontent.com/36910298/158905755-0586d952-1932-4c04-801b-afe158d73fa5.PNG">
I'm also facing the same issue now

**Comment by martinlippert** [comment] 2022-03-18 09:28
@jagankanipakam Yes, the code completion for `application.properties` files should work just fine. Do you have a few steps how to reproduce the problem? Maybe a sample project that we could use?

One of the things that I stumbled upon in the past is that the Java Language Tooling should run in the "Standard" launch mode in order to import and identify the Java projects in your workspace. If the Java tooling haven't identified the projects, the Spring Tooling can't do anything, so that code completion might not work (just guessing here). Take a look at the `Preferences -> Extensions -> Java -> Server: Launch Mode` and switch that to "Standard". Just guessing here, but would be good to double check this when writing down some steps how to reproduce the issue.

The background is:
The Spring Tools receive information from the Java tooling when projects get imported/identified in the workspace. The Spring Tools then can use this information to get access to the dependencies of the project (e.g. the Spring libs) and analyze them (look for metadata for property completion, for example). If the Java tooling runs in the "Lightweight" mode, it doesn't really fully import those Java projects in your workspace and therefore doesn't send that information to the Spring Tools.

**Comment by jagankanipakam** [comment] 2022-03-18 11:20
https://user-images.githubusercontent.com/36910298/158994102-5fc2d831-3314-4d90-8d62-e40f7339dd25.mp4

Please look at the attachment @martinlippert

**Comment by jagankanipakam** [comment] 2022-03-18 11:25
![image](https://user-images.githubusercontent.com/36910298/158994739-c1c91569-7342-4613-97da-e580f0a1cf95.png)
modified in workspace as well

**Comment by jagankanipakam** [comment] 2022-03-19 21:28
@martinlippert , the issue got resolved, actually i created the project in the desktop, later I moved it inside the c drive, now it's fine, I'm getting the code completion perfectly, thanks for your concern.

**Comment by martinlippert** [comment] 2022-03-20 08:32
@jagankanipakam Glad to hear that you got it working again. But what exactly was the problem in the first place? Sounds like you were not getting the completion while the project was on the desktop. Is that correct?

**Comment by murali-1999** [comment] 2022-11-09 06:33
@jagankanipakam , @martinlippert  .I experienced the same problem as @jagankanipakam did. I relocated my project folder from my desktop to my C drive in the same way you did, and everything went smoothly.

However, why is this the case? Is it because this pc only has only C drive?  **(I tested it on a different machine and it worked perfectly. I stored my project folder in G Drive.)**

**Comment by martinlippert** [comment] 2022-11-09 11:34
@murali-1999 Can you share a few more details, especially the exact and full path of the project you where using when it doesn't work?

And what exactly doesn't work? There are a few hints/questions mentioned in the comments above (especially around the file type being recognized as `Spring Boot Properties` automatically). And in addition to that maybe you can go to the preferences and set a log file location for the Spring Boot tools via

`"spring-boot.ls.logfile": "<somepath-on-your-machine>/vscode-logs.txt"`

and share the output with us here (in case it doesn't contain sensitive information)?
