### ISSUE TITLE
STS 4.2.0.RELEASE fails to update with "An error occurred while collecting items to be installed"

### ISSUE THREAD

**Issue by tjstuart** [spring-projects/sts4#287] opened 2019-05-07 23:10 UTC
Similar to #79, STS fails to update with below error.  I have tried the "Reload" suggestion in #79, but still the issue persists.  Find also below the contents of "Available Software Sites".  I'm not clear on which should be there, or can be removed or re-instated as #79 somewhat suggests.

Ultimately, I just wish to upgrade to 4.2.2 using the "Help | Check for Updates" menu as I have done in the past.

Win10 x64 launched via Java 8 Oracle JDK.

![image](https://user-images.githubusercontent.com/19812676/57338468-ca8c9f00-7170-11e9-90bf-637922a31179.png)

`An error occurred while collecting items to be installed
session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.eclipse.lsp4e,0.9.1.201904121104
No repository found containing: osgi.bundle,org.eclipse.xtext.xbase.lib,2.18.0.v20190408-0319
No repository found containing: osgi.bundle,org.springframework.boot.ide.branding,4.2.1.201904170946-RELEASE
No repository found containing: osgi.bundle,org.springframework.ide.eclipse.beans.ui.live,3.9.9.201904162228-CI-B2221
No repository found containing: osgi.bundle,org.springframework.ide.eclipse.boot,3.9.9.201904162228-CI-B2221
No repository found containing: osgi.bundle,org.springframework.ide.eclipse.boot.dash,3.9.9.201904162228-CI-B2221
No repository found containing: osgi.bundle,org.springframework.ide.eclipse.boot.launch,3.9.9.201904162228-CI-B2221
No repository found containing: osgi.bundle,org.springframework.ide.eclipse.boot.refactoring,3.9.9.201904162228-CI-B2221
No repository found containing: osgi.bundle,org.springframework.ide.eclipse.boot.restart,3.9.9.201904162228-CI-B2221
No repository found containing: osgi.bundle,org.springframework.ide.eclipse.boot.templates,3.9.9.201904162228-CI-B2221
No repository found containing: osgi.bundle,org.springframework.ide.eclipse.boot.validation,3.9.9.201904162228-CI-B2221
No repository found containing: osgi.bundle,org.springframework.ide.eclipse.boot.wizard,3.9.9.201904162228-CI-B2221
No repository found containing: osgi.bundle,org.springframework.ide.eclipse.buildship20,3.9.9.201904162228-CI-B2221
No repository found containing: osgi.bundle,org.springframework.ide.eclipse.buildship30,3.9.9.201904162228-CI-B2221
No repository found containing: osgi.bundle,org.springframework.ide.eclipse.cloudfoundry.manifest.editor,3.9.9.201904162228-CI-B2221
No repository found containing: osgi.bundle,org.springframework.ide.eclipse.editor.support,3.9.9.201904162228-CI-B2221
No repository found containing: osgi.bundle,org.springframework.ide.eclipse.imports,3.9.9.201904162228-CI-B2221
No repository found containing: osgi.bundle,org.springframework.tooling.boot.ls,1.6.0.201904170912
No repository found containing: osgi.bundle,org.springframework.tooling.bosh.ls,1.6.0.201904170912
No repository found containing: osgi.bundle,org.springframework.tooling.cloudfoundry.manifest.ls,1.6.0.201904170912
No repository found containing: osgi.bundle,org.springframework.tooling.cloudfoundry.manifeast.ls.integration,4.2.1.201904170912
No repository found containing: osgi.bundle,org.springframework.tooling.concourse.ls,1.6.0.201904170912
No repository found containing: osgi.bundle,org.springframework.tooling.jdt.ls.commons,4.2.1.201904170912
No repository found containing: osgi.bundle,org.springframework.tooling.ls.eclipse.commons,4.2.1.201904170912
No repository found containing: osgi.bundle,org.springframework.tooling.ls.eclipse.gotosymbol,4.2.1.201904170912
No repository found containing: osgi.bundle,org.springsource.ide.eclipse.commons.cloudfoundry.client.v2,3.9.9.201904162228-CI-B2221
No repository found containing: osgi.bundle,org.springsource.ide.eclipse.commons.core,3.9.9.201904121913-CI-B463
No repository found containing: osgi.bundle,org.springsource.ide.eclipse.commons.frameworks.core,3.9.9.201904121913-CI-B463
No repository found containing: osgi.bundle,org.springsource.ide.eclipse.commons.frameworks.ui,3.9.9.201904121913-CI-B463
No repository found containing: osgi.bundle,org.springsource.ide.eclipse.commons.jdk_tools,3.9.9.201904121913-CI-B463
No repository found containing: osgi.bundle,org.springsource.ide.eclipse.commons.livexp,3.9.9.201904121913-CI-B463
No repository found containing: osgi.bundle,org.springsource.ide.eclipse.commons.quicksearch,3.9.9.201904121913-CI-B463
No repository found containing: osgi.bundle,org.springsource.ide.eclipse.commons.ui,3.9.9.201904121913-CI-B463
No repository found containing: org.eclipse.update.feature,org.springframework.boot.ide.branding.feature,4.2.1.201904170946-RELEASE
No repository found containing: binary,org.springframework.boot.ide.branding.sts4.executable.win32.win32.x86_64,4.2.1.201904170946-RELEASE
No repository found containing: org.eclipse.update.feature,org.springframework.boot.ide.main.feature,4.2.1.201904170946-RELEASE
No repository found containing: binary,org.springframework.boot.ide.main.feature_root,4.2.1.201904170946-RELEASE
No repository found containing: org.eclipse.update.feature,org.springframework.ide.eclipse.boot.dash.feature,3.9.9.201904162228-CI-B2221
No repository found containing: org.eclipse.update.feature,org.springframework.tooling.boot.ls.feature,4.2.1.201904170912
No repository found containing: org.eclipse.update.feature,org.springframework.tooling.bosh.ls.feature,4.2.1.201904170912
No repository found containing: org.eclipse.update.feature,org.springframework.tooling.cloudfoundry.manifest.ls.feature,4.2.1.201904170912
No repository found containing: org.eclipse.update.feature,org.springframework.tooling.cloudfoundry.manifest.ls.integration.feature,4.2.1.201904170912
No repository found containing: org.eclipse.update.feature,org.springframework.tooling.concourse.ls.feature,4.2.1.201904170912
No repository found containing: org.eclipse.update.feature,org.springsource.ide.eclipse.commons.quicksearch.feature,3.9.9.201904121913-CI-B463`

**Comment by martinlippert** [comment] 2019-05-08 07:04
In case you already tried the "Reload" option and that didn't help, I would recommend to export all the update sites to a file, then delete them from the list in Eclipse/STS, and restart Eclipse/STS. Then re-import the list of update sites from the file again (there are buttons for that to the right of that list on the preference page). That should wipe out the stale cache data entirely.

In addition to that you should also remove the `e4.9` and ` e4.10` versions of the Spring Tools 4 update site from the list of available update sites first. As long as you have the `latest` in there, it is fine and you should always get the latest release.

The latest release version is 4.2.1 at the moment, btw. That is why I am a bit confused about your comment mentioning version 4.2.2. We currently work on that version. If you want to update to the latest nightly build of that, you could do that, too, but keep in mind that it is a continuous integration build, so you would always get the latest build, not the latest release. The p2 repo URLs for the nightly builds can be found here: https://dist.springsource.com/snapshot/STS4/nightly-distributions.html

**Comment by tjstuart** [comment] 2019-05-08 21:06
Thanks for the quick reply.  4.2.2 was a typo it seems.  I did try the reload option with no success.  I will try your other suggestion and report back.

**Comment by tjstuart** [comment] 2019-05-08 23:07
Issue resolved following suggestion around clearing the list of sites.  Steps were as below

* Export list of "Available Software Sites" to file (bookmarks.xml)
* Cleared list of "Available Software Sites"
* Edited xml file and removed those "e*" entries relating to "Spring Tool Suite 4" - kept just the "latest" one
* Restarted STS
* Imported xml file
* Restarted STS (perhaps not necessary)
* Help | Check for Updates
* Success am now using 4.2.1

One question though ... I left the below "e4.8" entry relating to the language server.  Should I remove  this also?  Below is all the entries relating to "springsource".

`<site url="https://download.springsource.com/release/TOOLS/sts4/update/latest" selected="true" name="Spring Tool Suite 4"/>`

`<site url="https://download.springsource.com/release/TOOLS/sts4-language-servers/e4.8" selected="true" name="Spring Tooling Language Servers for Eclipse"/>`

`<site url="https://download.springsource.com/release/TOOLS/sts4-language-server-integrations" selected="true" name="Spring Tools 4 Language Servers for Eclipse"/>`

**Comment by martinlippert** [comment] 2019-05-09 07:03
You can keep the language-server-related e4.8 entry, but it is really a left-over from the early days and will be cleaned up in future updates automatically for you.

Closing this item now since you got the issue resolved. Happy to hear that the workaround worked for you.

**Closed by martinlippert** 2019-05-09 07:03 UTC

**Comment by corinthian13** [comment] 2020-02-27 13:43
Update time takes too goddamn long. A lot easier just to delete old version and download + install new one. Crazy.

**Comment by martinlippert** [comment] 2020-03-06 09:26
@corinthian13 What exactly are you doing to trigger the update? `Check for Updates`? And what exactly takes a long time? Finding the updatable components or downloading them? Maybe we can figure out what is slowing down the process and improve, so more details would be much appreciated... :-)

**Comment by corinthian13** [comment] 2020-03-06 11:48
It was the installation phase of the update. Some of them were problematic to the installer. I tried the method alluded to above by yourself and it worked. (Why do we need to use such a gauche process in the first place?) But even that was a long drawn-out process.

**Comment by martinlippert** [comment] 2020-03-06 16:08
@corinthian13 The reason for the issue described above is caused by something inside of the Eclipse platform update process as far as I understand. The good news is that this might be finally identified and fixed in the Eclipse platform, so probably less likely to happen in the future.

The regular update process should be quite smooth and without any hiccups, so this is definitely not intended. Having said that, if you come across something like this after updating to the next (to be released) version of the Spring Tools, please file another issue. And if you observe any other performance issues while using the tools, please do not hesitate to contact us.

**Comment by corinthian13** [comment] 2020-03-06 17:31
I will. Maybe.
But I'm a bit mystified about the attitude of an organization like Pivotal Inc not giving enough resources (testers in particular) to a framework on which a lot of their revenue depends.
There's a touch of the Microsofts about your bug detection approach . . .

**Comment by martinlippert** [comment] 2020-03-06 18:11
This issue tracker is about questions and issues for the Spring Tools 4 and as you can see from all the other issues and our work with the community, we are happy to help and solve technical issues to the best of our users. Therefore please feel free to raise additional issues that you run into while using the Spring Tools 4 and maybe help us a bit analyzing the problem by providing as much information and details as possible. That would be much appreciated.

If you would like to share your thoughts about a specific company, an attitude you think you have identified, a different approach to allocate resources to specific topics, or have questions/thoughts about how revenue is being created or what the revenue depends on, please feel free to reach out to that company using the appropriate channel for that, which you can find on the company website.

**Comment by kdvolder** [comment] 2020-03-06 18:15
> But I'm a bit mystified about the attitude of an organization like Pivotal Inc not giving enough resources (testers in particular) to a framework on which a lot of their revenue depends

Actually, I think we (team working on STS and other related developer tooling) are considered a 'cost center' meaning we cost the company money and do not directly generate revenue. 

Perhaps you have to consider that, considering that STS is free, open source and user do not pay a penny for it.... you might wonder why a company like Pivotal or VMWare has a team of 5 people working on it more or less full-time (that is actually quite a large cost!). You are right, more testing would be good, but we do what we can.

BTW: Thanks for taking the time to file bugs, report problems etc. I beleave it is actually rare for users to bother with that. And it is much appreciated and very helpful to us.
