### ISSUE TITLE
Tomcat port issue

### ISSUE THREAD

**Issue by PNPavanKumar** [spring-projects/sts4#935] opened 2022-12-28 12:53 UTC
Hi ,
I am facing a issue regarding Tomcat server.port as i changed the default port using server.port=9090 but still the Tomcat is running in default port 8080 only . Please give suggestions on this issue ASAP.

**Comment by BoykoAlex** [comment] 2022-12-28 19:14
This is a duplicate of #929. Specify the port in launch config Boot tab as a workaround

**Closed by BoykoAlex** 2022-12-28 19:14 UTC

**Comment by martinlippert** [comment] 2022-12-29 11:13
Looks like you posted the same question on SO as well: https://stackoverflow.com/questions/74940624/server-port-issue-in-java
