### ISSUE TITLE
Navigation support from property placeholders to definitions

### ISSUE THREAD

**Issue by gayanper** [spring-projects/sts4#941] opened 2023-01-06 12:06 UTC
**Expected Behavior**

Navigation support from property placeholders in source code to property definition.

**Current Behavior**

No navigation, only completions are available.

**Comment by martinlippert** [comment] 2023-01-06 12:17
Thanks for the feature request @gayanper. I think this is a duplicate of #761, so closing this one here as a duplicate. If not, please comment and we can re-open.

**Closed by martinlippert** 2023-01-06 12:17 UTC
Labels: type: enhancement, theme: property-editing-support, for: eclipse, status: duplicate, for: vscode
