### ISSUE TITLE
While processing code complete in jsp editor using content assist will replace previous code type

### ISSUE THREAD

**Issue by nandakumardtc** [spring-projects/sts4#594] opened 2021-02-04 09:26 UTC
**Describe the bug**
While processing code complete in jsp editor using content assist ( **control+space** ) will replace previous typed code
am attaching an video for the same but if a space is given after the tag then it will not get replaced  

**To Reproduce**
Am attaching an demo project spring boot project please go to the path /demo/src/main/resource/views open demo.jsp file and 
i opened an div tag try the content assist by and close div it will replace the previously opened div tag. 

[demo.zip](https://github.com/spring-projects/sts4/files/5924301/demo.zip)

**Sample**
am attaching an video proof it will help you to understand

https://user-images.githubusercontent.com/40513758/106872279-20e99180-66f9-11eb-90a4-b293724cde10.mp4

**Comment by martinlippert** [comment] 2021-02-05 08:18
Thanks @nandakumardtc for reporting this issue and attaching the video, that is a great report. Using your material, I am easily reproduce the issue, which is great. Looks indeed like a very strange behavior.

Unfortunately, this JSP editing capability that is included in the Spring Tools 4 for Eclipse distribution (up to version 4.9.0) comes from the Eclipse WTP project, so you should reach out to that project and report the bug there. I would raise it via: https://bugs.eclipse.org/bugs/enter_bug.cgi?product=WTP%20Source%20Editing, select the `jst.jsp` component and let them know about the video and the sample project as well.

As an additional side note: We will not include the JSP editing from WTP by default anymore moving forward. Instead, we will include the Wild Web Developer tooling components for various different types of web components. Unfortunately, JSP files are not specifically supported, but you be able to use the HTML editing capabilities of the Wild Web Developer tools to get at least some support. As an alternative, you could also install the WTP-based tooling manually into your installation then.

Hope this helps. Since this should be reported to Eclipse (as described above), I will close this here, but please feel free to comment if there is a need to re-open this here. Happy to help.

**Closed by martinlippert** 2021-02-05 08:18 UTC
