### ISSUE TITLE
XML configuration autocomplete fails (STS 4.21.0)

### ISSUE THREAD

**Issue by mplukas** [spring-projects/sts4#1160] opened 2023-12-13 17:04 UTC
**Describe the bug**
The bug occurs in STS 4.21.0 (eclipse.buildId=4.21.0.202312011804)
In Spring XML beans configuration files autocomplete for property names and beans references is broken.

When pressing Ctrl+Space for the property name/bean's reference, an IDE error occurres:
```
java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Internal error.
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at org.eclipse.lsp4e.operations.completion.LSContentAssistProcessor.computeCompletionProposals(LSContentAssistProcessor.java:132)
	at org.eclipse.jface.text.contentassist.AsyncCompletionProposalPopup.lambda$10(AsyncCompletionProposalPopup.java:378)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.jface.text.contentassist.AsyncCompletionProposalPopup.lambda$9(AsyncCompletionProposalPopup.java:377)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Internal error.
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at org.eclipse.lsp4e.LanguageServerWrapper.lambda$3(LanguageServerWrapper.java:309)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```
This seems to be caused by LS LemMinx  error (file URI disguised):
```
[2023-12-13T18:35:37.472172900+02:00] LSP4E_TO_LANGUAGE_SERVER org.eclipse.wildwebdeveloper.xml:
{"jsonrpc":"2.0","id":"17","method":"textDocument/completion","params":{"context":{"triggerKind":1},"textDocument":{"uri":"file:///<...>.xml"},"position":{"line":64,"character":24}}}
[2023-12-13T18:35:37.527849900+02:00] LANGUAGE_SERVER_TO_LSP4E org.eclipse.wildwebdeveloper.xml:
{"jsonrpc":"2.0","id":"17","error":{"code":-32603,"message":"Internal error.","data":"java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke \"java.util.List.forEach(java.util.function.Consumer)\" because the return value of \"java.util.Map.get(Object)\" is null\r\n\tat java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)\r\n\tat java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)\r\n\tat java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)\r\n\tat java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)\r\n\tat java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)\r\n\tat java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)\r\n\tat java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)\r\n\tat java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)\r\n\tat java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)\r\nCaused by: java.lang.NullPointerException: Cannot invoke \"java.util.List.forEach(java.util.function.Consumer)\" because the return value of \"java.util.Map.get(Object)\" is null\r\n\tat org.eclipse.lemminx.utils.CompletionItemDefaultsUtils.setToMostCommonEditRange(CompletionItemDefaultsUtils.java:76)\r\n\tat org.eclipse.lemminx.utils.CompletionItemDefaultsUtils.process(CompletionItemDefaultsUtils.java:46)\r\n\tat org.eclipse.lemminx.services.XMLCompletions.doComplete(XMLCompletions.java:293)\r\n\tat org.eclipse.lemminx.services.XMLLanguageService.doComplete(XMLLanguageService.java:171)\r\n\tat org.eclipse.lemminx.XMLTextDocumentService.lambda$completion$3(XMLTextDocumentService.java:264)\r\n\tat org.eclipse.lemminx.commons.ModelTextDocuments.lambda$computeModelAsync$0(ModelTextDocuments.java:118)\r\n\tat java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)\r\n\t... 6 more\r\n"}}
```
Other functionality like listing of beans in XML configuration file (Ctrl+6, Ctrl+O),  XML schema processing, autocomplete of XML tags/attributes seems to be ok.

If LemMinx is disabled in "Language Server" preferences, then Spring beans XML autocomplete for property names/bean refs work as expected. (But then of course XML editing is disabled).

**Comment by BoykoAlex** [comment] 2023-12-13 19:38
Hmm... I'm inclined to move this over to LimMinx XML LS... There are bean refs and propety completions that we add to XML but these seem to run within Boot LS rather than XML LS... Seems that failure to compute completions on the XML LS lead to the issue... Boot LS contributes an extension to XML LS to resolve "project-aware" URIs but i doubt this would cause that much interference...
Wonder if you could unisnatll Boot LS extension, enable XML LS and check if the issue is still reproducible. If yes, I'd move this over to XML LS

**Comment by mplukas** [comment] 2023-12-13 21:04
It seems you are right - it's XML LS problem.
The error manifests itself with Spring LS uninstalled and also using "clean" Eclipse 2023-12 for Java.

It seems XML LS always tries to process Ctrl+Space (and Ctrl+6) but if cursor is in the "unexpected" location - like inside XML comment or attribute's value - where completion suggestions from XML point of view are empty, then XML LS fails with NPE.

**Comment by martinlippert** [comment] 2023-12-18 13:45
Thanks @mplukas for double checking, so please open an issue for this at https://github.com/eclipse/lemminx. Closing this one here.

**Closed by martinlippert** 2023-12-18 13:45 UTC
Labels: status: waiting-for-triage, type: bug

**Comment by mplukas** [comment] 2023-12-20 13:56
The issue in LemMinX seems already has been fixed while implementing [XML Files support with settings #1604 ](https://github.com/eclipse/lemminx/issues/1464).
See added check in the [commit ](https://github.com/eclipse/lemminx/pull/1604/commits/a7bafefa0fdeea44ee35d860e3cade1461d4d926#diff-adec7f9e64c515fab203b108dd1315757024e28ee770a7a42b7f9ebec237654)
```
		if (mostCommonRange == null) {
			return;
		}
```
So we just need to wait for the new LemMinx release, and then for the new Eclipse Wild Web Developer release...
