### ISSUE TITLE
sts4 vscode does not run when using cloud config options

### ISSUE THREAD

**Issue by Oscar-21** [spring-projects/sts4#480] opened 2020-06-11 16:02 UTC
The app runs fine in sts4 eclipse and intellij but running via sts4 vscode I get errors:
I believe this is related to using a cloud config instead of a yml file.

Unsatisfied dependency expressed through method 'awsParamStorePropertySourceLocator' parameter 0; 
nested exception is org.springframework.beans.factory.BeanCreationException: 
Error creating bean with name 'ssmClient' defined in class path resource [org/springframework/cloud/aws/autoconfigure/paramstore/AwsParamStoreBootstrapConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: 
Failed to instantiate
[com.amazonaws.services.simplesystemsmanagement.AWSSimpleSystemsManagement]: Factory method 'ssmClient' threw exception;
 nested exception is java.lang.IllegalArgumentException: java.net.URISyntaxException: Illegal character in authority at index 8: https://ssm.us-east-1.amazonaws.com

**Comment by kdvolder** [comment] 2020-06-11 16:23
Please provide some detailed instructions on how to reproduce the problem. Ideally you include a test project with these instructions, alongside precisely what steps you do to open the project into vscode and run it.

Note: How apps launch in vscode isn't actually part of the STS 4 plugins, it is actually the vscode-java extension that does this. But we can still try and help here to get to the bottom of what is going on and, if it seems waranted, follow up with a bug report against the right vscode extension.

However, we cannot do anything without a way to reproduce the problem.

**Comment by martinlippert** [comment] 2021-02-13 18:15
Closing this due to no additional feedback or sample project arrived here. If this is still an issue, please comment and we can re-open the item. In that case, please provide a sample project and your used launch config for VSCode, so that we can try to reproduce this.

**Closed by martinlippert** 2021-02-13 18:15 UTC
