### ISSUE TITLE
Support 'goto definition' in .properties / .yml boot-properties language server

### ISSUE THREAD

**Issue by dsyer** [spring-projects/sts4#16] opened 2017-11-13 06:44 UTC
It's nice to get the documentation in `application.properties`, but I don't see a way to jump to the source code (like you can in STS3). Am I missing something?

**Comment by kdvolder** [comment] 2017-11-14 22:28
It seems to be working for me. I tried with this properties file content:

```
server.port=5666
my.title=dssdf
```

Then hold down CTRL and click on either of the 2 properties. (The second one is defined in my own MyConfig @Configuration properties class, with source residing in the same project).

Both worked for me.

Note: I did just fix another bug around the configuration of the JDT annotation processor which might have been the cause of this not working for user-defined properties (i.e. annotation processor not executed => no metadata). But in that case probably there would also be other signs of 'trouble' such as the property name being underlined with 'unknown property warning'.

I could imagine that there may be some specific cases where the navigation is broken (but in that case its also broken for those same cases in STS 3). If you are still having problem in the latests CI build, can you provide more details on exactly the property key where this doesn't seem to work?

**Comment by kdvolder** [comment] 2017-11-14 22:32
BTW... if you hover your mouse inside the hover, you'll see that it changes appearance and a little 'goto declaration' button will appear in the lower-right corner of the hover control. clicking the button also opens the corresponding source code (and this also worked for me).

Closing for now. Can reopen if there's a more specific example where it doesn't work.

**Comment by dsyer** [comment] 2017-11-15 07:02
I installed the `vscode-boot-properties-0.0.10-201711141830.vsix` and tried again. Still not getting any "goto declaration" links (on an empty project from start.spring.io with server.port in application.properties). I can see the docs from the generated JSON. I don't see any autocompletes for local `@ConfigurationProperties` either, if I add one of those, so one of us is wrong.

**Comment by kdvolder** [comment] 2017-11-15 18:52
I was using STS 4, eclipse distribution, not the vscode extension. I don't 'goto declaration' is even implemented yet in the lsp-based version. So we should call this a 'known issue'. I'll leave it re-opened though and change the description a bit as its a real issue.

**Comment by kdvolder** [comment] 2017-11-15 18:56
BTW: Implementing this in language-server environment is probably a bit hard, especially for when the source-code is actually not readily available for .jar dependencies as we can not lean on Eclipse here to resolve source code for those things and open them in the editor.

**Comment by crazythinking** [comment] 2018-11-25 08:46
I also cannot go to definition source code even in STS4, here is logs when open .propertes/.yml file with Generic Editor:
16:42:33.758 [main] INFO  o.s.i.v.b.a.BootLanguagServerBootApp - Starting BootLanguagServerBootApp v1.1.0-SNAPSHOT on ericlu-HP-ENVY-15-Notebook-PC with PID 29169 (/opt/spring/sts-4.0.1.RELEASE/configuration/org.eclipse.osgi/527/data/1.1.0.201810300740-spring-boot-language-server-1.1.0-SNAPSHOT.jar started by ericlu in /home/ericlu)
16:42:33.761 [main] INFO  o.s.i.v.b.a.BootLanguagServerBootApp - No active profile set, falling back to default profiles: default
16:42:33.806 [main] INFO  o.s.c.a.AnnotationConfigApplicationContext - Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@1c53fd30: startup date [Sun Nov 25 16:42:33 CST 2018]; root of context hierarchy
16:42:34.227 [main] INFO  o.s.b.f.a.AutowiredAnnotationBeanPostProcessor - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
16:42:34.749 [main] INFO  o.s.j.e.a.AnnotationMBeanExporter - Registering beans for JMX exposure on startup
16:42:34.763 [main] INFO  o.s.i.v.b.a.BootLanguagServerBootApp - Started BootLanguagServerBootApp in 1.618 seconds (JVM running for 2.195)
16:42:34.765 [LanguageServerApp-lifecycle] INFO  o.s.i.v.c.l.LanguageServerRunner - Server ready to start after 2197 ms
16:42:34.767 [LanguageServerApp-lifecycle] INFO  o.s.ide.vscode.commons.util.Log - Starting LS
16:42:34.767 [LanguageServerApp-lifecycle] INFO  o.s.ide.vscode.commons.util.Log - Connected to parent using stdio
16:42:34.833 [pool-3-thread-1] INFO  o.s.i.v.c.l.u.SimpleLanguageServer - Initializing
16:42:35.931 [SimpleLanguaserver main thread] INFO  o.s.i.v.c.l.u.SimpleLanguageServer - Initialization completed after 3363 ms
16:42:35.979 [SimpleLanguaserver main thread] INFO  o.s.i.v.b.jdt.ls.JdtLsProjectCache - Project Created: file:/home/ericlu/java_workspaces/smartstar/smartstar-0.1.0/smartstar-web
16:42:35.985 [SimpleLanguaserver main thread] INFO  o.s.i.v.b.jdt.ls.JdtLsProjectCache - Classpath has 219 entries 185 source attachements
16:42:35.985 [SimpleLanguaserver main thread] INFO  o.s.i.v.b.a.BootLanguageServerInitializer - A project changed smartstar-web, triggering reconcile on all open documents
16:42:36.007 [Reconciler-1] INFO  o.s.ide.vscode.commons.util.Log - Indexing Spring Boot Properties for smartstar-web
16:42:36.008 [SimpleLanguaserver main thread] INFO  o.s.i.v.b.jdt.ls.JdtLsProjectCache - Project Created: file:/home/ericlu/java_workspaces/smartstar/smartstar-0.1.0/smartstar-biz-service
16:42:36.011 [SimpleLanguaserver main thread] INFO  o.s.i.v.b.jdt.ls.JdtLsProjectCache - Classpath has 173 entries 149 source attachements
16:42:36.011 [SimpleLanguaserver main thread] INFO  o.s.i.v.b.a.BootLanguageServerInitializer - A project changed smartstar-biz-service, triggering reconcile on all open documents
16:42:36.038 [SimpleLanguaserver main thread] INFO  o.s.i.v.b.jdt.ls.JdtLsProjectCache - Project Created: file:/home/ericlu/java_workspaces/gears/gm/gm-config
16:42:36.041 [SimpleLanguaserver main thread] INFO  o.s.i.v.b.jdt.ls.JdtLsProjectCache - Classpath has 183 entries 162 source attachements
16:42:36.041 [SimpleLanguaserver main thread] INFO  o.s.i.v.b.a.BootLanguageServerInitializer - A project changed gm-config, triggering reconcile on all open documents
16:42:36.251 [Reconciler-1] INFO  o.s.ide.vscode.commons.util.Log - Indexing Spring Boot Properties for smartstar-web DONE
16:42:36.251 [Reconciler-1] INFO  o.s.ide.vscode.commons.util.Log - Indexed 2112 properties.
16:42:36.272 [Reconciler-1] INFO  o.s.i.v.c.jandex.JandexClasspath - Creating JandexIndex for smartstar-web

**Comment by BoykoAlex** [comment] 2018-11-25 18:07
You should be able to use "goto definition" in STS4 starting with 4.0.2 which is to be released next week only. (Or you could try that from a CI build perhaps)

**Comment by crazythinking** [comment] 2018-11-26 03:06
thx, i will try next week

**Closed** 2018-12-04 12:01 UTC
Labels: enhancement
