### ISSUE TITLE
Lombok and spotless-maven-plugin Issues

### ISSUE THREAD

**Issue by CrisLi** [spring-projects/sts4#1008] opened 2023-03-17 02:30 UTC
**Describe the bug**

There are 3 issues I found after I upgraded to version 4.18.0.RELEASE.  

OS: MacOS 13.2.1
Chips: M1

1. XML (Maven POM) editor format action not working - When I press Command + Shift + F nothing happens.
2. `spotless-maven-plugin` and Lombok can't work together. `lombok.patcher.Symbols class not found`. 
3. Work with Lombok plunging, the `lombok.config` config file doesn't load.

Issue 2 screenshot

<img width="1525" alt="image" src="https://user-images.githubusercontent.com/360767/225794720-8521a817-e2b3-4c0d-a9b7-2e328a8453c4.png">

Issue 3 details

Here is my `lombok.config` 
<img width="657" alt="image" src="https://user-images.githubusercontent.com/360767/225796330-d851c66b-4831-459a-a30f-2c53c5a7fc58.png">

And in the IDE, there is a warning which should not be there.
<img width="388" alt="image" src="https://user-images.githubusercontent.com/360767/225796411-2f7f4fd7-90f1-4913-8aa6-890d1e0264e0.png">

When running the application in IDE, it prints out 'true', but when I run it in the terminal it prints out 'false', which my code expects should be.

<img width="469" alt="image" src="https://user-images.githubusercontent.com/360767/225796990-322c093d-5f1c-4419-a92e-07c1b82ad68d.png">

Same code in the IDE
<img width="704" alt="image" src="https://user-images.githubusercontent.com/360767/225796674-26049709-48c7-41d4-bcfd-5cff1ba05a3c.png">

Same code in the terminal
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/360767/225796706-75a2bbf3-ce31-431d-9bb6-c6d12d216d59.png">

**To Reproduce**
Steps to reproduce the behavior.

**Sample**

Sample source code [https://github.com/CrisLi/sts4-issues](https://github.com/CrisLi/sts4-issues)

**Comment by martinlippert** [comment] 2023-03-17 16:48
I can reproduce issue 1) with the latest STS 4.18.0 release, so we need to investigate why the format command is not working whereas it is working in a plain Eclipse Java 2023-03 package.

With regards to issue 2) and 3), it would be great if you could double check whether Lombok is working fine when having a plain Eclipse Java 2023-03 package with the Lombok extension installed? That would be great. We need to get an idea about whether this is an issue from the Lombok extension in general (maybe in combination with the latest m2e) or if this is specific to the Spring Tools distribution. Therefore it would be awesome if you could give a plain Eclipse 2023-03 + Lombok extension a try.

**Comment by thomseno** [comment] 2023-03-20 13:05
Having the same problem, looks like Lombok is already on it https://github.com/projectlombok/lombok/issues/3332

**Comment by martinlippert** [comment] 2023-03-20 13:12
Thanks for the link to the Lombok issue @thomseno , much appreciated.

Closing this one here as a duplicate of the newly created issue for the format issue (https://github.com/spring-projects/sts4/issues/1010) and the mentioned Lombok issue for the Lombok-related problems.

**Closed by martinlippert** 2023-03-20 13:12 UTC
Labels: status: waiting-for-feedback, type: bug, status: needs-investigation, for: eclipse

**Comment by aosavitski** [comment] 2025-02-18 21:37
I have issue 2 (spotless + lombok) in STS 4.28.1. Lombock is the latest (1.18.36)

**Comment by martinlippert** [comment] 2025-02-20 07:58
> I have issue 2 (spotless + lombok) in STS 4.28.1. Lombock is the latest (1.18.36)

Please report this to Lombok and/or the spotless maven plugin project.
