### ISSUE TITLE
'Scanning for Tasks' has encountered a problem

### ISSUE THREAD

**Issue by rwellman-ats** [spring-projects/sts4#677] opened 2021-08-25 16:31 UTC
**Describe the bug**
When starting STS, an error dialog sometimes appears. I will give the details below under -Sample-
Spring Tool Suite 4
Version: 4.11.0.RELEASE
Build Id: 202106180608

**To Reproduce**
This is intermittent on startup.  I am happy to provide whatever support is needed to gather more information.  I will just need someone knowledgeable about what to ask for to assist.

**Sample**

This appears to be a workspace startup issue not associated with a project, project configuration, or project code.

Here are the details as reported by the dialog followed by a screenshot:
Errors while detecting Tasks

assertion failed: Marker property value is too long: ",e.auth&&(t+=e.auth+"@"),e.host&&(t+=e.host),e.port&&(t+=":"+e.port),e.path&&(t+=e.path),t}function i(e){var r=e,n=s(e);if(n){if(!n.path)return e;r=n.path}for(var i,o=t.isAbsolute(r),u=r.split(/\/+/),l=0,c=u.length-1;c>=0;c--)"."===(i=u[c])?u.splice(c,1):".."===i?l++:l>0&&(""===i?(u.splice(c+1,l),l=0):(u.splice(c,2),l--));return""===(r=u.join("/"))&&(r=o?"/":"."),n?(n.path=r,a(n)):r}t.urlParse=s,t.urlGenerate=a,t.normalize=i,t.join=function(e,t){""===e&&(e="."),""===t&&(t=".");var r=s(t),o=s(e);if(o&&(e=o.path||"/"),r&&!r.scheme)return o&&(r.scheme=o.scheme),a(r);if(r||t.match(n))return t;if(o&&!o.host&&!o.path)return o.host=t,a(o);var u="/"===t.charAt(0)?t:i(e.replace(/\/+$/,"")+"/"+t);return o?(o.path=u,a(o)):u},t.isAbsolute=function(e){return"/"===e.charAt(0)||!!e.match(r)},t.relative=function(e,t){""===e&&(e="."),e=e.replace(/\/$/,"");for(var r=0;0!==t.indexOf(e+"/");){var n=e.lastIndexOf("/");if(n<0)return t;if((e=e.slice(0,n)).match(/^([^\/]+:\/)?\/*$/))return t;++r}return Array(r+1).join("../")+t.substr(e.length+1)};var o=!("__proto__"in Object.create(null));function u(e){return e}function l(e){if(!e)return!1;var t=e.length;if(t<9)return!1;if(95!==e.charCodeAt(t-1)||95!==e.charCodeAt(t-2)||111!==e.charCodeAt(t-3)||116!==e.charCodeAt(t-4)||111!==e.charCodeAt(t-5)||114!==e.charCodeAt(t-6)||112!==e.charCodeAt(t-7)||95!==e.charCodeAt(t-8)||95!==e.charCodeAt(t-9))return!1;for(var r=t-10;r>=0;r--)if(36!==e.charCodeAt(r))return!1;return!0}function c(e,t){return e===t?0:e>t?1:-1}t.toSetString=o?u:function(e){return l(e)?"$"+e:e},t.fromSetString=o?u:function(e){return l(e)?e.slice(1):e},t.compareByOriginalPositions=function(e,t,r){var n=e.source-t.source;return 0!==n||0!==(n=e.originalLine-t.originalLine)||0!==(n=e.originalColumn-t.originalColumn)||r||0!==(n=e.generatedColumn-t.generatedColumn)||0!==(n=e.generatedLine-t.generatedLine)?n:e.name-t.name},t.compareByGeneratedPositionsDeflated=function(e,t,r){var n=e.generatedLine-t.generatedLine;return 0!==n||0!==(n=e.generatedColumn-t.generatedColumn)||r||0!==(n=e.source-t.source)||0!==(n=e.originalLine-t.originalLine)||0!==(n=e.originalColumn-t.originalColumn)?n:e.name-t.name},t.compareByGeneratedPositionsInflated=function(e,t){var r=e.generatedLine-t.generatedLine;return 0!==r||0!==(r=e.generatedColumn-t.generatedColumn)||0!==(r=c(e.source,t.source))||0!==(r=e.originalLine-t.originalLine)||0!==(r=e.originalColumn-t.originalColumn)?r:c(e.name,t.name)}}),"/$$rollup_base$$/packages/babel-core/node_modules/source-map/lib"),AI=Object.prototype.hasOwnProperty,wI="undefined"!=typeof Map;function CI(){this._array=[],this._set=wI?new Map:Object.create(null)}CI.fromArray=function(e,t){for(var r=new CI,n=0,s=e.length;n<s;n++)r.add(e[n],t);return r},CI.prototype.size=function(){return wI?this._set.size:Object.getOwnPropertyNames(this._set).length},CI.prototype.add=function(e,t){var r=wI?e:DI.toSetString(e),n=wI?this.has(e):AI.call(this._set,r),s=this._array.length;n&&!t||this._array.push(e),n||(wI?this._set.set(e,s):this._set[r]=s)},CI.prototype.has=function(e){if(wI)return this._set.has(e);var t=DI.toSetString(e);return AI.call(this._set,t)},CI.prototype.indexOf=function(e){if(wI){var t=this._set.get(e);if(t>=0)return t}else{var r=DI.toSetString(e);if(AI.call(this._set,r))return this._set[r]}throw new Error('"'+e+'" is not in the set.')},CI.prototype.at=function(e){if(e>=0&&e<this._array.length)return this._array[e];throw new Error("No element indexed by "+e)},CI.prototype.toArray=function(){return this._array.slice()};var SI={ArraySet:CI};function TI(){this._array=[],this._sorted=!0,this._last={generatedLine:-1,generatedColumn:0}}TI.prototype.unsortedForEach=function(e,t){this._array.forEach(e,t)},TI.prototype.add=function(e){var t,r,n,s,a,i;t=this._last,r=e,n=t.generatedLine,s=r.generatedLine,a=t.generatedColumn,i=r.generatedColumn,s>n||s==n&&i>=a||DI.compareByGeneratedPositionsInflated(t,r)<=0?(this._last=e,this._array.push(e)):(this._sorted=!1,this._array.push(e))},TI.prototype.toArray=function(){return this._sorted||(this._array.sort(DI.compareByGeneratedPositionsInflated),this._sorted=!0),this._array};var jI=SI.ArraySet,PI={MappingList:TI}.MappingList;function II(e){e||(e={}),this._file=DI.getArg(e,"file",null),this._sourceRoot=DI.getArg(e,"sourceRoot",null),this._skipValidation=DI.getArg(e,"skipValidation",!1),this._sources=new jI,this._names=new jI,this._mappings=new PI,this._sourcesContents=null}II.prototype._version=3,II.fromSourceMap=function(e){var t=e.sourceRoot,r=new II({file:e.file,sourceRoot:t});return e.eachMapping((function(e){var n={generated:{line:e.generatedLine,column:e.generatedColumn}};null!=e.source&&(n.source=e.source,null!=t&&(n.source=DI.relative(t,n.source)),n.original={line:e.originalLine,column:e.originalColumn},null!=e.name&&(n.name=e.name)),r.addMapping(n)})),e.sources.forEach((function(t){var n=e.sourceContentFor(t);null!=n&&r.setSourceContent(t,n)})),r},II.prototype.addMapping=function(e){var t=DI.getArg(e,"generated"),r=DI.getArg(e,"original",null),n=DI.getArg(e,"source",null),s=DI.getArg(e,"name",null);this._skipValidation||this._validateMapping(t,r,n,s),null!=n&&(n=String(n),this._sources.has(n)||this._sources.add(n)),null!=s&&(s=String(s),this._names.has(s)||this._names.add(s)),this._mappings.add({generatedLine:t.line,generatedColumn:t.column,originalLine:null!=r&&r.line,originalColumn:null!=r&&r.column,source:n,name:s})},II.prototype.setSourceContent=function(e,t){var r=e;null!=this._sourceRoot&&(r=DI.relative(this._sourceRoot,r)),null!=t?(this._sourcesContents||(this._sourcesContents=Object.create(null)),this._sourcesContents[DI.toSetString(r)]=t):this._sourcesContents&&(delete this._sourcesContents[DI.toSetString(r)],0===Object.keys(this._sourcesContents).length&&(this._sourcesContents=null))},II.prototype.applySourceMap=function(e,t,r){var n=t;if(null==t){if(null==e.file)throw new Error('SourceMapGenerator.prototype.applySourceMap requires either an explicit source file, or the source map\'s "file" property. Both were omitted.');n=e.file}var s=this._sourceRoot;null!=s&&(n=DI.relative(s,n));var a=new jI,i=new jI;this._mappings.unsortedForEach((function(t){if(t.source===n&&null!=t.originalLine){var o=e.originalPositionFor({line:t.originalLine,column:t.originalColumn});null!=o.source&&(t.source=o.source,null!=r&&(t.source=DI.join(r,t.source)),null!=s&&(t.source=DI.relative(s,t.source)),t.originalLine=o.line,t.originalColumn=o.column,null!=o.name&&(t.name=o.name))}var u=t.source;null==u||a.has(u)||a.add(u);var l=t.name;null==l||i.has(l)||i.add(l)}),this),this._sources=a,this._names=i,e.sources.forEach((function(t){var n=e.sourceContentFor(t);null!=n&&(null!=r&&(t=DI.join(r,t)),null!=s&&(t=DI.relative(s,t)),this.setSourceContent(t,n))}),this)},II.prototype._validateMapping=function(e,t,r,n){if(t&&"number"!=typeof t.line&&"number"!=typeof t.column)throw new Error("original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values.");if((!(e&&"line"in e&&"column"in e&&e.line>0&&e.column>=0)||t||r||n)&&!(e&&"line"in e&&"column"in e&&t&&"line"in t&&"column"in t&&e.line>0&&e.column>=0&&t.line>0&&t.column>=0&&r))throw new Error("Invalid mapping: "+JSON.stringify({generated:e,source:r,original:t,name:n}))},II.prototype._serializeMappings=function(){for(var e,t,r,n,s=0,a=1,i=0,o=0,u=0,l=0,c="",p=this._mappings.toArray(),d=0,f=p.length;d<f;d++){if(e="",(t=p[d]).generatedLine!==a)for(s=0;t.generatedLine!==a;)e+=";",a++;else if(d>0){if(!DI.compareByGeneratedPositionsInflated(t,p[d-1]))continue;e+=","}e+=EI(t.generatedColumn-s),s=t.generatedColumn,null!=t.source&&(n=this._sources.indexOf(t.source),e+=EI(n-l),l=n,e+=EI(t.originalLine-1-o),o=t.originalLine-1,e+=EI(t.originalColumn-i),i=t.originalColumn,null!=t.name&&(r=this._names.indexOf(t.name),e+=EI(r-u),u=r)),c+=e}return c},II.prototype._generateSourcesContent=function(e,t){return e.map((function(e){if(!this._sourcesContents)return null;null!=t&&(e=DI.relative(t,e));var r=DI.toSetString(e);return Object.prototype.hasOwnProperty.call(this._sourcesContents,r)?this._sourcesContents[r]:null}),this)},II.prototype.toJSON=function(){var e={version:this._version,sources:this._sources.toArray(),names:this._names.toArray(),mappings:this._serializeMappings()};return null!=this._file&&(e.file=this._file),null!=this._sourceRoot&&(e.sourceRoot=this._sourceRoot),this._sourcesContents&&(e.sourcesContent=this._generateSourcesContent(e.sources,e.sourceRoot)),e},II.prototype.toString=function(){return JSON.stringify(this.toJSON())};var FI={SourceMapGenerator:II},kI=zt((function(e,t){function r(e,n,s,a,i,o){var u=Math.floor((n-e)/2)+e,l=i(s,a[u],!0);return 0===l?u:l>0?n-u>1?r(u,n,s,a,i,o):o==t.LEAST_UPPER_BOUND?n<a.length?n:-1:u:u-e>1?r(e,u,s,a,i,o):o==t.LEAST_UPPER_BOUND?u:e<0?-1:e}t.GREATEST_LOWER_BOUND=1,t.LEAST_UPPER_BOUND=2,t.search=function(e,n,s,a){if(0===n.length)return-1;var i=r(-1,n.length,e,n,s,a||t.GREATEST_LOWER_BOUND);if(i<0)return-1;for(;i-1>=0&&0===s(n[i],n[i-1],!0);)--i;return i}}),"/$$rollup_base$$/packages/babel-core/node_modules/source-map/lib");function OI(e,t,r){var n=e[t];e[t]=e[r],e[r]=n}function RI(e,t,r,n){if(r<n){var s=r-1;OI(e,(u=r,l=n,Math.round(u+Math.random()*(l-u))),n);for(var a=e[n],i=r;i<n;i++)t(e[i],a)<=0&&OI(e,s+=1,i);OI(e,s+1,i);var o=s+1;RI(e,t,r,o-1),RI(e,t,o+1,n)}var u,l}var NI=SI.ArraySet,BI=function(e,t){RI(e,t,0,e.length-1)};function _I(e){var t=e;return"string"==typeof e&&(t=JSON.parse(e.replace(/^\)\]\}'/,""))),null!=t.sections?new VI(t):new MI(t)}_I.fromSourceMap=function(e){return MI.fromSourceMap(e)},_I.prototype._version=3,_I.prototype.__generatedMappings=null,Object.defineProperty(_I.prototype,"_generatedMappings",{get:function(){return this.__generatedMappings||this._parseMappings(this._mappings,this.sourceRoot),this.__generatedMappings}}),_I.prototype.__originalMappings=null,Object.defineProperty(

assertion failed: Marker property value is too long: ",e.auth&&(t+=e.auth+"@"),e.host&&(t+=e.host),e.port&&(t+=":"+e.port),e.path&&(t+=e.path),t}function i(e){var r=e,n=s(e);if(n){if(!n.path)return e;r=n.path}for(var i,o=t.isAbsolute(r),u=r.split(/\/+/),l=0,c=u.length-1;c>=0;c--)"."===(i=u[c])?u.splice(c,1):".."===i?l++:l>0&&(""===i?(u.splice(c+1,l),l=0):(u.splice(c,2),l--));return""===(r=u.join("/"))&&(r=o?"/":"."),n?(n.path=r,a(n)):r}t.urlParse=s,t.urlGenerate=a,t.normalize=i,t.join=function(e,t){""===e&&(e="."),""===t&&(t=".");var r=s(t),o=s(e);if(o&&(e=o.path||"/"),r&&!r.scheme)return o&&(r.scheme=o.scheme),a(r);if(r||t.match(n))return t;if(o&&!o.host&&!o.path)return o.host=t,a(o);var u="/"===t.charAt(0)?t:i(e.replace(/\/+$/,"")+"/"+t);return o?(o.path=u,a(o)):u},t.isAbsolute=function(e){return"/"===e.charAt(0)||!!e.match(r)},t.relative=function(e,t){""===e&&(e="."),e=e.replace(/\/$/,"");for(var r=0;0!==t.indexOf(e+"/");){var n=e.lastIndexOf("/");if(n<0)return t;if((e=e.slice(0,n)).match(/^([^\/]+:\/)?\/*$/))return t;++r}return Array(r+1).join("../")+t.substr(e.length+1)};var o=!("__proto__"in Object.create(null));function u(e){return e}function l(e){if(!e)return!1;var t=e.length;if(t<9)return!1;if(95!==e.charCodeAt(t-1)||95!==e.charCodeAt(t-2)||111!==e.charCodeAt(t-3)||116!==e.charCodeAt(t-4)||111!==e.charCodeAt(t-5)||114!==e.charCodeAt(t-6)||112!==e.charCodeAt(t-7)||95!==e.charCodeAt(t-8)||95!==e.charCodeAt(t-9))return!1;for(var r=t-10;r>=0;r--)if(36!==e.charCodeAt(r))return!1;return!0}function c(e,t){return e===t?0:e>t?1:-1}t.toSetString=o?u:function(e){return l(e)?"$"+e:e},t.fromSetString=o?u:function(e){return l(e)?e.slice(1):e},t.compareByOriginalPositions=function(e,t,r){var n=e.source-t.source;return 0!==n||0!==(n=e.originalLine-t.originalLine)||0!==(n=e.originalColumn-t.originalColumn)||r||0!==(n=e.generatedColumn-t.generatedColumn)||0!==(n=e.generatedLine-t.generatedLine)?n:e.name-t.name},t.compareByGeneratedPositionsDeflated=function(e,t,r){var n=e.generatedLine-t.generatedLine;return 0!==n||0!==(n=e.generatedColumn-t.generatedColumn)||r||0!==(n=e.source-t.source)||0!==(n=e.originalLine-t.originalLine)||0!==(n=e.originalColumn-t.originalColumn)?n:e.name-t.name},t.compareByGeneratedPositionsInflated=function(e,t){var r=e.generatedLine-t.generatedLine;return 0!==r||0!==(r=e.generatedColumn-t.generatedColumn)||0!==(r=c(e.source,t.source))||0!==(r=e.originalLine-t.originalLine)||0!==(r=e.originalColumn-t.originalColumn)?r:c(e.name,t.name)}}),"/$$rollup_base$$/packages/babel-core/node_modules/source-map/lib"),AI=Object.prototype.hasOwnProperty,wI="undefined"!=typeof Map;function CI(){this._array=[],this._set=wI?new Map:Object.create(null)}CI.fromArray=function(e,t){for(var r=new CI,n=0,s=e.length;n<s;n++)r.add(e[n],t);return r},CI.prototype.size=function(){return wI?this._set.size:Object.getOwnPropertyNames(this._set).length},CI.prototype.add=function(e,t){var r=wI?e:DI.toSetString(e),n=wI?this.has(e):AI.call(this._set,r),s=this._array.length;n&&!t||this._array.push(e),n||(wI?this._set.set(e,s):this._set[r]=s)},CI.prototype.has=function(e){if(wI)return this._set.has(e);var t=DI.toSetString(e);return AI.call(this._set,t)},CI.prototype.indexOf=function(e){if(wI){var t=this._set.get(e);if(t>=0)return t}else{var r=DI.toSetString(e);if(AI.call(this._set,r))return this._set[r]}throw new Error('"'+e+'" is not in the set.')},CI.prototype.at=function(e){if(e>=0&&e<this._array.length)return this._array[e];throw new Error("No element indexed by "+e)},CI.prototype.toArray=function(){return this._array.slice()};var SI={ArraySet:CI};function TI(){this._array=[],this._sorted=!0,this._last={generatedLine:-1,generatedColumn:0}}TI.prototype.unsortedForEach=function(e,t){this._array.forEach(e,t)},TI.prototype.add=function(e){var t,r,n,s,a,i;t=this._last,r=e,n=t.generatedLine,s=r.generatedLine,a=t.generatedColumn,i=r.generatedColumn,s>n||s==n&&i>=a||DI.compareByGeneratedPositionsInflated(t,r)<=0?(this._last=e,this._array.push(e)):(this._sorted=!1,this._array.push(e))},TI.prototype.toArray=function(){return this._sorted||(this._array.sort(DI.compareByGeneratedPositionsInflated),this._sorted=!0),this._array};var jI=SI.ArraySet,PI={MappingList:TI}.MappingList;function II(e){e||(e={}),this._file=DI.getArg(e,"file",null),this._sourceRoot=DI.getArg(e,"sourceRoot",null),this._skipValidation=DI.getArg(e,"skipValidation",!1),this._sources=new jI,this._names=new jI,this._mappings=new PI,this._sourcesContents=null}II.prototype._version=3,II.fromSourceMap=function(e){var t=e.sourceRoot,r=new II({file:e.file,sourceRoot:t});return e.eachMapping((function(e){var n={generated:{line:e.generatedLine,column:e.generatedColumn}};null!=e.source&&(n.source=e.source,null!=t&&(n.source=DI.relative(t,n.source)),n.original={line:e.originalLine,column:e.originalColumn},null!=e.name&&(n.name=e.name)),r.addMapping(n)})),e.sources.forEach((function(t){var n=e.sourceContentFor(t);null!=n&&r.setSourceContent(t,n)})),r},II.prototype.addMapping=function(e){var t=DI.getArg(e,"generated"),r=DI.getArg(e,"original",null),n=DI.getArg(e,"source",null),s=DI.getArg(e,"name",null);this._skipValidation||this._validateMapping(t,r,n,s),null!=n&&(n=String(n),this._sources.has(n)||this._sources.add(n)),null!=s&&(s=String(s),this._names.has(s)||this._names.add(s)),this._mappings.add({generatedLine:t.line,generatedColumn:t.column,originalLine:null!=r&&r.line,originalColumn:null!=r&&r.column,source:n,name:s})},II.prototype.setSourceContent=function(e,t){var r=e;null!=this._sourceRoot&&(r=DI.relative(this._sourceRoot,r)),null!=t?(this._sourcesContents||(this._sourcesContents=Object.create(null)),this._sourcesContents[DI.toSetString(r)]=t):this._sourcesContents&&(delete this._sourcesContents[DI.toSetString(r)],0===Object.keys(this._sourcesContents).length&&(this._sourcesContents=null))},II.prototype.applySourceMap=function(e,t,r){var n=t;if(null==t){if(null==e.file)throw new Error('SourceMapGenerator.prototype.applySourceMap requires either an explicit source file, or the source map\'s "file" property. Both were omitted.');n=e.file}var s=this._sourceRoot;null!=s&&(n=DI.relative(s,n));var a=new jI,i=new jI;this._mappings.unsortedForEach((function(t){if(t.source===n&&null!=t.originalLine){var o=e.originalPositionFor({line:t.originalLine,column:t.originalColumn});null!=o.source&&(t.source=o.source,null!=r&&(t.source=DI.join(r,t.source)),null!=s&&(t.source=DI.relative(s,t.source)),t.originalLine=o.line,t.originalColumn=o.column,null!=o.name&&(t.name=o.name))}var u=t.source;null==u||a.has(u)||a.add(u);var l=t.name;null==l||i.has(l)||i.add(l)}),this),this._sources=a,this._names=i,e.sources.forEach((function(t){var n=e.sourceContentFor(t);null!=n&&(null!=r&&(t=DI.join(r,t)),null!=s&&(t=DI.relative(s,t)),this.setSourceContent(t,n))}),this)},II.prototype._validateMapping=function(e,t,r,n){if(t&&"number"!=typeof t.line&&"number"!=typeof t.column)throw new Error("original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values.");if((!(e&&"line"in e&&"column"in e&&e.line>0&&e.column>=0)||t||r||n)&&!(e&&"line"in e&&"column"in e&&t&&"line"in t&&"column"in t&&e.line>0&&e.column>=0&&t.line>0&&t.column>=0&&r))throw new Error("Invalid mapping: "+JSON.stringify({generated:e,source:r,original:t,name:n}))},II.prototype._serializeMappings=function(){for(var e,t,r,n,s=0,a=1,i=0,o=0,u=0,l=0,c="",p=this._mappings.toArray(),d=0,f=p.length;d<f;d++){if(e="",(t=p[d]).generatedLine!==a)for(s=0;t.generatedLine!==a;)e+=";",a++;else if(d>0){if(!DI.compareByGeneratedPositionsInflated(t,p[d-1]))continue;e+=","}e+=EI(t.generatedColumn-s),s=t.generatedColumn,null!=t.source&&(n=this._sources.indexOf(t.source),e+=EI(n-l),l=n,e+=EI(t.originalLine-1-o),o=t.originalLine-1,e+=EI(t.originalColumn-i),i=t.originalColumn,null!=t.name&&(r=this._names.indexOf(t.name),e+=EI(r-u),u=r)),c+=e}return c},II.prototype._generateSourcesContent=function(e,t){return e.map((function(e){if(!this._sourcesContents)return null;null!=t&&(e=DI.relative(t,e));var r=DI.toSetString(e);return Object.prototype.hasOwnProperty.call(this._sourcesContents,r)?this._sourcesContents[r]:null}),this)},II.prototype.toJSON=function(){var e={version:this._version,sources:this._sources.toArray(),names:this._names.toArray(),mappings:this._serializeMappings()};return null!=this._file&&(e.file=this._file),null!=this._sourceRoot&&(e.sourceRoot=this._sourceRoot),this._sourcesContents&&(e.sourcesContent=this._generateSourcesContent(e.sources,e.sourceRoot)),e},II.prototype.toString=function(){return JSON.stringify(this.toJSON())};var FI={SourceMapGenerator:II},kI=zt((function(e,t){function r(e,n,s,a,i,o){var u=Math.floor((n-e)/2)+e,l=i(s,a[u],!0);return 0===l?u:l>0?n-u>1?r(u,n,s,a,i,o):o==t.LEAST_UPPER_BOUND?n<a.length?n:-1:u:u-e>1?r(e,u,s,a,i,o):o==t.LEAST_UPPER_BOUND?u:e<0?-1:e}t.GREATEST_LOWER_BOUND=1,t.LEAST_UPPER_BOUND=2,t.search=function(e,n,s,a){if(0===n.length)return-1;var i=r(-1,n.length,e,n,s,a||t.GREATEST_LOWER_BOUND);if(i<0)return-1;for(;i-1>=0&&0===s(n[i],n[i-1],!0);)--i;return i}}),"/$$rollup_base$$/packages/babel-core/node_modules/source-map/lib");function OI(e,t,r){var n=e[t];e[t]=e[r],e[r]=n}function RI(e,t,r,n){if(r<n){var s=r-1;OI(e,(u=r,l=n,Math.round(u+Math.random()*(l-u))),n);for(var a=e[n],i=r;i<n;i++)t(e[i],a)<=0&&OI(e,s+=1,i);OI(e,s+1,i);var o=s+1;RI(e,t,r,o-1),RI(e,t,o+1,n)}var u,l}var NI=SI.ArraySet,BI=function(e,t){RI(e,t,0,e.length-1)};function _I(e){var t=e;return"string"==typeof e&&(t=JSON.parse(e.replace(/^\)\]\}'/,""))),null!=t.sections?new VI(t):new MI(t)}_I.fromSourceMap=function(e){return MI.fromSourceMap(e)},_I.prototype._version=3,_I.prototype.__generatedMappings=null,Object.defineProperty(_I.prototype,"_generatedMappings",{get:function(){return this.__generatedMappings||this._parseMappings(this._mappings,this.sourceRoot),this.__generatedMappings}}),_I.prototype.__originalMappings=null,Object.defineProperty(

![image](https://user-images.githubusercontent.com/85251807/130829145-f8cbce1e-58d0-415e-95ff-0aa9c291aa04.png)

**Comment by rwellman-ats** [comment] 2021-09-13 15:26
Sorry for the delayed response.  We do use a maven build plugin called 'babel-maven-plugin' in a project but I wouldn't see why that would affect the startup of the 'Tasks' feature.  Nor is there any sort of Eclipse plugin associated with that module.  I've been doing a little digging into that maven plugin (and will continue to do so) but there's not a lot of documentation and I'm a bit perplexed why it would affect the Tasks startup.  Any ideas would be appreciated.

**Comment by martinlippert** [comment] 2021-09-15 09:43
Yeah, I am puzzled by that as well. Can you take a look at the Error Log View to see if there are more details about the problem what shows up in the dialog? Maybe you can find a stack trace in there that could reveal a few more details where exactly the problem is coming from.

**Comment by rwellman-ats** [comment] 2021-09-27 19:02
I had a little time to spend on this today.  Though the error log wasn't extremely informative, it did send me down a train of thought that I hadn't boarded before :)  Silly me... up until now I have been assuming "Tasks" were "Task List" (i.e. Mylyn).  But the stack trace finally made me realize it was from the "Tasks" view (TODOs, etc.).  After adjusting my task filter, I narrowed it down to the item shown in the second screenshot.  Therefore, it apparently has something to do with scanning the babel.min.js file.  I wouldn't know if the minified file is simply too big (which the error seems to indicate) or what.  
Thoughts?

stack trace as text: 
```
at org.eclipse.core.runtime.Assert.isTrue(Assert.java:113)
	at org.eclipse.core.internal.resources.MarkerInfo.checkValidAttribute(MarkerInfo.java:63)
	at org.eclipse.core.internal.resources.MarkerInfo.setAttribute(MarkerInfo.java:149)
	at org.eclipse.core.internal.resources.MarkerInfo.setAttributes(MarkerInfo.java:175)
	at org.eclipse.core.internal.resources.Marker.setAttributes(Marker.java:354)
	at org.eclipse.wst.sse.core.internal.tasks.WorkspaceTaskScanner$1.run(WorkspaceTaskScanner.java:311)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2313)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2338)
	at org.eclipse.wst.sse.core.internal.tasks.WorkspaceTaskScanner.replaceTaskMarkers(WorkspaceTaskScanner.java:319)
	at org.eclipse.wst.sse.core.internal.tasks.WorkspaceTaskScanner.scanFile(WorkspaceTaskScanner.java:467)
	at org.eclipse.wst.sse.core.internal.tasks.WorkspaceTaskScanner.internalScan(WorkspaceTaskScanner.java:226)
	at org.eclipse.wst.sse.core.internal.tasks.WorkspaceTaskScanner.internalScan(WorkspaceTaskScanner.java:221)
	at org.eclipse.wst.sse.core.internal.tasks.WorkspaceTaskScanner.internalScan(WorkspaceTaskScanner.java:221)
	at org.eclipse.wst.sse.core.internal.tasks.WorkspaceTaskScanner.internalScan(WorkspaceTaskScanner.java:221)
	at org.eclipse.wst.sse.core.internal.tasks.WorkspaceTaskScanner.internalScan(WorkspaceTaskScanner.java:221)
	at org.eclipse.wst.sse.core.internal.tasks.WorkspaceTaskScanner.internalScan(WorkspaceTaskScanner.java:221)
	at org.eclipse.wst.sse.core.internal.tasks.WorkspaceTaskScanner.scan(WorkspaceTaskScanner.java:348)
	at org.eclipse.wst.sse.core.internal.tasks.TaskScanningJob.run(TaskScanningJob.java:210)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
![babel_task_error](https://user-images.githubusercontent.com/85251807/134968942-384421a9-6b76-4316-a3e8-f31c2fc1b114.png)

![babel_task](https://user-images.githubusercontent.com/85251807/134968955-97054749-d593-4e6f-9cb9-3d3c3926000f.png)

**Comment by martinlippert** [comment] 2021-09-28 08:43
Hey @rwellman-ats, this is great and points us towards the source of the problem. It clearly seems to be related to some Webtools components, so I would recommend to report this to the Webtools team for further investigation. Do you have a small sample project that could be used to reproduce this problem? I think it would speed up the investigation work on their side quite a bit if you could create this small sample project and attach that to the bug report.

I added a bug report here:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=576303

Would be great if you could jump on that bug report as well and provide some details over there as well, especially the sample project that could be used to reproduce this would be extremely helpful.

I am closing this one here as a duplicate of the bug at Eclipse mentioned here.

**Closed by martinlippert** 2021-09-28 08:43 UTC
Labels: status: waiting-for-feedback, type: bug, for: eclipse
