### ISSUE TITLE
STS4 automatically closes [crashes] on certain key press in xml files on MacOS Ventura

### ISSUE THREAD

**Issue by Abhi-Codes** [spring-projects/sts4#888] opened 2022-11-10 17:28 UTC
**Describe the bug**
I am on Mac OS Ventura and using STS installed from binary spring-tool-suite-4-4.16.1.RELEASE-e4.25.0-macosx.cocoa.x86_64.dmg. I see an issue when editing the pom.xml file. Whenever I try to comment out a dependency by typing in <!, STS abruptly closes. Also typing <! in any other file doesn't close the application, it happens only on XML files.

I didn't notice this behavior when using the same binary on Mac OS BigSur.

**To Reproduce**
1. Open STS4 on MacOS Ventura Intel Macbook. 
2. Start editing the pom.xml file and try to comment out a dependency. As you type in **<**, STS4 automatically closes. 

**Logs**
!SESSION 2022-11-10 22:51:18.936 -----------------------------------------------
eclipse.buildId=4.16.1.202210240748
java.version=17.0.4.1
java.vendor=Eclipse Adoptium
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_IN
Framework arguments:  -product org.springframework.boot.ide.branding.sts4 -keyring /Users/abcdef/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.springframework.boot.ide.branding.sts4 -keyring /Users/abcdef/.eclipse_keyring

!ENTRY org.eclipse.core.resources 2 10035 2022-11-10 22:51:20.327
!MESSAGE The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.

!ENTRY org.eclipse.jface 2 0 2022-11-10 22:51:22.392
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2022-11-10 22:51:22.392
!MESSAGE A conflict occurred for COMMAND+SHIFT+T:
Binding(COMMAND+SHIFT+T,
    ParameterizedCommand(Command(org.eclipse.jdt.ui.navigate.open.type,Open Type,
        Open a type in a Java editor,
        Category(org.eclipse.ui.category.navigate,Navigate,null,true),
        WorkbenchHandlerServiceHandler("org.eclipse.jdt.ui.navigate.open.type"),
        ,,true),null),
    org.eclipse.ui.defaultAcceleratorConfiguration,
    org.eclipse.ui.contexts.window,,,system)
Binding(COMMAND+SHIFT+T,
    ParameterizedCommand(Command(org.eclipse.lsp4e.symbolinworkspace,Go to Symbol in Workspace,
        ,
        Category(org.eclipse.lsp4e.category,Language Servers,null,true),
        WorkbenchHandlerServiceHandler("org.eclipse.lsp4e.symbolinworkspace"),
        ,,true),null),
    org.eclipse.ui.defaultAcceleratorConfiguration,
    org.eclipse.ui.contexts.window,,,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2022-11-10 22:51:22.392
!MESSAGE A conflict occurred for ALT+COMMAND+R:
Binding(ALT+COMMAND+R,
    ParameterizedCommand(Command(org.eclipse.ui.edit.rename,Rename,
        Rename the selected item,
        Category(org.eclipse.ui.category.file,File,null,true),
        WorkbenchHandlerServiceHandler("org.eclipse.ui.edit.rename"),
        ,,true),null),
    org.eclipse.ui.defaultAcceleratorConfiguration,
    org.eclipse.ui.contexts.window,,cocoa,system)
Binding(ALT+COMMAND+R,
    ParameterizedCommand(Command(org.eclipse.jdt.ui.edit.text.java.rename.element,Rename - Refactoring ,
        Rename the selected element,
        Category(org.eclipse.jdt.ui.category.refactoring,Refactor - Java,Java Refactoring Actions,true),
        WorkbenchHandlerServiceHandler("org.eclipse.jdt.ui.edit.text.java.rename.element"),
        ,,true),null),
    org.eclipse.ui.defaultAcceleratorConfiguration,
    org.eclipse.ui.contexts.window,,cocoa,system)

!ENTRY org.eclipse.m2e.logback.appender 2 0 2022-11-10 22:51:30.049
!MESSAGE The POM for com.google.code.gson:gson:jar:2.8.6 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details

!ENTRY org.eclipse.ui 4 0 2022-11-10 22:51:31.994
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "links" is null
    at org.eclipse.lsp4e.operations.documentLink.LSPDocumentLinkPresentationReconcilingStrategy.underline(LSPDocumentLinkPresentationReconcilingStrategy.java:92)
    at org.eclipse.lsp4e.operations.documentLink.LSPDocumentLinkPresentationReconcilingStrategy.lambda$5(LSPDocumentLinkPresentationReconcilingStrategy.java:83)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4318)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3941)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
    at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1467)

**Comment by martinlippert** [comment] 2022-11-11 07:34
I tried this on an M1 machine, but that doesn't reproduce the crash. Do you see a crash log file (`hs_err_pid....log`) being created when this happens? If so, it would be great to take a look at it.

**Comment by Abhi-Codes** [comment] 2022-11-11 08:41
Hi Martin, 

I see a crash report popup open. I have copied the contents into the below gist. 
https://gist.github.com/Abhi-Codes/6d01995aeba4a52836d0e06b33ad4769

**Comment by martinlippert** [comment] 2022-11-11 09:08
Can you double check this running a plain Eclipse 2022-09 installation? I don't have a Ventura machine on x86_64 around for testing at the moment and double checking this would be great.

**Comment by Abhi-Codes** [comment] 2022-11-11 09:28
I do see the same issue with the plain Eclipse 2022-09 installation .

**Comment by martinlippert** [comment] 2022-11-11 09:36
As you mentioned on some internal communication channel, this happens in standard Eclipse 2022-09 as well. It is probably a duplicate of https://github.com/eclipse-platform/eclipse.platform.swt/issues/452. There are many ways to reproduce this from what it looks like. Closing this one here as a duplicate of the mentioned issue.

**Closed by martinlippert** 2022-11-11 09:36 UTC
Labels: status: waiting-for-feedback, type: bug, for: eclipse

**Comment by martinlippert** [comment] 2022-11-14 07:07
Looks like a difficult issue. Maybe someone can try this workaround? https://github.com/eclipse-platform/eclipse.platform.swt/issues/452#issuecomment-1295806955 - doesn't seem to be clear whether it works around the problem or not, so giving this a try would be awesome. I don't have a Ventura Intel Mac machine around, so unfortunately can't test this myself at the moment.

**Comment by martinlippert** [comment] 2022-12-15 11:35
For your reference... Here is the workaround from ... to launch Spring Tool Suite 4 from the command line:

```
java
-XstartOnFirstThread
-Xdock:icon=/path_to/SpringToolSuite4.app/Contents/Resources/sts4.icns
-Dorg.eclipse.swt.internal.carbon.smallFonts
-Dosgi.requiredJavaVersion=17
-classpath /path_to/SpringToolSuite4.app/Contents/Eclipse/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar org.eclipse.equinox.launcher.Main
-launcher /path_to/SpringToolSuite4.app/Contents/MacOS/SpringToolSuite4
-name SpringToolSuite4
-showsplash 600
-product org.springframework.boot.ide.branding.sts4
-configuration file:/path_to/SpringToolSuite4.app/Contents/Eclipse/configuration
-os macosx
-ws cocoa
-arch x86_64
-nl en_GB
-consoleLog
```

Replace the `/path_to/` with the path to your local STS installation and turn this into one line - I put this into separate lines for better readability only. Also make sure your `java` command points to a JDK17 installation when running this.

You can add additional JVM args to this, like `-Xmx2048m` for example to limit the max heap size to 2GB - which is the default setting that we ship.
