### ISSUE TITLE
Queries that are divided into multiple String concatenations, are not syntax highlighted.

### ISSUE THREAD

**Issue by ahbali** [spring-projects/sts4#1391] opened 2024-10-19 17:50 UTC
I don't know if this is a Bug or a feature request.

**Describe the bug**
sometimes i divide Queries into multiple lines to be more readable.
The queries that are in a single string literal are syntax highlighted but when divided into multiple string literals concatenations, then there they stop being colorized.
PS: i know that i can use text blocks, but unfortunately the project is using java 11.

**To Reproduce**
change something like this:
```java
@Query("SELECT c FROM Client c JOIN c.chambres chambre WHERE chambre.id = :chambreId")
Set<Client> findByChambreId(@Param("chambreId") Long chambreId);
```
to this: 
```java
@Query("SELECT c \n" +
       "FROM Client c \n" +
       "   JOIN c.chambres chambre \n" +
       "WHERE chambre.id = :chambreId")
Set<Client> findByChambreId(@Param("chambreId") Long chambreId);
```
or this:
```java
@Query("SELECT c " +
       "FROM Client c " +
       "   JOIN c.chambres chambre " +
       "WHERE chambre.id = :chambreId")
Set<Client> findByChambreId(@Param("chambreId") Long chambreId);
```

**Sample**

[check the file `ClientRepository.java` in this repo](https://github.com/ahbali/spring-tools-bug)

**Comment by BoykoAlex** [comment] 2024-10-19 18:07
Duplicate of #1262 - there are at least 3 requests to support concatenated strings... Perhaps it's time to implement this support

**Closed by BoykoAlex** 2024-10-19 18:07 UTC
Labels: status: waiting-for-triage, type: bug
