### ISSUE TITLE
app randomly disappears from the screen

### ISSUE THREAD

**Issue by yrostov** [spring-projects/sts4#578] opened 2020-12-29 19:57 UTC
Hi,
    
Last week updated to Spring Tool Suite 4 4.9.0.202012132054 on Windows 10 and started to face two issues.  First, template proposal (Ctrl+Space) pop-up starts hanging on with message "Computing proposals (0%)...".

Second issue has to do with STS window briefly appearing, then completely disappearing from screen when app hits a brake point. I can still see process in Task Manager but there is no way to get to app's window except by killing as starting another instance.

Regards,
Yury

**Comment by martinlippert** [comment] 2020-12-30 09:16
Hey @yrostov, the first issue looks like a duplicate of https://github.com/spring-projects/sts4/issues/579. In case you can reproduce this, it would be awesome if you could capture a thread dump of the IDE process while the content-assist proposal popup hangs with that message and a thread dump from the spring-boot-language-server process that should also running on your machine while this happens. Also, if you have a sample project that could help to reproduce the issue, that would be awesome.

The second issue that you describe seems to be unrelated to the first one and it would be good to keep those different issues in different GitHub issue items. Therefore I will keep this one as the one for the app disappearing and we can move along with the first mentioned issue in https://github.com/spring-projects/sts4/issues/579.

**Comment by martinlippert** [comment] 2020-12-30 09:18
For the issue of the app disappearing randomly: Does this happen every time the app hits a breakpoint? And if so, can you try to reproduce that with a plain Eclipse SDK installation and a small sample project? If you can reproduce it that way, we should submit it as an issue to the Eclipse SDK project to see what a possible solution could be here.

**Comment by yrostov** [comment] 2020-12-30 21:20
Hey @martinlippert, unfortunately this only happened twice couple of days ago and hasn't happened since. I will update this issue if I encounter this problem again. 

As for issue 579, I will post IDE thread dump as soon as I reproduce the issue. Are you looking for Eclipse IDE, Boot Language Server or both thread dumps?

**Comment by martinlippert** [comment] 2020-12-31 11:45
> As for issue 579, I will post IDE thread dump as soon as I reproduce the issue. Are you looking for Eclipse IDE, Boot Language Server or both thread dumps?

Both would be good.

> Also, in my case I noticed there is no issue when IDE started, then after restarting debugged Boot app number of times, this starts to happen and this also effects other context - related operations, like highlighting reference or class under cursor. These actions become sluggish, taking effect for up to 10, 20 seconds.

I assume this is the same underlying issue, so taking thread dumps from both processes (as discussed above) when this happens would be interesting as well to verify the assumption.

**Comment by martinlippert** [comment] 2021-02-10 11:14
Closing this due to no additional details or feedback. The work on #579 is under way and continues, so that part is in progress and should be part of the 4.9.1 or 4.10.0 release. If you have any further details about that one, please comment on #579.

If you come across any additional details regarding the disappearing application, please comment and we can re-open this one.

**Closed by martinlippert** 2021-02-10 11:14 UTC
