### ISSUE TITLE
Kotlin Redeclaration Error with Maven Project

### ISSUE THREAD

**Issue by troyhart** [spring-projects/sts4#168] opened 2018-12-23 01:18 UTC
https://github.com/troyhart/kotlin-sts4-bug-demo

Above is a link to a very simple spring boot application that demonstrates an issue with kotlin in STS4. Specifically, the IDE report a "Redeclaration" error on a simple kotlin data class. When you import the project into an STS 3.9.6 IDE the project doesn't have any errors. However, when you import it into an STS 4.0.0 IDE you will see the errors.

**Comment by BoykoAlex** [comment] 2018-12-24 15:05
This is not STS specific... This is a bug in the Kotlin plugin for Eclipse. It needs to be reported here: https://github.com/JetBrains/kotlin-eclipse
Pretty sure you can get the same issue with STS 3.9.6 or plain eclipse 4.10

**Comment by troyhart** [comment] 2018-12-26 23:20
I don't think so. Did you look at the sample project I provided? It is stupid simple and if you import it into your IDEs it will demonstrates the issue. First, import it into an STS 4 workspace and then into an STS 3.9.6 workspace. You will see that STS 4 has errors and STS 3.9.6 doesn't. In my case, I have the same kotlin plugin in both STS 4 and 3.9.6 (Kotlin Plugin: 0.8.11.v20181207-0928).

**Comment by BoykoAlex** [comment] 2018-12-27 01:44
I did. Imported as Maven project and didn't see any errors. 
Now I figured i don't see the errors because there is no Kotlin nature on the project. Added it and still no errors.. Then I cleaned the project and saw the error.

**Comment by troyhart** [comment] 2019-01-11 16:20
FYI. I've seen reports of similar kotlin issues where it was recommended to remove the kotlin nature and then reinstate it. I have done this and it has seemed to resolve the issue.

**Comment by troyhart** [comment] 2019-01-11 18:12
Well, it worked for a little while. Now it's broken again and I can't seem to fix it by removing the nature and reinstating it. I've also tried to uninstall and then reinstall the kotlin plugin, but that doesn't help.

**Comment by BoykoAlex** [comment] 2019-03-12 22:19
@troyhart @1067511899 Please try the following workaround:

1. Go to STS4 Preferences
2. Open Maven -> Annotation Processing preference page
3. The radio button group at the top should currently have `Automatically configure JDT APT...` set (the top radio button)
4. Set it to the 3rd (lowest) setting `Do not automatically configure/execute...`
5. Then Apply, Save, close preferences
6. Now remove the Kotlin nature project and then add it back
Now you should have no "redeclaration" errors on your project... At least to same extent...
The problem is that the sts4 branding plugin sets the preference  setting above to true by default when STS4 first started and therefore the problem is visible right away.

**Comment by spring-issuemaster** [comment] 2019-03-12 22:48
(comment in Pivotal Tracker added by Alex Boyko:) 

If you disable JDT Annotation processing in the preferences these errors will go away
1. Go to STS4 Preferences
2. Open Maven -> Annotation Processing preference page
3. The radio button group at the top should currently have Automatically configure JDT APT... set (the top radio button)
4. Set it to the 3rd (lowest) setting Do not automatically configure/execute...
5. Then Apply, Save, close preferences
6. Now remove the Kotlin nature project and then add it back
Now the errors are gone.

https://youtrack.jetbrains.com/issue/KE-320

**Comment by Kordyjan** [comment] 2019-03-14 13:55
Issue should be fixed on current nightly build. You can grab it via update site: https://teamcity.jetbrains.com/guestAuth/repository/download/Kotlin_EclipsePlugin/.lastSuccessful/
Let me know if it works for you.

**Comment by spring-issuemaster** [comment] 2019-03-20 18:15
(comment in Pivotal Tracker added by Alex Boyko:) 

Confirmed the fix in Kotlin Eclipse plugin by installing Kotlin plugin from the nightly builds: https://teamcity.jetbrains.com/guestAuth/repository/download/Kotlin_EclipsePlugin/.lastSuccessful/

**Closed** 2019-03-20 18:15 UTC
Labels: delivered
