### ISSUE TITLE
Git status out of sync

### ISSUE THREAD

**Issue by hcic-rich** [spring-projects/sts4#369] opened 2019-09-20 19:30 UTC
STS 4.4.0 for Windows with Git 2.23.0.windows.1

In the Project Explorer window, all files in the project are showing as having been updated when none of them have been. See attached images.

![Capture2](https://user-images.githubusercontent.com/52932632/65353261-b1820900-dbba-11e9-92b7-6a2c3dd4ce19.PNG)
![Capture](https://user-images.githubusercontent.com/52932632/65353263-b1820900-dbba-11e9-8ae5-c67897429fec.PNG)

**Comment by BoykoAlex** [comment] 2019-09-20 19:58
That seems more like an eGit issue rather than STS4... Any chance you can try this workspace with plain Eclipse 4.13?

**Comment by hcic-rich** [comment] 2019-12-09 20:58
Sorry for the delayed response.

Yes, it is doing the same thing in plain Eclipse 2019-09. This happened after I switched laptops and did a fresh, complete install of STS4 and pulled from bitbucket. Any thoughts on how to resolve this?

Warm regards,

Rich Schramm

**Comment by martinlippert** [comment] 2019-12-10 09:08
This sounds indeed like an issue with the Git integration in Eclipse, so I would recommend to file a bug with the EGit project here: https://bugs.eclipse.org/bugs/enter_bug.cgi?product=EGit

I think your locally installed Git command line version doesn't really have an influence on this, since the Eclipse integration uses its own implementation of Git (via JGit). But it would be good to describe a few steps how to reproduce this.

**Comment by tomaswolf** [comment] 2020-03-01 17:24
I think that can be closed. This was an issue in EGit 5.4.2 and 5.5.0; it was fixed in [EGit 5.5.1](https://projects.eclipse.org/projects/technology.jgit/releases/5.5.1).

**Comment by hcic-rich** [comment] 2020-03-01 17:31
Yes recent update fixed it

Thanks,

Rich Schramm
CTO, HealthCare Information, LLC.
513.400.7390 (m)

Sent from my iPhone
________________________________

**Comment by martinlippert** [comment] 2020-03-02 08:10
Thanks for the update and glad to hear that is works again with the latest update.

**Closed by martinlippert** 2020-03-02 08:10 UTC
