### ISSUE TITLE
Advance Threat Pravention PoP in eclipse

### ISSUE THREAD

**Issue by VenkatRedddy** [spring-projects/sts4#398] opened 2019-12-19 20:35 UTC
<img width="443" alt="STS" src="https://user-images.githubusercontent.com/24688952/71207566-2970d580-2275-11ea-846a-3c9c37f608b2.png">

**Comment by VenkatRedddy** [comment] 2019-12-20 13:35
This is happening with STS3 and STS4 plugin in eclipse

**Comment by kdvolder** [comment] 2019-12-20 22:50
Does it also happen with plain Eclipse? 

I am guessing that the error means there was some sort of address error. Typically this kind of error would be caused by some bug in native libraries. As STS does not really have any of its own, the only ones are from Eclipse itself (mostly to support Eclipse SWT).

Another possibiity is that this is a JVM crash because of a JVM bug. Neither of these kind of things would be something STS itself is likely able to fix. 

One thing you could try is to make sure to run with recent JDK, if it is a JVM bug this might help. 

Also, I am not familiar with the `Advance Threat Prevention` tool that you are using. But is it possible to actually get a real error message from this. Segmentation fault would typically result in the JVM producing a error dump into a text file (unless the 'prevention tool' actually prevented the error destroyed the process before it could dump an error message).

If you can produce a more detailed error message we can try to analyze this but as it is:

- there is not enough information here to do anything
- the bug is most likely not actually in STS itself (but if we could see the message we may be able to determine where to raise a bug instead).

Anyway since there isn't much we can do right now, I will close this ticket.

Of course it can allways be re-opened later if more information is attached.

**Closed by kdvolder** 2019-12-20 22:50 UTC

**Comment by martinlippert** [comment] 2020-01-10 09:41
Quick update: there is a great analysis of this issue in https://github.com/spring-projects/sts4/issues/340#issuecomment-572558018. Please take a look, it includes a way to work around this.
