### ISSUE TITLE
Opening Preferences > Maven > Installations freezes STS 4.16.0 on Windows 10 20H2

### ISSUE THREAD

**Issue by PratimGhosh86** [spring-projects/sts4#850] opened 2022-09-19 17:17 UTC
**Describe the bug**
Opening `Preferences > Maven > Installations` freezes STS `4.16.0` on Windows 10 20H2 `19042.2006`

**To Reproduce**

- Download https://download.springsource.com/release/STS4/4.16.0.RELEASE/dist/e4.25/spring-tool-suite-4-4.16.0.RELEASE-e4.25.0-win32.win32.x86_64.self-extracting.jar
- Extract and run, create a new workspace
- Navigate to `Preferences > Maven > Installations`

**Sample**

None, no need to open/import any project. This issue exists with a fresh installation

**Comment by martinlippert** [comment] 2022-09-22 11:31
Thanks for reporting this @PratimGhosh86 , much appreciated. I can reproduce this, however the freeze doesn't seem to freeze the IDE forever, but for a certain (annoying) period of time (several seconds on my machine).

This this is something that seems to be related to the m2e project, I will close this one here as a duplicate and open another issue with the m2e project itself.

**Closed by martinlippert** 2022-09-22 11:31 UTC
Labels: type: bug, for: eclipse
