### ISSUE TITLE
eclipse 4.10 install sts4 4.1.2,all source java class Ctrl+left mouse button will fail

### ISSUE THREAD

**Issue by MayBing** [spring-projects/sts4#205] opened 2019-02-25 11:55 UTC

**Comment by martinlippert** [comment] 2019-02-25 13:14
Can you elaborate in more detail what happens and how to reproduce this issue? Would also be good to know whether this problems happens only if you install the STS4 pieces into Eclipse or even without that (using a plain Eclipse install).

**Comment by BoykoAlex** [comment] 2019-02-25 15:13
I reproduced... yes, STS4 to blame it seems :-(
```

**Comment by BoykoAlex** [comment] 2019-02-26 01:50
Should be fixed when this is resolved: https://bugs.eclipse.org/bugs/show_bug.cgi?id=544794

**Comment by MayBing** [comment] 2019-02-26 02:16
![2019-02-26_9-30-56](https://user-images.githubusercontent.com/11535042/53382206-6d28e480-39ae-11e9-87f1-65b8fc9fe980.gif)

The ctrl+left can be entered before the source code is installed. After installation, ctrl+left does not display open impelementation.

**Comment by spring-issuemaster** [comment] 2019-02-27 21:47
(comment in Pivotal Tracker added by Alex Boyko:) 

I think it's fixed with https://bugs.eclipse.org/bugs/show_bug.cgi?id=544794 Mikael merged the quick fix for it rather quickly without requiring a test... Think the next STS4 eclipse nightly build would have the fix since we are targeting smapshot builds of lsp4e

**Comment by spring-issuemaster** [comment] 2019-03-04 18:39
(comment in Pivotal Tracker added by Alex Boyko:) 

Should be in the nightly builds already...

**Closed** 2019-03-05 12:28 UTC
Labels: delivered

**Comment by user20161119** [comment] 2019-03-21 09:49
Waiting for 4.2.0

**Comment by BoykoAlex** [comment] 2019-03-21 14:43
Another option is try LSP4E project nightly build as the fix went in that project. Here is the nighly build update site: http://download.eclipse.org/lsp4e/snapshots/
