### ISSUE TITLE
Ctrl+Shift+C does not work for properties file

### ISSUE THREAD

**Issue by ksanjeev9211** [spring-projects/sts4#160] opened 2018-12-06 17:41 UTC

**Comment by ksanjeev9211** [comment] 2018-12-06 17:43
In any properties file I can't comment any entry or set of entries using the above command.

**Comment by kdvolder** [comment] 2018-12-06 19:01
This should have been fixed in the latest release of STS (version is 4.0.2). Is that the version you are using?

**Comment by ksanjeev9211** [comment] 2018-12-06 20:31
Ok.
I am using 4.0.1.

**Comment by martinlippert** [comment] 2018-12-07 08:52
Closing this as a duplicate of https://github.com/spring-projects/sts4/issues/100

**Closed by martinlippert** 2018-12-07 08:52 UTC
