### ISSUE TITLE
JPQL syntax - Support Concatenated Strings

### ISSUE THREAD

**Issue by raulvaldoleiros** [spring-projects/sts4#1262] opened 2024-06-05 13:19 UTC
## Suggestion

JPQL syntax is a great feature, it would be great if it supports:

- Text blocks
- String concatenation

In the following image you can see that right now isn't supported
![image](https://github.com/spring-projects/sts4/assets/10415832/e554eebf-3d97-4c75-96ca-9f9b50475abe)

Created from [issue](https://github.com/microsoft/vscode-java-pack/issues/1353)

**Comment by zarembo** [comment] 2024-10-10 17:31
This may be more important than it looks like. The problem is there is no syntax check at all. It just shows nothing. There is not even a warning that no check has been performed.

**Comment by BoykoAlex** [comment] 2024-11-06 01:24
Fixed with ea033714b47e3d8088a5f6135343743df0369d61

**Closed by BoykoAlex** 2024-11-06 01:24 UTC
Labels: type: enhancement, theme: spring-data-support, for: vscode
