### ISSUE TITLE
Problems with lombok annotations

### ISSUE THREAD

**Issue by explorer566** [spring-projects/sts4#1208] opened 2024-03-16 16:04 UTC
**Problem**
Lombok annotations with values don't get processed. This happens in STS 4.22.0 and was working in previous versions.

**Working example**

     import java.io.Serializable;
     import java.time.LocalDate;
     import lombok.EqualsAndHashCode;
     import lombok.Getter;
     import lombok.Setter;
     import lombok.ToString;

        @Getter
	@Setter
	@EqualsAndHashCode()
	@ToString()
	public class Test implements Serializable {

		private String myString;

		private LocalDate myDate;
	}

Generates getter, setter, equals, hashCode und toString methods.

**Non working example**

     import java.io.Serializable;
     import java.time.LocalDate;
     import lombok.EqualsAndHashCode;
     import lombok.Getter;
     import lombok.Setter;
     import lombok.ToString;

	@Getter
	@Setter
	@EqualsAndHashCode(of = { "myString", "myDate" })
	@ToString(doNotUseGetters = true)
	public class Test implements Serializable {

		private String myString;

		private LocalDate myDate;
	}

Generates only getter and setter methods.

**Comment by explorer566** [comment] 2024-03-16 16:14
I am using STS 4.22.0 under Windows and Lombok 1.18.30

**Comment by martinlippert** [comment] 2024-03-16 20:33
This is probably a duplicate of https://github.com/projectlombok/lombok/issues/3630, therefore closing this one here. Looks like the Lombok support for Eclipse is not yet compatible with the latest Eclipse 2024-03 release, which is the base for the latest Spring Tools 4.22.0 release.

**Closed by martinlippert** 2024-03-16 20:33 UTC
Labels: type: bug, for: eclipse, status: duplicate

**Comment by martinlippert** [comment] 2024-03-16 20:36
Another related issue: https://github.com/projectlombok/lombok/issues/3620. Maybe worth to give the latest Lombok edge release a try: https://projectlombok.org/download-edge

**Comment by martinlippert** [comment] 2024-03-17 17:17
According to https://github.com/projectlombok/lombok/issues/3630#issuecomment-2002342284, this is fixed in the latest Lombok Edge release.
