### ISSUE TITLE
SpringToolSuite (x_86_64 option) IDE keeps crashing frequently.

### ISSUE THREAD

**Issue by jbdundas** [spring-projects/sts4#1228] opened 2024-04-11 15:35 UTC
[hs_err_pid19148.log](https://github.com/spring-projects/sts4/files/14948171/hs_err_pid19148.log)
**Describe the bug**
The STS IDE keeps crashing whenever I try to use the AutoComplete/Suggestion window while writing in the Java class. For e.g. ResponseEntity -> type period symbol -> it hangs up after that event. Next, a pop-up window opens which asks me to either Wait or Force Quit the IDE.  The Wait option just continues a few times after which it crashes and quits on it's own. 

I am not able to use this IDE due to this issue. Please provide a solution how to fix this problem. Thank you!

**To Reproduce**
Download the latest STS IDE or even try Spring STS 4.2.2 Release version ( Linux - x86-64) . Then, follow the steps mentioned in the previous paragraph.

**Sample**
A copy of the PID log file( with stacktrace and thread dump which was automatically generated) is attached for your reference. PLease note that it is happening frequently. Changing the memory XmX and Xms to higher values does not make any difference.

**Comment by BoykoAlex** [comment] 2024-04-11 15:59
It'd be interesting to see the Boot Language server log file. Please enable Spring Boot Language Server logging via:
![Screenshot 2024-04-11 at 11 57 56](https://github.com/spring-projects/sts4/assets/6433390/27f02f71-9a76-4cf3-994f-9beea34aeec7)
Reproduce the hang and attach the log file here.

As a possible workaround: go in the preferences and uncheck the checkboxes below. This will disable Spring Boot Language Server and consequently contributions made by STS into the Java completion proposals.
![Screenshot 2024-04-11 at 11 54 30](https://github.com/spring-projects/sts4/assets/6433390/ba57c8f4-0100-4460-99f2-eb99e305b9af)

**Comment by martinlippert** [comment] 2024-04-11 16:17
There is also a workaround mentioned ("Start with GDK_BACKEND=x11"), would be good to know whether that helps or not.

**Comment by 4javier** [comment] 2024-04-14 11:21
Probably related
https://github.com/spring-projects/sts4/issues/1230

**Comment by martinlippert** [comment] 2024-04-15 06:44
Closing this one here as a duplicate of https://github.com/spring-projects/sts4/issues/1230. There is also some information on where to get snapshot builds from which already include a fix.

**Closed by martinlippert** 2024-04-15 06:44 UTC
Labels: status: waiting-for-feedback, type: bug, theme: performance, status: needs-investigation, for: eclipse, theme: code completion
