### ISSUE TITLE
i can't use tomcat server?

### ISSUE THREAD

**Issue by shmily2038** [spring-projects/sts4#93] opened 2018-09-30 01:51 UTC
why i improve my sts version to 4.0,i can't set the server of tomcat? no this choice.

**Comment by martinlippert** [comment] 2018-09-30 09:33
Is this a duplicate of https://github.com/spring-projects/sts4/issues/81 ? Sounds like it is, therefore closing this one as a duplicate. If not, please comment and we can re-open this one.

**Closed by martinlippert** 2018-09-30 09:33 UTC

**Comment by AlejandroMontes** [comment] 2018-10-01 14:00
Looks like they missed the JST Plugin, please follow these steps to fix it: 
1) Help> Install New Software 
2) Add this repository which comes from the last version of eclipse: http://download.eclipse.org/releases/photon/
3) Open Web, XML, Java EE ...
4) Select everything which starts with the prefix JST.

This will add the tomcat servers to your runtime options.

Regards
Alejandro Montes
