### ISSUE TITLE
"Code Completion" works fine in `application.properties` file, but does not work for `application.yml` file.

### ISSUE THREAD

**Issue by qinlinwang** [spring-projects/sts4#1242] opened 2024-04-27 04:33 UTC
**Describe the bug**
my environment:
os: macos 12.4
vscode: 1.88.0 (Universal)
jdk:jdk-11.0.16.1.jdk
vscode extensions:
Language Support for Java(TM) by Red Hat: v1.30.0
Spring Boot Tools: v1.53.0

"Code Completion" works fine in `application.properties` file, but does not work for `application.yml` file.
When i type in `application.properties` file,  `spring-boot.ls.logfile` is displayed as shown  in the below image(in the vscode terminal window):
<img width="1164" alt="image" src="https://github.com/spring-projects/sts4/assets/491831/f9f4b116-82c1-4bac-a4ac-b14322b18be9">

When i type in `application.yml` file,  `spring-boot.ls.logfile` is displayed as shown  in the below image:
<img width="1158" alt="image" src="https://github.com/spring-projects/sts4/assets/491831/0019dd3b-d3ee-44a3-a851-ad8aca740388">

and the `vscode-sping-boot-debug-log` shows an below:
<img width="1122" alt="image" src="https://github.com/spring-projects/sts4/assets/491831/75e84523-5eaf-41d2-bf77-87c51acfdfc2">

However, the `Information Hovers` feature is working fine.
<img width="1090" alt="image" src="https://github.com/spring-projects/sts4/assets/491831/6c37effd-1727-4117-b54d-6e9afd00b231">

**Comment by BoykoAlex** [comment] 2024-04-27 16:09
Hmm... I cannot reproduce this unfortunately... 
When you have properties in yaml and see hovers showing up does the content assist work then?

I've tried petclinic and consume rest guide project - yaml completions show up fine.

Not really sure what to suggest... Could you attach your project with both properties and yaml file for us to try. Also the spring boot ls log file might be useful.

**Comment by qinlinwang** [comment] 2024-04-30 07:21
> Hmm... I cannot reproduce this unfortunately... When you have properties in yaml and see hovers showing up does the content assist work then?
> 
> I've tried petclinic and consume rest guide project - yaml completions show up fine.
> 
> Not really sure what to suggest... Could you attach your project with both properties and yaml file for us to try. Also the spring boot ls log file might be useful.

On my machine, none of the projects are good. For example, the simplest Spring Boot project I newly created below.
[spring-boot-demo.zip](https://github.com/spring-projects/sts4/files/15159752/spring-boot-demo.zip)

**Comment by BoykoAlex** [comment] 2024-04-30 20:27
Still cannot reproduce...  as you can see below completion proposals are showing up for the project in the yaml file:
![Screenshot 2024-04-30 at 16 21 02](https://github.com/spring-projects/sts4/assets/6433390/51049d56-824b-4d8c-be30-08e4b3d401da)

I'll give this a try on an older mac maybe it has something to do with the OS. One thing to try would be JDK 17 for the Java LS and Spring Boot LS. I see you have JDK 11 listed. I thought both of these extensions require JDK 17 (although if that was off i think boot ls log would have been full of various errors)

Java LS Java Home:

![Screenshot 2024-04-30 at 16 25 59](https://github.com/spring-projects/sts4/assets/6433390/d0bc6a61-508f-4c8d-8407-5c986b07f415)

Spring Boot LS Java Home:

![Screenshot 2024-04-30 at 16 26 08](https://github.com/spring-projects/sts4/assets/6433390/094435fe-b59c-4a3b-9d51-ffe4220c32bf)

**Comment by qinlinwang** [comment] 2024-05-01 02:00
I specify the path for the jdk17 in the settings.json, but it still does't work.
```json
    "java.jdt.ls.java.home": "/Library/Java/JavaVirtualMachines/jdk-17.0.11.jdk/Contents/Home",
    "spring-boot.ls.java.home": "/Library/Java/JavaVirtualMachines/jdk-17.0.11.jdk/Contents/Home"
```
If it's because of the JDK, then the properties file should have the same issue, right? Is there anything else I can provide?

**Comment by BoykoAlex** [comment] 2024-05-01 20:17
Okay is the issue that once you type in the `application.properties` file that completion proposals just show up as you type the word `port`? Looks like you expect the same in the `application.yml` file...  In other words you d not invoke completion proposals with `Ctrl-Space` (`Cmd-Space` on mac) but expect completion proposals to show up as you type? Is this the issue?

**Comment by qinlinwang** [comment] 2024-05-04 10:58
> Okay is the issue that once you type in the `application.properties` file that completion proposals just show up as you type the word `port`? Looks like you expect the same in the `application.yml` file... In other words you do not invoke completion proposals with `Ctrl-Space` (`Cmd-Space` on mac) but expect completion proposals to show up as you type? Is this the issue?
> 
> `.` is the trigger character in yaml... if you type `.` then completion proposals would show up. Otherwise `Ctrl-Space` or `Cmd-Space` is the universal way to invoke completion proposals in any IDE everything else is just tiny perks here and there.

Thanks a lot, `.`  did work in yaml。   Why isn't the behavior designed to be the same in both file types?

**Comment by BoykoAlex** [comment] 2024-05-04 14:13
It is designed to be roughly the same however for some reason only a few trigger chars are working in VSCode for YAML. Something must be consuming the rest of the trigger chars... It is a rather low priority issue but requires quite a bit of preparation work to demonstrate the problem to vscode team.

**Comment by 661913** [comment] 2024-08-07 05:16
I'm having the same problem, yaml and yml suffix endings won't prompt, system is windows 10, vscode version is 1.92.0

**Comment by wangqing1001** [comment] 2024-08-09 11:59
I also have the same problem. It worked fine the first time, but when I input other attributes with the same prefix the second time, it doesn't prompt

**Comment by martinlippert** [comment] 2024-08-12 10:00
@661913 and @wangqing1001 Can you provide more details here, maybe sample snippets of your `application.yml` files and steps how to reproduce the issue? That would be awesome.

**Comment by martinlippert** [comment] 2024-08-15 08:28
@661913 , @wangqing1001 Any news on this? Any snippets or samples you can share?

**Comment by martinlippert** [comment] 2024-08-29 08:19
No additional feedback so far, so closing this one for now. If you have additional details, feel free to add them and we can re-open anytime.

**Closed by martinlippert** 2024-08-29 08:19 UTC
Labels: status: waiting-for-feedback, type: bug, theme: property-editing-support, for: vscode
