### ISSUE TITLE
J- Unit 5 testing cannot be run

### ISSUE THREAD

**Issue by lmillangoda** [spring-projects/sts4#381] opened 2019-10-22 06:42 UTC

**Comment by martinlippert** [comment] 2019-10-22 07:38
Can you please provide an example and more details on this? And are you using the latest version of Spring Tools 4 for Eclipse?

**Comment by BoykoAlex** [comment] 2019-10-22 13:29
It's a duplicate of #371 - there are some workarounds in the comments.

**Closed by BoykoAlex** 2019-10-22 13:29 UTC
