### ISSUE TITLE
YAML_UNKNOWN_PROPERTY on custom property

### ISSUE THREAD

**Issue by reszy** [spring-projects/sts4#425] opened 2020-03-21 23:35 UTC
VS code is showing `YAML_UNKNOWN_PROPERTY` on custom property even if `META-INF/spring-configuration-metadata.json` is present in project
https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-configuration-metadata.html

**Comment by kdvolder** [comment] 2020-03-23 16:33
Can you provide an example. E.g. ideally a small project that contains said metadata, and a application.yml file that shows the problem. 

I can of course try to make an example myself, but I have tried it in the past and it works for me. So it may be something specific detail about your project / property / metadata that is required for this bug to happen. And I am not able to guess at that.

**Comment by kdvolder** [comment] 2020-04-01 16:27
Closing because of no response from @reszy with more info. I have tried this sort of thing recently and it seemed to work fine for me. Hence closing as "Cannot Reproduce".

Can be re-opened if @reszy provides more info to help reproduce the issue.

**Comment by spring-issuemaster** [comment] 2020-04-01 16:27
(comment in Pivotal Tracker added by Kris De Volder:) 

Closing as 'cannot reproduce'.

**Closed by kdvolder** 2020-04-01 16:27 UTC
Labels: started

**Comment by martinlippert** [comment] 2020-04-02 13:02
Shortly after finally closing this ticket as not-reproducible, I came across something that is very similar to this (maybe related). I observed the properties editor to quickly become sluggish and slow, especially around content-assist, and keep on typing seemed to cause more or less random errors to show up in the properties file. Does that sound similar to what you experienced, @reszy ?

**Comment by reszy** [comment] 2020-04-03 14:11
Sorry for delay. I'm useing sts4 it with my side project and finally yesterday i had some time to create project to reproduce bug and it worked. But in original project I had some issues as @martinlippert says. 
I am migrating project from java8 to project with multiple modules in java 11. Probably it was lagging then, because of many unresolved issues in code. When I've created matedata file for spring it never worked, so I've made many changes to it and unfortunately left it with typo. When I've finally resolved all other issues in project it looked like not working and created this thread. So sorry for making trouble :)

**Comment by martinlippert** [comment] 2020-04-03 14:18
@reszy thanks for the additional feedback and no worries about any trouble, please keep on reporting problems and issues whenever they appear. I hope that we have a solution for this sometime soon (at least for the next release), so that those situations don't appear again.

**Comment by kdvolder** [comment] 2020-04-03 16:23
@reszy No problem. It sounds like the problems with your STS/IDE where somehow caused by having project with some issues. Even when projects themselves have issues this should not break the IDE or cause it to become laggy. This is something we should try to fix if we can. 

Unfortunately problems like this are a bit hard to reproduce and as a consequence fix. Which is why it is valuable if users like you report them (so we know there is a problem). Even more helpful is if you can have a sample of a 'broken' project that causes these issues and can shared this with us.

So please don't hesitate to raise issues again if you notice more problem in the future. And if you can try and 'capture' the state of your 'broken' project and are willing/able to share it that is even more helpful.
