### ISSUE TITLE
[Suggest] Create a dashboard for gradle projects

### ISSUE THREAD

**Issue by juniorjrjl** [spring-projects/sts4#385] opened 2019-10-26 17:34 UTC
Have plains to create a dashboard for gradle like a maven dashboard?

**Comment by BoykoAlex** [comment] 2019-10-27 14:52
The boot dashboard shows Gradle based Spring Boot projects as well. The Boot dashboard shows Boot projects based on the resultant classpath (presence of Spring Boot on the classpath) rather than a particular build tool like Maven or Gradle. If Gradle Spring Boot project is properly imported into Eclipse/STS it should show up in the Boot Dashboard.

**Comment by kdvolder** [comment] 2020-01-16 17:21
Since this is supposed to work already, and this issue has seen no comments for a while I'll close it.

@juniorjrjl If you have something that doesn't work, then please raise an issue for that problem specificially and try to document some steps we can follow to reproduce the issue and try to trouble-shoot and fix it.

**Closed by kdvolder** 2020-01-16 17:21 UTC
