### ISSUE TITLE
ssh cant not connact by 4.10

### ISSUE THREAD

**Issue by zhangmrit** [spring-projects/sts4#638] opened 2021-05-08 08:26 UTC
!ENTRY org.eclipse.egit.core 4 0 2021-05-08 16:18:27.023
!MESSAGE Pulling 1 repository
!SUBENTRY 1 org.eclipse.egit.core 4 0 2021-05-08 16:18:27.023
org.eclipse.jgit.api.errors.TransportException: git@xxx.com:xxx.git: Cannot log in at xxx.com:22
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:224)
	at org.eclipse.jgit.api.PullCommand.call(PullCommand.java:263)
	at org.eclipse.egit.core.op.PullOperation$PullJob.run(PullOperation.java:255)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

BUT
all the same in 4.9 is ok

**Comment by martinlippert** [comment] 2021-05-18 10:24
@zhangmrit Sorry for the late reply here. This sounds very much like a problem with JGit, looks like this one here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=572194 - so I will close this item here as a duplicate of that.

**Closed by martinlippert** 2021-05-18 10:24 UTC
Labels: status: waiting-for-triage, type: bug

**Comment by martinlippert** [comment] 2021-05-18 10:27
Here is a direct link to the "known issues" of EGit/JGit (including a workarounds). Probably worth a try?
https://wiki.eclipse.org/EGit/New_and_Noteworthy/5.11#Known_problems
