### ISSUE TITLE
Eclipse Run Configuration - Use Temporary Jar becomes secretly unchecked

### ISSUE THREAD

**Issue by toddfroyland** [spring-projects/sts4#1248] opened 2024-05-06 17:16 UTC
In Eclipse Run Configurations, spring Boot App, modifying anything on any tab causes the "Use temporary JAR to specify classpath" checkbox on the Classpath tab to become unchecked, although it still shows as checked. Unchecking the box does not cause the "Apply" button to activate. Checking the box again allows you to click on "Apply". This ritual, uncheck, re-check, click Apply, must be done every time a configuration change is made.

**To Reproduce**

1. Create a Spring Boot App run configuration that has the "Use temporary JAR to specify classpath" box on the Classpath tab checked.
2. Save the configuration.
3. Edit the configuration.
4. Add, delete, or change something on the Environment tab. Click "Apply" there.
5. Switch to the Classpath tab. Notice that the "Apply" button is grayed out.
6. Uncheck the "Use temporary JAR to specify classpath" checkbox. Notice that the "Apply" button is still grayed out.
7. Check the "Use temporary JAR to specify classpath" checkbox. Notice that the "Apply" button is now available to select

This has been an issue for several years. Since I just upgraded to the latest Eclipse (2024-03) and Spring Tool Suite 4 (4.22.0.202403071427), I thought I should finally report it.

Exported launch configuration attached.

[DashboardBoot.launch.txt](https://github.com/spring-projects/sts4/files/15224051/DashboardBoot.launch.txt)

**Comment by martinlippert** [comment] 2024-05-07 07:54
@toddfroyland Thanks for reporting this and the details steps how to reproduce this. I can clearly reproduce this on my end as well... :-) So let's get that fixed for the next release.

**Comment by BoykoAlex** [comment] 2024-06-04 22:10
Turns out that for Java version greater than 8 it should be **Dependencies** tab instead of **Classpath**. JDT launching sets the temp JAR classpath to `false` for "modular" projects (Java 9 and above) on each apply automatically hence we observe the behaviour on the **Classpath** tab that shouldn't be there. Instead for projects on Java 9 and above the **Dependencies** tab should be showing that doesn't have the checkbox for temp JAR classpath.
Fixed with 7ec8bc14cd49718b6f18d6d7cd0eaadcad8d959b

**Closed by BoykoAlex** 2024-06-04 22:10 UTC
Labels: type: bug, status: needs-investigation, for: eclipse
