### ISSUE TITLE
YAML Property completion: Superclass properties not detected in case of List or Map

### ISSUE THREAD

**Issue by beckermarc** [spring-projects/sts4#449] opened 2020-04-15 10:18 UTC
Hi,

I am using Spring Boot Tools 1.16.0 in VS Code. I am observing a problem with property completion in application.yaml files, that occurs whenever a property (`bar`) is defined in a superclass (`SuperclassProperties`) of a type (`NestedProperties`), that can be provided as a List or Map (`nested`). The property (`bar`) is not found in that case and reported as invalid, only properties defined in the child class (`foo`) work correctly.

If the property `nested` is not defined as a list or map (`private NestedProperties nested`), the 
`bar` property is explicitly listed in the `spring-configuration-metadata.json` file and code-completion works as expected.

Example:

```java
package my.property.test;

import java.util.ArrayList;
import java.util.List;

import org.springframework.boot.context.properties.ConfigurationProperties;

@ConfigurationProperties("myprops")
public class TestProperties {

	private List<NestedProperties> nested = new ArrayList<>();

	public List<NestedProperties> getNested() {
		return nested;
	}

	public void setNested(List<NestedProperties> nested) {
		this.nested = nested;
	}

	public static class NestedProperties extends SuperclassProperties {

		private String foo;

		public String getFoo() {
			return foo;
		}

		public void setFoo(String foo) {
			this.foo = foo;
		}

	}

	public static class SuperclassProperties {

		private String bar;

		public String getBar() {
			return bar;
		}

		public void setBar(String bar) {
			this.bar = bar;
		}

	}

}
```

```json
{
  "groups": [
    {
      "name": "myprops",
      "type": "my.property.test.TestProperties",
      "sourceType": "my.property.test.TestProperties"
    }
  ],
  "properties": [
    {
      "name": "myprops.nested",
      "type": "java.util.List<my.property.test.TestProperties$NestedProperties>",
      "sourceType": "my.property.test.TestProperties"
    }
  ],
  "hints": []
}
```

As you can see, only `foo` is suggested, but not `bar`:
![image](https://user-images.githubusercontent.com/27853796/79326420-1c0de400-7f13-11ea-9104-b2d249b9da36.png)

**Comment by kdvolder** [comment] 2020-04-17 16:45
Reproducible. I tried it in Eclipse but it's the same issue since uses same language server under the hood.

**Comment by kdvolder** [comment] 2020-04-17 16:46
Thanks for the nice and detailed bug report and example by the way.

**Comment by spring-issuemaster** [comment] 2020-04-17 19:03
(comment in Pivotal Tracker added by Kris De Volder:) 

Pushed a fix.

**Comment by spring-issuemaster** [comment] 2020-04-17 21:21
(comment in Pivotal Tracker added by Kris De Volder:) 

Verfied the fix with a vscode snapshot build. Delivering.

Note: Did not verify the Eclipse build, I think the change is still working it's way through the slow build pipeline.

**Closed** 2020-04-20 09:32 UTC
Labels: delivered

**Comment by beckermarc** [comment] 2020-04-20 10:00
Thanks for the fast fix @kdvolder :)
