### ISSUE TITLE
LSP/.metadata corruption in 4.17.0 :   Caused by: java.io.IOException: Stream closed with LSP

### ISSUE THREAD

**Issue by space88man** [spring-projects/sts4#938] opened 2022-12-31 02:13 UTC
**Describe the bug**
When starting SpringToolSuite4 4.17.0 it stalls at Language Server Background job and shows a
`Caused by: java.io.IOException: Stream closed` similar to this issue: https://github.com/gtache/intellij-lsp/issues/20

**To Reproduce**

- a Spring boot project, not terribly complicated, uses JPA+JUnit5; Java 17
- close STS; and restart (hard to reproduce; need to work on the project for a few coding sessions, compile/debug cycle, check for STS updates etc etc)

Occasionally the LSP background process hangs/crashes during a fresh start and the UI will emit the Exception messages in the terminal.

In this state `.metadata/` is "corrupted" and non-recoverable:  STS will go into this hang on each attempt to start.

Workarounds:
- delete `.metadata/` and recreate the workspace OR
- restore a backup of a working `.metadata/`

[failed.log](https://github.com/spring-projects/sts4/files/10326729/failed.log)

Update:
- going to try uninstalling Ansi Console and see what happens...

**Comment by martinlippert** [comment] 2023-01-01 17:59
This is most likely a duplicate of https://github.com/spring-projects/sts4/issues/925 and already fixed, will ship as part of the next update release 4.17.1, to be released asap.

**Closed by martinlippert** 2023-01-01 17:59 UTC
Labels: type: bug, for: eclipse, status: duplicate
