### ISSUE TITLE
broken lombol decorator toString with callsuper true param

### ISSUE THREAD

**Issue by ricca90** [spring-projects/sts4#1210] opened 2024-03-19 08:28 UTC
hi, i just update sts at the 4.22.0 version and all classes in the workspace with this lombok decorator "@ToString(callSuper = true)" doesn't compile.
here the error "Lombok annotation handler class lombok.eclipse.handlers.HandleToString failed".
with only @ToString there is no problem. 
here the log file from sts. [errorLog.txt](https://github.com/spring-projects/sts4/files/14647646/errorLog.txt)

Thanks,
Riccardo

**Comment by martinlippert** [comment] 2024-03-19 08:35
This is a duplicate of https://github.com/spring-projects/sts4/issues/1208. Lombok isn't yet compatible with the latest Eclipse release `2024-03`, which is the foundation for the Spring Tools `4.22.0` release. You need to install the latest Lombok Edge release.

**Closed by martinlippert** 2024-03-19 08:35 UTC
Labels: type: bug, for: eclipse
