### ISSUE TITLE
Atom-Concourse : Add content assist to user-defined resources

### ISSUE THREAD

**Issue by rbosse** [spring-projects/sts4#178] opened 2019-01-10 15:47 UTC
Hi,

In VSCode, it is possible to display the list of resources with Ctrl-Space like this:
![capture d ecran de 2019-01-10 10-45-13](https://user-images.githubusercontent.com/3311751/50979681-05354200-14c5-11e9-9d6b-9a0da22870e8.png)

In Atom, it is not possible to do so.  Would it be possible to add this feature?

**Comment by BoykoAlex** [comment] 2019-01-10 16:43
I believe it is possible and it's working. The problem is that it is blocked by https://github.com/atom/atom-languageclient/issues/218
The first character need to be typed for CA to work in Atom unfortunately... For example if you type `a` you'd see all resources starting with `a`

**Comment by rbosse** [comment] 2019-01-10 17:03
Ok, thanks for the quick response!  Do you want me to close the issue or we should leave it open?

**Comment by kdvolder** [comment] 2019-01-10 17:07
I think we should close. Nothing much we can do in STS itself. You can comment on the atom issue that Alex linked to if you feel like sending them a signal you'd really like to have this fixed.

**Comment by BoykoAlex** [comment] 2019-01-10 17:08
Lets close it. I really think that atom-languageclient should fix this. The LS providing CA proposals has the right proposals... Can't override what atom-languageclient does currently

**Closed by kdvolder** 2019-01-10 17:07 UTC
