### ISSUE TITLE
No margin markers for method calls

### ISSUE THREAD

**Issue by dsyer** [spring-projects/sts4#70] opened 2018-09-04 08:02 UTC
I'm not seeing any margin markers for method calls when I select a private method. Don't know if this is related but there are a lot of these in the SBLS console:

```
[pool-2-thread-1] ERROR org.springframework.ide.vscode.boot.java.utils.SpringIndexer - error extracting symbol information in project 'spring-boot-allocations' - for docURI 'file:///home/dsyer/dev/boot/spring-boot-allocations/src/main/java/com/example/auto/ConditionEvaluator.java' - on node: @Nullable
org.eclipse.jdt.internal.compiler.problem.AbortCompilation: Pb(324) The type javax.annotation.meta.When cannot be resolved. It is indirectly referenced from required .class files
	at org.eclipse.jdt.internal.compiler.problem.ProblemHandler.handle(ProblemHandler.java:159)
	at org.eclipse.jdt.internal.compiler.problem.ProblemHandler.handle(ProblemHandler.java:226)
	at org.eclipse.jdt.internal.compiler.problem.ProblemReporter.handle(ProblemReporter.java:2542)
	at org.eclipse.jdt.internal.compiler.problem.ProblemReporter.isClassPathCorrect(ProblemReporter.java:4997)
	at org.eclipse.jdt.internal.compiler.lookup.UnresolvedReferenceBinding.resolve(UnresolvedReferenceBinding.java:120)
	at org.eclipse.jdt.internal.compiler.lookup.BinaryTypeBinding.resolveType(BinaryTypeBinding.java:228)
	at org.eclipse.jdt.internal.compiler.lookup.ElementValuePair$UnresolvedEnumConstant.getResolved(ElementValuePair.java:40)
	at org.eclipse.jdt.internal.compiler.lookup.ElementValuePair.getValue(ElementValuePair.java:118)
	at org.eclipse.jdt.internal.compiler.lookup.UnresolvedAnnotationBinding.getElementValuePairs(UnresolvedAnnotationBinding.java:56)
	at org.eclipse.jdt.internal.compiler.lookup.AnnotationBinding.hashCode(AnnotationBinding.java:262)
	at org.eclipse.jdt.core.dom.DefaultBindingResolver$AnnotationIdentityBinding.hashCode(DefaultBindingResolver.java:541)
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1012)
	at java.util.concurrent.ConcurrentHashMap.putIfAbsent(ConcurrentHashMap.java:1535)
	at org.eclipse.jdt.core.dom.DefaultBindingResolver.getAnnotationInstance(DefaultBindingResolver.java:556)
	at org.eclipse.jdt.core.dom.TypeBinding.resolveAnnotationBindings(TypeBinding.java:132)
	at org.eclipse.jdt.core.dom.TypeBinding.getAnnotations(TypeBinding.java:118)
	at org.springframework.ide.vscode.boot.java.annotations.AnnotationHierarchies.getDirectSuperAnnotations(AnnotationHierarchies.java:46)
	at org.springframework.ide.vscode.boot.java.annotations.AnnotationHierarchyAwareLookup.findElements(AnnotationHierarchyAwareLookup.java:113)
	at org.springframework.ide.vscode.boot.java.annotations.AnnotationHierarchyAwareLookup.get(AnnotationHierarchyAwareLookup.java:92)
...
```

**Comment by martinlippert** [comment] 2018-09-05 10:09
I did a screen share session with @dsyer and we found that the settings for the text editor annotations were gone for almost all annotation types. As soon as you manually enable the annotations for the overview ruler, they show up again just fine. But the reason why those settings got changed is still unknown. And the "restore defaults" doesn't restore the old settings, so you would have to enable all of them again (with colors, styles, etc.), a really annoying work.

**Comment by martinlippert** [comment] 2018-09-05 10:11
The exception from the language server is about something else that should be investigated separately, I will add a bug item to tracker for that.

**Comment by martinlippert** [comment] 2018-09-07 12:49
Side note: the bug entry that covers the exceptions that you saw in the log is fixed, latest nightly updates should not show these ugly exceptions anymore.

**Comment by martinlippert** [comment] 2018-10-19 14:14
Closing this one for now, too. The problem with the missing margin markers where caused by a strange reset of the default annotation visibility settings, but we never found out why this happened. But since there is not a lot we can do at the moment about this, I am closing this one for now.

**Closed by martinlippert** 2018-10-19 14:14 UTC
