### ISSUE TITLE
Make jdt ls claspath infrastructure more reliable at detecting project deletions

### ISSUE THREAD

**Issue by kdvolder** [spring-projects/sts4#69] opened 2018-08-21 20:29 UTC
For some steps that demonstrate how unreliable it is... see: https://github.com/Microsoft/vscode-spring-boot-dashboard/issues/15

**Comment by spring-issuemaster** [comment] 2018-08-22 19:15
(comment in Pivotal Tracker added by Kris De Volder:) 

Looks there was a bug making deletion events unreliable when more than one classpath listener is attached. Whichever listener was the second one added would not get the deletion event. Which listener that turned out to be, was somewhat unpredictable at runtime. So that was what causes the kind of 'random behavior' we have observed in the vscode-spring-boot-dashboard sometimes not reacting to deleted projects.

I've now pushed a fix for this.

**Comment by spring-issuemaster** [comment] 2018-08-22 21:56
(comment in Pivotal Tracker added by Kris De Volder:) 

Verified with latest vscode-spring-boot ci build as follows:

1) install vscode-spring-boot from ci vsix vile
2) clone vsoce-spring-boot-dashboard repo: https://github.com/Microsoft/vscode-spring-boot-dashboard
3) run 'npm install' from vscode-spring-boot-dashboard
4) open vscode-spring-boot-dashboard in vscode
5) run vscode-spring-boot-dashboard in vscode by pressing F5
6) Follow the steps as described in this github ticket: https://github.com/Microsoft/vscode-spring-boot-dashboard/issues/15

**Comment by spring-issuemaster** [comment] 2018-08-28 15:01
(comment in Pivotal Tracker added by Martin Lippert:) 

Tried the steps as described and works pretty reliable for me know. Great that you found the root cause of this!!!

**Closed** 2018-08-28 15:01 UTC
Labels: delivered
