### ISSUE TITLE
Add Spring Data JPA assist in Visual Studio Code

### ISSUE THREAD

**Issue by FaiyazMujawar** [spring-projects/sts4#824] opened 2022-08-31 14:12 UTC
It would be nice to have Spring Data Jpa Assist support in Visual Studio Code, as in Intellij. 

Intellij has a nice feature that suggests which properties and operations can be specified in the function name in a repository interface for building a JPA query. It would be nice to have the same in vscode as well.

Currently, no such feature is available through any extension 🥲

**Comment by martinlippert** [comment] 2022-08-31 14:48
Closing this one as a duplicate of https://github.com/spring-projects/sts4/issues/107. Please feel free to comment on that, especially with key features you would like to see first and foremost. Would be interesting to hear about your priorities in this space.

**Closed by martinlippert** 2022-08-31 14:48 UTC
Labels: type: enhancement, status: duplicate
