### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Ivancito-ur** [spring-projects/sts4#479] opened 2020-06-11 11:52 UTC
- Issue Type: `Bug`
- Extension Name: `vscode-spring-boot`
- Extension Version: `1.18.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.46.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by martinlippert** [comment] 2020-06-11 13:03
Hey @Ivancito-ur from this description it is somewhat unclear what the issue exactly is that you have with the extension. Can you provide more details what the issue is? And how to reproduce this?

**Comment by martinlippert** [comment] 2021-02-16 13:08
Closing this issue due to no additional feedback nor details being provided. If you come across this again, please comment and provide more details and we can re-open the issue anytime.

**Closed by martinlippert** 2021-02-16 13:08 UTC
