### ISSUE TITLE
when I click maven installations the IDE stops responding

### ISSUE THREAD

**Issue by ksanjeev9211** [spring-projects/sts4#855] opened 2022-10-09 19:39 UTC
STS-4.16 :
windows->preferences->maven->installation-> IDE stops responding.

when I try the same with STS-4.3.2 or other older versions, there is no problem

**Comment by ksanjeev9211** [comment] 2022-10-09 19:40
![image](https://user-images.githubusercontent.com/4118153/194776316-15948687-c18b-4692-aa66-2a0c755c8e7f.png)

**Comment by martinlippert** [comment] 2022-10-10 07:27
This was reported to m2e here: https://github.com/eclipse-m2e/m2e-core/issues/923
Another duplicate of this in the sts4 repo is: https://github.com/spring-projects/sts4/issues/850

**Closed by martinlippert** 2022-10-10 07:27 UTC
Labels: type: bug, for: eclipse, status: duplicate

**Comment by ksanjeev9211** [comment] 2022-10-10 13:57
Thanks a lot!
One quick question, not sure where to create one more issue regarding import of lombok based multi module maven project, m2e never generates .classpath,  shall I go to m2e forum  or shall I create one here?

**Comment by martinlippert** [comment] 2022-10-10 14:44
@ksanjeev9211 That sounds like a problem at the intersection of m2e and Lombok, so probably the best choice here is to discuss that at the Lombok issue tracker first and see where you get from there: https://github.com/projectlombok/lombok
