### ISSUE TITLE
Error on installing Mylyn JIRA Connector in STS 4.9.0

### ISSUE THREAD

**Issue by dominik42** [spring-projects/sts4#599] opened 2021-02-13 17:16 UTC
**Describe the bug**
I'm using Mylyn and the Mylyn JIRA Connector since several years together with STS4. After the last update, it's not longer possible to use the Mylyn JIRA connector. But if I manually install Eclipse IDE for Enterprise Java Developers 2020.12 / 4.18 and install Mylyn and the JIRA connector there, it works.

**To Reproduce**
- Download and install STS4 4.9.0 for MacOS
- install Mylyn 3.25 via Eclipse Marketplace
  - Open View "Task Repositories" should work
- install Mylyn JIRA Connector via "Install New Software" from http://update.atlassian.com/atlassian-eclipse-plugin/rest/e3.7
  - Open View "Task Repositories" leads to the following error
```
Removing PartDescriptorImpl with the "org.eclipse.mylyn.tasks.ui.views.repositories" id and the   
"Task Repositories" label.  It points to the non available "bundleclass://org.eclipse.ui.workbench  /org.eclipse.ui.internal.e4.compatibility.CompatibilityView" class. Bundle might have been uninstalled  
Removing PartDescriptorImpl with the "org.eclipse.mylyn.tasks.ui.views.tasks" id and the "Task List" label.    
It points to the non available "bundleclass://org.eclipse.ui.workbench  /org.eclipse.ui.internal.e4.compatibility.CompatibilityView" class. Bundle might have been uninstalled
```

I know that the Mylyn JIRA Connector is outdated but it still works with the last version of STS4 and also with the current raw Eclipse package plus Mylyn installed additionally.

Kind regards
Dominik

**Comment by martinlippert** [comment] 2021-02-15 08:45
This is the same issue as #588 so closing this as a duplicate of this one.

The details and a workaround are described in this comment:
https://github.com/spring-projects/sts4/issues/588#issuecomment-762313076

**Closed by martinlippert** 2021-02-15 08:45 UTC
Labels: type: bug, type: install-issue

**Comment by martinlippert** [comment] 2021-03-05 11:32
A workaround for has also been added to the upcoming Spring Tools 4.10.0.RELEASE.
