### ISSUE TITLE
Refreshing Live Data over HTTP is not working on VS Code

### ISSUE THREAD

**Issue by Eskibear** [spring-projects/sts4#872] opened 2022-11-08 08:14 UTC
Following https://github.com/spring-projects/sts4/wiki/Live-Application-Information , configure `boot-java.remote-apps` to get live data over http, it failed to refresh data.

Originally I wanted to connect my app running on Azure, which only expose actuator endpoints over HTTP (JMX port is internal, no public access). It failed to refresh the data. Then I tried locally, it also failed with same error message and same sts-log.

settings:
```jsonc
    "boot-java.remote-apps": [
        // {
        //     "host": "my-app-name.azuremicroservices.io",
        //     "jmxurl": "https://my-app-name.azuremicroservices.io/actuator"
        // },
        {
            "host": "localhost",
            "jmxurl": "http://localhost:8080/actuator"
        }
    ],
```

exception location:
https://github.com/spring-projects/sts4/blob/e9c813279f15f5f48144d5d8eb13c232e62c4134/headless-services/spring-boot-language-server/src/main/java/org/springframework/ide/vscode/boot/java/livehover/v2/SpringProcessConnectorOverHttp.java#L135

sts log:

```log
15:56:50.895 [pool-10-thread-1] INFO  o.s.i.v.b.j.l.v.SpringProcessConnectorRemote - Creating RemoteStringBootApp: RemoteBootAppData [jmxurl=http://localhost:8080/actuator, host=localhost, urlScheme=https, port=443, manualConnect=false, keepChecking=true, processId=null, processName=null]
15:56:50.895 [pool-10-thread-1] INFO  o.s.i.v.b.j.l.v.SpringProcessConnectorService - connect to process: remote process - http://localhost:8080/actuator
15:56:50.895 [pool-10-thread-1] INFO  o.s.i.v.b.j.l.v.SpringProcessConnectorService - Connecting to process: remote process - http://localhost:8080/actuator - retry no: 0
15:56:50.895 [pool-10-thread-1] INFO  o.s.i.v.b.j.l.v.SpringProcessConnectorRemote - updating settings for remote processses to track - done
15:56:50.900 [pool-6-thread-4] INFO  o.s.i.v.b.j.l.v.SpringProcessConnectorService - refresh process: remote process - http://localhost:8080/actuator
15:56:50.900 [pool-6-thread-4] INFO  o.s.i.v.b.j.l.v.SpringProcessConnectorService - Refreshing data from Spring process: remote process - http://localhost:8080/actuator - retry no: 0
15:56:50.900 [pool-6-thread-4] INFO  o.s.i.v.b.j.l.v.SpringProcessConnectorService - refresh process: remote process - http://localhost:8080/actuator
15:56:50.900 [pool-6-thread-4] INFO  o.s.i.v.b.j.l.v.SpringProcessConnectorService - Refreshing data from Spring process: remote process - http://localhost:8080/actuator - retry no: 0
15:56:50.900 [pool-6-thread-4] INFO  o.s.i.v.b.j.l.v.SpringProcessConnectorService - refresh process: remote process - http://localhost:8080/actuator
15:56:50.900 [pool-6-thread-4] INFO  o.s.i.v.b.j.l.v.SpringProcessConnectorService - Refreshing data from Spring process: remote process - http://localhost:8080/actuator - retry no: 0
...
15:57:18.055 [pool-6-thread-5] INFO  o.s.i.v.b.j.l.v.SpringProcessConnectorService - Refreshing data from Spring process: remote process - http://localhost:8080/actuator - retry no: 10
15:57:21.069 [pool-6-thread-5] ERROR o.s.i.v.b.j.l.v.SpringProcessLiveDataExtractorOverJMX - Error parsing beans
org.springframework.web.client.HttpClientErrorException$NotFound: 404 : [no body]
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:113)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:168)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:122)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:819)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:777)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:334)
	at org.springframework.ide.vscode.boot.java.livehover.v2.HttpActuatorConnection.getLiveMetrics(HttpActuatorConnection.java:87)
	at org.springframework.ide.vscode.boot.java.livehover.v2.SpringProcessLiveDataExtractorOverHttp.getLiveMetrics(SpringProcessLiveDataExtractorOverHttp.java:388)
	at org.springframework.ide.vscode.boot.java.livehover.v2.SpringProcessLiveDataExtractorOverHttp.retrieveLiveGcPausesMetricsData(SpringProcessLiveDataExtractorOverHttp.java:201)
	at org.springframework.ide.vscode.boot.java.livehover.v2.SpringProcessConnectorOverHttp.refreshGcPausesMetrics(SpringProcessConnectorOverHttp.java:120)
	at org.springframework.ide.vscode.boot.java.livehover.v2.SpringProcessConnectorService.lambda$scheduleRefresh$4(SpringProcessConnectorService.java:247)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
15:57:21.071 [pool-6-thread-5] INFO  o.s.i.v.b.j.l.v.SpringProcessConnectorService - problem occured during process live data refresh
java.lang.Exception: no live gc pauses metric data received, lets try again
	at org.springframework.ide.vscode.boot.java.livehover.v2.SpringProcessConnectorOverHttp.refreshGcPausesMetrics(SpringProcessConnectorOverHttp.java:135)
	at org.springframework.ide.vscode.boot.java.livehover.v2.SpringProcessConnectorService.lambda$scheduleRefresh$4(SpringProcessConnectorService.java:247)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
15:57:21.071 [pool-6-thread-5] INFO  o.s.i.v.b.j.l.v.SpringProcessConnectorService - disconnect from process: remote process - http://localhost:8080/actuator
15:57:21.071 [pool-6-thread-5] INFO  o.s.i.v.b.j.l.v.SpringProcessConnectorService - Disconnect from process: remote process - http://localhost:8080/actuator - retry no: 0

```

**Comment by Eskibear** [comment] 2022-11-08 08:15
sample project is spring-petclinic, and I was using latest CI build `vscode-spring-boot-1.41.0-202211080047.vsix`

**Comment by martinlippert** [comment] 2022-11-08 14:33
Yepp, I can reproduce the issue, will work on a fix.

**Comment by BoykoAlex** [comment] 2022-11-08 20:58
Hopefully #875 would fix it but it requires discussion before going in.

**Comment by Eskibear** [comment] 2022-11-09 02:23
Thanks for the quick fix.
Some additional thoughts about remote-apps scenario. In such cases, apps are already running with their own configurations, that some actuator endpoints might not be exposed. Here querying gcPauses breaks the whole live data feature even though other data like beans and request mappings are successfully fetched. 

I think we should make it as robust as not to break the whole feature when some endpoints are not exposed. E.g. when `management.endpoints.web.exposure.exclude=metrics` according to [actuator docs](https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints.exposing). WDYT?

**Comment by martinlippert** [comment] 2022-11-09 09:42
@Eskibear Agree, a problem while fetching the metrics data should not break the whole feature. But such a problem should also not be ignored silently without telling the user. Otherwise users might be confused why, e.g., GC information is not showing up in the graph. So we need some kind of error reporting mechanism here to show those problems on the UI. WDYT?

**Comment by BoykoAlex** [comment] 2022-11-09 18:57
Should be fixed now with a41166383353374d7d422b9496e99c8c425c399f

**Closed by BoykoAlex** 2022-11-09 18:57 UTC
Labels: type: bug, theme: live-data

**Comment by martinlippert** [comment] 2022-11-10 11:36
@Eskibear I tried this with the latest Spring Tools extension CI build and the pre-release dashboard version.

It looks like the overall mechanism to fetch the data via HTTP seems to work, since I can see the live hovers showing up in the source code.

The remote process also shows up in the dashboards view for beans (not for request mappings though), but there are no beans showing up in the tree.

**Comment by Eskibear** [comment] 2022-11-10 15:47
> The remote process also shows up in the dashboards view for beans (not for request mappings though)

That's fixed in https://github.com/microsoft/vscode-spring-boot-dashboard/commit/57ca22d7487cbfdd285f1661ace9a9531547a851 . It will be auto shipped in next pre-release version (probably 10 hours later from now).
