### ISSUE TITLE
White artifact in project explorer in STS using the dark theme

### ISSUE THREAD

**Issue by vogella** [spring-projects/sts4#355] opened 2019-08-29 12:52 UTC
package.json look wrong in the dark theme. Not sure where this is coming from, I checked in a plain Eclipse SDK and it looks fine.

Spring Tool Suite 4 
Version: 4.4.0.CI-B1961
Build Id: 201908211948
OS: Linux, v.5.0.0-25-generic, x86_64 / gtk 3.24.8
Java version: 12.0.1

![image](https://user-images.githubusercontent.com/139910/63941756-8cdbbb00-ca6c-11e9-8a18-80f16e221c77.png)

**Comment by kdvolder** [comment] 2019-08-29 15:55
Also no idea where this might be coming from. To the best of my knowledge we don't do anything to change the appearance of package.json files. Maybe this must be coming down from something STS has installed as a dependency that isn't in the plain eclipse SDK. Maybe something from Eclipse WTP and friends. I.e. Eclipse pieces geared towards javascript and web development.

**Comment by vogella** [comment] 2019-08-29 16:12
Once @martinlippert moves to Wild Web Developer in #354 this might be solved. So maybe park it until the new JS tooling is used?

**Comment by martinlippert** [comment] 2020-01-15 08:33
The root cause of this is now investigated and documented at https://bugs.eclipse.org/bugs/show_bug.cgi?id=534424, therefore closing this one here.

**Closed by martinlippert** 2020-01-15 08:33 UTC
Labels: unscheduled
