### ISSUE TITLE
there is two question ,1.Strange hint。2Cannot open Eclipse Marketplace

### ISSUE THREAD

**Issue by rongflag** [spring-projects/sts4#95] opened 2018-10-01 07:51 UTC
1. 
Each class has a warn prompt.“Can't get the delegate of the gradle IncrementalProcessingEnvironment.”  
It does not affect usage but is uncomfortable.
2.
Yesterday was all right to   open Eclipse Marketplace .But not today.
Then,I unpacked a new STS，Not so.
Cannot open Eclipse Marketplace
Cannot install remote marketplace locations: Resource not found: http://marketplace.eclipse.org/catalogs/api/p
Cannot complete request to http://marketplace.eclipse.org/catalogs/api/p: http://marketplace.eclipse.org/catalogs/api/p
http://marketplace.eclipse.org/catalogs/api/p
Resource not found: http://marketplace.eclipse.org/catalogs/api/p
http://marketplace.eclipse.org/catalogs/api/p

**Comment by martinlippert** [comment] 2018-10-01 09:35
Regarding 1: I would recommend to report this to the Gradle integration that you might use in your IDE environment (probably Buildship here?!?)

Regarding 2: Maybe a network issue of the Marketplace had an issue? In case the problem persists, I would recommend to double check this with a regular and fresh Eclipse installation to see if the problem is specific to STS or not.

**Comment by aaguilera** [comment] 2018-10-01 10:33
This morning I had the same issue trying to access Eclipse Marketplace. Not it is working, so I'm pretty sure it was a Marketplace issue.

**Comment by rongflag** [comment] 2018-10-01 15:29
But I didn't use gradle, and I confirmed that Maven was used. So I can't find any reason.
![image](https://user-images.githubusercontent.com/35942815/46298514-d4926200-c5d1-11e8-8c6a-770145a7d1cd.png)

**Comment by kdvolder** [comment] 2018-10-01 17:19
> But I didn't use gradle, and I confirmed that Maven was used. So I can't find any reason

That is a little strange, but BuildShip is still installed so it might still be the source of the error. Can you find more details about the error like maybe a full stacktrace? It might be in the error log which you can open with 'Window >> Show View >> Other >> Error Log'.

**Comment by martinlippert** [comment] 2018-10-02 07:09
Ok, so the marketplace issue seems to be related to the marketplace server or network.

The message about the "gradle IncrementalProcessingEnvironment" looks like this one:

https://stackoverflow.com/questions/52598383/cant-get-the-delegate-of-the-gradle-incrementalprocessingenvironment-in-sts-4

Do you have Lombok installed, too?

**Comment by rongflag** [comment] 2018-10-02 08:34
yes  .
This is the "-javaagent:D:\develop\IDE\sts-4.0.0.RELEASE\lombok.jar" I added in the configuration file “SpringToolSuite4.ini”. I use the 1.18.2 version.  And I tried not to use lomok, and then there was no warn prompt.

**Comment by martinlippert** [comment] 2018-10-04 09:40
People using the Lombok project with Eclipse Photon (and probably later) reported this for Lombok already:

https://github.com/rzwitserloot/lombok/issues/1813

And it sounds like the edge build fixed the issue for them:

https://projectlombok.org/download-edge

Can you give that a try?

**Comment by martinlippert** [comment] 2018-10-06 09:00
As reported here on SO:

https://stackoverflow.com/questions/52598383/cant-get-the-delegate-of-the-gradle-incrementalprocessingenvironment-in-sts-4/52643484?noredirect=1#comment92248716_52643484

it looks like the new Lombok edge version solves this problem. Therefore closing this issue now.

**Closed by martinlippert** 2018-10-06 09:00 UTC

**Comment by rongflag** [comment] 2018-10-08 03:43
I'm sorry, I was traveling the other day, so the response was slow. I looked at it and it was probably settled. I'll try it after work today, and then give it back. Thank you.

**Comment by pawantiwari224** [comment] 2018-11-22 11:02
I got the same warnings. But I'm not using lambok in my project. I use maven as a build tool for my project. But still I get this warning
`Can't get the delegate of the gradle IncrementalProcessingEnvironment` 
Any suggestions.?

**Comment by martinlippert** [comment] 2018-11-22 14:15
Are you sure that you don't have the Lombok agent installed in your Eclipse/STS IDE (independent of your project using Lombok or not)

**Comment by pawantiwari224** [comment] 2018-11-23 08:15
@martinlippert I'm pretty sure of that.

**Comment by cedosw** [comment] 2018-11-24 08:00
I got those warnings as well. I´m using lombok version 1.18.4. Warnings disappear as soon as remove lombok dependency from my pom.xml.

For me the problem occur immediatly after creating a simple spring starter project with lombok.

I have a fresh installation of sts 4.0.1 with only the java 11 support plugin installed.

**Comment by pawantiwari224** [comment] 2018-11-29 05:20
@martinlippert I guess I've figured it out. I have installed Azure web toolkit to deploy the jar to Azure. After that, I'm getting that error. Since I created a new project with spring boot web and there was not such a warning. So I guess that was it.
