### ISSUE TITLE
There has been a Chinese annotation problem since STS3.9.5

### ISSUE THREAD

**Issue by yl-yue** [spring-projects/sts4#147] opened 2018-11-22 03:34 UTC
**environment**
STS4.0.1, JDK10, win10 1709

**question description one**
Chinese annotations are automatically indented.
It will only appear if the starting position is annotated in Chinese.
Strange Chinese annotation, as illustrated in following figure:
![image](https://user-images.githubusercontent.com/39790401/48880057-971bb980-ee49-11e8-93dd-191881ad7ab6.png)

**question description two**
The Chinese annotated font is automatically enlarged: 
![image](https://user-images.githubusercontent.com/39790401/48884587-15835600-ee60-11e8-9f9e-2183f7a33fd4.png)

**Comment by martinlippert** [comment] 2018-11-22 14:34
Seems like the same issue as described here: https://github.com/spring-projects/spring-ide/issues/319 - closing this one as a duplicate of the other one. And please re-test this with a plain Eclipse installation so see if this is STS-specific or not.

**Closed by martinlippert** 2018-11-22 14:34 UTC

**Comment by zxbfriend** [comment] 2019-03-31 04:09
This problem has persisted since STS 4.x。chinese

**Comment by martinlippert** [comment] 2019-04-02 15:32
@zxbfriend did you take a look at the referenced bug description mentioned above? It contains more details that this one and it also sounds like someone found a workaround for this. But anyhow, this seems to be more of a general Eclipse platform or java tooling issue that anything specific for the Spring tools. So in case the workaround doesn't work for you, please try this with a vanilla Eclipse 2019-03 installation, just to verify that this problem is related to the Eclipse platform - or not.

**Comment by yl-yue** [comment] 2019-04-04 01:18
@zxbfriend @martinlippert 
中文：
这是一个通用eclipse平台出现的问题和spring提供的插件无关。
相关问题目前已提上日程，等待eclipse社区的修复。
如有必要这个临时解决方案可供参考：
https://blog.csdn.net/u013600314/article/details/85262257
---
English:
This is a generic eclipse platform issue that has nothing to do with the plug-ins provided by spring.Related issues are currently on the agenda, waiting to be fixed by the eclipse community.This temporary solution is available for reference if necessary:
https://blog.csdn.net/u013600314/article/details/85262257
