### ISSUE TITLE
JMX connection issues when using OpenJDK Java 11/OpenJ9 runtime in STS 4.0.1

### ISSUE THREAD

**Issue by tjstuart** [spring-projects/sts4#138] opened 2018-11-13 23:32 UTC
I wasn't sure how best to title this issue as not entirely sure what exactly is at fault, though it does appear to only manifest in STS.  It could however could be an Eclipse issue.

**Environment**

- Windows 10, 64bit
- STS 4.0.1 (launched via Java 8 Oracle JDK)
- Trivial Spring Boot 2.1.0 app with one Controller (see attached OpenJ9.zip)
- Embedded Tomcat with below runtime JRE
- OpenJDK11-jre_x64_windows_openj9_11.0.1_13 from https://adoptopenjdk.net/installation.html

**Observations**

1. After starting the app in STS via the Boot Dashboard, the "working" spinner never changes to the green "up arrow".  I guess some signal or status is not detected by STS.  Note that the app appears to start OK.

2. When stop the app via the Boot Dashboard, `HttpSessionListener.sessionDestroyed()` does not fire.  Other events may also not be firing, but this is the most obvious to me.

Above is observed only in STS.  When run the app as a JAR externally with OpenJ9, all works as it should.  

There is no issue with OpenJDK HotSpot VM.

I am not sure if the issue manifests in other application servers (non Tomcat) or older versions of STS.

**Repro**

- See attached trivial SB 2.1.0 project in OpenJ9.zip
- Run it with above mentioned OpenJ9 VM
- Note the spinner never changes in Boot Dashboard
- Hit the root, it will say "Hello session-id"
- Stop the app
- Missing log statement from `SessionListener.java` "Session session-id destroyed"

**Attachments**

[OpenJ9.zip](https://github.com/spring-projects/sts4/files/2578527/OpenJ9.zip)

![image](https://user-images.githubusercontent.com/19812676/48449941-5217d780-e7f8-11e8-9df7-968ae1b19daa.png)

**Comment by kdvolder** [comment] 2018-11-14 17:20
At first sight, I'd say something is going wrong with the JMX connection we use to detect whether the app is started/ready and also used to request the boot app to shutdown gracefully. Without looking any deeper, it is hard to be sure of this. But that explanation seems to be consistent with all the facts:

- app seems to start fine
- STS 'spinner' doesn't notice the app is 'ready'
- App doesn't shutdown gracelfully (some events you expected aren't happening which probably means process got killed forcibly because the 'graceful termination request' wasn't obeyed in reasonable time.

**Comment by martinlippert** [comment] 2018-11-15 08:41
There is an important note mentioned here, we need to double check whether we set all the necessary options when starting up the app:

https://github.com/eclipse/openj9/issues/629#issuecomment-345747344

**Comment by tjstuart** [comment] 2018-11-18 23:50
I tried the suggestions in the above referenced issue, but no luck.  Passed various combinations via the "VM Arguments" to OpenJ9 run config.  Same result.  Happy to try anything else if anyone has any suggestions.

**Comment by kdvolder** [comment] 2018-11-19 17:09
@tjstuart Thanks for trying things. I will try a few things myself today and the information you have posted will be very helpful :-)

**Comment by kdvolder** [comment] 2018-11-19 20:11
I tried to reproduce this on Linux but things seem to work fine. I'll see if I have more "luck" on a Windows VM.

**Comment by kdvolder** [comment] 2018-11-19 23:55
No luck reproducing on Windows VM. When I try to launch with OpenJ9 it crashes with some nasty segmentation fault before it does anything. I tried both the JDK/JRE with same result.

I also tried OpenJDK and that launched fine. 

Not really sure why I can't launch the boot app with openJ9. I'm not too familiar with running things in OpenJ9 / Windows, so maybe I did something wrong. 

Error I am getting is this:

```
Unhandled exception
Type=Segmentation error vmState=0x00040000
Windows_ExceptionCode=c0000139 J9Generic_Signal=00000004 ExceptionAddress=00007FFF7EA999B8 ContextFlags=0010000f
Handler1=00007FFF73486020 Handler2=00007FFF71AAECA0
RDI=00007FFF7EB103B0 RSI=0000015EEFA5E058 RAX=0000000000000000 RBX=00000000C0000139
RCX=0000000070690000 RDX=00007FFF7EB148B0 R8=0000000000000000 R9=000000007FFE0384
R10=0000000000000002 R11=000000007FFE0385 R12=0000000000000003 R13=0000000000000000
R14=0000015EEFA5E058 R15=0000000000000003
RIP=00007FFF7EA999B8 RSP=00000010D3CFBE50 RBP=00000010D3CFC4F0 GS=002B
FS=0053 ES=002B DS=002B
XMM0 00000010d3cfc1c0 (f: 3553608192.000000, d: 3.570765e-313)
XMM1 00007fff7eb14648 (f: 2125547136.000000, d: 6.953249e-310)
XMM2 00007fff7eb14610 (f: 2125547008.000000, d: 6.953249e-310)
XMM3 0000015eedbe4ed0 (f: 3988672256.000000, d: 7.446692e-312)
XMM4 00000010d3cfc510 (f: 3553608960.000000, d: 3.570765e-313)
XMM5 00007fff7eb14648 (f: 2125547136.000000, d: 6.953249e-310)
XMM6 00000010d3cfe7f0 (f: 3553617920.000000, d: 3.570765e-313)
XMM7 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM8 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM9 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM10 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM11 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM12 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM13 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM14 0000000000000000 (f: 0.000000, d: 0.000000e+00)
XMM15 0000000000000000 (f: 0.000000, d: 0.000000e+00)
Module=C:\WINDOWS\SYSTEM32\ntdll.dll
Module_base_address=00007FFF7EA00000 Offset_in_DLL=00000000000999b8
Target=2_90_20181020_83 (Windows 10 10.0 build 10240)
CPU=amd64 (4 logical CPUs) (0x1fff8d000 RAM)
----------- Stack Backtrace -----------
```

**Comment by kdvolder** [comment] 2018-11-20 00:08
Weird, after restarting the windows VM I'm not longer getting the segmentation fault. The sample app starts up fine, including the ready state detecting in STS. So still no luck reproducing this.

For reference, this is what I did to set everything up.

- Downloaded and installed STS nightly for Eclipse 4.9 for windows from here: http://dist.springsource.com/snapshot/STS4/nightly-distributions.html

- Running STS with JDK 8 that was installed on my windows VM (so not using JDK 11 to run STS).

- Installed Java 11 support for Eclipse 4.9 from the Eclipse marketplace

- Downloaded Open J9 JDK 11 from the link you posted above

- Configured the Open J9 JDK as a 'workspace JRE'

- Imported OpenJ9.zip project as a 'existing maven project'.

- Changed the java.version property in the pom.xml from `1.8` into `11`.

- Execute 'Update Maven Projects' on the project to update JRE / classpath to use JDK 11.

- Double-check the JRE enttry on classpath is now pointing to a Java 11.

- Run the app from the boot dash by clicking start button.

=> starts up fine (at least when the openJ9 doesn't outright crash with segfault first).

If you are seeing any difference in the steps, you can add some comments and maybe I can try again. 

In the mean time, I'll close the ticket as 'cannot reproduce'. But we can always re-open it later.

**Comment by BobVul** [comment] 2018-11-20 04:58
I managed to reproduce, but only when targeting the OpenJ9 11 **JRE**. I did not get any segfaults. Tested with sts-4.0.2.CI-B1364 on Windows 10 v1803.

Specifically:

| STS JDK | Runtime JDE/JRE | Works |
| --- | --- | --- |
|Oracle Java 8 Update 131 JDK|AdoptOpenJDK OpenJ9 11.0.1+13 **JDK**|✅|
|Oracle Java 8 Update 131 JDK|AdoptOpenJDK OpenJ9 11.0.1+13 **JRE**|❌|
|Oracle Java 8 Update 191 JDK|AdoptOpenJDK OpenJ9 11.0.1+13 **JDK**|✅|
|Oracle Java 8 Update 191 JDK|AdoptOpenJDK OpenJ9 11.0.1+13 **JRE**|❌|
|AdoptOpenJDK OpenJ9 11.0.1+13 JDK|AdoptOpenJDK OpenJ9 11.0.1+13 **JDK**|✅|
|AdoptOpenJDK OpenJ9 11.0.1+13 JDK|AdoptOpenJDK OpenJ9 11.0.1+13 **JRE**|❌|


<sub>I work with @tjstuart.</sub>

**Comment by kdvolder** [comment] 2018-11-20 17:19
Okay thanks for the extra info. I'll give it another try specifically focusing on targeting Java 11 JRE. Reopening ticket.

**Comment by kdvolder** [comment] 2018-11-20 18:44
Alas, my windows VM doesn't want to launch the openj9 jre at all today. All I get is segmentation fault. Yesterday, rebooting seemed to help but not today. So I'm a bit stuck at the moment trying to reproduce this.

**Comment by tjstuart** [comment] 2018-11-20 22:31
All good, issue is not a showstopper by any means, and can target the OpenJ9 JDK in STS as my colleague @BobVul discovered.  In the meantime, if you have anything you want us to try, we are happy to do so.

**Comment by kdvolder** [comment] 2019-02-15 23:41
Finally circling back to this. I am no longer plagued by the segmentation fault, seems OpenJ9 fixed this after I reported it. Trying with latest openj9 jre (jdk8u202-b08-jre) everything seems to be working fine. Boot app launches correctly and the 'spinner' state in the dashboard also is updated correctly.

I'm going to close this as 'cannot reproduce' again.

If you are still having issues... about the only thing that comes to mind is that it might be some issue around permission in the tmp folder. Part of the JMX machinery depends on jvm processes being able to create files / folders in there. I don't know exactly how this works (it is part of JVM behavior not something we implemented ourselves). But I did have problems with this myself at one point using Oracle JDK/JRE on Windows. So this might be a similar thing. 

Here's some info that may help: 

https://stackoverflow.com/questions/3805376/jps-returns-no-output-even-when-java-processes-are-running

Note that this is for `jps` but the mechanic that jps uses to detect process and connect to them is the same. (So another test you can do is see if you can see your processes with tools like jps, jstack and jconsole).

Anyhow, if you are having still issues with this, I think it may be something specific about your setup than something STS itself is doing wrong. If you find out anytthing else that seems to indicate otherwise feel free to post it here and we can always take another look.

**Comment by spring-issuemaster** [comment] 2019-02-15 23:44
(comment in Pivotal Tracker added by Kris De Volder:) 

Tried this again and still not able to reproduce it. Closing / Delivering ticket.

**Comment by spring-issuemaster** [comment] 2019-02-20 11:04
(comment in Pivotal Tracker added by Martin Lippert:) 

I also tried this again on a Windows 10 machine and the results are a bit strange. When executing the boot app with jdk-1.8.0_191, everything is just fine. When running with OpenJ9-JDK, the live hovers do not show up, but the arrow up in the dashboard appears. When starting the app with OpenJ9-JRE, the arrow never shows up in the dashboard and the live hovers don't work either.

**Comment by spring-issuemaster** [comment] 2019-02-20 11:07
(comment in Pivotal Tracker added by Martin Lippert:) 

The good thing here is that I can reproduce this on my Mac, too... :-)

**Comment by spring-issuemaster** [comment] 2019-02-20 11:27
(comment in Pivotal Tracker added by Martin Lippert:) 

OK, so from my additional testing, it looks like there is an issue with the way the language server tries to identify the running java processes. It looks like the JDK that is used to run the language server can only find processes that use a similar JDK in terms of HotSpot vs. OpenJ9.

So if the IDE runs on top of a HotSpot-based JDK, it can't find the apps that are started using an OpenJ9-based JDK and vice versa.

This makes it pretty difficult for us to solve this situation, since there is a clear distinction between the JVM that is used to run the IDE (and therefore the anguage server) and the JVM that is used by the user to run their apps from within the IDE - and this distinction makes a lot of sense. We should not requite people to run their IDE on a specific JVM just to allow the language server to find the user-started apps.

I will raise an issue with the OpenJ9 team to further investigate this.

**Comment by martinlippert** [comment] 2019-02-22 13:22
Ok, according to this comment:
https://github.com/eclipse/openj9/issues/4799#issuecomment-465588376

I don't see a way for us to implement the cross-JVM process discovery. As a workaround, you could define the JMX connection parameters for the process that you want to let the tooling connect to via the manual JMX connection option in STS4.

Closing this again.

If you come across issues using OpenJ9 in addition to what has already been discussed, let me know.

**Closed by martinlippert** 2019-02-22 13:22 UTC
Labels: unstarted
