### ISSUE TITLE
Child Project can not auto complete application.yml and application. properties but only one project yes

### ISSUE THREAD

**Issue by successismyonlyway** [spring-projects/sts4#1054] opened 2023-06-12 05:39 UTC
[Error - 1:29:41 PM] Stopping server failed
Error: Stopping the server timed out
	at c:\Users\15162\.vscode\extensions\vmware.vscode-spring-boot-1.47.2023061004\node_modules\vscode-languageclient\lib\common\client.js:933:23
	at runNextTicks (node:internal/process/task_queues:61:5)
	at process.processTimers (node:internal/timers:499:9)
[Error - 1:29:41 PM] Stopping server failed
Error: Stopping the server timed out
	at c:\Users\15162\.vscode\extensions\vmware.vscode-spring-boot-1.47.2023061004\node_modules\vscode-languageclient\lib\common\client.js:933:23
	at runNextTicks (node:internal/process/task_queues:61:5)
	at process.processTimers (node: internal/timers:499:9)

**Comment by successismyonlyway** [comment] 2023-06-12 10:25
for vscode

**Comment by BoykoAlex** [comment] 2023-06-12 14:45
Do you mind attaching a sample a project and a few steps to reproduce the issue? 

I have. tried opening sts4 project itself in vscode, found `application.properties` file under `spring-boot-language-server` project opened it and tried completions in the editor - seemed to work for me.

**Comment by successismyonlyway** [comment] 2023-06-12 15:02
> Do you mind attaching a sample a project and a few steps to reproduce the issue?
> 
> I have. tried opening sts4 project itself in vscode, found `application.properties` file under `spring-boot-language-server` project opened it and tried completions in the editor - seemed to work for me.

I have found that spring initializer created project is same.

**Comment by successismyonlyway** [comment] 2023-06-12 15:03
Stopping the server timed out
	at c:\Users\15162\.vscode\extensions\vmware.vscode-spring-boot-1.47.2023061004\node_modules\vscode-languageclient\lib\common\client.js:933:23

**Comment by successismyonlyway** [comment] 2023-06-12 15:04
![image](https://github.com/spring-projects/sts4/assets/60887371/e554117f-8c3a-409f-b740-0be371dfc10d)

**Comment by successismyonlyway** [comment] 2023-06-12 15:04
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.1.0</version>
		<relativePath/> 
	</parent>
	<groupId>com.example</groupId>
	<artifactId>demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>demo</name>
	<description>Demo project for Spring Boot</description>
	<properties>
		<java.version>17</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-configuration-processor</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<excludes>
						<exclude>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
						</exclude>
					</excludes>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>

**Comment by successismyonlyway** [comment] 2023-06-12 15:05
![image](https://github.com/spring-projects/sts4/assets/60887371/b6002e75-3679-4231-a2cc-dd26bc34a24d)

**Comment by successismyonlyway** [comment] 2023-06-12 15:06
<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.1.0</version>
		<relativePath/> 
	</parent>
	<groupId>com.example</groupId>
	<artifactId>demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>demo</name>
	<description>Demo project for Spring Boot</description>
	<properties>
		<java.version>17</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-configuration-processor</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

**Comment by successismyonlyway** [comment] 2023-06-12 15:07
`
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.1.0</version>
		<relativePath/> 
	</parent>
	<groupId>com.example</groupId>
	<artifactId>demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>demo</name>
	<description>Demo project for Spring Boot</description>
	<properties>
		<java.version>17</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-configuration-processor</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<excludes>
						<exclude>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
						</exclude>
					</excludes>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>

`

**Comment by successismyonlyway** [comment] 2023-06-12 15:16
> Do you mind attaching a sample a project and a few steps to reproduce the issue?
> 
> I have. tried opening sts4 project itself in vscode, found `application.properties` file under `spring-boot-language-server` project opened it and tried completions in the editor - seemed to work for me.

![image](https://github.com/spring-projects/sts4/assets/60887371/334bc259-92b1-4d41-9c0e-a6be51026f49)
Seems like this, a Parent project that packing pom and no any code and only affects dependency version management and extends spring-boot-start-parent.
Child projects do not extend spring-boot-start-parent but extend parent project.

**Comment by successismyonlyway** [comment] 2023-06-12 15:18
> Do you mind attaching a sample a project and a few steps to reproduce the issue?
> 
> I have. tried opening sts4 project itself in vscode, found `application.properties` file under `spring-boot-language-server` project opened it and tried completions in the editor - seemed to work for me.

![image](https://github.com/spring-projects/sts4/assets/60887371/e476dcb4-caae-4783-adbe-7ed16d1572a4)

**Comment by BoykoAlex** [comment] 2023-06-13 15:19
It is fixed with this PR: https://github.com/openrewrite/rewrite-static-analysis/pull/122. We need to wait until the JAR is published and then it'd be fixed for us too.
Essentially, any sys out calls in Boot LS or its dependencies corrupt JSON RPC comm between ls and the client since the comm is via standard in/out of the ls process. The comm expect only json messages with proper headers.

**Comment by BoykoAlex** [comment] 2023-06-13 19:02
Should be fixed now

**Closed by BoykoAlex** 2023-06-13 19:02 UTC
Labels: type: bug, for: vscode
