### ISSUE TITLE
can not navigate jar class source code

### ISSUE THREAD

**Issue by user20161119** [spring-projects/sts4#257] opened 2019-03-21 08:32 UTC
I can navigate Class from project to jar file,but can not navigate Class in jar (Ctrl + click).
![image](https://user-images.githubusercontent.com/123967/54740597-d939e980-4bf6-11e9-85b2-3673377609fb.png)

**Comment by martinlippert** [comment] 2019-03-21 08:58
this is a duplicate of #205

**Closed by martinlippert** 2019-03-21 08:58 UTC
