### ISSUE TITLE
Fix to close and explain the purpose of the "Call Hierarchy" and "Type Hierarchy" views at "Others"

### ISSUE THREAD

**Issue by manueljordan** [spring-projects/sts4#1352] opened 2024-09-11 15:14 UTC
For STS 4.23.1 

doing the following

* _Window_ -> _Show View_ -> _Java_

is possible to open the two following views

* Call Hierarchy
* Type Hierarchy

From them some observations:

1. I know how to use each one
2. Each one has an icon as green 
3. Is possible to close each one through the 'x' icon

Now due the following post:

* https://github.com/spring-projects/sts4/issues/1351

I did do realize the following that at:

* _Window_ -> _Show View_ -> _Others_

Exists and is possible to open the two following views

* Call Hierarchy
* Type Hierarchy

From them some observations:

1. What are their purpose?
2. Each one has an icon as "yellow"
3. Is **not** possible to close each one through the 'x' icon - _is it a bug right?_ Pls indicate me how to close each one :(

Therefore is confuse the existence of this pair repeated

```
Window_ -> Show View -> Java
 Call Hierarchy
 Type Hierarchy
Window_ -> Show View -> Others
 Call Hierarchy
 Type Hierarchy
```

Thanks for your understanding

**Comment by manueljordan** [comment] 2024-09-11 15:19
To close each one so far the workaround approach is:

* right click in the view -> detach -> close

**Comment by martinlippert** [comment] 2024-09-13 08:25
I don't see `Call Hierarchy` nor `Type Hierarchy` views in the `Other` category when running a plain vanilla Spring Tools for Eclipse distribution, so it seems to be like those views come from another plugin/extension that you have installed in your IDE.

If you have a standard Spring Tools for Eclipse installation running, you can select the view and press `Alt` + `Shift` + `F1` to inspect that element and see where this element comes from.

**Comment by manueljordan** [comment] 2024-09-15 16:19
Hello Martin

> I don't see Call Hierarchy nor Type Hierarchy views in the Other category when running a plain vanilla Spring Tools for Eclipse distribution,

Yes, It is correct. I've tested for 4.25.0

>  so it seems to be like those views come from another plugin/extension that you have installed in your IDE.

Yes it is correct. I installed for the 4.25.0 from the scratch the 2 following plugins one by one and checking the `Others` view:

* AnyEdit Tools
* Darkest Dark Theme with DevStyle

Therefore the second is the cause of this situation

> If you have a standard Spring Tools for Eclipse installation running, you can select the view and press Alt + Shift + F1 to inspect that element and see where this element comes from.

Very interesting and useful that keyboard shortcut. Now, what to do? Close this issue?

Apart: could you consider in add for "each" view of the IDE the option to see the same report but by right click? (Contextual Menu) I am doing this question because I tried the keyboard shortcut through a remote desktop (Remmina) and didn't work. It worked in the same laptop - thus if it has sense for you indicate me if I should create a new issue to request that feature .

Thanks for your understanding

**Comment by martinlippert** [comment] 2024-09-16 09:26
Since the issue that you originally described is not caused by the Spring Tools and can't be fixed as part of the Spring Tools, we should close this issue and you should report that to the authors of the `Darkest Dark Theme` extension that is causing the issue.

With regards to the plugin spy tool, you can ask the PDE project for that change/addition: https://github.com/eclipse-pde/eclipse.pde - or you could implement that yourself and submit a PR.

**Closed by martinlippert** 2024-09-16 09:26 UTC
Labels: status: waiting-for-feedback, for: eclipse, type: install-issue
