### ISSUE TITLE
Unable launch project: NPE

### ISSUE THREAD

**Issue by 452** [spring-projects/sts4#418] opened 2020-03-11 16:17 UTC
https://youtu.be/5YxHK5yQGjA
Spring Tool Suite 4 
Version: 4.5.1.RELEASE
Build Id: 202001211336

```
!ENTRY org.eclipse.core.jobs 4 2 2020-03-11 18:10:45.373
!MESSAGE An internal error occurred during: "Launching Operational".
!STACK 0
java.lang.NullPointerException
	at org.springframework.ide.eclipse.boot.launch.AbstractBootLaunchConfigurationDelegate.configureClassPathProviders(AbstractBootLaunchConfigurationDelegate.java:377)
	at org.springframework.ide.eclipse.boot.launch.AbstractBootLaunchConfigurationDelegate.launch(AbstractBootLaunchConfigurationDelegate.java:359)
	at org.springframework.ide.eclipse.boot.launch.BootLaunchConfigurationDelegate.launch(BootLaunchConfigurationDelegate.java:155)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:860)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:719)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1017)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$2.run(DebugUIPlugin.java:1220)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by kdvolder** [comment] 2020-03-11 17:50
I've added a null check to avoid the NPE. 

It seems like for some reason the project for the launch config is 'null'. 

I don't know why this may be. Maybe the project was deleted, closed or renamed or something like that. Anyway, the NPE should not happen and seems very disruptive. Even if the launch config is broken there should be no NPE like this. So adding a null check makes good sense.

However, that doesn't mean this will make the underlying problem go away. Whatever reason the project is not known probably means the launch config can never be properly launched. Something is wrong with the launch configuration. My suggestion to you would be to simply delete that particular launch configuration (it should be recreated when you launch the same project again). That will probably solve the problem for you. 

If you have any idea how the launch config got broken we could try to address that problem somehow directly (e.g. do you remember doing something that changes project name?). Until we know what causes the 'corrupted/invalid' launch config we can't fix the root cause.

**Comment by martinlippert** [comment] 2021-02-16 13:30
Looks like this got fixed up to a certain degree already for Spring Tools 4 for Eclipse 4.6.0, so I am closing this one now. If you come across this again, please try to add a few more details about the launch config, so that we can analyze the corrupted state of it in a bit more detail. Thanks!!!

**Closed by martinlippert** 2021-02-16 13:30 UTC
Labels: type: bug
