### ISSUE TITLE
docker not supported in vscode manifest extension

### ISSUE THREAD

**Issue by cheahkhing** [spring-projects/sts4#302] opened 2019-05-29 14:45 UTC
Unknown property 'docker' for type 'Application'.

According to [https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html#docker](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html#docker), docker should be supported.

**Comment by kdvolder** [comment] 2019-07-23 17:07
I'm closing this as a duplicate of this other issue which covers the same problem:

https://github.com/spring-projects/sts4/issues/330

**Comment by kdvolder** [comment] 2019-07-23 17:10
Sorry... I jumped to the wrong conclusion there. The issues are similar but distinct. This one is about the CF manifest editor, whereas the other one is about the CF resource in the Concourse editor.

**Closed** 2019-07-29 13:10 UTC
Labels: delivered
