### ISSUE TITLE
Can't use clipboard to/from outside STS under swaywm (linux)

### ISSUE THREAD

**Issue by rdady** [spring-projects/sts4#840] opened 2022-09-10 18:41 UTC
**Describe the bug**
Fedora 36 + swaywm (wayland)
Control+C Control+V Control+X content coming from other application or wanting to copy from STS into other application has no effect. Although it works in KDE Plasma wayland session.

**To Reproduce**
Choose swaywm at linux login, start STS.
Copy from e.g. Firefox/terminal anything, try to paste with Control+V, nothing happens.
If previously copied something from STS to clipboard you can expect this to be pasted instead of correct content.
Same effect for clipboard and primary as well.

**Sample**
NA

Spring Tool Suite 4 
Version: 4.15.3.RELEASE
Build Id: 202208110744

**Comment by martinlippert** [comment] 2022-09-14 05:48
Thanks for reporting this @rdady. This sounds like an issue on the IDE platform level that we leverage, so would it be possible for you to verify that in your environment by trying a plain vanilla Eclipse installation to see if the issue is specific for the Spring Tools distribution or a general issue with Eclipse on your system platform? That would be awesome.

**Comment by rdady** [comment] 2022-09-16 19:01
Your are right. Same disability in fresh Eclipse as well.
It must be a special behaviour of some key binding I was not able to resolve.
But why would Eclipse set that as default, make the clipboard functionality a mess ? - Retorical question.

**Comment by martinlippert** [comment] 2022-09-19 06:17
@rdady Thanks for testing this on a vanilla Eclipse installation and for verifying that this seems to be related to the platform and it nothing specific to the Spring Tools. I would recommend to file the issue against the Eclipse platform then and we close this one here as a duplicate then.

**Closed** 2023-02-24 15:30 UTC
Labels: status: waiting-for-feedback, type: bug, for: eclipse
