### ISSUE TITLE
Java process remains after vscode has been closed

### ISSUE THREAD

**Issue by Feichtmeier** [spring-projects/sts4#646] opened 2021-06-10 14:18 UTC
**Describe the bug**
The additional java process spawned for the vscode spring boot extension remains after vscode has been closed

**To Reproduce**
1) Open and/or create a spring boot project with vscode with this extension installed
2) Close vscode
3) See a java process pointing to this very extension remaining 

vscode version: 1.65.2
spring boot tools version: v1.25.1
java version: open-jdk11
operating system: Ubuntu 21.04

![Peek 2021-06-10 16-10](https://user-images.githubusercontent.com/15329494/121541249-6d2a4280-ca07-11eb-88df-169f5d47adc4.gif)

Thanks for developing this awesome extension!

**Comment by martinlippert** [comment] 2021-06-10 16:57
Closing as duplicate of #636. This is fixed for the upcoming release. Feel free to install nightly build via the VSIX file provided here to double check: http://dist.springsource.com/snapshot/STS4/nightly-distributions.html

**Closed by martinlippert** 2021-06-10 16:57 UTC
Labels: for: vscode, status: duplicate, type: bug

**Comment by Feichtmeier** [comment] 2021-06-10 18:11
> 
> 
> Closing as duplicate of #636. This is fixed for the upcoming release. Feel free to install nightly build via the VSIX file provided here to double check: http://dist.springsource.com/snapshot/STS4/nightly-distributions.html

Oh! Awesome - thanks for the info! 🥳
