### ISSUE TITLE
Bug In menu.

### ISSUE THREAD

**Issue by OmyPanwar** [spring-projects/sts4#1319] opened 2024-08-11 05:12 UTC
After installing the latest version of the Spring Tools 4 plugin on Eclipse 2023-09, the "Source" menu is duplicated when a Java source file is opened.**Describe the bug**

![SharedScreenshot](https://github.com/user-attachments/assets/abd7b609-b222-4301-82b3-d3d7feb30cc5)

**Comment by BoykoAlex** [comment] 2024-08-11 14:15
This lilekely to the old version of LSP4E present in 2023-09 Eclipse. The issue in later LSP4E versions has been fixed. Try installing Spring Tools 4 plugin into some 2024 Eclipse...

**Comment by martinlippert** [comment] 2024-08-12 09:34
Very likely a duplicate of https://github.com/spring-projects/sts4/issues/1111.
@OmyPanwar Can you double check the version of the plugin `org.eclipse.lsp4e` to verity? It should be `org.eclipse.lsp4e_0.18.3.202401311302` or newer.

As a side note: The latest version of the Spring Tools for Eclipse is not available nor compatible with Eclipse 2023-09 anymore. The latest version supports Eclipse 2024-06 and 2024-03.

**Closed** 2024-08-19 12:27 UTC
Labels: type: bug, for: eclipse, status: duplicate
