### ISSUE TITLE
Shortcut key not working in release 4.14.0.RELEASE

### ISSUE THREAD

**Issue by shankarwww** [spring-projects/sts4#746] opened 2022-03-22 19:15 UTC
In the 4.14.0.RELEASE, shortcut key like rename-refactoring(Alt+Shift+R) is not working.  Open a class, select a method or class name to rename, some other dialog box is getting opened. The was issue in 4.13.0.RELEASE too where window use to shake when u try Alt+Shift+R.

**Comment by imtiaz-rahi** [comment] 2022-03-23 12:34
I am also facing this issue and can confirm this. unable to rename anything in Java sources.

**Comment by ThomasD281** [comment] 2022-03-24 06:37
I am having this issue also on a Mac. For me it is not working since the update to STS 4.14. Settings should be correct - see image
<img width="927" alt="settings" src="https://user-images.githubusercontent.com/30520882/159856941-5c66ea8b-bcb1-417e-a0a6-fb7612fe2907.png">
e

**Comment by mweirauch** [comment] 2022-03-24 07:18
Can confirm on Linux, Eclipse 20220310-1457 with STS addon site. I even had a conflict with "Rename" in category "File" and "Rename - Refactoring" in category "Refactor - Java" on "Shift + Alt + R", but didn't help to resolve this.

**Comment by martinlippert** [comment] 2022-03-24 09:11
Is this behavior different from a plain Eclipse installation?

**Comment by ThomasD281** [comment] 2022-03-24 10:23
> Is this behavior different from a plain Eclipse installation?

Yes, for me in eclipse Version: 2022-03 (4.23.0) with the default key settings the renaming shortcut is working

**Comment by martinlippert** [comment] 2022-03-24 10:47
@ThomasD281 Which exact distribution of Eclipse? On which OS? And what exact keybinding on your system? Asking to be able to understand and reproduce this exactly... :-)

**Comment by ofornes-basecat** [comment] 2022-03-24 11:16
The shortcut doesn't work, yes, but if select with left-button over class name, parameter, property or variable, and entry 'refactor->rename' the renaming operation itself doesn't work. An error is produced.

But only if select renaming on editor file. If select renaming classes from project explorer, all will be fine.
Attach the log for error I was get.
[Untitled.log](https://github.com/spring-projects/sts4/files/8340961/Untitled.log)

**Comment by martinlippert** [comment] 2022-03-24 11:24
@ofornes-basecat This sounds/looks like a slightly different problem. Is this an upgraded instance of STS4? The error log that you attached is pointing into a direction where multiple versions of JDT types are around, so I am wondering what might have caused this.

Question to all here:
Are you all running an upgraded version or does this happen with a fresh and clean install of STS 4.14.0.RELEASE as well? And if so, is there also an error showing up somewhere or is this purely the key binding not working?

**Comment by imtiaz-rahi** [comment] 2022-03-24 12:48
> @ThomasD281 Which exact distribution of Eclipse? On which OS? And what exact keybinding on your system? Asking to be able to understand and reproduce this exactly... :-)


I have been having this problem for last 1 month (STS 4.9.0.RELEASE-e4.18.0) surely and upgraded to STS 4.14.0 yesterday and yet the problem persisted. So, tried by downloading STS 4.14.0 on Eclipse 4.23.0 and still problem exists.

**Comment by ThomasD281** [comment] 2022-03-24 13:03
> Question to all here: Are you all running an upgraded version or does this happen with a fresh and clean install of STS 4.14.0.RELEASE as well? And if so, is there also an error showing up somewhere or is this purely the key binding not working?

Running upgraded version of STS from 4.13.1 to 4.14.0 on mac os. Error log when pressing shortcut for refactor -> rename in java source window see attached log
[error.log](https://github.com/spring-projects/sts4/files/8341629/error.log)

**Comment by martinlippert** [comment] 2022-03-24 13:27
@ThomasD281 This looks like the same error as @ofornes-basecat reported above, but I am still puzzled why that happens or how to reproduce that. Installed a fresh STS 4.13.1 release on my machine (macOS), upgraded to 4.14.0, but the keyboard shortcut (Cmd-Alt-R) still works when the cursor is, for example, on a class name in the Java editor.

Can you open a Console view, then choose "Host OSGi Console" from the drop-down, and type in `ss` (for short status) and press enter. It lists all the running plugins in your installation. Then, look for all plugins/bundles with the name `org.eclipse.jdt.core` and `org.eclipse.jdt.ui`. Can you paste the details of those installed bundles? Are there multiple versions of those bundles around?

**Comment by ThomasD281** [comment] 2022-03-24 13:51
found only these 2:
704	STARTING org.eclipse.jdt.core.formatterapp_1.1.0.v20210618-1653
1324 ACTIVE org.eclipse.jdt.core.manipulation_1.16.0.v20220214-0655

**Comment by martinlippert** [comment] 2022-03-24 14:03
This is just a wild guess... From the installed bundles, everything looks fine, right versions of JDT are installed, so there no reason why the exception that you see in the logs should appear. I know that Lombok modifies JDT core at load time, therefore that could be an explanation (if you have the Lombok extension installed in your `.ini` file).

**Comment by ThomasD281** [comment] 2022-03-24 14:07
> Do you have Lombok installed/added to your IDEs?

yes

**Comment by martinlippert** [comment] 2022-03-24 14:26
The issue is already filed and marked as fixed on Lombok: https://github.com/projectlombok/lombok/issues/3134 - fix version seems to be `1.18.24`. So closing this one here as a duplicate of the Lombok issue.

In case someone runs across this issue without Lombok being involved, please comment and we can re-open or create a new issue for that.

**Closed by martinlippert** 2022-03-24 14:26 UTC
Labels: type: bug, for: eclipse

**Comment by ThomasD281** [comment] 2022-03-24 14:33
> Ok, can you uninstall Lombok and try again?

uninstalling lombok and shortcut works again. thx for the help ...

**Comment by imtiaz-rahi** [comment] 2022-03-24 14:46
> Can confirm on Linux, Eclipse 20220310-1457 with STS addon site. I even had a conflict with "Rename" in category "File" and "Rename - Refactoring" in category "Refactor - Java" on "Shift + Alt + R", but didn't help to resolve this.

found same (running Ubuntu). resolved conflict but no joy.

**Comment by imtiaz-rahi** [comment] 2022-03-24 14:52
> Ok, can you uninstall Lombok and try again?

Just installed latest lombok "v**1.18.23** "Edgy Guinea Pig" - 2022-03-16" from [here](https://github.com/projectlombok/lombok/issues/3134#issuecomment-1074778735) and it worked. Thanks a lot.

**Comment by ofornes-basecat** [comment] 2022-03-25 06:49
> @ofornes-basecat This sounds/looks like a slightly different problem. Is this an upgraded instance of STS4? The error log that you attached is pointing into a direction where multiple versions of JDT types are around, so I am wondering what might have caused this.
> 
> Question to all here: Are you all running an upgraded version or does this happen with a fresh and clean install of STS 4.14.0.RELEASE as well? And if so, is there also an error showing up somewhere or is this purely the key binding not working?

I use an upgrade version of STS. The original was sts-4.13.1.RELEASE

**Comment by ofornes-basecat** [comment] 2022-03-25 06:51
> Do you have Lombok installed/added to your IDEs?

@martinlippert Yes, I have added lombok installed in my IDE

**Comment by ofornes-basecat** [comment] 2022-03-25 07:02
I can confirm that lombok agent is the problem. Under the same context but without lombok agent, all works like a charm

**Comment by ofornes-basecat** [comment] 2022-03-25 10:12
> @ofornes-basecat This sounds/looks like a slightly different problem. Is this an upgraded instance of STS4? The error log that you attached is pointing into a direction where multiple versions of JDT types are around, so I am wondering what might have caused this.
> 
> Question to all here: Are you all running an upgraded version or does this happen with a fresh and clean install of STS 4.14.0.RELEASE as well? And if so, is there also an error showing up somewhere or is this purely the key binding not working?

@martinlippert I test STS 13 upgraded to 14 and fresh install of STS 14.
In both cases, the lombok agent produces the error.
 - Without lombok agent, both cases run with no problem
 - With lombok agent, both cases crashes

I think the problem is only the lombok agent.

**Comment by martinlippert** [comment] 2022-03-25 10:25
@ofornes-basecat Thanks for double checking and confirming our initial results here. So everybody who uses Lombok should make sure to use the latest Lombok extension for Eclipse with the latest STS 4.14.0 release.

**Comment by shankarwww** [comment] 2022-03-28 21:28
It seems the issue is still not completely fixed. Try to rename the file using Crtl+Shift+R by clicking the on the file in the package explorer. The window and different options in the toolbar menu starts flickering.

**Comment by shankarwww** [comment] 2022-03-28 23:14
![sts_flickering_issue](https://user-images.githubusercontent.com/18091406/160502353-403507c3-a283-4a80-b8ce-396d2b7242f5.png)

Please refer to above pic for more details and steps to replicate this flickering issue

**Comment by shankarwww** [comment] 2022-05-31 20:41
> @shankarwww Do you have the Lombok extension installed as well? Or does the problem appear even without anything Lombok-related being installed?

yes, I have lombok plugin installed.

**Comment by martinlippert** [comment] 2022-06-01 08:29
> > @shankarwww Do you have the Lombok extension installed as well? Or does the problem appear even without anything Lombok-related being installed?
> 
> yes, I have lombok plugin installed.

As discussed in this issue, the problem got fixed in Lombok 1.18.24 (here is the related Lombok issue: https://github.com/projectlombok/lombok/issues/3134), so please make sure you have the latest Lombok extension installed.
