### ISSUE TITLE
missing "Focus on Active Task" button in Package Explorer

### ISSUE THREAD

**Issue by dominik42** [spring-projects/sts4#637] opened 2021-05-07 11:08 UTC
**Describe the bug**
Using STS 4.10 with Mylyn, there is no "Focus on Active Task" button in the package explorer view.
Other views contains this button, e.g. project explorer and navigator.

**To Reproduce**
- Download STS 4.10, 
- install a mylyn connector (gitlab or jira connector) 
- connect to your issue tracker
- see your tasks in mylyn task list view
- activate a tasks
- open Project Explorer: "Focus on Active Task" button is visible
- open Navigator: "Focus on Active Task" button is visible
- open Package Explorer: "Focus on Active Task" button is not visible

**Comment by martinlippert** [comment] 2021-05-07 11:34
Does this work in a regular Eclipse 2021-03 package without any Spring Tools components involved? This sounds very much like a general Mylyn-related issue. There might also be an installation issue going on under the hood that is specific to the STS 4 distribution, but to rule that out, it would be great if you could try this with a vanilla Eclipse package.

**Comment by dominik42** [comment] 2021-05-13 20:36
>Does this work in a regular Eclipse 2021-03 package without any Spring Tools components involved?
1) Using "Eclipse IDE for Enterprise Java and Web Developers" (has Mylyn included) the packages explorer contains the "Focus on Active Task" button 
2) using "Eclipse IDE for Java Developers" (comes without Mylyn), installed Mylyn 3.23 via Marketplace the same error occured as with STS: package explorer doesn't show the button but project explorer and navigator shows the button.

So it seems to be effectively a Mylyn-related issue or at least affects plain Eclipse too. 
How we handle to issue under those circumstances ?

**Comment by martinlippert** [comment] 2021-05-18 10:17
@dominik42 Thanks for checking this with the various plain Eclipse packages. Let me try to reproduce this locally to see if I can come up with a rough guess about what is going wrong under the hood - and therefore with an idea where to report this.

**Comment by martinlippert** [comment] 2021-05-18 12:06
I tried to reproduce this with a vanilla STS 4.10.0 RELEASE installation and then installed a number of Mylyn features from the main Eclipse repo (via `Install New Software`), but without any connectors. I think these are the components:

```
    Mylyn Context Connector: Eclipse IDE	3.25.2.v20200828-1617
    Mylyn Context Connector: Java Development	3.25.2.v20200828-1617
    Mylyn Context Connector: Plug-in Development	3.25.2.v20200828-1617
    Mylyn Context Connector: Team Support	3.25.2.v20200828-1617
    Mylyn Task List	3.25.2.v20200814-0512
    Mylyn Task-Focused Interface	3.25.2.v20200828-1617
```

With that, I get the `Focus on Active Task` button in both, the `Package Explorer` view as well as the `Project Explorer` view. I also tried to add the Atlassian support from the Marketplace, but the buttons stay where they are.

I vaguely guess that you are hitting an incompatibility behind the scenes with the Mylyn version that you are installing. Can you try to start with a fresh STS4 4.10.0.RELEASE distribution and install the Mylyn features from the main Eclipse repo (instead of using the Marketplace)? Would be interesting to see how far you get with this approach and the latest versions of Mylyn here.

**Comment by dominik42** [comment] 2021-05-18 13:02
with a fresh STS4 4.10.0.RELEASE distribution and install the Mylyn features from the main Eclipse repo already works as expected.

My STS installation uses the following components/versions from your list of mylyn components:

Mylyn Context Connector: Eclipse IDE	                3.25.2.v20200828-1617
Mylyn Context Connector: Java Development	fehlt
Mylyn Context Connector: Plug-in Development	fehlt
Mylyn Context Connector: Team Support	         3.25.2.v20200828-1617
Mylyn Task List	                                                 3.25.2.v20200814-0512
Mylyn Task-Focused Interface	                        3.25.2.v20200828-1617

I installed the missing components via your suggested "Install New Software" and afterwards the button is available.
So it seems, that the installation process via Marketplace misses something.

My problem is solved with the installation of Mylyn components via "Install New Software".

**Comment by martinlippert** [comment] 2021-05-18 14:13
Okay, so lets close this one here, since the latest version of Mylyn seems to work fine. 😀

**Closed by martinlippert** 2021-05-18 14:13 UTC
Labels: for: eclipse, status: waiting-for-feedback, type: bug
