### ISSUE TITLE
STS Eclipse: Hovers error.

### ISSUE THREAD

**Issue by stephenlam520** [spring-projects/sts4#470] opened 2020-05-29 09:49 UTC
Checked  Preferences -> Java -> Editor -> Hovers -> Combined Hover, but not show the problem description.

STS Version: 4.6.2.RELEASE

![7(%CEYJ@KWJ98~2J4T4QUYS](https://user-images.githubusercontent.com/49053556/83246395-a44efc80-a1d4-11ea-9cdc-846fba09f6d3.png)
![_(OE_773LH1ITSC14E9J%_4](https://user-images.githubusercontent.com/49053556/83246412-aadd7400-a1d4-11ea-8aef-2fe96385714e.png)

**Comment by martinlippert** [comment] 2020-05-29 13:31
Hey @stephenlam520, I tried a sample code snippet with an error and hovering over the error shows the error description just fine in my STS 4.6.2 install, so I am not exactly sure what is not working on your end (and why). Can you provide a sample project and a few steps how to reproduce this?

**Comment by SledgeHammer01** [comment] 2020-05-31 06:04
> Hey @stephenlam520, I tried a sample code snippet with an error and hovering over the error shows the error description just fine in my STS 4.6.2 install, so I am not exactly sure what is not working on your end (and why). Can you provide a sample project and a few steps how to reproduce this?

@martinlippert I am seeing this exact issue too. In 4.6.2, "Combined Hover" is checked and Problem Description is unchecked. If I hover over an error as shown in the screenshot, the quick fixes are not available and it doesn't let me check the problem description without setting a modifier key. If I uncheck Combined Hover and check Problem Description, then the quick fixes are shown, but then it disables a bunch of other hover stuff.

**Comment by cmagroup** [comment] 2020-05-31 22:10
Hi, having same issue as @stephenlam520 and @SledgeHammer01. STS 4.6.2 broke Eclipse hover as quick fix for errors is not showed. I have the exact same configuration, but running Eclipse under Ubuntu 2020-04. Tested on two different machines, with same result. Removing STS 4.6.2 fixed the issue.

**Comment by stephenlam520** [comment] 2020-06-01 07:35
@martinlippert  Is there a temporary solution?

**Comment by BoykoAlex** [comment] 2020-06-01 15:14
Yes, indeed something is broken as quickfixes not shown in the hover.
The workaround would be click the error marker in the gutter ruler area and it'd show the quick fixes:
![Screen Shot 2020-06-01 at 11 13 35](https://user-images.githubusercontent.com/6433390/83423452-fd977580-a3f8-11ea-8528-123e7adf851f.png)

**Comment by BoykoAlex** [comment] 2020-06-01 17:50
Look like LS Hover provider overrides the JDT hover providers as downstream hover providers take precedence over up stream ones.
Therefore instead of the `ProblemHover` the `LSJavaHoverProvider` is showing its stuff...
Looks like previously if LS hover content is empty an empty hover was returned and hence other JDT hover provider would return something thus the problem wasn't as visible.

Maybe try removing `org.eclipse.lsp4e.jdt` plugin from the plugins folder or disable it somehow...

**Comment by BoykoAlex** [comment] 2020-06-01 21:03
Here is Eclipse side issue: https://bugs.eclipse.org/bugs/show_bug.cgi?id=563802

**Comment by stephenlam520** [comment] 2020-06-02 02:52
@BoykoAlex Thanks.

**Comment by martinlippert** [comment] 2020-06-02 13:34
Alex worked on a fix for this, which is already committed to the Eclipse project. Now we are waiting for the various CI builds to finish. Then you could use the nightly CI update site for Spring Tools 4 for Eclipse to get that fix asap (in case you don't want to wait for the next release, which ships late in June).

**Comment by BoykoAlex** [comment] 2020-06-02 15:30
Just in case here is the STS4 nightly update site: https://dist.springsource.com/snapshot/TOOLS/sts4-language-server-integrations/nightly
(just tried to install STS4 LS Integration for Eclipse and it works now)

**Closed by BoykoAlex** 2020-06-02 15:30 UTC
