### ISSUE TITLE
High CPU usage without any visible background tasks

### ISSUE THREAD

**Issue by vertx-one** [spring-projects/sts4#931] opened 2022-12-19 16:41 UTC
**Describe the bug**
High CPU usage without any visible background tasks. My machine: 6-core Ryzen 4600/16Gb. After upgrade STS to 4.17 CPU usage about 70-80%. Before upgrade CPU usage was about 20%. I tried to reinstall STS from marketplace, but result is the same. Also i reboot laptop but no difference in performace.

**To Reproduce**
Ubuntu 22.04, Eclipse 2022.09, STS 4.17
Start Eclipse without opened editors and got
![image](https://user-images.githubusercontent.com/1396808/208407945-71922b38-4592-433f-b249-f0520a243414.png)
for 5-7 minutes after that period cpu usage little decrease, but editing performace is dealy slow
![image](https://user-images.githubusercontent.com/1396808/208475309-1eb8cb0f-d3f7-454f-98e5-b24001df2e03.png)

**Comment by martinlippert** [comment] 2022-12-19 17:43
I am closing this one as a duplicate of #922

**Closed by martinlippert** 2022-12-19 17:43 UTC
Labels: type: bug, theme: performance, status: needs-investigation, for: eclipse, status: duplicate, theme: validation
